OOPath tests - logical operators
apache/incubator-kie pull request #1115
Opened 2017-02-23 14:34 UTC by winklerm

Adding a few OOPath tests for rules containing multiple logical branches to test (originally intended to check that the UnsupportedOperationException thrown at [1] does not cause problems).

More PRs for different aspects will follow (OOPath with CEP, OOPath with persistence, ...).

[1] https://github.com/droolsjbpm/drools/blob/master/drools-core/src/main/java/org/drools/core/rule/constraint/XpathConstraint.java#L91

2017-02-23 15:04 UTC, baldimir requested changes
Please see comments. There are 2 things. Otherwise it looks good.

2017-02-23 15:04 UTC, baldimir commented on drools-test-coverage/test-suite/src/test/java/org/drools/testcoverage/functional/oopath/OOPathLogicalBranchesTest.java
> +                "        Employee( this != $emp, /address{ street == 'Elm' || city == 'Big City' } )\n" +
It would be useful to test DRL where $address is used in OOPath constraint. E.g.:

Employee( this != $emp, /address{ street == $address.street || city == 'Big City' } )

2017-02-23 15:04 UTC, baldimir commented on drools-test-coverage/test-suite/src/test/java/org/drools/testcoverage/functional/oopath/OOPathLogicalBranchesTest.java
> +        final Address addressOfBruno = new Address("Elm", 10, "Small City");
This is repeated often, could be probably extracted to separate method and reused.

2017-02-23 15:07 UTC, winklerm commented on drools-test-coverage/test-suite/src/test/java/org/drools/testcoverage/functional/oopath/OOPathLogicalBranchesTest.java
> +                "        Employee( this != $emp, /address{ street == 'Elm' || city == 'Big City' } )\n" +
Agreed, will create a new test for it.

2017-02-23 15:07 UTC, winklerm commented on drools-test-coverage/test-suite/src/test/java/org/drools/testcoverage/functional/oopath/OOPathLogicalBranchesTest.java
> +        final Address addressOfBruno = new Address("Elm", 10, "Small City");
Will do.

2017-02-23 15:55 UTC, winklerm commented
@baldimir I have updated the PR with the suggested changes.

2017-02-23 16:40 UTC, baldimir approved these changes
+1, looks good.

2017-02-24 14:52 UTC, yurloc commented on drools-test-coverage/test-suite/src/test/java/org/drools/testcoverage/common/model/Employee.java
> + * Copyright 2016 Red Hat, Inc. and/or its affiliates.
It's 2017.

2017-02-24 15:20 UTC, winklerm commented on drools-test-coverage/test-suite/src/test/java/org/drools/testcoverage/common/model/Employee.java
> + * Copyright 2016 Red Hat, Inc. and/or its affiliates.
Good catch, fixed.

2017-02-24 16:39 UTC, yurloc commented on drools-test-coverage/test-suite/src/test/java/org/drools/testcoverage/functional/oopath/OOPathLogicalBranchesTest.java
> +        Assertions.assertThat(this.results).containsExactlyInAnyOrder("Big City", "Small City");
I recommend using a static import for assert methods. It makes the test more readable and it is de facto standard style in Drools tests.

2017-02-27 10:59 UTC, merged