Oopath test dtables
apache/incubator-kie pull request #1147
Opened 2017-03-14 16:17 UTC by cimbalek

2017-03-14 16:20 UTC, triceo requested changes

2017-03-14 16:20 UTC, triceo commented on drools-test-coverage/test-suite/src/test/java/org/drools/testcoverage/functional/oopath/OOPathDtablesTest.java
> +                .containsAll(Arrays.asList("SafeDriver", "Risky Driver"));
I think the second `contains` is redundant, isn't it?`

2017-03-14 16:20 UTC, triceo commented on drools-test-coverage/test-suite/src/test/java/org/drools/testcoverage/functional/oopath/OOPathDtablesTest.java
> +                .containsAll(Arrays.asList("Nice City", "Big City"))
I'm sure there's a variant of the assertion that does not require the list.

2017-03-14 16:20 UTC, triceo commented on drools-test-coverage/test-suite/src/test/java/org/drools/testcoverage/functional/oopath/OOPathDtablesTest.java
> +                .containsAll(Arrays.asList("SafeDriver", "Risky Driver"));
And if it is, so is the `hasSize()` :-)

2017-03-14 16:52 UTC, cimbalek commented on drools-test-coverage/test-suite/src/test/java/org/drools/testcoverage/functional/oopath/OOPathDtablesTest.java
> +                .containsAll(Arrays.asList("SafeDriver", "Risky Driver"));
You're right that `.containsAll(...)` is redundant. I wasn't sure of `.containsOnly(...)` behavior.
But I cannot agree with leaving the `hasSize(2)` out, because otherwise it would pass even if it contained some of desired entries multiple times.

However, these two asserts can be replaced by `.containsExactlyInAnyOrder(...)`

2017-03-14 17:46 UTC, triceo approved these changes

2017-03-15 08:31 UTC, baldimir requested changes
Review done, please see my comment.

2017-03-15 08:31 UTC, baldimir commented on drools-test-coverage/test-suite/src/test/java/org/drools/testcoverage/functional/oopath/OOPathDtablesTest.java
> +        List<String> list = new ArrayList<>();
This whole test method body except session creation could be extracted to a method and reused in each test. E.g. testOOPathWithDTable(final KieSession session).

2017-03-15 08:40 UTC, baldimir approved these changes
Looks good now, +1.

2017-03-29 07:07 UTC, merged