[DROOLS-1379] Add tests for OOPath in queries
apache/incubator-kie pull request #1148
Opened 2017-03-14 16:28 UTC by jiripetrlik

New tests for OOPath [DROOLS-1379]. These tests are focused on OOPath usage in queries. It also tests reactive and non-reactive behaviour of OOPath in queries.

2017-03-14 20:11 UTC, triceo reviewed
Few stylistic comments, nothing serious.

2017-03-14 20:11 UTC, triceo commented on drools-compiler/src/test/java/org/drools/compiler/oopath/OOPathQueriesTest.java
> +        final List<String> itemList = Arrays.asList(new String[] { "display", "keyboard", "processor" });
I suggest you pay more attention to variable locality. (Even if not literal.) `itemList` is first used on line 58, why is it declared on line 51? `ksession` is first used on line 63, why is it declared on line 53?

Don't force people to keep in their heads more than they need to, for longer than they need to.

2017-03-14 20:11 UTC, triceo commented on drools-compiler/src/test/java/org/drools/compiler/oopath/OOPathQueriesTest.java
> +        }
This loop incl. the list initialization would look sooo nice as a `Stream`. ;-)

2017-03-15 08:50 UTC, baldimir requested changes
Review done. Please see my and Lukas's comments. Only minor things.

2017-03-15 08:50 UTC, baldimir commented on drools-compiler/src/test/java/org/drools/compiler/oopath/OOPathQueriesTest.java
> +        Thing smartphone = new Thing("smartphone");
Please make local variables final. Currently some of them are final and some not (I mean some of them that could be marked final are not). It's a bit confusing if it is mixed up like this.

2017-03-15 08:50 UTC, baldimir commented on drools-compiler/src/test/java/org/drools/compiler/oopath/OOPathQueriesTest.java
> +        Room room = new Room("Room");
This test method body looks the same in each test. Probably could be extracted to a method and reused.

2017-03-16 12:45 UTC, jiripetrlik commented
I've improved PR according to suggestions.

2017-03-16 12:49 UTC, baldimir approved these changes
Looks good, +1.

2017-03-16 12:52 UTC, triceo approved these changes

2017-03-16 12:57 UTC, yurloc commented on drools-compiler/src/test/java/org/drools/compiler/oopath/OOPathQueriesTest.java
> +        assertThat(resultList).as("Querry does not contain all items").containsAll(itemList);
Typo querry -> query.

2017-03-16 12:58 UTC, yurloc commented on drools-compiler/src/test/java/org/drools/compiler/oopath/OOPathQueriesTest.java
> +                .map(row -> (Thing) row.get("$y")).map(thing -> thing.getName()).collect(Collectors.toList());
Can be simplified to a single map call `.map(row -> ((Thing) row.get("$y")).getName())`.

2017-03-16 13:40 UTC, jiripetrlik commented
Thank you @yurloc. Typo was fixed and stream expression was improved according to your suggestion.

2017-04-04 13:41 UTC, baldimir commented
jenkins retest this

2017-04-13 16:55 UTC, mariofusco commented
ok to test

2017-05-29 10:35 UTC, baldimir commented
jenkins retest this

2017-05-30 14:20 UTC, mariofusco commented
Replaced by https://github.com/kiegroup/drools/pull/1292 with 2 tests removed as explained in https://issues.jboss.org/browse/RHBRMS-2761

2017-05-30 14:20 UTC, closed without merging