Ext elements
apache/incubator-kie pull request #1192
Opened 2017-04-04 22:56 UTC by akoufoudakis

_**Please, review the following code. Update after the first review.**_

    To use extension elements inside inputData elements in order to provide “external” information: GEO location, time and location tracking of a decision making (when and were specific decision was taken). This is the primary scope of the use.

    In case extension element represents a complex type customer prefers to get back an instance of the complex type, assuming the complex type is defined as a class by the development team on the customer side. However, the customer also understands that it can be more complex and considers the possibility to get the complex type as an XML snippet. The parsing and turning the XML snippet into the complex type, defined by the customer.

    The possibility of getting the list of extension elements is expected from other DMN elements, which extend from DMNElement, according to the DMN specification and meta model diagram by OMG. In other words, the usage of extension elements is not limited to be a part of input data elements only.

    The client is not expecting “authoring” of the extension elements.
    Since extension elements are a part of DMN specification, this is an attempt to make it possible for drools to register custom extension elements in a generic way.

2017-04-04 23:52 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/api/DMNFactory.java
> +    public static DMNCompiler newCompilerWithConfiguration(DMNCompilerConfiguration dmnCompilerConfig) {
We usually keep the method name the same, just overload it with the parameter:

```java
public static DMNCompiler newCompiler( DMNCompilerConfiguration config )
```

Also, can you please create a factory method for the config?

```java
public static DMNCompilerConfiguration newCompilerConfiguration()
```

2017-04-04 23:53 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/assembler/DMNAssemblerService.java
> +                DMNExtensionRegister extRegister = (DMNExtensionRegister)( (KnowledgeBuilderImpl) kbuilder ).getRootClassLoader()
You will need to wrap this in a try/catch to avoid blowing up in case one of the classes can't be loaded.

2017-04-04 23:54 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/assembler/DMNAssemblerService.java
> +            DMNCompilerConfiguration compilerConfig = new DMNCompilerConfigurationImpl();
... then use the factory method here to instantiate the compiler configuration.

2017-04-04 23:54 UTC, etirelli commented
@akoufoudakis this is excellent, thank you! Just take a look at the minor changes in my comments and add the tests and we are good to go!

2017-04-10 14:56 UTC, etirelli commented
@akoufoudakis did you had time to create some tests for this feature?

2017-04-21 16:07 UTC, tarilabs commented on kie-dmn/kie-dmn-backend/src/main/java/org/kie/dmn/backend/marshalling/v1_1/xstream/DMNElementConverter.java
> +            ((DMNElement)parent).setExtensionElements((DMNElement.ExtensionElements)child);
as discussed, yes.

2017-04-21 16:07 UTC, tarilabs commented on kie-dmn/kie-dmn-backend/src/main/java/org/kie/dmn/backend/marshalling/v1_1/xstream/ExtensionElementsConverter.java
> +            parseElements( reader, context, obj );
as suggested, yes.

2017-04-21 16:07 UTC, tarilabs commented on kie-dmn/kie-dmn-backend/src/main/java/org/kie/dmn/backend/marshalling/v1_1/xstream/ExtensionElementsConverter.java
> +        id.getAny().add(child);
correct, as suggested.

2017-04-21 16:07 UTC, tarilabs commented on kie-dmn/kie-dmn-backend/src/main/java/org/kie/dmn/backend/marshalling/v1_1/xstream/XStreamMarshaller.java
> +        xStream.registerConverter(new ExtensionElementsConverter( xStream, extensionRegisters ) );
correct.

2017-04-21 16:07 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/test/resources/org/kie/dmn/core/compiler/extensions/dakkapel_uitvoering_en_conversie.xml
> +		<uitv:uitvoeringsregels>
I think the question about this file - in general - is that seems to be related to a specific customer business logic. I'm not sure if it's meant to be kept internal and a good idea to have it in the upstream codebase. Possibly an "anonymized" file can be created or a simplified one?

2017-04-21 16:11 UTC, akoufoudakis commented on kie-dmn/kie-dmn-core/src/test/resources/org/kie/dmn/core/compiler/extensions/dakkapel_uitvoering_en_conversie.xml
> +		<uitv:uitvoeringsregels>
We have a couple of simple files in our test cases: drools/kie-dmn/kie-dmn-core/src/test/resources/org/kie/dmn/core/0001-filter.dmn. Can I add a couple of extension elements to a couple of InputData elements?

2017-04-21 16:16 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/test/resources/org/kie/dmn/core/compiler/extensions/dakkapel_uitvoering_en_conversie.xml
> +		<uitv:uitvoeringsregels>
@akoufoudakis I think _better_ to add a new file, even just a copy and augment the copy, leaving the original sample files unchanged.
First, because this is a new feature which is unrelated with the existing files.
Second, I believe this would be a better approach because the current existing files are used in the unit test and I would leave them unchanged to more easily detect regression (shall a regression occur).

2017-04-21 16:17 UTC, akoufoudakis commented on kie-dmn/kie-dmn-core/src/test/resources/org/kie/dmn/core/compiler/extensions/dakkapel_uitvoering_en_conversie.xml
> +		<uitv:uitvoeringsregels>
Sure... Of course.

2017-04-21 16:26 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/test/java/nl/rws/dso/inception/backend/extension/ConversieregelRefRegister.java
> +        xStream.alias("conversieregelRef", String.class);
Not 100% what was the real intent here.
In the test, there appears to be an annotated `ConversieregelRef` class.
Here, `conversieregelRef` is aliased directly to a `java.lang.String`.
I think it depends what a "Conversieregel" is meant to be in the use-case demonstrated by this test:

1. a simple String, but then it cannot be differentiated inside a potential collection of heterogeneous extensionelements
2. a proper business domain object as represented by the `ConversieregelRef` class

If case n1, then there is no need for the `ConversieregelRef` class.
If the case n2, then here was possibly meant to be `processAnnotations` and the test case
https://github.com/kiegroup/drools/pull/1192/files#diff-a3b9b0a42509b9e6a4138c8b76cbe099R132
need to be aligned accordingly.

Hope this helps?

2017-04-21 16:30 UTC, akoufoudakis commented on kie-dmn/kie-dmn-core/src/test/java/nl/rws/dso/inception/backend/extension/ConversieregelRefRegister.java
> +        xStream.alias("conversieregelRef", String.class);
Yes... Anyway, it will be gone, because I will use a different file and different extension elements.

2017-04-22 12:27 UTC, etirelli commented on drools-persistence/drools-persistence-jpa/src/test/resources/META-INF/persistence.xml
> +</persistence>
I am confused. Why is this file part of this PR? I don't see the relationship with the extension elements support...

2017-04-22 12:36 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/assembler/DMNAssemblerService.java
> +        model = dmnCompiler.compile(resource);
this can throw a null pointer exception. We need to decide if in case of errors loading extension classes we still create a compiler or we abort. In either case, this has to be handled here.

2017-04-22 12:38 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/assembler/DMNAssemblerService.java
> +                logger.error( "Trying to load a non-existing extension element register {}", e.getLocalizedMessage());
In case of errors, we should also add a DMNKnowledgeBuilderError into the builder I believe.

2017-04-22 12:40 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/extensions/DMNExtensionRegisterTesting.java
> +    private void setProperties() {
this method should be annotated with @Before instead of calling it from tests, otherwise and error might propagate between tests.

2017-04-22 12:41 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/extensions/DMNExtensionRegisterTesting.java
> +    private void clearProperties() {
this method should be annotated with @After instead of calling it from tests, otherwise and error might propagate between tests.

2017-04-22 13:01 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/assembler/DMNAssemblerService.java
> +        if(!extensionProperties.isEmpty()) {
Isn't this code reloading the extension registers for each resource in the kjar? I believe we need to move the creation of the compilerConfig (and possibly the compiler itself) into the class constructor and cache it. This way we can reuse it for each resource. Before we were not caching the compiler because the creation was very lightweight, but scanning the classpath to load classes every time is a really heavy operation.

2017-04-22 13:04 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNCompilerImpl.java
> +                if (dmnCompilerConfig.getRegisteredExtensions().isEmpty()) {
this code seems wrong. If the dmnCompilerConfig is !=null but the list of extensions is not empty, it will not unmarshall the source.

2017-04-22 13:08 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/extensions/DMNExtensionRegisterTesting.java
> +    public void checkClassesLoaded() {
Unfortunately this test is testing the test code (method loadDMNCompilerConfig()). Instead, I believe the loadDMNCompilerConfig() method should be completely removed from here and the test should instantiate the DMNAssemblerService and test that.

2017-04-22 13:10 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/extensions/DMNExtensionRegisterTesting.java
> +    public void testFirstNameConverter() {
similar to above, this method is testing the test code. We need to create the kjar (in memory as other tests do) and test that the model is properly loaded.

2017-04-22 13:13 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/extensions/DMNExtensionRegisterTesting.java
> +    public void testFirstNameConverter() {
If we need to support straight unmarshalling with models (without compilation), then we should move the code from the loadDMNCompilerConfig() into the DMNMarshallerFactory (or a helper class), so that it can be used elsewhere.

2017-04-22 13:13 UTC, etirelli requested changes
Please see my comments.

2017-04-22 13:14 UTC, etirelli commented
Is there a JIRA for this work? I don't see it referenced in the commit messages.

2017-04-22 20:42 UTC, triceo commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/extensions/DMNExtensionRegisterTesting.java
> +        System.clearProperty("org.kie.dmn.marshaller.extension.lastname");
Ideally, the property names would be externalized into a constant.

2017-04-22 20:44 UTC, triceo commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/assembler/DMNAssemblerService.java
> +        Map<String, String> extensionProperties = new HashMap<String, String>();
We're on Java 8 - `new HashMap<>()` will suffice.

2017-04-22 20:46 UTC, triceo commented on kie-dmn/kie-dmn-backend/src/main/java/org/kie/dmn/backend/marshalling/v1_1/xstream/XStreamMarshaller.java
> +        this.extensionRegisters.addAll(extensionRegisters);
`new ArrayList<>(extensionRegisters)` will do the same thing, with the additional benefit of properly sizing the list.

2017-04-22 20:48 UTC, triceo commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/extensions/DMNExtensionRegisterTesting.java
> +            System.out.println( "Trying to load a non-existing extension element register " + e.getLocalizedMessage());
Let's not use `System.out` - slf4j logging is preferred.

2017-04-23 09:07 UTC, yurloc commented on kie-dmn/kie-dmn-api/src/main/java/org/kie/dmn/api/core/DMNCompilerConfiguration.java
> + * Copyright 2016 Red Hat, Inc. and/or its affiliates.
It's 2017.

2017-04-23 09:12 UTC, yurloc commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/extensions/DMNExtensionRegisterTesting.java
> +public class DMNExtensionRegisterTesting {
Let's rename this class to `DMNExtensionRegisterTest` to keep consistency.

For example, when one needs to search for a pattern in all test files, it's possible to do `grep --include=*Test.java foo` if all tests are named by this convention.

2017-04-24 08:13 UTC, tarilabs commented on kie-dmn/kie-dmn-backend/src/main/java/org/kie/dmn/backend/marshalling/v1_1/xstream/ExtensionElementsConverter.java
> +            this.extensionRegisters.addAll(extensionRegisters);
I'm reworking this code in the context of the class, also to avoid potential NPE if the extensionRegisters field might have not been initialized, from the no-args constructor.

2017-04-24 08:13 UTC, tarilabs commented on kie-dmn/kie-dmn-backend/src/main/java/org/kie/dmn/backend/marshalling/v1_1/xstream/XStreamMarshaller.java
> +        this.extensionRegisters.addAll(extensionRegisters);
I think it's more dangerous the potential NPE if the extensionRegisters field might have not been initialized, from the no-args constructor; I'm reworking the code in this perspective.

2017-04-24 08:13 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/assembler/DMNAssemblerService.java
> +                logger.error( "Trying to load a non-existing extension element register {}", e.getLocalizedMessage());
I think we discussed this previously and the decision was the logger-only, but I will consider this comment for the code rework.

2017-04-24 08:13 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/assembler/DMNAssemblerService.java
> +        model = dmnCompiler.compile(resource);
looks like line 86 is a dup of line 84 making the compilation twice? Will take into account into code rework,

2017-04-24 08:13 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/assembler/DMNAssemblerService.java
> +        if(!extensionProperties.isEmpty()) {
I believe it cannot be done in the constructor as the `KnowledgeBuilder` is required to understand which are the classes to be loaded as extension, but I will take into account the caching requirement for the code rework.

2017-04-24 08:13 UTC, tarilabs commented on kie-dmn/kie-dmn-api/src/main/java/org/kie/dmn/api/core/DMNCompilerConfiguration.java
> + * Copyright 2016 Red Hat, Inc. and/or its affiliates.
ok.

2017-04-24 08:13 UTC, tarilabs commented on drools-persistence/drools-persistence-jpa/src/test/resources/META-INF/persistence.xml
> +</persistence>
erased, ok.

2017-04-24 13:54 UTC, tarilabs commented
Jenkins, test this please.

2017-04-24 14:01 UTC, tarilabs commented on drools-compiler/src/main/java/org/drools/compiler/builder/impl/KnowledgeBuilderConfigurationImpl.java
> +            chainedProperties.addProperties(additionalProperty);
@etirelli please notice as discussed this required the `KnowledgeBuilderConfiguration(Impl)` to stop ignoring not-known properties from the kmodule and inserting them inside the ChainedProperties.

2017-04-24 14:01 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/extensions/DMNExtensionRegisterTest.java
> +            System.clearProperty("org.kie.dmn.marshaller.extension.lastname");
System properties is only used in this test.

2017-04-24 14:01 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/extensions/DMNExtensionRegisterTest.java
> +    public void testUsingKModuleProperty_WrongClasses() {
added test for demonstrate wrong configuration.

2017-04-24 15:21 UTC, tarilabs commented
Jenkins, test this please

2017-04-24 18:05 UTC, etirelli commented on drools-compiler/src/main/java/org/drools/compiler/builder/impl/KnowledgeBuilderConfigurationImpl.java
> +            chainedProperties.addProperties(additionalProperty);
ok

2017-04-24 18:08 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/extensions/DMNExtensionRegisterTest.java
> +    public void testUsingKModuleProperty_WrongClasses() {
ok

2017-04-24 18:09 UTC, etirelli approved these changes

2017-04-24 18:11 UTC, merged