[DROOLS-1629] Allow multiple instances of ObjectMarshallingStrategy of the same class
apache/incubator-kie pull request #1364
Opened 2017-07-07 14:47 UTC by ngs-mtech

With this implementation, dependant on[https://github.com/kiegroup/droolsjbpm-knowledge/pull/249| https://github.com/kiegroup/droolsjbpm-knowledge/pull/249, the bug DROOLS-1629] the issue should be fixed.

2017-07-07 14:52 UTC, ngs-mtech commented
Its required to pull before https://github.com/kiegroup/droolsjbpm-knowledge/pull/249 in order to allow this one!

2017-07-07 15:20 UTC, mswiderski commented
ok to test

2017-07-07 15:21 UTC, mswiderski commented
same here, could you apply the formatting rules as the diff looks really bad - no idea what are the changes, and please squash the commits

2017-07-08 05:15 UTC, mswiderski requested changes
Overall looks good, just few comments to address

2017-07-08 05:15 UTC, mswiderski commented on drools-core/src/main/java/org/drools/core/marshalling/impl/SerializablePlaceholderResolverStrategy.java
>      public int getIndex() {
Changes in this file are not needed as they are just spaces

2017-07-08 05:15 UTC, mswiderski commented on drools-persistence/drools-persistence-jpa/src/main/java/org/drools/persistence/jpa/marshaller/JPAPlaceholderResolverStrategy.java
> +        EntityManager em = getEntityManager();
Why not using entity manager factory to get the metamodel?

2017-07-08 05:15 UTC, mswiderski commented on drools-persistence/drools-persistence-jpa/src/main/java/org/drools/persistence/jpa/marshaller/JPAPlaceholderResolverStrategy.java
> +    		Set<EntityType<?>> entities = em.getMetamodel().getEntities();
Instead iterating over list of entities we coul use the metamodel.entity method https://docs.oracle.com/javaee/7/api/javax/persistence/metamodel/Metamodel.html#entity-java.lang.Class- and catch IllegalArgumentException in case it is not an entity

2017-07-08 05:15 UTC, mswiderski commented on drools-core/src/main/java/org/drools/core/marshalling/impl/ObjectMarshallingStrategyStoreImpl.java
> -public class ObjectMarshallingStrategyStoreImpl implements ObjectMarshallingStrategyStore {
This class still seems to have wrong formatting as it shows to be completely replaced and thus I can't see what has actually changed

2017-07-08 08:47 UTC, ngs-mtech commented on drools-persistence/drools-persistence-jpa/src/main/java/org/drools/persistence/jpa/marshaller/JPAPlaceholderResolverStrategy.java
> +    		Set<EntityType<?>> entities = em.getMetamodel().getEntities();
Throwing an exception is something very expensive, the building of a callstack is a pain for the VM, 
Let me perform another approach.

2017-07-08 09:13 UTC, ngs-mtech reviewed
All your proposals implemented, some changes added to JPAPlaceholderResolverStrategy

2017-07-08 10:27 UTC, mswiderski requested changes
Last concern to address for jpa strategy and I think we are good with it

2017-07-08 10:27 UTC, mswiderski commented on drools-persistence/drools-persistence-jpa/src/main/java/org/drools/persistence/jpa/marshaller/JPAPlaceholderResolverStrategy.java
> +    private void initializeManagedClasses(){
I like this approach! Nice work

2017-07-08 10:27 UTC, mswiderski commented on drools-persistence/drools-persistence-jpa/src/main/java/org/drools/persistence/jpa/marshaller/JPAPlaceholderResolverStrategy.java
> +        this.name += ":" + persistenceUnit;
I believe this is breaking backward compatibility as it will register itself with different name then it was persisted before this change so I think we should make it via additional cunstructor so we won't break existing sessions

2017-07-08 10:29 UTC, mswiderski commented on drools-persistence/drools-persistence-jpa/src/main/java/org/drools/persistence/jpa/marshaller/JPAPlaceholderResolverStrategy.java
> +        this.name += ":" + persistenceUnit;
Just noticed there is this additional constructor in place do it is a matter of removing this append of pu to name by default, wdyt?

2017-07-08 10:52 UTC, mswiderski commented
If I am not mistaken this already solves this issue JBPM-6175

2017-07-09 21:33 UTC, ngs-mtech commented on drools-persistence/drools-persistence-jpa/src/main/java/org/drools/persistence/jpa/marshaller/JPAPlaceholderResolverStrategy.java
> +        this.name += ":" + persistenceUnit;
Ok, I understand your approach.

2017-07-09 21:43 UTC, ngs-mtech commented
I hope so!.

2017-07-10 06:54 UTC, mswiderski approved these changes
looks good to me

@mariofusco @DuncanDoyle any comments?

2017-07-10 08:26 UTC, DuncanDoyle commented
No comments, LGTM.

2017-07-10 17:35 UTC, mariofusco commented
@mswiderski This is ok also for me. Let me know if I can merge it.

2017-07-11 08:11 UTC, merged