DROOLS-1676
apache/incubator-kie pull request #1391
Opened 2017-07-27 13:54 UTC by akoufoudakis

We have the following use case.
There are two DMN models (files). One of them is a "central" file, which contains top level decision.
The second DMN model (file) contains a "local" decision, which is, in its turn, a required decision for the top level decision, declared in the first file.
Due to incompleteness of DMN specification for DMN Import we agreed to try to implement a new FEEL function, which would evaluate the decision by name and namespace.

There are still few assumptions, which we have to verify, however, this pull request checks whether the whole "approach" is appropriate. Additionally, we had to modify some existing to be able to pass an instance of DMNRuntime.

2017-07-27 14:43 UTC, etirelli commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/CallDecisionFunction.java
> +                                          @ParameterName("decisionName") String decisionName, @ParameterName("dmnContext") DMNContext dmnContext) {
minor thing, but the @ParameterNames should use FEEL "practices", so use spaces instead of camel case. For instance: @ParameterName("decision name"), etc.

2017-07-27 14:46 UTC, etirelli commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/CallDecisionFunction.java
> +        return FEELFnResult.ofResult(requiredDecisionResult);
Needs to check for errors before returning the value, and in case of success, return only the value of the decision invoked, not the whole DMNResult. E.g.:

```
return FEELFnResult.ofResult(requiredDecisionResult.getContext().get(decisionName));
```

the code above is just a snippet, but the actual code needs to check for nulls, errors, etc.

2017-07-27 14:47 UTC, etirelli commented
The overall idea is correct. You will need to change the code to call the appropriate constructor for the EvaluationContextImpl to inject the DMNRuntime into it.
We will also need appropriate tests.
Good job!

2017-07-27 17:29 UTC, akoufoudakis commented
About the constructor... Do we have to replace all invocations of the old constructor with one parameter to the new one with two parameters? Or should it be only done only for specific invocations? I would say for all. What do you think about it?

2017-08-02 14:36 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DMNInvocationEvaluator.java
> +            EvaluationContextImpl ctx = new EvaluationContextImpl(feel.getEventsManager(), (DMNRuntime)eventManager);
We need to review this cast. It is doable, but not ideal.

2017-08-02 14:46 UTC, akoufoudakis commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DMNInvocationEvaluator.java
> +            EvaluationContextImpl ctx = new EvaluationContextImpl(feel.getEventsManager(), (DMNRuntime)eventManager);
Sure... Do we want to hide cast inside the constructor implementation? @tarilabs mentioned that instead we could add DMNRuntime to DMNRuntimeEventManager, but it would "break" the interface...

2017-08-02 15:08 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DMNInvocationEvaluator.java
> +            EvaluationContextImpl ctx = new EvaluationContextImpl(feel.getEventsManager(), (DMNRuntime)eventManager);
I actually proposed to add `DMNRuntime` as a field inside `DMNRuntimeEventManager` because it is, as per discussions and if I understood correctly the points, acting as a "evaluation context" class.

I mentioned I would like `DMNRuntimeEventManager` be renamed to something like `DMNRuntimeEvaluationContext` but that would break an interface we have exposed in -api.
Or we could have `DMNRuntimeEvaluationContext` as a separate class/interface in core, although doing this instead would break the `evaluate()` method signature of `DMNExpressionEvaluator`...

Bottom line my understanding is this method signature:
https://github.com/kiegroup/drools/blob/9a48e63077d7a1bc0b36596bf77100de6752e0ae/kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/api/DMNExpressionEvaluator.java#L36
somehow should allow to receive a "DMN evaluation context" comprised of the Event Manager and now the DMNRuntime, but I'm not sure which is the most affordable break to achieve so.

Unless we simply add method in `DMNRuntimeEventManager` to return the DMNRuntime, wouldn't break anything in -api I think; but this is like saying everything which is an "event manager" must be able to provide back its "parent" DMNRuntime; I'm speaking just from an API/interface semantic point of view. If this is acceptable, it is the non-breaking change which could avoid this internal cast.

2017-08-03 06:59 UTC, tarilabs commented
Commit 083f853 implements indeed the last idea proposed, for me is good thank you. We shall wait for @etirelli  to validate is a valid approach.

2017-08-03 17:46 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DMNInvocationEvaluator.java
> +            //EvaluationContextImpl ctx = new EvaluationContextImpl( feel.getEventsManager() );
minor thing, but as a general rule, we should remove old code, instead of commenting it.

2017-08-03 17:51 UTC, etirelli commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/CallDecisionFunction.java
> +    public FEELFnResult<DMNResult> invoke(@ParameterName("ctx") EvaluationContext ctx, @ParameterName("namespace") String namespace, @ParameterName("modelName") String modelName,
The result type of the invoke should be FEELFnResult<Object>. See comment below about the reason.

2017-08-11 15:05 UTC, etirelli commented
@akoufoudakis All the changes look good! I think we are ready to merge, just missing tests. Can you add them, please?

2017-09-08 09:35 UTC, tarilabs commented
Jenkins, test again.

2017-09-08 09:53 UTC, tarilabs commented
When the test is run by itself, it passes.
When the test is run as part of the suite, the number of error doesn't match.
I believe is a problem of the running order of decisions, and something is not working; investigating.

2017-09-08 10:32 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/impl/DMNRuntimeImpl.java
> +                    return false;
@etirelli I believe during CI it emerged a bug which was related to the runtime order by which dependent decisions are executed.

In this case, Line 378 implies this branch is NOT a success (in contrast to line 338)
It would have set the status to failed.

But.
It would have jumped to the finally (line 395), and then proceeded to line 394 returning a `true`.

This is wrong, in all other cases if status != SUCCESS it is returning false.
Even more problematic because when decision calls other decision, they rely on the boolean return type of this method, for instance line 289.

the introduced `return false` at the highlighted line should solve for this bug which emerged.

2017-09-08 10:32 UTC, tarilabs commented
Jenkins, test again

2017-09-08 10:41 UTC, tarilabs commented
Jenkins, test again

2017-09-08 10:53 UTC, tarilabs commented
To recap.

A "Caller" model,
![image](https://user-images.githubusercontent.com/1699252/30208370-6b0ca964-9493-11e7-9da5-2a51385f4edf.png)

where decision "Calling outside" is calling the externalized decision evaluation:
![image](https://user-images.githubusercontent.com/1699252/30208650-acd31ce2-9494-11e7-9f0c-813890e3601b.png)

In the normal/good test case, the parametrized serves to call the following "Calling" model:
![image](https://user-images.githubusercontent.com/1699252/30208428-ae13bd06-9493-11e7-9333-defefdd47421.png)

@etirelli can you please check the boxed invocation, the parameter names are correct, specifically the last parameter "invocation context" is the desired one, and the introduced FEEL function name "call decision" the same. Thanks

2017-09-08 13:13 UTC, etirelli commented
@tarilabs looks good to me! The only thing I am considering is if we should name the function "invoke" instead of "call decision"? It gives us more flexibility in terms of semantics (we can extend it later to invoke multiple decisions instead) and also keeps consistency with the parameter name "invocation context" (although we could abbreviate it to simply "parameters" instead). Wdyt?

2017-09-08 13:19 UTC, akoufoudakis commented
@etirelli Parameters looks more concise and make more sense. As for the invoke function... DMN standard calls many things invocation. So, we can be consistent and rename it... Shall I do it now?

2017-09-08 13:33 UTC, tarilabs commented
good for me

2017-09-08 13:47 UTC, akoufoudakis commented
Jenkins, test again

2017-09-08 14:30 UTC, tarilabs commented
Jenkins, test again

2017-09-11 13:55 UTC, baldimir requested changes
Please see my comment, otherwise looks good.

2017-09-11 13:55 UTC, baldimir commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/DMNRuntimeTest.java
> +        {
Please split these cases into separate test methods. If we have these together like this and e.g. the first case fail, we don't know if the other ones are working, because the assert failure will end the test method.

2017-09-11 13:58 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/DMNRuntimeTest.java
> +        {
in this case, that's what I want. Invoking an external decision must first work when "all is good" but also must throw errors when errors. Can I leave it as is ?

2017-09-11 15:37 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/DMNRuntimeTest.java
> +        {
@tarilabs I think @baldimir is right here, each of these cases should be an individual test to make any problem immediately visible... just split into multiple test methods.

2017-09-11 15:44 UTC, akoufoudakis commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/DMNRuntimeTest.java
> +        {
@tarilabs @etirelli If it is just splitting three cases (one successful, two failures) into three separate test methods, can I quickly do it?

2017-09-11 17:00 UTC, akoufoudakis commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/DMNRuntimeTest.java
> +        {
@baldimir @tarilabs @etirelli Committed the changes. Please, check. If it is fine, run the Jenkins build, in case it is needed.

2017-09-11 17:13 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/DMNRuntimeTest.java
> +        {
I think the question here is if instead of cloning the context it is fine to just have it in-place --with the right or wrong data-- for each test.

2017-09-11 22:45 UTC, akoufoudakis commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/DMNRuntimeTest.java
> +        {
@tarilabs @etirelli Ooops. Haven't seen the one above. Have already committed the changes, suggested by @tarilabs.

2017-09-12 07:03 UTC, baldimir approved these changes
Looks good now, +1.

2017-09-12 07:05 UTC, baldimir commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/DMNRuntimeTest.java
> +        {
@tarilabs yes, it is enough. If we want to test the clone() context operation, it should be in its own test.

2017-09-12 07:23 UTC, akoufoudakis commented
@baldimir Thanks for your comments previously. Should we run checks? I don't have access rights to do it. Can anyone else initiate the checks?

2017-09-12 07:25 UTC, baldimir commented
Jenkins test again

2017-09-12 08:10 UTC, akoufoudakis commented
@baldimir Thanks for running the check. "All checks have passed".

2017-09-13 12:19 UTC, etirelli approved these changes
Looks good.

2017-09-13 12:23 UTC, merged