DROOLS-2274 support '?' variable in decision tables
apache/incubator-kie pull request #1747
Opened 2018-02-05 02:00 UTC by kurobako

https://issues.jboss.org/browse/DROOLS-2274

2018-02-05 02:26 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNEvaluatorCompiler.java
> +            ctx.setVariable("?", model.getTypeRegistry().resolveType(DMNModelInstrumentedBase.URI_FEEL, "string"));
this doesn't look correct. The type of ? is the same type as the inputEntry, not hard coded string.

2018-02-05 02:27 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNEvaluatorCompiler.java
> +                    Collections.singletonMap("?", inputExpressionText),
not sure about this...

2018-02-05 02:27 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNFEELHelper.java
> +            feelctx.addInputVariable( entry.getKey(), entry.getValue() );
the value of ? is not known at compile time, only its type.

2018-02-05 09:14 UTC, kurobako commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNFEELHelper.java
> +            feelctx.addInputVariable( entry.getKey(), entry.getValue() );
@etirelli not sure what you mean. if ? should serve as a placeholder for the header, how come its value is not known?

2018-02-05 14:42 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNFEELHelper.java
> +            feelctx.addInputVariable( entry.getKey(), entry.getValue() );
@kurobako ? is a variable, and its value is only known at runtime. Maybe the confusion is that you think "?" is a macro to replace with the "text" of the header, but it is not. It is really a variable... it could have been called "myVariable", but it was called "?" in the 1.2 spec.

2018-02-06 18:21 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNEvaluatorCompiler.java
> +                    c.setValue("?", compiledInput.evaluate(c));
@kurobako although this is technically correct, I think we will face a performance issue because it will force the expression to be re-evaluated for each row of the decision table. In our example, it means that if our input expression is Person.name and the decision table has 1000 rows, this will be evaluated 1000 times. We need to set this in the context outside of the lambda as I mentioned in the e-mail.

2018-02-06 18:36 UTC, kurobako commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNEvaluatorCompiler.java
> +                    c.setValue("?", compiledInput.evaluate(c));
@etirelli I see. I was afraid evaluation context might be different outside of lambda and we get different value. I will rewrite this part

2018-02-08 09:54 UTC, baldimir requested changes

2018-02-08 09:54 UTC, baldimir commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/DMNRuntimeTest.java
> +    public void testDROOLS2274() {
Please name the test based on the functionality it tests. I know there are other tests with JIRA numbers, but that's not a good practice, because it removes the "quicklook what the test is about" possibility.

2018-02-08 12:33 UTC, kurobako commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/DMNRuntimeTest.java
> +    public void testDROOLS2274() {
sure, not a problem

2018-05-03 00:58 UTC, closed without merging

2018-05-03 00:58 UTC, etirelli commented
Closing as this PR was replaced by #1890