PMML_Refactor
apache/incubator-kie pull request #1884
Opened 2018-05-01 23:38 UTC by lanceleverich

Moved PMML generation of Java classes to KnowledgeBuilderImpl and removed it from KieBuilderImpl.

2018-05-03 07:37 UTC, baldimir requested changes
Please see my comments.

2018-05-03 07:37 UTC, baldimir commented on drools-compiler/src/main/java/org/drools/compiler/builder/impl/KnowledgeBuilderImpl.java
> +//                results.addMessage(problem);
Empty loop here. Either please remove it or handle the warnings.

2018-05-03 07:37 UTC, baldimir commented on drools-compiler/src/main/java/org/drools/compiler/builder/impl/KnowledgeBuilderImpl.java
> +    private static final int PARALLEL_RULES_BUILD_THRESHOLD = 10;
This shouldn't be here. It was removed recently. Please check if you have rebased the latest changes.

2018-05-03 07:37 UTC, baldimir commented on drools-compiler/src/main/java/org/drools/compiler/builder/impl/KnowledgeBuilderImpl.java
> +        System.out.println("!!!!! PMMLCompiler version = "+compiler.getCompilerVersion()+" !!!!!");
Sysout here, please use logger or remove it.

2018-05-03 07:37 UTC, baldimir commented on drools-compiler/src/main/java/org/drools/compiler/builder/impl/KnowledgeBuilderImpl.java
> +            // TODO Auto-generated catch block
This exception is swallowed here. Please handle it correctly.

2018-05-03 07:37 UTC, baldimir commented on drools-compiler/src/main/java/org/drools/compiler/builder/impl/KnowledgeBuilderImpl.java
> +                System.out.println(name);
Sysout here, please remove it or use logger.

2018-05-09 06:36 UTC, baldimir commented on drools-compiler/src/main/java/org/drools/compiler/builder/impl/KnowledgeBuilderImpl.java
> +        List<PackageDescr> pkgDescrs = new ArrayList<>();
Nitpicking: Please doublecheck if the indentation in this method is with tabs or spaces. It looks like tabs are used.

2018-05-09 06:37 UTC, baldimir commented on drools-compiler/src/main/java/org/drools/compiler/builder/impl/KnowledgeBuilderImpl.java
> +        File dumpDir = this.configuration.getDumpDir();
Nitpicking: Please doublecheck if the indentation in this method is with tabs or spaces. It looks like tabs are used.

2018-05-09 06:42 UTC, baldimir commented on drools-compiler/src/main/java/org/drools/compiler/builder/impl/KnowledgeBuilderImpl.java
> +            for (String key: res.getRules().keySet()) {
Sorry missed this in the first review. This could iterate over entrySet. It is more performant than iterating keys and always getting value based on the key.

```
for (Map.Entry<String, String> entry : res.getRules().entrySet()) {
    String key = entry.getKey();
    String src = entry.getValue();
    ...
 }
```

2018-05-09 06:44 UTC, baldimir commented on drools-compiler/src/main/java/org/drools/compiler/builder/impl/KnowledgeBuilderImpl.java
> +        for (String key: javaSources.keySet()) {
Again, you can iterate with entrySet here. See previous comment.

2018-05-09 06:46 UTC, baldimir commented
@lanceleverich thanks for fixes. I found other small things (sorry I missed them in the first review). Otherwise looks good. If these are fixed I will approve this.

2018-05-10 06:46 UTC, baldimir commented on drools-compiler/src/main/java/org/drools/compiler/builder/impl/KnowledgeBuilderImpl.java
> +        File dumpDir = this.configuration.getDumpDir();
This is still tab indented.

2018-05-10 06:47 UTC, baldimir commented on drools-compiler/src/main/java/org/drools/compiler/builder/impl/KnowledgeBuilderImpl.java
> +                    for (PackageDescr descr: descrs) {
Again, tab indent.

2018-05-10 16:22 UTC, lanceleverich commented
I have searched for tab characters in the file, using vim in hex-mode, and cannot find any. I also used Atom editor with showInvisibles turned on (it will display hard tab characters), and could not find any tab characters.

2018-05-11 06:28 UTC, baldimir approved these changes

2018-05-11 06:30 UTC, baldimir commented
Thanks, approved.

2018-05-14 08:05 UTC, merged