JBPM-7266 Eagerly open connection
apache/incubator-kie pull request #1939
Opened 2018-06-06 06:10 UTC by rsynek

[DO NOT MERGE]

Fix to jBPM issue with Narayana and DBCP connection pooling DS proposed by @mswiderski

2018-06-07 05:54 UTC, baldimir commented
jenkins retest this

2018-06-11 10:49 UTC, rsynek commented
jenkins retest this

2018-07-09 07:35 UTC, baldimir approved these changes

2018-07-09 14:22 UTC, rsynek commented
@mariofusco could you please take a look? There are another PRs in jBPM depending on this one. Thanks!

2018-07-10 11:19 UTC, rsynek commented
execute full downstream build

2018-07-10 12:42 UTC, rsynek commented
jenkins execute full downstream build

2018-07-10 16:58 UTC, mariofusco commented
@rsynek This change seems to have broken some persistence related tests in optaplanner. Please check them before I merge this pull request.

2018-07-11 06:30 UTC, rsynek commented
@mariofusco yes - very likely the same changes with DBCP pooling datasource will be required for OptaPlanner persistence too. I will hopefully get to it today.

2018-07-12 08:28 UTC, rsynek commented
jenkins execute full downstream build

2018-07-13 07:21 UTC, rsynek commented
Fixed the corresponding TransactionManager changes in jBPM.

2018-07-13 07:21 UTC, rsynek commented
jenkins execute full downstream build

2018-07-13 11:10 UTC, rsynek commented
Recent failures are not connected to this PR. Will retry the FDB once it's resolved.

2018-07-16 07:02 UTC, rsynek commented
jenkins execute full downstream build

2018-07-17 06:59 UTC, rsynek commented
PR check on jBPM and this FDB show failures in modules that were not covered by preliminary testing. Merging will have to wait until these are resolved.

2018-07-17 11:05 UTC, rsynek commented
jenkins retest this

2018-08-17 08:13 UTC, rsynek commented
jenkins execute full downstream build

2018-08-24 09:40 UTC, rsynek commented
jenkins execute full downstream build

2018-10-25 12:26 UTC, rsynek commented
jenkins retest this

2018-10-25 12:38 UTC, rsynek commented
@baldimir @mariofusco the PR has been changed significantly; could you please review once more? The aim is to reuse the code - except for PersistenceUtil - in jBPM too.

2018-10-25 12:52 UTC, baldimir commented on kie-test-util/src/main/java/org/kie/test/util/db/DataSourceFactory.java
> +final public class DataSourceFactory {
Nitpicking: public final

2018-10-25 12:59 UTC, baldimir requested changes
Other than the comments, please check "final" keyword usage consistency.

2018-10-25 12:59 UTC, baldimir commented on kie-test-util/src/main/java/org/kie/test/util/db/DataSourceFactory.java
> +                for (String propertyName : new String[]{"databaseName", "portNumber", "serverName", "url"}) {
You can join this with MYSQL and MARIADB.. they are the same.

2018-10-25 12:59 UTC, baldimir commented on kie-test-util/src/main/java/org/kie/test/util/db/DataSourceFactory.java
> +                for (String propertyName : new String[]{"databaseName", "portNumber", "serverName", "url"}) {
You can join this with MYSQL and MARIADB.. they are the same.

2018-10-25 12:59 UTC, baldimir commented on kie-test-util/src/main/java/org/kie/test/util/db/DataSourceFactory.java
> +                for (String propertyName : new String[]{"serverName", "portNumber", "databaseName"}) {
You could do this like you will fill serverName, portNumber, databaseName for all cases and then add url for the remaining ones.

2018-10-25 13:11 UTC, rsynek commented
@baldimir thanks for the review, fixed (changed the DB checking a little bit differently, though).

2018-10-25 13:12 UTC, baldimir approved these changes
Approving if checks are green.

2018-10-25 13:14 UTC, rsynek commented
@baldimir there might be a PR to OptaPlanner required before we run FDB, will check.

2018-10-26 09:10 UTC, rsynek commented
jenkins execute full downstream build

2018-10-26 09:11 UTC, rsynek commented
@baldimir fixed the setup for OptaPlanner, running the FDB, let's see.

2018-10-26 11:31 UTC, rsynek commented
jenkins execute full downstream build

2018-10-30 13:07 UTC, rsynek commented
jenkins execute full downstream build

2018-10-31 07:40 UTC, mswiderski approved these changes

2018-10-31 07:51 UTC, rsynek commented
FDN build failed due to enforcer rules; already fixed in a related PR to jBPM.

2018-10-31 07:52 UTC, rsynek commented
jenkins execute full downstream build

2018-10-31 14:49 UTC, merged