DROOLS-2719 DMN DecisionService backport on DMN v1.1
apache/incubator-kie pull request #1986
Opened 2018-07-18 14:33 UTC by tarilabs

2018-07-18 14:41 UTC, tarilabs reviewed
some comments.

2018-07-18 14:41 UTC, tarilabs commented on kie-dmn/kie-dmn-api/src/main/java/org/kie/dmn/api/core/DMNRuntime.java
> +    DMNResult evaluateDecisionService(DMNModel model, DMNContext context, String decisionServiceName);
new public API method (minimal)

2018-07-18 14:41 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DMNBaseNode.java
> +                parent = parent.getParent();
this was a bug, lingering there. Corrected as part of this pr.

2018-07-18 14:41 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DMNDecisionServiceEvaluator.java
> +        if (decisionIDs.size() == 1 && coerceSingletonResult) {
coercion of singleton output Decision Service as discussed.

2018-07-18 14:41 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DecisionServiceNodeImpl.java
> +        throw new UnsupportedOperationException("A Decision Service has no dependency");
> a Decision Service has no Dependency

2018-07-18 14:41 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DecisionServiceNodeImpl.java
> +    public Map<String, DMNNode> getInputParameters() {
InputParameters is list of InputData following by list of InputDecision. Please notice order is retained. DMNNode is required when identifying input of importED inputs.

2018-07-18 14:41 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNCompilerHelper.java
> +    public static void reportMissingVariable(DMNModelImpl model, NamedElement node, DMNModelInstrumentedBase source, Msg.Message1 message) {
Because of backport onto v1.1, the DecisionService is a `NamedElement`, not a DRGElement.
Also `NamedElement` was sufficient for the scope of this method anyway.

2018-07-18 14:41 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNCompilerImpl.java
> +                        // the introduction of an on-the-fly ItemDefinition has been removed. The variable type will be evaluated as feel:any, or in v1.2 will receive the (user-defined, explicit) Ite
removed artificial introduction of ItemDefinition as discussed with Edson

2018-07-18 14:41 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNCompilerImpl.java
> +    public DMNType resolveTypeRef(DMNModelImpl dmnModel, NamedElement model, DMNModelInstrumentedBase localElement, QName typeRef) {
`DMNNode node, ` parameter was in fact, not used.

2018-07-18 14:41 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/impl/DMNRuntimeImpl.java
> +    public DMNResult evaluateDecisionService(DMNModel model, DMNContext context, String decisionServiceName) {
This represent a call from the end-user of the public API to evaluate a Decision Service.

2018-07-18 14:41 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/impl/DMNRuntimeImpl.java
> +    private void evaluateDecisionService(DMNContext context, DMNResultImpl result, DecisionServiceNode d, boolean typeCheck) {
this instead happens when a Decision Service is being evaluated as part of a general model evaluation, for instance a Decision depends on a Decision Service as a requirement, the result will be a function when called will trigger the evaluation of the DS

2018-07-18 14:41 UTC, tarilabs commented on kie-dmn/kie-dmn-model/src/main/java/org/kie/dmn/model/v1_1/DecisionService.java
> +    private InformationItem variable;
required for having this backport forward compatible with v1.2

2018-07-18 14:43 UTC, tarilabs commented
/cc @etirelli @baldimir @winklerm this despite several commits through time is really the minimal implementation I can realistically expect can be merged on master.

I have some doubts for other "use-cases", for example when a Decision Service encapsulates a Decision which depends on an imported Decision Service, but given the new agile approach I will follow-up with another JIRA and PR later

2018-07-18 17:03 UTC, tarilabs commented
```
Build timed out (after 85 minutes). Marking the build as aborted.
18:27:54 Build was aborted
```

Please bear in mind this is building fine locally.

Jenkins test again

2018-07-18 17:57 UTC, tarilabs commented
Jenkins test again

2018-07-19 08:00 UTC, baldimir requested changes
Please see my comment.

2018-07-19 08:00 UTC, baldimir commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DMNDecisionServiceEvaluator.java
> +        return new EvaluatorResultImpl(evaluatorResultValue, ResultType.SUCCESS);
Please consider other ResultType(s) for cases when the evaluation fails. Currently it always return SUCCESS.

2018-07-19 08:17 UTC, baldimir approved these changes

2018-07-19 09:39 UTC, tarilabs commented
```
Test Result (20 failures / +20)
org.kie.pmml.pmml_4_2.KieBaseTest.testKieBaseCompilation
org.kie.pmml.pmml_4_2.predictive.models.DecisionTreeTest.testSimpleTree
org.kie.pmml.pmml_4_2.predictive.models.DecisionTreeTest.testReturnLastNoTrueChildPredictionStrategy
org.kie.pmml.pmml_4_2.predictive.models.DecisionTreeTest.testReturnNullNoTrueChildPredictionStrategy
org.kie.pmml.pmml_4_2.predictive.models.DecisionTreeTest.testTreeFromMiningModel
org.kie.pmml.pmml_4_2.predictive.models.DecisionTreeTest.testMissingTreeWeighted1
org.kie.pmml.pmml_4_2.predictive.models.DecisionTreeTest.testMissingTreeWeighted2
org.kie.pmml.pmml_4_2.predictive.models.DecisionTreeTest.testWeightedConfidenceMissingValueStrategy
org.kie.pmml.pmml_4_2.predictive.models.DecisionTreeTest.testMissingTree
org.kie.pmml.pmml_4_2.predictive.models.DecisionTreeTest.testDefaultChildMissingValueStrategy
org.kie.pmml.pmml_4_2.predictive.models.DecisionTreeTest.testNullPredictionMissingValueStrategy
org.kie.pmml.pmml_4_2.predictive.models.DecisionTreeTest.testLastPredictionMissingValueStrategy
org.kie.pmml.pmml_4_2.predictive.models.DecisionTreeTest.testTreeWithNumericValueOutcome
org.kie.pmml.pmml_4_2.predictive.models.MiningmodelTest.testSum
org.kie.pmml.pmml_4_2.predictive.models.MiningmodelTest.testSelectFirstSegmentFirst
org.kie.pmml.pmml_4_2.predictive.models.MiningmodelTest.testSelectSecondSegmentFirst
org.kie.pmml.pmml_4_2.predictive.models.MiningmodelTest.testWithScorecard
org.kie.pmml.pmml_4_2.predictive.models.MiningmodelTest.testWeightedAverage
org.kie.pmml.pmml_4_2.predictive.models.MiningmodelTest.testWithRegression
org.kie.pmml.pmml_4_2.predictive.models.MiningmodelTest.testSimpleModelChain
```

unrelated

2018-07-19 09:39 UTC, tarilabs commented
Jenkins test again

2018-07-19 10:10 UTC, baldimir commented
@lanceleverich could you please take a look at the failures? They are in PMML stuff.

2018-07-19 10:48 UTC, tarilabs commented
@lanceleverich just for tracking the build# which failed the PMML test was: https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/drools-pullrequests/2082/

2018-07-19 17:16 UTC, lanceleverich commented
I saw those errors when I was building locally, until I did a pull that included fix DROOLS-2767. After that pull, the errors went away.

2018-07-20 12:30 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DMNBaseNode.java
> +                parent = parent.getParent();
+1

2018-07-20 12:33 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DecisionServiceNodeImpl.java
> +        throw new UnsupportedOperationException("A Decision Service has no dependency");
I think the setDependencies() and addDependecy() methods should throw an exception, but the getDependecies() method should simply return either null or empty map... this makes implementation of visitors much easier as we don't need to trap exceptions on get methods...

2018-07-20 12:37 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/impl/DMNRuntimeImpl.java
> +    private void evaluateDecisionService(DMNContext context, DMNResultImpl result, DecisionServiceNode d, boolean typeCheck) {
As part of another feature, I would like to create callback methods for both "before/after invoke BKM/DS", so that we can report on actual execution of BKMs and Decision Services. But this is a conversation for another day.

2018-07-20 12:38 UTC, etirelli approved these changes

2018-07-20 12:58 UTC, merged