Improve DMN execution performance
apache/incubator-kie pull request #1997
Opened 2018-07-27 08:03 UTC by ignacio-ifm

The DMN feel evaluation runs the same Java reflection calls for previously seen Objects, which is not performant. A cache of known accessors is added to avoid useless computation. The cache is a simple HashMap and thus does not have an eviction policy. This has an impact on memory but it is assumed that the amount of different Classes mapped to DMN rules is neglible for a single application and is naturally bounded.

Additionally, a cache is added to the normalization of variable names that was also detected as a performance bottleneck, same logic applies there.

On a simple perfomance test agains a similar boolean rule using DRL the results are:
Before: DMN is x5 times slower than DRL
After: DMN is x2 times slower than DRL

2018-07-27 08:18 UTC, kiereleaseuser2 commented
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

2018-07-27 08:18 UTC, kiereleaseuser2 commented
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

2018-07-27 08:25 UTC, triceo commented
ok to test

2018-07-27 17:24 UTC, mariofusco requested changes
Should this stuff be thread safe? If not it's ok, but I'd keeè only the cache of the accessor method and not of the regular expression.

2018-07-27 17:24 UTC, mariofusco commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/EvalHelper.java
> +		if (normalizationCache.containsKey(name)){
Are we caching the result of the application of a regular expression to a String here? Unless there are very good reason to do this, and we can demonstrate it with a benchmark, this seems really a bad idea.

2018-07-27 17:24 UTC, mariofusco commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/EvalHelper.java
> +        String accessorQualifiedName = new StringBuilder(clazz.getCanonicalName())
Caching an accessor method could make a bit more sense. Maybe we can just make it nicer using the computeIfAbsent() method.

2018-07-30 06:48 UTC, baldimir requested changes
Hi, sorry this won't work without cache eviction, because of incremental compilation. Imagine a new version of kjar is loaded at runtime with different definitions. This cache will contain the first versions forever.

2018-07-30 08:08 UTC, ignacio-ifm commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/EvalHelper.java
> +		if (normalizationCache.containsKey(name)){
Although in my tests it showed about 10% performance improvement I'll focus the PR in the reflection side, which has the bigger impact. So I removed this improvement.

2018-07-30 08:11 UTC, ignacio-ifm commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/util/EvalHelper.java
> +        String accessorQualifiedName = new StringBuilder(clazz.getCanonicalName())
Yes, computeIfAbsent() made it nicer!

I didn´t quite get the "Caching an accessor method could make a bit more sense" part. I built the string as key because otherwise you would need a map within a map (clazz > field > Method) and would make the look up slower. You suggest something else as key?

2018-07-30 08:17 UTC, ignacio-ifm commented
@mariofusco I changed it to a ConcurrentHashMap for Thread safety.

@baldimir what eviction strategy would you recommend that covers the dynamic loading case and still improves the performance? Maybe a direct eviction when the reload is detected? Can you point me where in the code would that happen?

2018-07-31 13:58 UTC, tarilabs commented
Hi @ignacio-ifm
thank you for this PR. Unfortunately without a mechanism for eviction the cache would actually create troubles during a KieContainer upgrade use-case. The KieContainer upgrade was/is a foreseen use-case, but we didn't have an explicit JUnit test for this in the codebase; I added it as part of PR #2000 .

2018-07-31 13:59 UTC, tarilabs commented
Jenkins test again

2018-07-31 16:14 UTC, tarilabs requested changes
Demonstrated by #2000 problem with cache without eviction policy. @mariofusco do you have a suggestion for a callback to be placed in `EvalHelper`, please?

2018-08-16 12:44 UTC, kiereleaseuser2 commented
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

2018-08-17 09:20 UTC, ghost commented
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

2018-08-24 11:15 UTC, tarilabs commented
(I am working on a proposal for a cache eviction based on the original content of this PR, preserving commit authoring --will keep posted)

2018-08-27 09:51 UTC, tarilabs commented
@ignacio-ifm unfortunately the master branch diverged quite a bit in the meantime, so this requires a rebase. Let me know if that is feasible from your side to rebase, otherwise I will create on my side a new PR (preserving commit authoring as possible) with all changes.

2018-08-27 11:38 UTC, ignacio-ifm commented
@tarilabs I did the rebase. There was a minor conflict on some imports with a strange org.kie.dmn.model.api.(v1_1).Definitions I kept the ones without the version.

Please check.

2018-08-27 11:42 UTC, tarilabs commented
> There was a minor conflict on some imports 

Correct, this package changed in between when this PR originally raised, and currently on master, hence the git diff unmatched because it was in the nearby lines of the diff.

2018-08-27 13:01 UTC, tarilabs approved these changes

2018-08-27 13:01 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/assembler/DMNAssemblerService.java
> +        EvalHelper.clearGenericAccessorCache();
@mariofusco cache eviction has been added. Can you kindly merge with squash and title "`DROOLS-2923 Improve DMN execution performance`", please?

2018-08-27 13:07 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/assembler/DMNAssemblerService.java
> +        EvalHelper.clearGenericAccessorCache();
(better to rename the PR title as well with the same, but I don't have authorization to do it)

2018-08-28 08:35 UTC, merged

2018-08-28 09:18 UTC, tarilabs commented
@ignacio-ifm thanks again and this was merged with the cache eviction discussed.

I seize the chance to mention that we are currently working on a next generation of optimisations which will include benefit also for FEEL evaluations too. We will update the Release Notes and communicate when this will be available, I suggest for you to eventually try that out too, and feedback will be appreciated.

2018-08-28 16:49 UTC, ignacio-ifm commented
@tarilabs That sounds great. I'll do. Thanks!