DROOLS-2972 Don't use Collections.emptyList() as a class provided to PMML template
apache/incubator-kie pull request #2060
Opened 2018-09-10 12:04 UTC by baldimir

- This fixes the failing Scorecard tests

Collections.emptyList() returns an EmptyList instance, which is then checked with reflection during RuleUnit generation process - mvel tries to call size() on the EmptyList through reflection, which fails, because EmptyList is an internal private class of Collections class (so it is not accessible with reflection). 

@jiripetrlik @lanceleverich please be aware that the randomness of the failures indicates that there might be another bug in the RuleUnit generation process, because it implies that EmptyList class was not generated all the time for the RuleUnit. Mentioning this because it could be a good area to extend test coverage, so we find out what is going on in case of the randomness.

2018-09-10 12:24 UTC, baldimir commented
The plan is to run 10 Jenkins runs without any Scorecard test fail, 5 to go. (I will keep updating this comment)

2018-09-10 13:32 UTC, baldimir commented
Fail not related.

2018-09-10 13:33 UTC, baldimir commented
jenkins retest this

2018-09-10 18:49 UTC, triceo requested changes
This is a weird quirk. IMHO Should be centralized and documented.

2018-09-10 18:49 UTC, triceo commented on kie-pmml/src/main/java/org/kie/pmml/pmml_4_2/PMML4Compiler.java
> +        return (resources != null) ? resources : new ArrayList<>();
If it's so important to not have `Collections.emptyList()` here, perhaps there should be a comment saying so? Otherwise I can just see some smart code reviewer "fixing this" in the future.

2018-09-10 18:49 UTC, triceo commented on kie-pmml/src/main/java/org/kie/pmml/pmml_4_2/model/PMMLDataField.java
> +    	return new ArrayList<>();
And while we're doing that, let's size the list to `0` so that we don't waste memory needlessly.

2018-09-10 18:49 UTC, triceo commented on kie-pmml/src/main/java/org/kie/pmml/pmml_4_2/model/AbstractModel.java
> +        return list != null ? list : new ArrayList<>();
In fact, thinking about it, perhaps there should be a utility method that does that, with the proper comment?

2018-09-11 02:37 UTC, lanceleverich commented on kie-pmml/src/main/java/org/kie/pmml/pmml_4_2/model/AbstractModel.java
> +        return list != null ? list : new ArrayList<>();
The fix proposed here may address some issue, but it does not address the issue that I have seen with drools-scorecards; mainly that there are some tests that periodically fail. I have applied the fixes from this PR to my local machine and I still get the intermittent errors in the ScorecardReasonCodeTest. Please see https://issues.jboss.org/browse/DROOLS-2592 to see my latest notes and results from my testing.

2018-09-11 06:49 UTC, baldimir commented on kie-pmml/src/main/java/org/kie/pmml/pmml_4_2/model/AbstractModel.java
> +        return list != null ? list : new ArrayList<>();
Yes @lanceleverich, this fix addresses just 25 scorecards tests that were failing at the same time. I can take a look on that other issue in another PR if needed.

2018-09-11 06:50 UTC, baldimir commented on kie-pmml/src/main/java/org/kie/pmml/pmml_4_2/model/AbstractModel.java
> +        return list != null ? list : new ArrayList<>();
@triceo I don't think that a utility method for a oneliner is necessary.

2018-09-11 07:03 UTC, baldimir commented on kie-pmml/src/main/java/org/kie/pmml/pmml_4_2/PMML4Compiler.java
> +        return (resources != null) ? resources : new ArrayList<>();
Removed the whole method, because I found out it was not used anywhere.

2018-09-11 07:03 UTC, baldimir commented on kie-pmml/src/main/java/org/kie/pmml/pmml_4_2/model/PMMLDataField.java
> +    	return new ArrayList<>();
Removed the whole method, because I found out it was not used anywhere.

2018-09-11 07:04 UTC, baldimir commented on kie-pmml/src/main/java/org/kie/pmml/pmml_4_2/model/AbstractModel.java
> +        return list != null ? list : new ArrayList<>();
@triceo comment and initial size added.

2018-09-11 07:04 UTC, baldimir commented
jenkins retest this

2018-09-11 07:24 UTC, triceo approved these changes

2018-09-11 07:57 UTC, baldimir commented
@lanceleverich just a note for future work - we need to cleanup the PMML code, because there are e.g. many unused methods. Would you mind if I do it when having a bit of time?

2018-09-11 08:02 UTC, jiripetrlik commented
@baldimir 
+1 for cleanup of unused methods. It would be really useful.

2018-09-11 08:02 UTC, jiripetrlik approved these changes

2018-09-11 09:40 UTC, baldimir commented
jenkins retest this

2018-09-11 11:48 UTC, baldimir commented
jenkins retest this

2018-09-11 13:47 UTC, baldimir commented
jenkins retest this

2018-09-12 06:57 UTC, merged