JBPM-7685: disabling pooling from Narayana
apache/incubator-kie pull request #2092
Opened 2018-10-03 17:06 UTC by mareknovotny

this a tryout to disable Narayana database connection pooling for tests.

related to https://github.com/kiegroup/droolsjbpm-integration/pull/1554

2018-10-04 08:47 UTC, rsynek requested changes

2018-10-04 08:47 UTC, rsynek commented on kie-test-util/src/main/java/org/kie/test/util/db/PoolingDataSource.java
> +        properties.put(TransactionalDriver.poolConnections, false);
The `Properties` class is a bit misused in the `TransactionalDriver`, but this particular property is accessed as a property - it's a `String`, not `Boolean`. Please see https://github.com/jbosstm/narayana/blob/5.9.0.Final/ArjunaJTA/jdbc/classes/com/arjuna/ats/internal/jdbc/ConnectionManager.java#L61.

2018-10-17 10:53 UTC, mareknovotny commented
Jenkins retest this

2018-10-23 12:55 UTC, mareknovotny commented
@krisv @mariofusco @baldimir can one of you look at the issues while dbcp is disabled?

2018-10-23 12:59 UTC, baldimir commented
@rsynek tagging you so you get notified about everything Narayana related.

2018-10-23 14:09 UTC, mareknovotny commented
ok, one idea showed up, so my best effort ends here to changed `persistence.xml`

2018-10-24 06:59 UTC, mareknovotny commented
So this test results correspond with FDB in https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/804

2018-10-31 16:55 UTC, mareknovotny commented
so @rsynek did update the persistence test code, so this should not be needed.

2018-10-31 16:55 UTC, closed without merging