DO NOT MERGE [DROOLS-3112] FEEL Compiler: modularize FEELImpl compiler/interpreter vs. DMNFEELHelper
apache/incubator-kie pull request #2112
Opened 2018-10-17 15:08 UTC by evacchi

Waiting for #2107 to be merged before merging this

Summary:

- added new method in FEEL interface to compile unary tests
- removed most compilation-related logic from DMNFEELHelper
- reduced API surface in CompilerBytecodeLoader 
- the classes in the ProcessedFEELUnit (ProcessedExpression and ProcessedUnaryTest) provide all the methods to return the compilable, interpretable, or source code version of the given expression (or the given unary test sequence)

e.g. usage (pseudocode)

```java
CompiledExpression compiled = feel.compile(expr, compilerCtx)
var r = feel.evaluate(compiled, evalCtx) // will use current mode set in feel instance (compiled or interpreted)
// you can also explicitly request the version you want
var pe = (ProcessedExpression) compiled;
CompiledExecutableExpression cee = pe.getCompiled();
InterpretedExecutableExpression iee = pe.getInterpreted()

// we can still eval' these:
var r1 = feel.evaluate(cee, evalCtx);
var r2 = feel.evaluate(iee, evalCtx);

// we can use the source code for $stuff (e.g. used in DMN to generate wrapper classes)
CompilationUnit cu = pe.getSourceCode();

```

same as above is for UnaryTests, but 

```java
CompiledExpression compiled = feel.compile(expr, compilerCtx)
var r = feel.evaluate(compiled, evalCtx) 
```
is always **interpreted** (that's how it's working now)
you can always request the compiled or the source code version, using 

```java
var pe = (ProcessedUnaryTest) compiled;
var cut = pe.getCompiled();
var iut = pe.getInterpreted()
var cu = pe.getSourceCode();
```

2018-10-23 07:10 UTC, baldimir commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/ast/DMNLiteralExpressionEvaluator.java
> +                || expression instanceof ProcessedExpression && ((ProcessedExpression) expression).getInterpreted().isFunctionOhNoWhyAreYouDoingThis() ;
isFunctionOhNoWhyAreYouDoingThis()? :D

2018-10-23 08:13 UTC, baldimir requested changes
Please see comments. Nothing major.

2018-10-23 08:13 UTC, baldimir commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNCompilerContext.java
> +        if (v.isCollection()) return BuiltInType.LIST;
Please write this with braces for maintainability purposes. (Writing from my previous experience)

2018-10-23 08:13 UTC, baldimir commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNFEELHelper.java
> +        ProcessedUnaryTest compiledUnaryTest = ((FEELImpl) feel).compileUnaryTests(unaryTests, compilerContext);
We might consider using FEELImpl directly in this helper class if we need to cast it. But just for consideration. I don't like casts :)

2018-10-23 08:13 UTC, baldimir commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/codegen/feel11/ASTCompilerVisitor.java
> +        throw new UnsupportedOperationException("Not yet implemented");
Just a "notification comment" so you see this and it is not accidentally missed.

2018-10-23 08:13 UTC, baldimir commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/codegen/feel11/Contexts.java
> +            throw new UnsupportedOperationException("A Composite type is either MapBacked or JavaBAcked");
Nitpicking: Typos "neither" and "JavaBAcked"

2018-10-23 08:13 UTC, baldimir commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/codegen/feel11/Expressions.java
> +    private static final Expression QUANTIFIER_SOME = JavaParser.parseExpression("org.kie.dmn.feel.lang.ast.QuantifiedExpressionNode.Quantifier.SOME");
Could be used rather like this: 
`QuantifiedExpressionNode.Quantifier.class.getCanonicalName() + ".SOME"`

The same with `EVERY`. This helps with potential refactoring in the future.

2018-10-23 08:24 UTC, evacchi commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNFEELHelper.java
> +        ProcessedUnaryTest compiledUnaryTest = ((FEELImpl) feel).compileUnaryTests(unaryTests, compilerContext);
fully agree there

2018-11-21 13:20 UTC, evacchi commented
Jenkins execute full downstream build

2018-11-21 16:21 UTC, tarilabs commented
I believe this needs

```
    <dependency>
        <groupId>org.drools</groupId>
        <artifactId>drlx-parser</artifactId>
    </dependency>
```

in the `pom.xml` of `kie-dmn-core`.

2018-11-21 18:54 UTC, tarilabs approved these changes

2018-11-21 18:55 UTC, tarilabs commented
I am not sure we need the full downstream

Jenkins test again

2018-11-22 07:54 UTC, merged