DROOLS-3351 [DMN Designer] Font size information is not being persisted
apache/incubator-kie pull request #2169
Opened 2018-11-28 10:55 UTC by tarilabs

/cc @etirelli @baldimir @jiripetrlik

2018-11-28 12:55 UTC, etirelli approved these changes

2018-11-28 13:01 UTC, baldimir requested changes
One comment.

2018-11-28 13:01 UTC, baldimir commented on kie-dmn/kie-dmn-backend/src/test/java/org/kie/dmn/backend/marshalling/v1_2/UnmarshalMarshalTest.java
> +    private static final DMNMarshaller MARSHALLER = new org.kie.dmn.backend.marshalling.v1x.XStreamMarshaller();
This will share the marshaller instance between tests. Is that ok? It could be created as part of a `@Before` method. In that case a fresh clean marshaller instance will be used in each of the tests.

2018-11-28 14:03 UTC, tarilabs commented on kie-dmn/kie-dmn-backend/src/test/java/org/kie/dmn/backend/marshalling/v1_2/UnmarshalMarshalTest.java
> +    private static final DMNMarshaller MARSHALLER = new org.kie.dmn.backend.marshalling.v1x.XStreamMarshaller();
Indeed that's okay, the Mashaller is meant to be shared

2018-11-28 14:08 UTC, baldimir approved these changes

2018-11-28 14:10 UTC, tarilabs commented on kie-dmn/kie-dmn-backend/src/test/java/org/kie/dmn/backend/marshalling/v1_2/UnmarshalMarshalTest.java
> +    private static final DMNMarshaller MARSHALLER = new org.kie.dmn.backend.marshalling.v1x.XStreamMarshaller();
on second though I realized we are not really sharing it :D but I still believe it is fine with the current code in this PR, as the Marshaller at least is not meant to encapsulate any state. Keep as in current PR code would later show if any problem. Agree @baldimir ?

2018-11-29 09:01 UTC, tarilabs commented
Jenkins test again

2018-11-30 08:37 UTC, merged