[DROOLS-3380] minimize calls to feel variable names normalization
apache/incubator-kie pull request #2192
Opened 2018-12-12 13:30 UTC by mariofusco

2018-12-12 13:32 UTC, mariofusco commented
@etirelli @tarilabs I know the change looks trivial but benchmarks result are the following for me

BEFORE

Benchmark                                                          (dmnFileName)  Mode  Cnt    Score    Error  Units
DMNEvaluateDecisionNameLengthBenchmark.evaluateDecision  example_short_names.xml    ss   45  187.426 ± 10.207  ms/op
DMNEvaluateDecisionNameLengthBenchmark.evaluateDecision   example_long_names.xml    ss   45  328.034 ±  6.303  ms/op

AFTER

Benchmark                                                          (dmnFileName)  Mode  Cnt   Score   Error  Units
DMNEvaluateDecisionNameLengthBenchmark.evaluateDecision  example_short_names.xml    ss   45  77.886 ± 7.317  ms/op
DMNEvaluateDecisionNameLengthBenchmark.evaluateDecision   example_long_names.xml    ss   45  79.747 ± 4.470  ms/op

2018-12-12 13:34 UTC, etirelli commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/impl/DMNContextImpl.java
> +        return getCurrentEntries().get( EvalHelper.normalizeVariableName( name ) );
If the variable name is normalized on the set() method, is it necessary to normalize on the get() as well?

2018-12-12 13:36 UTC, mariofusco commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/impl/DMNContextImpl.java
> +        return getCurrentEntries().get( EvalHelper.normalizeVariableName( name ) );
@etirelli I'm not entirely sure tbh, I thought that somebody could ask for a value passing a non-normalized name, but I'll check what happens if I remove it.

2018-12-12 13:46 UTC, mariofusco commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/impl/DMNContextImpl.java
> +        return getCurrentEntries().get( EvalHelper.normalizeVariableName( name ) );
@etirelli You were right, normalization on get is also not necessary. New benchmark results are

Benchmark                                                          (dmnFileName)  Mode  Cnt   Score   Error  Units
DMNEvaluateDecisionNameLengthBenchmark.evaluateDecision  example_short_names.xml    ss   45  72.983 ± 3.376  ms/op
DMNEvaluateDecisionNameLengthBenchmark.evaluateDecision   example_long_names.xml    ss   45  70.427 ± 3.009  ms/op

Now the long names benchamark is around 4.5 times faster than before :)

2018-12-12 13:55 UTC, tarilabs commented
This is promising.
However, I am afraid this is breaking some of the prerequisites which originally @etirelli wrote in the README.md about FEEL being insensitive to number of spaces. If that is fine, this is good but won't be enough as the model nodes names will still need be normalized --just wild guessing I need to build a test case to actually confirm the problem.

2018-12-12 14:00 UTC, mariofusco commented
@tarilabs if you see a potential problem with this, I'd need a reproducer for it. We can delay this discussion to tomorrow if you're busy today, but that normalize method is clearly the elephant in the room and the more we avoid calling it the better it is.

2018-12-12 18:42 UTC, mariofusco commented
ok to test

2019-01-28 16:07 UTC, tarilabs commented
@mariofusco please rename this PR title to link to DROOLS-3563 instead. Thanks.

2019-06-27 13:28 UTC, tarilabs requested changes
As discussed there are safer and less-risky idea which can be implemented, and in turn that make this idea of minimizing surface of normalization less relevant.
You can please close this PR now.

2019-10-14 10:06 UTC, closed without merging