DO NOT MERGE: DROOLS-3594: adding support for interval-based algebra.
apache/incubator-kie pull request #2237
Opened 2019-02-03 16:19 UTC by etirelli

2019-02-04 22:38 UTC, etirelli commented
jenkins test this

2019-02-04 22:39 UTC, etirelli commented
@tarilabs @baldimir this is ready for your review.

2019-02-05 13:55 UTC, baldimir requested changes
See comments please.

2019-02-05 13:55 UTC, baldimir commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/interval/AfterFunction.java
> +                    ( range.getHighBoundary() == Range.RangeBoundary.OPEN && value.compareTo( range.getHighEndPoint() ) >= 0 );
You don't need to check that the boundary is OPEN, after checking it is CLOSED. Similarly as in the last invoke method comparing 2 ranges. This comment applies for all invokes with ranges (please check also other functions).

2019-02-05 13:55 UTC, baldimir commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/interval/FinishedByFunction.java
> +                    range1.getHighBoundary() == Range.RangeBoundary.CLOSED && range2.getHighBoundary() == Range.RangeBoundary.CLOSED &&
Is this boundary check necessary? This way we omit the OPEN boundaries.

2019-02-05 13:55 UTC, baldimir commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/interval/FinishesFunction.java
> +                    range1.getHighBoundary() == Range.RangeBoundary.CLOSED && range2.getHighBoundary() == Range.RangeBoundary.CLOSED &&
Same comment as in finishedBy about boundaries.

2019-02-05 13:55 UTC, baldimir commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/interval/StartedByFunction.java
> +            boolean result = ( range.getLowBoundary() == Range.RangeBoundary.CLOSED && value.compareTo( range.getLowEndPoint() ) == 0 );
Shouldn't this work also for open boundaries? I mean comparing with range.getLowBoundary() + 1?

2019-02-05 13:55 UTC, baldimir commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/interval/StartedByFunction.java
> +                    range1.getLowBoundary() == Range.RangeBoundary.CLOSED && range2.getLowBoundary() == Range.RangeBoundary.CLOSED &&
Same comment about boundaries as before. Shouldn't this work also with OPEN boundaries? Please think about that also regarding other functions. I won't comment that again, because I would have to put it are more places.

2019-02-05 13:55 UTC, baldimir commented on kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/functions/interval/StartsFunctionTest.java
> +        FunctionTestUtil.assertResult( startsFunction.invoke( "a",
Just an example of a case with OPEN boundaries as I commented before and should work: 

`        FunctionTestUtil.assertResult( startsFunction.invoke( "b",
                new RangeImpl( Range.RangeBoundary.OPEN, "a", "f", Range.RangeBoundary.CLOSED )),
                Boolean.FALSE );`

2019-02-05 19:04 UTC, etirelli commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/interval/AfterFunction.java
> +                    ( range.getHighBoundary() == Range.RangeBoundary.OPEN && value.compareTo( range.getHighEndPoint() ) >= 0 );
I believe I do need to check for OPEN, otherwise it would allow a CLOSED boundary to have a compareTo() result == 0. I could try to rewrite the complete expression as nested if's, but I think the alternative would be more complicated to understand and heavier from a performance perspective than just checking for OPEN and CLOSED. Please let me know if I misunderstood your suggestion.

2019-02-05 19:07 UTC, etirelli commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/interval/FinishedByFunction.java
> +                    range1.getHighBoundary() == Range.RangeBoundary.CLOSED && range2.getHighBoundary() == Range.RangeBoundary.CLOSED &&
Yes, the algebra is only defined for CLOSED intervals. In some cases, like the after() function, I relaxed the rules to allow for an OPEN interval. 
I guess, in this particular case, one can argue that as long as both boundaries are the same, either OPEN or CLOSED, this function would work, but I am not 100% sure of the side-effects of this assumption. 
If you think I *should* relax the restriction here, I can go ahead and change, but I would prefer to be on the safe side for this first implementation.

2019-02-05 19:08 UTC, etirelli commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/interval/FinishesFunction.java
> +                    range1.getHighBoundary() == Range.RangeBoundary.CLOSED && range2.getHighBoundary() == Range.RangeBoundary.CLOSED &&
See previous answer.

2019-02-05 19:09 UTC, etirelli commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/interval/StartedByFunction.java
> +            boolean result = ( range.getLowBoundary() == Range.RangeBoundary.CLOSED && value.compareTo( range.getLowEndPoint() ) == 0 );
No, you can't do +1 because we are talking about continuous intervals. We are not dealing with integer numbers, we are dealing with real numbers, and strings, etc.

2019-02-05 19:10 UTC, etirelli commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/interval/StartedByFunction.java
> +                    range1.getLowBoundary() == Range.RangeBoundary.CLOSED && range2.getLowBoundary() == Range.RangeBoundary.CLOSED &&
see previous answer.

2019-02-05 19:13 UTC, baldimir commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/interval/FinishedByFunction.java
> +                    range1.getHighBoundary() == Range.RangeBoundary.CLOSED && range2.getHighBoundary() == Range.RangeBoundary.CLOSED &&
Thanks for explanation. OK for of then as it is.

2019-02-05 19:16 UTC, etirelli commented on kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/functions/interval/StartsFunctionTest.java
> +        FunctionTestUtil.assertResult( startsFunction.invoke( "a",
No, that is not correct. The immediate successor of "a" is NOT "b". 
Lets use a simple example, we know that "a" < "b", but the following is also true: "a" < "aa" < "b". Also "a" < "aa" < "aaa" < "b". Etc.
In fact, since we are dealing with unicode characters here, the immediate successor of "a" is "a\u0000". But this will make practical use cases not viable, so I prefer to restrict the cases to closed intervals.

2019-02-05 19:17 UTC, etirelli commented
@baldimir thanks for the review, and please let me know if my answers make sense. In case I misunderstood any of your suggestions, please let me know and I will fix it.

2019-02-05 19:20 UTC, baldimir commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/interval/StartedByFunction.java
> +            boolean result = ( range.getLowBoundary() == Range.RangeBoundary.CLOSED && value.compareTo( range.getLowEndPoint() ) == 0 );
Yes agree, forgot about continous ranges here where there isn't a discrete step.

2019-02-05 19:24 UTC, baldimir commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/interval/AfterFunction.java
> +                    ( range.getHighBoundary() == Range.RangeBoundary.OPEN && value.compareTo( range.getHighEndPoint() ) >= 0 );
Yes you are right. How about the other way? Accepting all greater than 0 or OPEN equal 0? Either way this is just nitpicking. So I agree to have it also as it is.

2019-02-05 19:25 UTC, baldimir commented
Thanks Edson, yes they make sense. Will approve this.

2019-02-05 19:26 UTC, baldimir approved these changes

2019-02-06 15:17 UTC, merged