Test list contains for structures
apache/incubator-kie pull request #2256
Opened 2019-02-14 14:24 UTC by jomarko

@tarilabs I created this simple test where I check if an element is in a list, but the test fails. Could you please have a look if the test result is correct? I have this problem just if I work with structures. `list contains` function works fine if I use simple data types.

2019-02-14 15:13 UTC, tarilabs requested changes

2019-02-14 15:13 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/DMNRuntimeTest.java
> +        assertThat(result.get("is there"), is("true"));
@jomarko you are asserting the result to be the string literal `"true"`. The actual result is the literal boolean `true`.
from `"true"`
to `true`

2019-02-14 15:13 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/DMNRuntimeTest.java
> +        context.set("an employee", prototype(entry("age", 50)));
Number in a Map must be Java BigDecimal, as per other tests in the suite.
I know this might be slightly annoying but this is something we didn't support to date. /cc @etirelli

2019-02-15 04:46 UTC, jomarko commented
@tarilabs thank you, I updated the PR accordingly your comments and the test passes now, may I ask you for a re-review please?

2019-02-15 08:52 UTC, tarilabs approved these changes
minor comments and not really sure if this test is overlapping with already existing test; otherwise looks correct to me.

2019-02-15 08:52 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/DMNRuntimeTest.java
> +        // DROOLS-2416
I am not sure the JIRA reference is correct?

2019-02-15 08:52 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/DMNRuntimeTest.java
> +
can we avoid committing to lines which are not impacted to this PR please?

2019-02-15 09:22 UTC, jomarko commented
@tarilabs thank you, I updated the PR accordingly.

@baldimir could you also please have a look and advice if this PR overlays with existing tests? If yes, please close, otherwise please merge once green.

2019-02-15 09:54 UTC, baldimir approved these changes

2019-02-15 18:36 UTC, merged