Add or clause bug reproducer
apache/incubator-kie pull request #2276
Opened 2019-03-07 12:05 UTC by Fonifan

This test reproduces issue described in [PLANNER-1433](https://issues.jboss.org/browse/PLANNER-1433).

2019-03-08 07:29 UTC, rsynek requested changes

2019-03-08 07:29 UTC, rsynek commented on drools-compiler/src/test/java/org/drools/compiler/integrationtests/OrClauseTest.java
> +    public void testOrClause() {
@Fonifan would you please rename the test method to describe precisely what you're testing?

e.g: "twoConditionsInOrClause_shouldFireRuleOnce"

2019-03-08 09:36 UTC, mariofusco commented
The rule is firing twice and this is not a bug but just how Drools is intended to work. In Drools a rule with a 'or' is totally equivalent to having 2 separated rules. I agree that this is questionable, but we cannot change this, first because it would be very hard to fire the rule only once, and second because if we do so we will break backward compatibility.

2019-03-12 09:25 UTC, rsynek commented
Closing this PR as the behaviour we are experiencing turned out to be expected and the fix must be done in OptaPlanner.

2019-03-12 09:25 UTC, closed without merging