DROOLS-4061 : Guided Score card rules not executed via test scenario.
apache/incubator-kie pull request #2356
Opened 2019-05-21 16:55 UTC by Rikkola

2019-05-22 11:30 UTC, Rikkola commented
jenkins please execute full downstream build

2019-05-22 11:33 UTC, Rikkola commented on drools-workbench-models/drools-workbench-models-test-scenarios/src/main/java/org/drools/workbench/models/testscenarios/backend/ScenarioRunner.java
> +        } else {
Actual change is here.

2019-05-23 10:39 UTC, Rikkola commented
jenkins please execute full downstream build

2019-05-23 10:49 UTC, Rikkola commented
jenkins execute compile downstream build

2019-05-23 10:53 UTC, Rikkola commented
@mariofusco @lanceleverich Could you review please.

2019-05-23 11:35 UTC, Rikkola commented
@jomarko and others. This PR changes the test scenario runner to test runner for scorecards if the model name is set.

2019-05-30 08:14 UTC, jomarko commented
@Rikkola https://github.com/Rikkola/drools/pull/3, what do you think?

2019-05-30 12:02 UTC, jomarko reviewed
### Manual check
Passed

2019-06-04 07:19 UTC, jomarko approved these changes
Thank you.

2019-06-06 16:45 UTC, danielezonca requested changes

2019-06-06 16:45 UTC, danielezonca commented on drools-workbench-models/drools-workbench-models-test-scenarios/src/main/java/org/drools/workbench/models/testscenarios/backend/ScenarioPMMLRunner4JUnit.java
> +                    eachNotifier.addFailure(new IllegalArgumentException("Scorecard test can not contain " + fixture));
Why have you removed the `throw new`? It will be catch and added to eachNotifier directly there without duplicate the logic here

2019-06-06 16:45 UTC, danielezonca commented on drools-workbench-models/drools-workbench-models-test-scenarios/src/main/java/org/drools/workbench/models/testscenarios/backend/ScenarioRunner.java
> +                                     kieBase).run(new RunNotifier());
Can you explain the scope of this method? Used in this way it ignore all the failures

2019-06-06 16:45 UTC, danielezonca commented on drools-workbench-models/drools-workbench-models-test-scenarios/src/main/java/org/drools/workbench/models/testscenarios/backend/ScenarioRunner.java
> +        } else {
I don't really like this change, it creates a completely different code path to "plug" the new runner. Please add at least a comment or refactor it.
It is not that clear too that modelName != null means score card to test

2019-06-06 16:45 UTC, danielezonca commented on drools-workbench-models/drools-workbench-models-test-scenarios/src/test/java/org/drools/workbench/models/testscenarios/backend/Person.java
>      //    public void readExternal(ObjectInput in) throws IOException, ClassNotFoundException {
Commented code!!!!! :smile:

2019-06-06 16:45 UTC, danielezonca commented on drools-workbench-models/drools-workbench-models-test-scenarios/src/test/java/org/drools/workbench/models/testscenarios/backend/ScenarioRunnerTest.java
> +        verify(run).runScorecardTest(any(), any());
Is it possible to remove these `any`? I think you can use `eq(scenario)` and something similar for kieBase too

2019-06-06 16:45 UTC, danielezonca commented on drools-workbench-models/drools-workbench-models-test-scenarios/src/test/java/org/drools/workbench/models/testscenarios/backend/ScenarioRunnerTest.java
> +        verify(run, never()).runScorecardTest(any(), any());
Is it possible to remove these any? I think you can use eq(scenario) and something similar for kieBase too

2019-06-06 16:45 UTC, danielezonca commented on kie-pmml/src/test/java/org/kie/pmml/pmml_4_2/predictive/models/Helper.java
> +public class Helper {
What the scope of this class?

2019-06-07 11:45 UTC, Rikkola commented on drools-workbench-models/drools-workbench-models-test-scenarios/src/test/java/org/drools/workbench/models/testscenarios/backend/Person.java
>      //    public void readExternal(ObjectInput in) throws IOException, ClassNotFoundException {
The shame!

2019-06-07 12:15 UTC, Rikkola commented on drools-workbench-models/drools-workbench-models-test-scenarios/src/main/java/org/drools/workbench/models/testscenarios/backend/ScenarioPMMLRunner4JUnit.java
> +                    eachNotifier.addFailure(new IllegalArgumentException("Scorecard test can not contain " + fixture));
Now throws.

2019-06-07 12:17 UTC, Rikkola commented on kie-pmml/src/test/java/org/kie/pmml/pmml_4_2/predictive/models/Helper.java
> +public class Helper {
Removed.

2019-06-07 12:43 UTC, danielezonca approved these changes
Much better now, approved! :+1:

2019-06-17 05:06 UTC, Rikkola commented
Jenkins please retest this.

2019-08-19 11:28 UTC, mareknovotny commented
I think @Rikkola you need to run full downstream build from here as drools are not downstream for kie-wb-common repo

Jenkins execute full downstream build

2019-08-20 13:24 UTC, Rikkola commented
"org.kie.hacep.RemoteStreamingKieSessionImplTest.getListKieSessionObjectsTest"
From full downstream.

2019-08-20 13:59 UTC, mareknovotny commented
both failed tests are not related to the change

2019-08-21 08:01 UTC, merged