DROOLS-4156 DMN noname PMML model and DROOLS-4154
apache/incubator-kie pull request #2389
Opened 2019-06-14 09:17 UTC by tarilabs

@etirelli @baldimir @jiripetrlik

/cc @manstis @jomarko

2019-06-14 09:37 UTC, jomarko reviewed
Just one comment as I like discussion about code.

2019-06-14 09:37 UTC, jomarko commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/DMNEvaluatorCompiler.java
> +                                                          .filter(x -> x != null)
I think would be better to use variable name saying what is content of the stream (name, modelName ...) or the oppostie way, omit the variable name `.filter(Objects::nonNull)`

2019-06-14 09:40 UTC, jomarko commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/util/Msg.java
> +    public static final Message1 FUNC_DEF_PMML_MISSING_MODEL_NAME                    = new Message1( DMNMessageType.INVALID_SYNTAX, "The PMML function definition did not provide 'model' attribute, wh
Message looks good to me.

2019-06-14 12:04 UTC, manstis commented
Testing I get (adding a PMML document name but no model name):
```
[INFO] java.lang.NullPointerException: null
[INFO] 	at org.kie.dmn.core.compiler.DMNEvaluatorCompiler.compileFunctionDefinitionPMML(DMNEvaluatorCompiler.java:491)
[INFO] 	at org.kie.dmn.core.compiler.DMNEvaluatorCompiler.compileFunctionDefinition(DMNEvaluatorCompiler.java:335)
[INFO] 	at org.kie.dmn.core.compiler.DMNEvaluatorCompiler.compileExpression(DMNEvaluatorCompiler.java:144)
[INFO] 	at org.kie.dmn.core.compiler.DecisionCompiler.compileEvaluator(DecisionCompiler.java:125)
[INFO] 	at org.kie.dmn.core.compiler.DMNCompilerImpl.processDrgElements(DMNCompilerImpl.java:405)
[INFO] 	at org.kie.dmn.core.compiler.DMNCompilerImpl.compile(DMNCompilerImpl.java:224)
[INFO] 	at org.kie.dmn.core.compiler.DMNCompilerImpl.compile(DMNCompilerImpl.java:155)
[INFO] 	at org.kie.dmn.core.compiler.DMNCompilerImpl.compile(DMNCompilerImpl.java:139)
```
I'll investigate more after lunch.

2019-06-14 12:55 UTC, manstis commented
@tarilabs OK, the NPE has magically disappeared after lunch. Sweet.

However I find the WARNING reported for a missing PMML model name is not propagated through to the `IncrementalResults` returned by `org.drools.compiler.kie.builder.impl.KieBuilderSetImpl.buildChanges(..)`. This appears to only report ERROR messages in the incremental build mechanism. 

This can be demonstrated (using our infamous incremental build test) by first adding a `FunctionDefinition` for PMML with no PMML document or model name and building the `KieModule`. An ERROR is returned stating they need to be provided. Then perform an incremental build passing an updated DMN file that has the PMML document value complete. `DMNEvaluatorCompiler.compileFunctionDefinitionPMML(..)` will now report a WARNING due to the missing model value; however this message does not appear in the incremental build results.

The impact is that in the WB if a User adds a `Function` with PMML and saves it, the ERROR will correctly appear. If they then set the PMML document value and save the ERROR will disappear but the WARNING does not appear. The WARNING only appears if the User performs a full compilation of the project.

So.. we'll either need to make the missing PMML model name an ERROR (easy fix) or change `KieBuilderSetImpl` to also support add/removal of any message type (ERROR, WARNING and INFO). This second option is probably the more complete however may be more effort.

2019-06-14 12:55 UTC, manstis requested changes
Please see my [comment](https://github.com/kiegroup/drools/pull/2389#issuecomment-502098526).

2019-06-14 14:38 UTC, tarilabs commented
> we'll either need to make the missing PMML model name an ERROR (easy fix) or change KieBuilderSetImpl to also support add/removal of any message type (ERROR, WARNING and INFO). This second option is probably the more complete however may be more effort.

I don't concur the missing PMML model name is an ERROR, as other PMML runtimes are supporting running without the name just fine. That reduces our options I guess :)

2019-06-14 19:27 UTC, manstis commented
@tarilabs I agree, preserving the WARNING is far better than making it an ERROR... I was trying to be helpful by proposing alternative solutions (to the issue that WARNINGs are not handled by the incremental build mechanism)...

2019-06-17 07:08 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/pmml/DMNRuntimeKiePMMLTest.java
> +        assertTrue(addResults.getAddedMessages().size() > 0);
@manstis can you kindly confirm this line make an assert for where you would expect to find the WARN messages, please?
On confirmation, I'll ask support for indeed the addedMessages from KieBuilder to report all messages besides errors.

2019-06-17 08:25 UTC, manstis commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/pmml/DMNRuntimeKiePMMLTest.java
> +        assertTrue(addResults.getAddedMessages().size() > 0);
@tarilabs Yes, that looks to be perfect (I stepped through this test and `KieBuilderSetImpl.buildChanges(..)` L#154 retrieves the "errors" from `KnowledgeBuilderImpl` however skips DMN's warnings (you can see they are present in `KnowledgeBuilderImpl.getErrorList()` L#1981 `results` property).

It'd be great if you could also add a subsequent step in the test to then update ` KiePMMLScoreCard_NOPMMLmodelName.dmn` (perhaps with `KiePMMLScoreCard.dmn`) to then observe there is a (warning) message removed too.

BTW, there is already a "stepped" test in `kie-dmn-core`, `org.kie.dmn.core.incrementalcompilation.WBCompilationTest`. I'll leave the decision with you as to whether the new test should better live there; or with the PMML tests.

2019-06-17 08:28 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/pmml/DMNRuntimeKiePMMLTest.java
> +        assertTrue(addResults.getAddedMessages().size() > 0);
> BTW, there is already a "stepped" test in kie-dmn-core, org.kie.dmn.core.incrementalcompilation.WBCompilationTest.

yes, but that is a working test an inherited down the line by jpmml-integrations.
This test instead is only a problem for this module locally.

2019-06-17 09:44 UTC, mariofusco commented
@manstis @tarilabs I don't think that I could just add also WARN and INFO among the Messages contained in the IncrementalResults returned by the KieBuilderSet, because this will very likely break many tests that don't expect anything else than ERRORs inside those lists.

At the moment we're creating the KieBuilderSet through which the incremental compilation is performed using the method of the InternalKieBuilder:

`KieBuilderSet createFileSet(String... files)`

My suggestion is to create an overload of this method like

`KieBuilderSet createFileSet(Level minimalLevel, String... files)`

where the additional Level argument is the minimal level of messages that you want in the IncrementalResults.

2019-06-18 08:14 UTC, tarilabs commented
Superseeded by https://github.com/kiegroup/drools/pull/2394#pullrequestreview-250926787

2019-06-18 08:14 UTC, closed without merging