RHPAM-1049 Wrong output variable values in PMML mining model
apache/incubator-kie pull request #2505
Opened 2019-08-15 21:58 UTC by lanceleverich

* Changed output of the target field to be a simple value that is set at
the same time as the Sum_ version is created.
* Updated test to make sure change was effective in adding the output
value

2019-08-19 08:10 UTC, jiripetrlik requested changes
Only minor comment. There is probably accidentally changed indent in one file. Otherwise looks good. But we need to wait for finishing of downstream PR check before merge.

2019-08-19 08:10 UTC, jiripetrlik commented on kie-pmml/src/test/java/org/kie/pmml/pmml_4_2/predictive/models/mining/MiningModelSumRegressionTest.java
> +                                            {Optional.of(200.0), Optional.of(-1.0), Optional.of(2.0), -299},
Please revert back original indent.

2019-08-19 15:06 UTC, jiripetrlik commented
jenkins execute full downstream build

2019-08-20 19:55 UTC, lanceleverich commented on kie-pmml/src/test/java/org/kie/pmml/pmml_4_2/predictive/models/mining/MiningModelSumRegressionTest.java
> +                                            {Optional.of(200.0), Optional.of(-1.0), Optional.of(2.0), -299},
Fixed

2019-08-21 13:27 UTC, jiripetrlik commented
One more comment. I did not notice it before, but please change JIRA name in PR and in commit. It is RHDM-1049 instead of RHPAM-1049.

2019-08-22 08:27 UTC, jiripetrlik approved these changes

2019-08-22 08:28 UTC, danielezonca approved these changes

2019-08-22 08:28 UTC, merged