[DROOLS-4588] Add support for MVEL expression on simple types in Rule test scenario
apache/incubator-kie pull request #2563
Opened 2019-10-02 09:45 UTC by danielezonca

https://issues.jboss.org/browse/DROOLS-4588

Implementation details:
- Add `#` at the beginning of the expression to use MVEL syntax (i.e. `# 10 + 10`)
- Use `actualValue` variable to refer actual value in a EXPECT condition that use MVEL (i.e. `# java.util.Objects.equals(actualValue, 10)`)
- MVEL expression used in GIVEN cell has to return a value/object of the same type of the corresponding column
- MVEL expression in EXPECT columns should return a `boolean` value or the same type of the column and in that case it will be used `compare`/`equals` to compare with actual value (i.e. `# new MyObject()` in a EXPECT cell will be evaluated as `actualValue.compareTo(new MyObject())` if `MyObject` is `Comparable` or `actualValue.equals(new MyObject())` otherwise). This corner case has been introduced to avoid to write `# actualValue.equals(...)` in every MVEL expression in EXPECT section

@yesamer @gitgabrio @dupliaka

2019-10-03 07:39 UTC, yesamer approved these changes
@danielezonca well done, just a very little suggestion.

2019-10-03 07:39 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        if (rawValue instanceof String && ((String) rawValue).startsWith("#")) {
@danielezonca 
I suggest to always use a static variable to refer to "#" char, in any place is used, in order to easily update it in case of change request.

2019-10-03 07:39 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactoryTest.java
> +        FactMappingValue mvelFMV = new FactMappingValue(FactIdentifier.INDEX, ExpressionIdentifier.INDEX, "# 10");
Same of previous comment.

2019-10-03 10:02 UTC, dupliaka commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        Object rawValue = factMappingValue.getRawValue();
SuggestionL: rawValue could be final

2019-10-03 10:04 UTC, dupliaka commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +    }
Suggestion: better to keep only one exit point

2019-10-03 10:15 UTC, dupliaka commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluator.java
> +        return (boolean) expressionResult;
Suggestion: One exit point as well.

2019-10-03 11:12 UTC, gitgabrio requested changes

2019-10-03 11:12 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/DMNFeelExpressionEvaluator.java
> +    public Object evaluateLiteralExpression(String className, List<String> genericClasses, Object rawExpression) {
@danielezonca 
It seems that this method is exactly the same as BaseExpressionEvaluator.evaluateLiteralExpression.
If so, can't we unify them in one single place ? Since it does not use any "state" - it could also be a _static_ method somewhere

2019-10-03 11:12 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        if (rawValue instanceof String && ((String) rawValue).startsWith("#")) {
@danielezonca 
Beside @yesamer suggestion, and to recap what we discussed, I think it would be a good idea to have two "expression" indicators (not only the "#") to clearly differentiate all over the whole stack (from user interface to backend) if the expression is meant as "value generator" or "method invocator". Even if now it is not strictly needed, it would reflect more exactly the possible use cases without relying on convention/assumption, and in general this lead to better results/avoid issues in long term.

2019-10-03 11:12 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +    public static ExpressionEvaluatorFactory create(ClassLoader classLoader, Type type) {
@danielezonca 
Is this indirection really useful? Hiding the instantiation of the **ExpressionEvaluator** behind a static _Factory_ that in turns hide its private constructor, and at the end **ExpressionEvaluator** instantiation depends on a state of the factory itself. I do not read the whole code at glance, so it is possible there is a good reason, but looking at this piece I fail to understand it.

2019-10-03 11:12 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +    private ExpressionEvaluator getOrCreateBaseExpressionEvaluator() {
@danielezonca 
Related to comment about factory, here it is clear that the code need a _state_ to works because of the original design, but I have the impression that, without the factory indirection, all this could have been implemented in more functional way

2019-10-03 11:12 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluator.java
> +    public static final String MVEL_ESCAPE_SYMBOL = "#";
@danielezonca 
This relates to my comment about having two -specific - mvel escape symbol, one for "value generator" and another for "method invocation"

2019-10-03 11:12 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluator.java
> +            throw new IllegalArgumentException("Raw value should be a String and not a '" + rawClass + "'");
@danielezonca 
I would replace "Raw value" with "Expression"; beside that: how it is possible to get to this method with a "rawExpression" that is not a "String" ? I have the impression it should be blocked before

2019-10-03 11:12 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluator.java
> +        if (!(expressionResult instanceof Boolean)) {
@danielezonca 
This relates on the assumptions that I think we should not rely - and code - upon

2019-10-03 11:12 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluator.java
> +            throw new IllegalArgumentException("Raw value should be a String and not a '" + rawExpression.getClass().getCanonicalName() + "'");
@danielezonca 
See my previous comment

2019-10-03 11:12 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/runner/AbstractRunnerHelper.java
>          } else if (!resultValue.isSatisfied()) {
@danielezonca 
Reverting the order of these evaluations would simplify the overall structure: the first two _if_ relates to the same main condition: _!resultValue.isSatisfied()_ and the first one (_resultValue.getErrorMessage().isPresent()_)   is a sub-condition of it

2019-10-03 11:12 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/util/MigrationStrategy.java
> +    ThrowingConsumer<Document> from1_0to1_1();
@danielezonca 
Good job!

2019-10-03 11:14 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        if (rawValue instanceof String && ((String) rawValue).startsWith("#")) {
@danielezonca @yesamer 
I think this static constant could be put in the class @yesamer created to store all such kind of strings, since it could potentially be used in a lot of different places

2019-10-03 11:58 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        if (rawValue instanceof String && ((String) rawValue).startsWith("#")) {
@gitgabrio @danielezonca Unfortunately, the PR where I introduced that class is now closed, bacause part of the previous FE logic which was discarded. If we want to put this (and other constants) in a single "constants" holder class, we need to add it in this PR.

2019-10-03 12:10 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        if (rawValue instanceof String && ((String) rawValue).startsWith("#")) {
@yesamer @danielezonca 
If possible, I would prefer to add it now - I think it would be useful to have it, and this could be a good time to introduce it.

2019-10-04 06:08 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        if (rawValue instanceof String && ((String) rawValue).startsWith("#")) {
@yesamer @danielezonca @gitgabrio I am not sure, but wouldn't be the topic we discuss here, two characters for distinguish expression type, brought a backward incompatibility? Asking as currently users do not need to prefix cell inputs with any character, am I missing something?

2019-10-04 06:58 UTC, jomarko reviewed
Few questions, also a PR with coverage increase is coming.

2019-10-04 06:58 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluator.java
> +            throw new IllegalArgumentException("Raw value should be a String and not a '" + rawClass + "'");
We should extract this piece of code [1] as a private method and use it both in `evaluateUnaryExpression` and `evaluateLiteralExpression`

[1]
```java
if (!(rawExpression instanceof String)) {
    String rawClass = rawExpression == null ? null : rawExpression.getClass().getCanonicalName();
    throw new IllegalArgumentException("Raw value should be a String and not a '" + rawClass + "'");
}
```

2019-10-04 06:58 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluator.java
> +        throw new UnsupportedOperationException("The condition has not been satisfied");
The message doesn't sound describing unsupported operation to me, but just double checking.

2019-10-04 07:02 UTC, jomarko commented
Proposed coverage increase https://github.com/kiegroup/drools/pull/2566

2019-10-04 07:04 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        if (rawValue instanceof String && ((String) rawValue).startsWith("#")) {
@danielezonca @gitgabrio @jomarko If I correctly understood, the 2 new characters will cover new cases: one for handle value generator and another to handle method invocator. Both will be managed with the new MVEL expression evaluator introduced by Daniele. This means the old expression evaluator (without any char) will continue to work. Am I correct?

2019-10-04 07:10 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        if (rawValue instanceof String && ((String) rawValue).startsWith("#")) {
@jomarko 
Hi. This is the result of discussion with UX. Anyway, point is: inside DMN editor the user is expected to insert "expressions", but until now - _inside scenario grid_ - (s)he 's expected to insert _raw values_. Now, this is the proposed way to let the user insert arbitrarily _raw value_ **OR** _expression_ - the prefixes are needed to know (server side) what is the case (I'm asking for two different prefixes because the "expression" use case has - in turns - two different usages)

2019-10-04 07:26 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        if (rawValue instanceof String && ((String) rawValue).startsWith("#")) {
@gitgabrio @yesamer thank you, if the discussed characters are related just tho new MVEL, I am fine, just would be good to add both characters into cheat-sheet we have in right panel.

2019-10-04 08:54 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluator.java
> +        throw new UnsupportedOperationException("The condition has not been satisfied");
This method is invoked to obtain a String expression that represent the actual value but this is not possible with MVEL expression. That's the reason of the `UnsupportedOperationException`. At the same time this message is the error message displayed in the UI so I decided to use this message instead of "It is not possible to suggest the value to use"

2019-10-04 09:00 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluator.java
> +        throw new UnsupportedOperationException("The condition has not been satisfied");
@danielezonca thank you, I have no better message in mind, so fine for me.

2019-10-04 16:31 UTC, gitgabrio requested changes

2019-10-04 16:31 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-api/src/main/java/org/drools/scenariosimulation/api/utils/ConstantsHolder.java
> +    public static final String MVEL_ESCAPE_SYMBOL = "#";
@danielezonca 
Please use two different constants to differentiate the use cases - beside that, probably is better to have a slightly more complex pattern - `#` is too easy and common to use

2019-10-04 17:09 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        if (rawValue instanceof String && ((String) rawValue).startsWith("#")) {
Moved symbol to a common class.
About the possibility to use two different symbols to distinguish "expression that define a value" and "expression that verify a condition" this is an ongoing discussion so I will add a comment to the PR as soon as this will be clarified (probably on Monday)

@jomarko 
@yesamer is right, this PR introduce MVEL support to Rule scenarios and we are discussing about MVEL expression only, a simple value can still be specified without MVEL (i.e. `MyString`)

2019-10-04 17:09 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactoryTest.java
> +        FactMappingValue mvelFMV = new FactMappingValue(FactIdentifier.INDEX, ExpressionIdentifier.INDEX, "# 10");
Done

2019-10-04 17:15 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        Object rawValue = factMappingValue.getRawValue();
I don't like to specify `final` for local variable, actually most/all of local variable we are usually using could be declared as `final` (Jave 8 introduced the definition of _effectively final_ for this kind of situation) but I think this has an impact in terms of readability without a real benefit

2019-10-07 07:34 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/util/MigrationStrategy.java
> +    ThrowingConsumer<Document> from1_0to1_1();
Yes, I'm very proud of this change :smile:

2019-10-07 07:52 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +    }
The method is really small and to have a single exit point I need to initialize a variable initialized as `null` and then reassign it. I prefer to have multiple returns rather than additional variables (especially with small methods)

2019-10-07 07:52 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluator.java
> +        return (boolean) expressionResult;
Same comment as above

2019-10-08 06:24 UTC, jomarko commented
@danielezonca hello, is this ready for a re-review?

2019-10-08 06:27 UTC, danielezonca commented
Not yet, I want to perform another couple of tests on my side first

2019-10-08 12:36 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/DMNFeelExpressionEvaluator.java
> +    public Object evaluateLiteralExpression(String className, List<String> genericClasses, Object rawExpression) {
I have created a ticket for that [DROOLS-4618](https://issues.jboss.org/browse/DROOLS-4618)

2019-10-08 12:36 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +    public static ExpressionEvaluatorFactory create(ClassLoader classLoader, Type type) {
As agreed added javadoc to explain the logic of this factory class

2019-10-08 12:36 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +    private ExpressionEvaluator getOrCreateBaseExpressionEvaluator() {
Same as above

2019-10-08 12:40 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluator.java
> +            throw new IllegalArgumentException("Raw value should be a String and not a '" + rawClass + "'");
Error renamed and created a ticket for expression evaluator refactoring [DROOLS-4618](https://issues.jboss.org/browse/DROOLS-4618)

2019-10-08 12:40 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluator.java
> +            throw new IllegalArgumentException("Raw value should be a String and not a '" + rawExpression.getClass().getCanonicalName() + "'");
Done

2019-10-08 12:42 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/runner/AbstractRunnerHelper.java
>          } else if (!resultValue.isSatisfied()) {
Done

2019-10-08 13:35 UTC, danielezonca commented
@gitgabrio @jomarko @dupliaka 
PR is ready for review

2019-10-09 07:26 UTC, gitgabrio approved these changes

2019-10-10 06:35 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluator.java
> +        throw new UnsupportedOperationException("The condition has not been satisfied");
@danielezonca it seems you decided to not incorporate my point about `if (!(rawExpression instanceof String))` extraction as private method, could you please at least respond why?

2019-10-10 06:42 UTC, jomarko approved these changes
Approving, however one of my comments from previous review round still not answered.

2019-10-10 07:19 UTC, danielezonca commented
@jomarko 
I have created this ticket https://issues.jboss.org/browse/DROOLS-4618 to refactor all `ExpressionEvaluator`s and change `rawExpression` from `Object` to `String` as Gabriele suggested. Doing that I plan to refactor/remove also all these `instanceof String`. Sorry but I forgot to explicitly answer you about that point, feel free to edit/add information in that ticket too.
Is it fine for you?

2019-10-10 07:27 UTC, jomarko commented
@danielezonca unfortunately, I think it doesn't cover my comment. There is no link to code lines/my github comment/this original PR. However I have no capacity to invest more time into this PR. Assume my approval still as valid.

2019-10-10 08:16 UTC, dupliaka reviewed
Reviewed with comments

2019-10-10 08:16 UTC, dupliaka commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/runner/AbstractRunnerHelper.java
>          }
```java
if (resultValue.isSatisfied()) {
            expectedResult.resetStatus();
        } else {
            if (resultValue.getErrorMessage().isPresent()) {
                expectedResult.setExceptionMessage(resultValue.getErrorMessage().get());
            } else {
                try {
                    expectedResult.setErrorValue(expressionEvaluator.fromObjectToExpression(resultValue.getResult()));
                } catch (Exception e) {
                    expectedResult.setExceptionMessage(e.getMessage());
                }
            }
        }
```
I know it looks a bit spaghetti like, but at least it is more readable

2019-10-10 08:16 UTC, dupliaka commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/runner/AbstractRunnerHelper.java
>          for (FactMappingValue factMappingValue : factMappingValues) {
Suggestion: That is not regression case but probably we could Create one instance of IllegalStateException("Wrong expression, this should not happen")) before the loop and reuse it inside?

2019-10-10 08:16 UTC, dupliaka commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluatorTest.java
> +        assertThatThrownBy(() -> evaluator.evaluateLiteralExpression(String.class.getCanonicalName(), Collections.emptyList(), new Object()))
duplicate

2019-10-10 08:16 UTC, dupliaka commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        Object rawValue = factMappingValue.getRawValue();
Sorry I suggest this idea just for better code readability so the next user could understand the value won't change anymore. I have notice that practice several times in the code so I've made a wrong conclusion about this code style agreement. Thanks

2019-10-10 08:44 UTC, dupliaka commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/runner/AbstractRunnerHelper.java
>          }
Done in later commit
https://github.com/kiegroup/drools/blob/09e30a280c914af88241ff04184a4aad4c255b0e/drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/runner/AbstractRunnerHelper.java#L232-L246

2019-10-10 09:26 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/runner/AbstractRunnerHelper.java
>          for (FactMappingValue factMappingValue : factMappingValues) {
I think we should stay with the code like it is now because if we create the instance of `IllegalStateException` at the beginning of the method the stack trace will refer to that line instead of the line where the proper `throw` will be performed. Moreover in the current code the exception is created lazily (only if it happens) while if we move this code at the beginning of the method it will be always created

2019-10-10 09:28 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluatorTest.java
> +        assertThatThrownBy(() -> evaluator.evaluateLiteralExpression(String.class.getCanonicalName(), Collections.emptyList(), new Object()))
Done, good catch :)

2019-10-10 11:41 UTC, dupliaka commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/runner/AbstractRunnerHelper.java
>          for (FactMappingValue factMappingValue : factMappingValues) {
All right

2019-10-10 14:31 UTC, dupliaka approved these changes
Manual check done.
Here is a small summary:

Expressions for Rule based scenarios for simple types
Starts from “#”
Runs for properties
Runs for duplicated properties
Returns the same type as property type in GIVEN
Returns boolean in EXPECTED
Receives rule processed value as a parameter in EXPECTED via keyword “actualValue”
Applies java.util.Objects.equals(actualValue, expression result) if the expression result if the EXPECTED value not a boolean
Works for Simple types only
Could run any of java function for the project
Exports and imports as any other value


Limitation for GIVEN
1. Mvel expression results not property same type - drives scenario failure, error reason and highlighted
Use case:
User inputs 1/2 to Integer property
2.Mvel execution throws exception - drives scenario execution stopping, failure, error alert
Use case:
User inputs inexistent MVEL function  in one of the properties
3.Mvel expression exception stops expression execution for all EXPECT colons
Use case:
User got one of the GIVEN fact expression excepted 
4.It cannot be mixed with simple expressions in one cell
Use cases:
For cell inputs :
[#4+4,68]
#actualvalue>1

2019-10-11 07:42 UTC, danielezonca commented
jenkins retest this please

2019-10-11 14:54 UTC, danielezonca commented
jenkins retest this please

2019-10-14 09:38 UTC, merged