DROOLS-4588: Coverage increase
apache/incubator-kie pull request #2566
Opened 2019-10-04 07:01 UTC by jomarko

Dependent on #2563

2019-10-04 16:31 UTC, gitgabrio requested changes
@jomarko 
I read the very last commit and looks almost fine for me - beside a small detail.
What is not really clear to me is that in the PR made by @danielezonca something is already changed

2019-10-04 16:31 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluatorTest.java
> +        assertTrue(evaluator.evaluateUnaryExpression("# " + ACTUAL_VALUE_IDENTIFIER + " == 123", 123, Integer.class));
@jomarko 
Hi. I think @danielezonca  is creating a specific class to hold the string constants used throughout the code, so probably that `#` should be replaced. Beside that, I think we are also going to have two different "expression" identifier, one for value creation (the one used in all this tests, I think) and one for method invocation. This latter case seems not covered- even if I am not sure on how to test it. @danielezonca ?

2019-10-14 13:43 UTC, jomarko commented
@gitgabrio @dupliaka @yesamer @danielezonca may I ask you for a re-review?

2019-10-14 13:43 UTC, danielezonca approved these changes

2019-10-15 12:08 UTC, jomarko commented
@danielezonca may I ask you for help? As you see in last commit I updated the test to use proper type for particular expressions, however problem is with array expressions like **# {"Jim"}** where I expect the type **Object[]** however getting an exception from class loader that it can not be loaded. Any advice?

2019-10-15 12:17 UTC, yesamer approved these changes
@jomarko fine for me, my only suggestion is to apply the change requested by @gitgabrio during his review.

2019-10-15 12:22 UTC, jomarko commented
@yesamer yes, good point, @danielezonca could you please point me to the class with those constants?

2019-10-15 12:23 UTC, yesamer commented
> @yesamer yes, good point, @danielezonca could you please point me to the class with those constants?

It should be `ConstantHolder' class

2019-10-15 15:48 UTC, danielezonca commented
@jomarko 
I had a look to your failing test and the problem is related to load class of arrays. It is broken/not supported so I have created a ticket for that ([DROOLS-4649](https://issues.jboss.org/browse/DROOLS-4649))

2019-10-16 06:19 UTC, dupliaka approved these changes
Fine for me.

2019-10-16 06:19 UTC, jomarko commented
jenkins please retest this

2019-10-16 09:43 UTC, gitgabrio approved these changes

2019-10-16 09:46 UTC, merged