DROOLS-4650 : GDST: Re-editing BRL columns causes NPE
apache/incubator-kie pull request #2587
Opened 2019-10-16 09:51 UTC by Rikkola

https://issues.jboss.org/browse/DROOLS-4650

2019-10-16 09:55 UTC, Rikkola commented
I'll try to get green builds before review. I fear this is a risky change.

2019-10-16 09:58 UTC, manstis commented
@Rikkola I think this is also a fix for https://github.com/kiegroup/drools-wb/pull/1212?

It might be worth linking the JIRA, if that is true.

2019-10-16 10:06 UTC, Rikkola commented
@manstis This fixes that. There are two product tickets, but only linked this to one. I'll link both.

2019-10-16 19:07 UTC, Rikkola commented
All green, nice. I'll fix the code smell, but removing the diamond operator should not change behaviour.

2019-10-16 19:08 UTC, Rikkola commented
@jomarko @manstis if you two would be kind enough to share some thoughts about the changes.

2019-10-17 08:07 UTC, Rikkola commented on drools-workbench-models/drools-workbench-models-guided-dtable/src/main/java/org/drools/workbench/models/guided/dtable/shared/model/ConditionCol52.java
> +    private static final long serialVersionUID = 729l;
No idea if these matter, but thought that I'll update these to current version :)

2019-10-18 06:17 UTC, jomarko requested changes
![Screenshot from 2019-10-18 07-34-23](https://user-images.githubusercontent.com/8044780/67070196-ad2c1a00-f17f-11e9-86c1-4e6c534be523.png)

Still doesn't work for BRL action columns

2019-10-18 06:17 UTC, jomarko commented on drools-workbench-models/drools-workbench-models-guided-dtable/src/main/java/org/drools/workbench/models/guided/dtable/shared/model/ConditionCol52.java
> +    private static final long serialVersionUID = 729l;
Shouldn't we change it witch each community release then?

2019-10-18 06:17 UTC, jomarko commented on drools-workbench-models/drools-workbench-models-guided-dtable/src/main/java/org/drools/workbench/models/guided/dtable/shared/model/DTColumnConfig52.java
> +        if(o == null || o.getClass() != this.getClass()){
This change is not needed, https://docs.oracle.com/javase/specs/jls/se11/html/jls-15.html#jls-15.20.2

2019-10-18 07:00 UTC, jomarko commented
@Rikkola as this is about NPE in equals so I (understand my Intelij Idea) reimplemented equals of dtables, I guess also rule model need similar update. https://github.com/Rikkola/drools/pull/6

It solved issue I reported https://github.com/kiegroup/drools/pull/2587#pullrequestreview-303673306

2019-10-21 08:26 UTC, Rikkola commented on drools-workbench-models/drools-workbench-models-guided-dtable/src/main/java/org/drools/workbench/models/guided/dtable/shared/model/ConditionCol52.java
> +    private static final long serialVersionUID = 729l;
Probably only worth it to update when a release has changes.

2019-10-23 16:21 UTC, Rikkola commented
@jomarko Is this now ok from you side. Retested and can't figure out how to break it.

2019-10-24 12:17 UTC, jomarko approved these changes

2019-10-24 12:28 UTC, Rikkola commented
@manstis Hi, I could use your feedback on this.

2019-10-24 13:06 UTC, manstis approved these changes
Thanks @Rikkola so my [suspicion](https://github.com/kiegroup/drools-wb/pull/1212#issuecomment-520838543) about equals somewhere was correct.

2019-10-24 13:06 UTC, merged

2019-10-24 13:08 UTC, Rikkola commented
@manstis Yep that helped. Although debugging to figure out what exactly is the problem was PITA, but can't imagine how long it would have taken without any hints ;)

2019-10-25 10:48 UTC, Rikkola commented
@kiegroup/gatekeepers Can I get this reverted, it breaks unit tests for drools-wb, but the fix will take some time to get green.

2019-10-25 10:50 UTC, Rikkola commented
Actually not sure if github has a revert button, I'll make a PR just in case.

2019-10-25 11:27 UTC, mareknovotny commented
The Revert button is there, but it generates new PR ;)

2019-10-25 11:35 UTC, Rikkola commented
@mareknovotny managed to find it, hehe.