DROOLS-4650 : GDST: Re-editing BRL columns causes NPE (#2587)
apache/incubator-kie pull request #2623
Opened 2019-10-24 13:15 UTC by Rikkola

* DROOLS-4650 : GDST: Re-editing BRL columns causes NPE

* DROOLS-4650: Reimplement equals of drools-workbench-models-guided-dtable

* DROOLS-4650: Incorporate review feedback, bring test to the original state

(cherry picked from commit 019c0ba36a6c5e858c6a45215f59829398a7a313)

https://issues.jboss.org/browse/DROOLS-4650

2019-10-24 13:16 UTC, manstis approved these changes

2019-10-24 13:16 UTC, Rikkola commented
@jomarko @manstis Same as master, but for 7.26.x if you could please review.

2019-10-25 05:30 UTC, jomarko approved these changes

2019-10-25 07:52 UTC, jomarko requested changes
Sorry, need to take the ack back, there are some test failures in drools-wb repository.

2019-10-25 07:52 UTC, jomarko commented
jenkins execute full downstream build

2019-10-25 10:20 UTC, jomarko commented
Toni we need to update this PR, it will actually became an ensemble, see my PRs for master:
- https://github.com/kiegroup/drools/pull/2624
- https://github.com/kiegroup/drools-wb/pull/1252

2019-10-25 10:22 UTC, Rikkola commented
@jomarko I'll work those changes in.

2019-10-25 10:42 UTC, Rikkola commented
jenkins execute full downstream build

2019-10-25 11:48 UTC, jomarko commented
Approving, tried briefly manually. If jenkins to the green, lets merge.

2019-10-25 11:48 UTC, jomarko approved these changes

2019-10-25 17:48 UTC, Rikkola commented
> org.kie.server.integrationtests.controller.WebSocketKieControllerNotificationIntegrationTest.testKieServerEvents
> org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest.allPerspectivesCanBeLoaded
> org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest
> org.kie.hacep.RemoteStreamingKieSessionImplTest.getListKieSessionObjectsTest

jenkins execute full downstream build

2019-10-28 06:24 UTC, Rikkola commented
> org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromStockRepository
jenkins execute full downstream build

2019-10-28 06:25 UTC, Rikkola commented
I think this missed the train, but let's see if I hit randomly failing Selenium tests for a third time.

2019-10-28 13:06 UTC, Rikkola commented
Selenium failed 3 times. Checking if it does it 4 times

> org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest.allPerspectivesCanBeLoaded

jenkins execute full downstream build

2019-10-29 08:40 UTC, mareknovotny commented
that selenium test fails on other FDB PRs too, can we get to fix it  @jomarko @tomasdavidorg ?

2019-10-29 09:34 UTC, jomarko commented
@mareknovotny looking

2019-10-29 12:24 UTC, jomarko commented
@Rikkola I try to stabilize the failing test via https://github.com/kiegroup/kie-wb-distributions/pull/981 and https://github.com/kiegroup/kie-wb-distributions/pull/982

2019-10-29 16:34 UTC, mareknovotny commented
jenkins execute full downstream build

2019-10-30 06:23 UTC, jomarko commented
@mareknovotny I see also `allPerspectivesCanBeLoaded` failed. Do you think some old version of the test could be started due to some cache?

2019-10-30 08:00 UTC, mareknovotny commented
not sure, but the master is not affected so we can try to backport some of the selenium fixes to 7.26.x like:

- https://github.com/kiegroup/kie-wb-distributions/commit/ea8a63190f6f3222ee13acafe4cf7d15e8369710

The another fix is already there, but this upgrade of gecko driver not.

2019-10-30 12:29 UTC, jomarko commented
@mareknovotny ok, lets see https://github.com/kiegroup/kie-wb-distributions/pull/983

2019-10-30 15:49 UTC, mareknovotny commented
jenkins execute full downstream build

2019-10-30 15:53 UTC, mareknovotny commented
I tried to trigger FDB just for completion of the validation of backported changes, but this PR can be closed as we won't release this bug fix in 7.26.x branch

2019-10-31 05:52 UTC, jomarko commented
@mareknovotny the same test failed, could you please point me to another PR where the same test is failing?

2019-10-31 08:02 UTC, mareknovotny commented
@jomarko the same test doesn't fail in the last run ;)
See the history from Jenkins job:
- Run #7 (30.10.2019 16:03:30) 
    org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testLibraryPerspectiveWithHeader

- Run #6 (29.10.2019 16:39:24)
    org.kie.server.integrationtests.controller.WebSocketKieControllerNotificationIntegrationTest.testKieServerEvents
    org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest
    org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest.allPerspectivesCanBeLoaded

- Run #5 (28.10.2019 13:13:42)
    org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest.allPerspectivesCanBeLoaded

- Run #4 (28.10.2019 6:30:59) 
    org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest.allPerspectivesCanBeLoaded

- Run #3 (25.10.2019 18:02:01)
    org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromStockRepository

- Run #2 (25.10.2019 10:55:01) 
    org.kie.server.integrationtests.controller.WebSocketKieControllerNotificationIntegrationTest.testKieServerEvents
    org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest.allPerspectivesCanBeLoaded
    org.kie.hacep.PodAsReplicaTest.processOneSentMessageAsLeaderAndThenReplicaTest
    org.kie.hacep.RemoteStreamingKieSessionImplTest.getListKieSessionObjectsTest

2019-10-31 08:13 UTC, mareknovotny commented
the previous test failures of `org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest.allPerspectivesCanBeLoaded` are reproduced on 
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/7.26.x/job/deployedRep/job/kie-wb-distributions-7.26.x/

2019-10-31 12:18 UTC, jomarko commented
See my PRs
- https://github.com/kiegroup/kie-wb-distributions/pull/984
- https://github.com/kiegroup/kie-wb-distributions/pull/985

2019-10-31 14:15 UTC, mareknovotny commented
jenkins execute full downstream build

2019-11-01 05:53 UTC, jomarko commented
Seems selenium didn't fail, but totally fresh failure appeared:
`org.jbpm.test.functional.timer.ConcurrentGlobalTimerServiceTest.testSessionPerProcessInstance`

2019-11-01 09:00 UTC, mareknovotny commented
@jomarko finally we got green for all selenium tests here and here too https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/7.26.x/job/deployedRep/job/kie-wb-distributions-7.26.x/88

I will close this PR now, as the bug fixing is moved to master only and it was done before on master.
now here fails the `org.jbpm.test.functional.timer.ConcurrentGlobalTimerServiceTest.testSessionPerProcessInstance` which was due timeout of the test

2019-11-01 09:00 UTC, closed without merging