[DROOLS-4698] Managing used defined expressions for Collections
apache/incubator-kie pull request #2691
Opened 2019-12-16 22:51 UTC by yesamer

* work in progress *

2020-01-03 12:36 UTC, jomarko commented
I think review should be postponed until https://github.com/kiegroup/drools/pull/2690 is in, WDYT @yesamer ?

2020-01-03 13:26 UTC, yesamer commented
> I think review should be postponed until #2690 is in, WDYT @yesamer ?

Yes, fine for me.

2020-01-08 10:00 UTC, jomarko commented
jenkins please retest this

2020-01-08 10:00 UTC, jomarko commented
jenkins execute compile downstream build

2020-01-08 10:42 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +    protected boolean isAnMVELExpression(Object rawValue) {
Please change to `String`: we just changed all ExpressionEvaluator to manage only `String`s so we can assume a string also here (with a cast on caller side)

2020-01-08 10:42 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        if (optionalNode.isPresent()) {
You can use `optionalNode.ifPresent(jsonNode -> ...`

2020-01-08 10:42 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/DMNFeelExpressionEvaluator.java
> +     * i.e. an user defined expression (The JSON textual must be processed to take its value)
DMN doesn't support Map in the collection editor: context (Map equivalent for DMN) is managed as normal string

2020-01-08 10:42 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/util/JsonUtils.java
> +                return jsonNode.isTextual();
Use `convertFromStringToJSONNode` to simplify the implementation

2020-01-08 11:13 UTC, jomarko reviewed
Some comments to code

2020-01-08 11:13 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/AbstractExpressionEvaluator.java
>                                             genericClasses);
Could we please put comments in the way bellow, it is minor thing, but that ways kiegroup code-formatting will not change the code
```java
if (jsonNode.isTextual()) {
                /* JSON String: User defined Expression */
                return extractAndEvaluateExpression((TextNode) jsonNode, className);
            } else if (jsonNode.isArray()) {
                /* JSON Array: User defined List */
                return createAndFillList((ArrayNode) jsonNode, new ArrayList<>(), className, genericClasses);
            } else if (jsonNode.isObject()) {
                /* JSON Object: User defined Map */
                return createAndFillObject((ObjectNode) jsonNode,
                                           createObject(className, genericClasses),
                                           className,
                                           genericClasses);
```

2020-01-08 11:13 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/AbstractExpressionEvaluator.java
>              }
I have concern about repeating the conditions. There is a risk of adding one more `else if` into `convertResult` and forgetting updating `verifyResult`, what do you think?

Also putting comments inside {} blocks would satisfy kiegroup code formatting.

2020-01-08 11:13 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/DMNFeelExpressionEvaluator.java
>      }
The implementation seems to be same, I had idea about using private method with single implementation, let me kwno what do you think.
```java
    /**
     * In DMN only Lists are structured result while Maps are context so "plain" FEEL expressions
     * Maps are considered structured only when the given raw value is a JSON textual type
     * i.e. an user defined expression (The JSON textual must be processed to take its value)
     * @param resultClass
     * @return
     */
    @Override
    protected boolean isStructuredResult(Class<?> resultClass, String raw) {
        return resultClass != null && isStructured(resultClass.getCanonicalName(), raw);
    }

    /**
     * In DMN only Lists are structured input while Maps are context so "plain" FEEL expressions.
     * Maps are considered structured only when the given raw value is a JSON textual type
     * i.e. an user defined expression (The JSON textual must be processed to take its value)
     * @param className
     * @param raw
     * @return
     */
    @Override
    protected boolean isStructuredInput(String className, String raw) {
        return isStructured(className, raw);
    }

    private boolean isStructured(String className, String raw) {
        return className != null && (ScenarioSimulationSharedUtils.isList(className) ||
                (ScenarioSimulationSharedUtils.isMap(className) && JsonUtils.isAJSONTextualNode(raw)));
    }
```

2020-01-08 11:13 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +           and it's value starts with MVEL_ESCAPE_SYMBOL ('#') */
This seems to be different from what we say in method javadoc, could you please double check?

2020-01-08 11:13 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluator.java
> +        throw new IllegalArgumentException("Malformed MVEL expression '" + rawExpression + "'");
Do we want to put message into `ContantHolder` class?

2020-01-08 11:13 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/BaseExpressionEvaluatorTest.java
> +        expressionEvaluator.verifyResult(expressionCollectionJsonString, new ArrayList<>(), null);
Can we please use `Collections.empyList()`

2020-01-08 11:13 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/BaseExpressionEvaluatorTest.java
> +        expressionEvaluator.verifyResult(expressionCollectionJsonString, new HashMap<>(), null);
Can we please use `Collections.emptyMap()`?

2020-01-08 11:54 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/util/JsonUtils.java
> +                return jsonNode.isTextual();
Done

2020-01-08 11:54 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/DMNFeelExpressionEvaluator.java
> +     * i.e. an user defined expression (The JSON textual must be processed to take its value)
Done

2020-01-08 11:55 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        if (optionalNode.isPresent()) {
Done

2020-01-08 11:55 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +    protected boolean isAnMVELExpression(Object rawValue) {
Done

2020-01-09 10:37 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +           and it's value starts with MVEL_ESCAPE_SYMBOL ('#') */
@jomarko I simplified it

2020-01-09 10:38 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/DMNFeelExpressionEvaluator.java
>      }
@jomarko I reverted all changes on that class.

2020-01-09 10:46 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/AbstractExpressionEvaluator.java
>                                             genericClasses);
Done

2020-01-09 10:48 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/AbstractExpressionEvaluator.java
>              }
@jomarko Comments fixed. About your concern, it could be a risk but I think it's a Developer responsibility to handle it in the correct way. In addition, how we should impose this constraint? Probably we should completely change the architecture of these classes.

2020-01-09 10:49 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluator.java
> +        throw new IllegalArgumentException("Malformed MVEL expression '" + rawExpression + "'");
@jomarko I removed this test because this case is no more handled

2020-01-09 10:49 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/BaseExpressionEvaluatorTest.java
> +        expressionEvaluator.verifyResult(expressionCollectionJsonString, new ArrayList<>(), null);
@jomarko I removed this test because this case is no more handled

2020-01-09 10:49 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/BaseExpressionEvaluatorTest.java
> +        expressionEvaluator.verifyResult(expressionCollectionJsonString, new HashMap<>(), null);
@jomarko I removed this test because this case is no more handled

2020-01-13 13:58 UTC, gitgabrio requested changes
@yesamer 
Just some minor changes, pls

2020-01-13 13:58 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/AbstractExpressionEvaluator.java
>      protected boolean isStructuredInput(String className) {
@yesamer 
This method is functionally identical to the previous one, even if written differently: please remove one of them

2020-01-13 13:58 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        String rawValue = (String) factMappingValue.getRawValue();
@yesamer 
Not related to this PR, but we have to get rid of this `Object` _rawValue_ (is cast to String everywhere)

2020-01-13 13:58 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/util/JsonUtils.java
> +            return Optional.empty();
@yesamer 
Not sure about swallowing this exception that way: if we get here rawValue is expected to be a valid json, but if it throws exception, something bad has happened, IMO. 
"Given a json in String format, it try to convert it in a <code>JsonNode</code>. In case of success, i.e.
    the given string is a valid json"...: what would mean a "json in String format" but invalid json?

2020-01-13 13:58 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/util/JsonUtils.java
> +    public static boolean isAJSONTextualNode(String json) {
@yesamer 
I'm not sure where it is used, but I'm almost sure you would need to re-convert the string again and retrieve the `.isTextual` object: would not be better to directly return an Optional"<TextNode or whatever>" here, as in convertFromStringToJSONNode?

2020-01-13 14:33 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/util/JsonUtils.java
> +    public static boolean isAJSONTextualNode(String json) {
@gitgabrio To be honest it's not used, I removed it.

2020-01-13 14:41 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/AbstractExpressionEvaluator.java
> +                /* JSON Object: User defined Map */
@yesamer 
Can you please update the comments with something like?
Text: expression manually written by the user to build a list/map
Array: list of expressions created using List collection editor
Map: map of expressions created using Map collection editor

2020-01-13 14:41 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/AbstractExpressionEvaluator.java
> +                /* JSON Object: User defined Map */
Same as above

2020-01-13 14:41 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluator.java
> +        Object expressionResult = compileAndExecute(rawExpression, new HashMap<>());
This changed has been moved to [this PR](https://github.com/kiegroup/drools/pull/2713) so we can remove it from here (with the tests of course)

2020-01-13 14:41 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluator.java
> +                return expression.replaceFirst(MVEL_ESCAPE_SYMBOL, "");
I think we can use `rawExpression` instead of convert back `jsonNode` to text. Wdyt?

2020-01-13 14:41 UTC, danielezonca commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/BaseExpressionEvaluatorTest.java
> +        assertTrue(expressionEvaluator.verifyResult(mapJsonString, toCheck, null));
Can you please add a test where the last parameter of `verifyResult` is used and it has to be different from `null`?

2020-01-13 14:45 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/util/JsonUtils.java
> +            return Optional.empty();
@gitgabrio This is a good point, I had the thought, but I didn't find a different way to validate a json. 
According to Jackson docs:

    

>  * @throws JsonParseException if underlying input contains invalid content
>      *    of type {@link JsonParser} supports (JSON for default case)
>      */
>     public JsonNode readTree(String content) throws IOException {
>         return _readTreeAndClose(_jsonFactory.createParser(content));
>     }

Then, I can improve it managing `JsonParseException` and `IOException` in different ways: in the first case, it's a malformed content i.e. not a JSON, in the second case It could be any other IOException, I can re-throw it with an other exception (which one?)

2020-01-13 15:01 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/util/JsonUtils.java
> +            return Optional.empty();
@yesamer 
`JsonParseException` extends `IOException`.
If I've understood correctly, `ObjectMapper.readTree(String content)` may throw one or the other (it declares only the latter, being the ancestor).
So, I think both of them should be catch and managed in different way (if the json is invalid, I definitely would not hide that - for other underlying IO exceptions is debatable).
This could also be tested, I think.

2020-01-13 15:04 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/util/JsonUtils.java
> +    public static boolean isAJSONTextualNode(String json) {
@yesamer 
great!

2020-01-13 15:04 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/AbstractExpressionEvaluator.java
>      protected boolean isStructuredInput(String className) {
@gitgabrio done! Thanks!

2020-01-13 15:05 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        String rawValue = (String) factMappingValue.getRawValue();
@gitgabrio @danielezonca already planned a future refactor to set rawValue to `String` everywhere.

2020-01-14 08:45 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/util/JsonUtils.java
> +            return Optional.empty();
@gitgabrio no, a `JsonParseException` is thrown if the input is not a valid json. In this case, I return an empty `Optional` which means: the given string can't be parsed as json and then it's not a json. In all other cases, when a generic `IOException` is thrown, then I re-throw an `IllegalArgumentException`

2020-01-14 08:45 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/AbstractExpressionEvaluator.java
> +                /* JSON Object: User defined Map */
@danielezonca Done

2020-01-14 08:45 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/AbstractExpressionEvaluator.java
> +                /* JSON Object: User defined Map */
@danielezonca Done

2020-01-14 08:46 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluator.java
> +        Object expressionResult = compileAndExecute(rawExpression, new HashMap<>());
@danielezonca I just merged master which now contains that PR.

2020-01-15 10:14 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/BaseExpressionEvaluatorTest.java
> +        assertTrue(expressionEvaluator.verifyResult(mapJsonString, toCheck, null));
@danielezonca added :)

2020-01-15 11:08 UTC, gitgabrio commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/util/JsonUtils.java
> +            return Optional.empty();
@yesamer 
I thought that method would be invoked *only* to parse an (expected) json string. If this is true, then IMO `JsonParseException` should not be hided behind an `Optional.empty()`, because it means something unexpected is happening. If - instead - this method is invoked on any possible String to verify if it is a valid json, then the javadoc should somehow clarify that

2020-01-15 12:32 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/util/JsonUtils.java
> +            return Optional.empty();
@gitgabrio 
> If - instead - this method is invoked on any possible String to verify if it is a valid json,
This is the correct case, I'll updated the javadoc to clarify it.

2020-01-15 15:00 UTC, gitgabrio approved these changes

2020-01-16 12:06 UTC, danielezonca approved these changes

2020-01-17 09:30 UTC, jomarko reviewed
### Code review
See inline comments

2020-01-17 09:30 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +    protected boolean isAnMVELExpression(String rawValue) {
This is standard public static final helper method, so just wondering if the placement is the best choice we have.

2020-01-17 09:30 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        if (isAnMVELExpression(rawValue)) {
Please notice we changed the logic, we are now not checking `instanceof` in the `isAnMVELExpression`. We automatically cast to String what theoretically can cause cast exception.

2020-01-17 09:30 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/BaseExpressionEvaluatorTest.java
>      }
Could you please help me understand this, why `IllegalArgumentException` is expected in both cases? Is it because `expressionCollectionJsonString` needs to start with '[' and ends with ']' ?

2020-01-17 09:30 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluatorTest.java
> +                                                                                          new ArrayList<>()
Could we please use `Collections.emptyList()`?

2020-01-17 09:30 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluatorTest.java
> +                                                                      new ArrayList<>()
Could we please use `Collections.emptyList()`?

2020-01-17 09:30 UTC, jomarko commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluatorTest.java
> +                                                                      new ArrayList<>()
Could we please use `Collections.emptyList()`?

2020-01-17 10:13 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/BaseExpressionEvaluatorTest.java
>      }
@jomarko Yes, the expression collection feature doesn't work with `BaseExpressionEvaluator`, but only with `MVELExpressionEvaluator` and `DMNExpressionEvaluator`. Consider that the frontend, with the current status, can never sends an expression defined collection to be evaluated with `BaseExpressionEvaluator`. If happens, it's not expected.

2020-01-17 10:21 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +        if (isAnMVELExpression(rawValue)) {
@jomarko You right BUT: rawValue is always a `String`, even if it's declared as `Object` in `FactMappingValue` DTO. If is not a String, it's an error, then it's correct to receive an exception. Consider that we planned with @danielezonca a refactor where we'll change that `Object` type in `String` -->  https://issues.redhat.com/browse/DROOLS-4948

2020-01-17 10:27 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/main/java/org/drools/scenariosimulation/backend/expression/ExpressionEvaluatorFactory.java
> +    protected boolean isAnMVELExpression(String rawValue) {
@jomarko It could be moved to a Util class. On the other side, this method is used only in this class and I don't see another place where it could be used. In my opinon, an `Util` class should be created if we can hold static method which can be shared in multiple places. This is not the case.  I vote to don't change it, if you have an alternative pls share.

2020-01-17 10:29 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluatorTest.java
> +                                                                                          new ArrayList<>()
@jomarko Done!

2020-01-17 10:29 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluatorTest.java
> +                                                                      new ArrayList<>()
@jomarko Done!

2020-01-17 10:29 UTC, yesamer commented on drools-scenario-simulation/drools-scenario-simulation-backend/src/test/java/org/drools/scenariosimulation/backend/expression/MVELExpressionEvaluatorTest.java
> +                                                                      new ArrayList<>()
@jomarko Done!

2020-01-24 07:34 UTC, jomarko approved these changes
Approving this part, but before merge I would like to:
- increase coverage https://github.com/yesamer/drools/pull/2 slightly
- Review drools-wb- part of ensemble
- Do manual check

Thank you @yesamer

2020-01-27 13:12 UTC, merged