DROOLS-4882 : [Guided DecisionTable] Incorrect getters and setters for fields that starts with one lowercase letter
apache/incubator-kie pull request #2695
Opened 2019-12-18 13:58 UTC by Rikkola

https://issues.redhat.com/browse/DROOLS-4882

(cherry picked from commit 4ec9c2d81038264b4a29243ab5ca272254204c67)

2019-12-18 15:06 UTC, manstis approved these changes
LGTM.

2020-01-02 10:19 UTC, jomarko commented
@Rikkola Hello, I am sorry, I am confused with your message "cherry picked from". I expect such message in cases we have the issue already solved in some stream, but neither DROOLS-4882 or RHPAM-412 seems to be resolved. Could you please explain me what are we cherry-picking?

2020-01-06 14:58 UTC, jomarko requested changes
I think we need to update the PR due to a corner case - two letter fields in the form [lower case letter][upper case letter].

2020-01-06 14:58 UTC, jomarko commented on drools-workbench-models/drools-workbench-models-commons/src/main/java/org/drools/workbench/models/commons/backend/rule/RuleModelDRLPersistenceImpl.java
> +            if (fieldName.length() > 2 && Character.isLowerCase(fieldName.charAt(0)) && Character.isUpperCase(fieldName.charAt(1))) {
I think the condition needs top start as `fieldName.length() > 1` instead  of `fieldName.length() > 2 `.

I think the generated code getters/setters has same rules for fields **aField** and **aF**. Or am I wrong?

2020-01-08 12:06 UTC, Rikkola commented on drools-workbench-models/drools-workbench-models-commons/src/main/java/org/drools/workbench/models/commons/backend/rule/RuleModelDRLPersistenceImpl.java
> +            if (fieldName.length() > 2 && Character.isLowerCase(fieldName.charAt(0)) && Character.isUpperCase(fieldName.charAt(1))) {
Fixed and unit test updated to cover this.

2020-01-08 12:07 UTC, Rikkola commented
@jomarko The "cherry picked from" was due to me cherry-picking this from another branch that had other changes not related to this ticket. I removed the text from the commit. Ready for rereview now.

2020-01-08 14:50 UTC, jomarko approved these changes
Thank you @Rikkola

2020-01-14 11:23 UTC, Rikkola commented
Jenkins please execute SonarCloud Code Analysis

2020-01-15 10:15 UTC, Rikkola commented
Jenkins please execute SonarCloud Code Analysis

2020-01-15 10:45 UTC, Rikkola commented
@kiegroup/gatekeepers Can't get the Analysis green due to it being broken. Based on the repository commit history this does not stop merges. So can I have a merge please :)

2020-01-15 10:57 UTC, merged