Drools 4933 - Setup PMML refactoring implementation
apache/incubator-kie pull request #2757
Opened 2020-02-10 18:18 UTC by gitgabrio

@danielezonca @mariofusco 

See https://issues.redhat.com/browse/DROOLS-4933

2020-02-11 15:53 UTC, jiripetrlik reviewed
Hello @gitgabrio thank you for your PR with PMML architecture! I have some comments for discussion.

2020-02-11 15:53 UTC, jiripetrlik commented on kie-pmml-refactoring/pom.xml
> +  <artifactId>kie-pmml-refactoring</artifactId>
I would suggest to not use word refactoring in GAV. I know this module is not part of KIE build yet. But if it is merged and added into Drools parent pom as module these GAVs will be exported to Maven central etc. I would suggest to choose something which can be published from the start.

2020-02-11 15:53 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/model/KiePMMLExtension.java
> +public class KiePMMLExtension implements Serializable {
Do we need this class to be serializable. Is there some use case which requires serialization. There is already different serialization implemented in KIE.

2020-02-11 15:53 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/model/abstracts/KiePMMLExtensionedNamed.java
> +    public boolean equals(Object o) {
Do we expect to compare objects of this class somewhere?

2020-02-11 15:53 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/model/abstracts/KiePMMLTerm.java
> +
Please remove unnecessary new lines.

2020-02-11 15:53 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-api/src/test/java/org/kie/pmml/api/model/TestUtils.java
> +public class TestUtils {
I would suggest to do not add any test utils to API.

2020-02-11 15:53 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-integration-tests/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
I think we do not need any integration tests in architecture which you proposed. I expect there will be unit tests for models in kie-pmml-models module. Integration tests maybe for example on the level of kie-server. I would suggest to stay with only unit tests in new PMML implementation.

It is also much easier to measure test coverage when there are only unit tests located in proper modules with implementation.

2020-02-11 15:53 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-library/kie-pmml-library-api/pom.xml
> +        <version>${version.org.kie}</version>
Manage version of this artifact in the parent or even better in kie-parent.

2020-02-11 15:53 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-library/kie-pmml-library-api/pom.xml
> +        <version>${version.org.kie}</version>
Isn't the version of kie-test-util managed in kie-parent. If not I think we should add it there.

2020-02-11 15:53 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-library/kie-pmml-library-api/src/test/java/org/kie/pmml/library/testutils/TestUtils.java
> +
Please remove unnecessary new lines.

2020-02-11 15:53 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/functionals/FunctionUtils.java
> +/*
I think it is not a proper place to add definition of functional interfaces here. API should serve for methods like loadModel, verifyModel, evaluateModel etc. and not for extending Java 8 implementation. If we really need these utils and interfaces we should move it to some "*common*" module.

2020-02-11 15:53 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-library/kie-pmml-library-commons/pom.xml
> +      <artifactId>kie-pmml-library-api</artifactId>
Do we need a separate API for library. Can't we merge it with kie-pmml-api. It would be much easier for user to have only one API. Many API modules are usually source of mistakes and confusion.

2020-02-11 15:53 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-library/kie-pmml-library-compiler/pom.xml
> +
Remove new lines.

2020-02-11 15:53 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-runtime/kie-pmml-runtime-core/src/main/java/org/kie/pmml/runtime/core/utils/Converter.java
> +
Please remove newlines.

2020-02-11 15:53 UTC, jiripetrlik commented on kie-test-util/src/test/java/org/kie/test/util/filesystem/ResourceHelperTest.java
> +
Please remove newlines.

2020-02-12 07:54 UTC, gitgabrio commented on kie-pmml-refactoring/pom.xml
> +  <artifactId>kie-pmml-refactoring</artifactId>
@jiripetrlik 
Hi! @danielezonca asked me to name it that way. Anyway, I would prefer not to spend too much time in such kind of details right now. If the new and old modules will have to live together (that I would prefer not) we will address this. In the meantime, I did not add kie-pmml-refactoring to parent pom exactly for this reason.

2020-02-12 08:00 UTC, gitgabrio commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/model/abstracts/KiePMMLExtensionedNamed.java
> +    public boolean equals(Object o) {
@jiripetrlik 
Hi! All "equals" method of child classes have this snippet
`  if (!super.equals(o)) {
            return false;
        }`
 - so implementing "equals" on abstract/parent classes allow "equals" on children to also considering inherited fields.

2020-02-12 08:05 UTC, gitgabrio commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/functionals/FunctionUtils.java
> +/*
@jiripetrlik 
Hi! I may rename the "api" module to "common" - anyway I would like to avoid proliferation of unneeded modules: if I follow your logic, in that top-level module I should create a "common" package for shared methods/utils, a "model" package" for models, and an api module for interfaces that has to be implemented - and all of them should always -anyway - be declared as dependency together.

2020-02-12 08:11 UTC, gitgabrio commented on kie-pmml-refactoring/kie-pmml-library/kie-pmml-library-commons/pom.xml
> +      <artifactId>kie-pmml-library-api</artifactId>
@jiripetrlik 
Hi! Let's consider for main group of modules
1) kie-pmml-refactoring
2) kie-pmml-library
3) kie-pmml-runtime
4) kie-pmml-models-(model_name)

Each of this need an api/common/whatever shared package to allow decoupling of implementations - e.g. kie-pmml-models-regression-api will define some "model" that must to be visible to both kie-pmml-models-regression-library and kie-pmml-models-regression-runtime, without having one the them to depend on the other. Recursively, same logic apply to all other group of modules. Does this make sense?

2020-02-12 08:14 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/model/abstracts/KiePMMLExtensionedNamed.java
> +    public boolean equals(Object o) {
Ok, but the question is why you need to compare children of this class? What is the example or use case for it?

2020-02-12 08:15 UTC, jiripetrlik commented on kie-pmml-refactoring/pom.xml
> +  <artifactId>kie-pmml-refactoring</artifactId>
I'm ok with it. I have no strong opinion about it. We only need to make sure that we do not publish the artifacts on Maven central etc., because it may confuse users in the future.

2020-02-12 08:29 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/functionals/FunctionUtils.java
> +/*
I think API usually contains only interfaces which are supposed to be used by user. It is usually very stable and there should be no breaking changes with new versions. In PMML evaluator I would expect only methods or classes related directly to evalution of PMML in API. Such as loadPMML, evaluatePMML etc.

It is not good to use API to share the "implementation" with other modules. Users may start using these shared utils methods and it is not possible to change them in the future because of breaking contract. Utils classes etc. which are not supposed to be used directly by users are usually placed in commons modules. But maybe we can find some decomposition where these "common" modules will not be necessary.

2020-02-12 10:45 UTC, gitgabrio commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/model/abstracts/KiePMMLExtensionedNamed.java
> +    public boolean equals(Object o) {
@jiripetrlik 
This is part of models that will be put in set/map/list - so having the equals/hashmap will avoid clashing of instances.
Beside that, IIRC it was suggested by Sonar. Last, I think it is a good practice to add such methods to DTOs because it add predictable behavior.

2020-02-12 10:50 UTC, gitgabrio commented on kie-pmml-refactoring/pom.xml
> +  <artifactId>kie-pmml-refactoring</artifactId>
@jiripetrlik 
agreed with @danielezonca and @mariofusco to call it "kie-pmml-new"

2020-02-12 10:51 UTC, gitgabrio commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/model/KiePMMLExtension.java
> +public class KiePMMLExtension implements Serializable {
This class is contained in models that - in turns - will be serialized during kjar compilation (not implemented yet). At the same time, this module (kie-pmml-new) should not depend in anyway from something more "drools/kie" specific - that's why I've used java standard "Serializable" interface

2020-02-12 11:10 UTC, danielezonca commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/KiePMMLStatusHolder.java
> + * Class used inside drools. Rules are fired based on the value of status
If this is used only by Drools implementation it should be in a implementation module and not here in the common API. Wdyt?

2020-02-12 11:10 UTC, danielezonca commented on kie-pmml-refactoring/ToDo.md
> +TO-DOs
I think it should be better to track TODOs with a Jira epic or similar instead of a MD file here. Wdyt?

2020-02-12 11:10 UTC, danielezonca commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/annotations/Nullable.java
> +public @interface Nullable {
Can you please remove it? It is not used

2020-02-12 11:10 UTC, danielezonca commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/exceptions/KiePMMLException.java
> +public class KiePMMLException extends Exception {
Why `Exception` instead of `RuntimeException`? This change has as consequence a sort of "duplication" of many Java 8 interfaces (`Stream` and `Function` as first).
If your goal is to enforce user to manage the errors I would suggest to use one/more RuntimeException internally and then do a try/catch at public method level and generate the checked exception only there. In this way you should be able to avoid interface duplication. Wdyt?

2020-02-12 11:10 UTC, danielezonca commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/model/abstracts/KiePMMLExtensionedNamed.java
> +    public boolean equals(Object o) {
@jiripetrlik 
All these models/pojos are defined to represent XML content and should be not changed. Implementing `equals`/`hashCode` give you the possibility to manage them as "values" easier (for example compare or add them to a `Set`).
I don't think there is a specific use case for now because this PR is just a "stub" of the design that will be extended later with multiple model implementations so it is safer to already implement a meaningful equals.
Does this answer to your question?

2020-02-12 11:10 UTC, danielezonca commented on kie-pmml-refactoring/kie-pmml-api/src/test/java/org/kie/pmml/api/model/TestUtils.java
> +public class TestUtils {
I think this module is more intended to be a -common more than API so I would suggest to rename it to -common.
@gitgabrio wdyt?

2020-02-12 11:10 UTC, danielezonca commented on kie-pmml-refactoring/kie-pmml-library/kie-pmml-library-compiler/src/test/resources/LinearRegressionSample.xml
> +<PMML xmlns="http://www.dmg.org/PMML-4_2" version="4.2">
Isn't it a copy of [this](https://github.com/kiegroup/drools/blob/1073fc4f1da4d51c1d54b7f003f189699fc62e6d/kie-pmml-refactoring/kie-pmml-integration-tests/src/test/resources/LinearRegressionSample.xml) ?

2020-02-12 11:10 UTC, danielezonca commented on kie-pmml-refactoring/kie-pmml-runtime/kie-pmml-runtime-api/pom.xml
> +  <artifactId>kie-pmml-runtime-api</artifactId>
I don't like the name `runtime` to refer to a sort of "kie-integration" module. Wdyt?

2020-02-12 11:10 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-library/kie-pmml-library-commons/pom.xml
> +      <artifactId>kie-pmml-library-api</artifactId>
I'm not sure whether this is not too complex for what we want to achieve. Which is basically PMML evaluator. It sounds like we will end up with for example 40 or more modules. Which is quite much I think.
- PMML itself defines about 20 models. If we want implementation and interface for each module it is about 40 modules.
- Other modules such as library, runtime etc. It will probably be at lease 5 modules.
If you want more implementations for modules than it will be even more modules. It will be probably impossible or very hard to maintain. Especially it might be very hard for user to get oriented in it.

2020-02-12 11:12 UTC, gitgabrio commented on kie-pmml-refactoring/kie-pmml-api/src/test/java/org/kie/pmml/api/model/TestUtils.java
> +public class TestUtils {
@danielezonca @jiripetrlik 
Renamed to kie-pmml-commons -as it is actually used for

2020-02-12 11:13 UTC, gitgabrio commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/functionals/FunctionUtils.java
> +/*
@danielezonca @jiripetrlik
Renamed to kie-pmml-commons -as it is actually used for

2020-02-12 11:25 UTC, gitgabrio commented on kie-pmml-refactoring/kie-pmml-library/kie-pmml-library-commons/pom.xml
> +      <artifactId>kie-pmml-library-api</artifactId>
@jiripetrlik 
Each model may have a different optimal way to be implemented - e.g. I'm implementing Regression in pure java, while Tree will be done with drools. As such, each model has a different dependency requirement. 
At the same time, we want to avoid to create a can of worms where one model depends to a lot of unneeded others only for transitive dependencies. 
That lead to a design that is easy to understand, even if complex:

- library  (we have to rename it) is responsible to translation of original PMML to "internal" model; 
- runtime is responsible to actual evaluation.

Every model will have its own implementation of both, with its own internal model definition.
Encapsulating every model in specific module, from my point of view, allow and enforce the developer to focus *only* in the implementation is currently doing **regardless** the "abstraction" layer - that as you see is pretty thin.
PMML is an "aggregator" of different models, and the complexity of implementation reflect that. It is -more or less - like put all other models (scorecard, guideddecisions, whatever) under the same roof.
The biggest mistake -in my opinion - of the previous implementation was exactly to have (tried to) managed all of them in one single way.

2020-02-12 11:28 UTC, gitgabrio commented on kie-pmml-refactoring/ToDo.md
> +TO-DOs
@danielezonca 
Removed

2020-02-12 11:35 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/model/abstracts/KiePMMLExtensionedNamed.java
> +    public boolean equals(Object o) {
I'm probably fine with that. I still don't see your point why to define it without use case. But we can keep it there just for safety. Do you plan to use it as keys in HashMaps? Or why to store XMLs in sets? But I'm ok with it to keep it as it is.

2020-02-12 11:36 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/model/KiePMMLExtension.java
> +public class KiePMMLExtension implements Serializable {
Thank you for explanation!

2020-02-12 12:00 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-library/kie-pmml-library-commons/pom.xml
> +      <artifactId>kie-pmml-library-api</artifactId>
@gitgabrio 
I see your point. However consider the number of modules (40 or more) which need to be managed. Each module effectively means one artifact to publish etc. And it will be quite hard for user to figure out which artifact add to his dependencies when.

Of course we can and probably will have to do some "aggregating" module which will transitively collect all modules as dependencies, but it will effectively end up to adding all modules implementation and their transitive dependencies (for example Drools) to one classloader anyway. So we will effectively gain nothing from separate modules. Also consider that PMML need to work also as part of kie server and user will not tune jars which are present in WEB-INF/lib himself. Again we will probably end up with adding everything to classpath.

Maybe we can find some compromise between complexity and having separate modules. @gitgabrio @danielezonca @mariofusco Do you see any compromise or less complex approach?

2020-02-12 12:06 UTC, gitgabrio commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/KiePMMLStatusHolder.java
> + * Class used inside drools. Rules are fired based on the value of status
@danielezonca 
Moved to "drooled" module

2020-02-12 12:06 UTC, gitgabrio commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/annotations/Nullable.java
> +public @interface Nullable {
@danielezonca 
done

2020-02-12 12:08 UTC, gitgabrio commented on kie-pmml-refactoring/kie-pmml-library/kie-pmml-library-compiler/src/test/resources/LinearRegressionSample.xml
> +<PMML xmlns="http://www.dmg.org/PMML-4_2" version="4.2">
@danielezonca 
Yes

2020-02-12 12:13 UTC, gitgabrio commented on kie-pmml-refactoring/kie-pmml-runtime/kie-pmml-runtime-api/pom.xml
> +  <artifactId>kie-pmml-runtime-api</artifactId>
@danielezonca @jiripetrlik @mariofusco 

We have broadly two main functionalities/components:
1) translation from original PMML to internal model (to be used for actual evaluation)
2) actual execution of the evaluation inside the kie container (i.e. submit user input to retrieve predicted value).

Currently the first one is called "library", but I think "compiler" would be more appropriate; for the latter, beside "runtime", I do not have any special idea.
Anyway, let's just decide all together those names once and for all, because I have three branch to keep in sync and such renaming are pretty disruptive.
What's your suggestion for them?

2020-02-12 14:38 UTC, gitgabrio commented on kie-pmml-refactoring/kie-pmml-library/kie-pmml-library-commons/pom.xml
> +      <artifactId>kie-pmml-library-api</artifactId>
@jiripetrlik @danielezonca @mariofusco 
It may well be that in future we'll see a lot of unneeded complexity. 
If - for ex, all modules will be implemented only in two ways, probably it will make sense to simplify collapsing them. But, IMO, all this is "optimization", that I would like to postpone. For the moment being, this "complexity" enforce some clear boundaries and avoid mixing up things - it is easy to remove such separations in future, but it is extremely hard to do the other way around

2020-02-12 15:33 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-library/kie-pmml-library-commons/pom.xml
> +      <artifactId>kie-pmml-library-api</artifactId>
@gitgabrio 
Agree. It is probably preliminary optimization. Let's continue with more modules for now and optimize in the future.

2020-02-14 08:32 UTC, gitgabrio commented on kie-pmml-refactoring/kie-pmml-integration-tests/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
@jiripetrlik 
TBH I think such tests are needed, **beside** unit tests.
One of the main reason is that actual implementations are not hardcoded, but dinamically retrieved at runtime. So, only firing up the whole environment it is possible to verify that all components are found in proper place when needed. Does this make sense?

2020-02-14 08:33 UTC, gitgabrio commented on kie-pmml-refactoring/kie-pmml-library/kie-pmml-library-api/pom.xml
> +        <version>${version.org.kie}</version>
@jiripetrlik 
All those dependency management definitions are only transitory, since as soon as the module will be merged they will be defined in kie-parent

2020-02-14 11:14 UTC, gitgabrio commented on kie-pmml-refactoring/kie-pmml-library/kie-pmml-library-api/pom.xml
> +        <version>${version.org.kie}</version>
@jiripetrlik 
It seems needed. See answer to above question

2020-02-14 11:14 UTC, gitgabrio commented on kie-pmml-refactoring/kie-pmml-library/kie-pmml-library-api/pom.xml
> +        <version>${version.org.kie}</version>
@jiripetrlik 
... anyway, for the moment being I've put all of them (the management only) inside parent pom

2020-02-14 11:24 UTC, gitgabrio commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/exceptions/KiePMMLException.java
> +public class KiePMMLException extends Exception {
@danielezonca 
I'm not convinced of that. I understand your point, but at the same time it is not clear where such boundaries should be drawn. Putting them too "deep" would not change that much, but putting them too "high" would vanify the scope of the checked exception

2020-02-14 11:31 UTC, gitgabrio commented
jenkins please retest this

2020-02-14 11:37 UTC, gitgabrio commented
@danielezonca @mariofusco @jiripetrlik
Hi guys! I've done all the renaming/refactoring we have talked about, and managed all (but one) of your proposals. Could you please take a look again? 
Of course you will see a lot of file changed, but it is just because they have been moved

2020-02-14 12:44 UTC, danielezonca commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/exceptions/KiePMMLException.java
> +public class KiePMMLException extends Exception {
I would say that the boundary should be public (= end-user) API. My proposal is to limit this checked exception at `PMMLRuntime` level. It should be enough to try/catch runtime exceptions in `PMMLRuntimeImpl` and wrap them in the checked exception. Wdyt?

2020-02-17 11:42 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-library/kie-pmml-library-api/pom.xml
> +        <version>${version.org.kie}</version>
@gitgabrio 
Yes agree. It is probably the best place for dependency management during refactoring.

2020-02-17 11:50 UTC, jiripetrlik commented on kie-pmml-refactoring/kie-pmml-api/src/main/java/org/kie/pmml/api/exceptions/KiePMMLException.java
> +public class KiePMMLException extends Exception {
@gitgabrio @danielezonca 
I have no strong opinion here. But I would also vote for avoiding of checked exceptions, because I also don't like them.

For example if I recall correctly it was also not recommended in Clean Code book, because: 
Using checked exceptions comes with a cost - it breaks the open-closed principle: You have to declare the checked exception (in throws clause) in signatures of all methods between the throwing and catching the exception.

But I'm not sure. As I've said I have no strong opinion here.

2020-02-17 13:00 UTC, jiripetrlik reviewed
Added second round of comments. I have only few comments. But the bigger problem is that there are various util methods in this skeleton of implementation and these methods have zero test coverage. I think if we want to go from POC to ready to merge I think we need to implement tests for these methods.

2020-02-17 13:00 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/exceptions/ExternalException.java
> +public class ExternalException extends Exception {
Can we change also this to RuntimeException?

2020-02-17 13:00 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/exceptions/KiePMMLException.java
> +public class KiePMMLException extends Exception {
Can we change also this to RuntimeException?

2020-02-17 13:00 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/functionals/FunctionUtils.java
> +public class FunctionUtils {
I'm not sure about adding these functional utils into code. Can't we use some library instead?

@mariofusco 
What do you think? Can you help us to find some library with these functional utils?

2020-02-17 13:00 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/model/enums/INVALID_VALUE_TREATMENT_METHOD.java
> +        return Arrays.stream(INVALID_VALUE_TREATMENT_METHOD.values()).filter(value -> name.equals(value.name)).findFirst().orElseThrow(() -> new KieEnumException("Failed to find MINING_FUNCTION with
Can we add test for this method?

2020-02-17 13:00 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/model/enums/FIELD_USAGE_TYPE.java
> +        return Arrays.stream(FIELD_USAGE_TYPE.values()).filter(value -> name.equals(value.name)).findFirst().orElseThrow(() -> new KieEnumException("Failed to find FIELD_USAGE_TYPE with name: " + nam
Can we add test for this method?

2020-02-17 13:00 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/model/enums/MINING_FUNCTION.java
> +        return Arrays.stream(MINING_FUNCTION.values()).filter(value -> name.equals(value.name)).findFirst().orElseThrow(() -> new KieEnumException("Failed to find MINING_FUNCTION with name: " + name)
Can we add test for this method?

2020-02-17 13:00 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/model/enums/MISSING_VALUE_TREATMENT_METHOD.java
> +        return Arrays.stream(MISSING_VALUE_TREATMENT_METHOD.values()).filter(value -> name.equals(value.name)).findFirst().orElseThrow(() -> new KieEnumException("Failed to find MINING_FUNCTION with
Can we add test for this method?

2020-02-17 13:00 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/model/enums/OP_TYPE.java
> +        return Arrays.stream(OP_TYPE.values()).filter(value -> name.equals(value.name)).findFirst().orElseThrow(() -> new KieEnumException("Failed to find MINING_FUNCTION with name: " + name));
Can we add test for this method?

2020-02-17 13:00 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/model/enums/OUTLIER_TREATMENT_METHOD.java
> +        return Arrays.stream(OUTLIER_TREATMENT_METHOD.values()).filter(value -> name.equals(value.name)).findFirst().orElseThrow(() -> new KieEnumException("Failed to find MINING_FUNCTION with name:
Can we add test for this method?

2020-02-17 13:00 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/model/enums/PMML_MODEL.java
> +        return Arrays.stream(PMML_MODEL.values()).filter(value -> name.equals(value.name)).findFirst().orElseThrow(() -> new KieEnumException("Failed to find PMMLModelType with name: " + name));
Can we add test for this method?

2020-02-17 13:00 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/model/enums/VALUE_PROPERTY.java
> +        return Arrays.stream(VALUE_PROPERTY.values()).filter(value -> name.equals(value.name)).findFirst().orElseThrow(() -> new KieEnumException("Failed to find VALUE_PROPERTY with name: " + name));
Can we add test for this method?

2020-02-17 13:00 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-compiler/kie-pmml-compiler-commons/src/main/java/org/kie/pmml/compiler/commons/factories/KiePMMLExtensionFactory.java
> +        return extensions.stream().map(KiePMMLExtensionFactory::getKiePMMLExtension).collect(Collectors.toList());
Can we add test for this method?

2020-02-17 13:00 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-compiler/kie-pmml-compiler-commons/src/main/java/org/kie/pmml/compiler/commons/implementations/KiePMMLModelRetriever.java
> +        logger.info("getFromModel {}", model);
Can we add test for this method?

2020-02-17 13:00 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-compiler/kie-pmml-compiler-commons/src/main/java/org/kie/pmml/compiler/commons/implementations/ModelImplementationProviderFinderImpl.java
> +        logger.info("getImplementations {}", refresh);
Can we add test for this method?

2020-02-17 13:00 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-compiler/kie-pmml-compiler-commons/src/main/java/org/kie/pmml/compiler/commons/utils/ModelUtils.java
> +        return model.getMiningSchema().getMiningFields().stream()
Can we add test for this method?

2020-02-17 13:54 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/exceptions/ExternalException.java
> +public class ExternalException extends Exception {
@jiripetrlik 
Hi. Nope. This is meant exactly to be a checked exception.

2020-02-17 13:54 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/exceptions/KiePMMLException.java
> +public class KiePMMLException extends Exception {
@jiripetrlik
Hi. Nope. This is meant exactly to be a checked exception.

2020-02-17 14:15 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/model/enums/INVALID_VALUE_TREATMENT_METHOD.java
> +        return Arrays.stream(INVALID_VALUE_TREATMENT_METHOD.values()).filter(value -> name.equals(value.name)).findFirst().orElseThrow(() -> new KieEnumException("Failed to find MINING_FUNCTION with
@jiripetrlik 
Hi Jiri. What would you like to test? Those are five basic java calls in chain:
1) ENUM.values
2) Arrays.stream
3) Stream.filter
4) Stream.findFirst
5) Optional.orElseThrow

2020-02-17 14:20 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-compiler/kie-pmml-compiler-commons/src/main/java/org/kie/pmml/compiler/commons/implementations/ModelImplementationProviderFinderImpl.java
> +        logger.info("getImplementations {}", refresh);
@jiripetrlik 
This would an "integration" test to ServiceLoader.reload () and ServiceLoader.iterator(). I think it is already covered inside integration test module

2020-02-17 14:20 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-compiler/kie-pmml-compiler-commons/src/main/java/org/kie/pmml/compiler/commons/utils/ModelUtils.java
> +        return model.getMiningSchema().getMiningFields().stream()
Will do

2020-02-17 14:21 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-compiler/kie-pmml-compiler-commons/src/main/java/org/kie/pmml/compiler/commons/implementations/KiePMMLModelRetriever.java
> +        logger.info("getFromModel {}", model);
This would be an "integration" test. Without any real implementation, hard to see what/how to test.

2020-02-17 14:24 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/model/enums/INVALID_VALUE_TREATMENT_METHOD.java
> +        return Arrays.stream(INVALID_VALUE_TREATMENT_METHOD.values()).filter(value -> name.equals(value.name)).findFirst().orElseThrow(() -> new KieEnumException("Failed to find MINING_FUNCTION with
@gitgabrio 
We can add some simple test whether it works as expected.
- positive example - if filter finds something
- negative - if filter does not and exception is thrown

2020-02-17 14:26 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/functionals/FunctionUtils.java
> +public class FunctionUtils {
@jiripetrlik @mariofusco @danielezonca 
Fine for me if there is already such functionality in the classpath.
Anyway, a couple of things to keep in mind
1) it must not add dependency on any other drools module
2) it is a bad practice to put new libraries inside projects only to use one single feature of such libraries - duplicated code is not bad by itself, if it avoid creating/increasing coupling between otherwise unrelated code
3) Watch carefully about "functional monolith masked behind modular layout"

2020-02-17 14:46 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/functionals/FunctionUtils.java
> +public class FunctionUtils {
As I wrote. I'm not sure whether something like that exists. I've added it mostly as possible point for discussion.

2020-02-17 14:56 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/model/enums/INVALID_VALUE_TREATMENT_METHOD.java
> +        return Arrays.stream(INVALID_VALUE_TREATMENT_METHOD.values()).filter(value -> name.equals(value.name)).findFirst().orElseThrow(() -> new KieEnumException("Failed to find MINING_FUNCTION with
@jiripetrlik 
Hi Jiri. I understand you point, but I'm not fully convinced.
Basically, behind all the "wrapping", the test you are proposing would just verify that `String.equals(String)` behave as expected. It is true that there are a series of method chained together, but each of them is a standard java invocation - the result of which is the argument for the next one. 
IMO, it is the client code that has to be tested in this situation - I mean if a "compiler" call this one, we should verify the "caller" is not invoking it with wrong value: wdyt ?
As a side note, what I'm gonna do is to replace that `name.equals` with `Objects.equals`

2020-02-17 15:49 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/model/enums/INVALID_VALUE_TREATMENT_METHOD.java
> +        return Arrays.stream(INVALID_VALUE_TREATMENT_METHOD.values()).filter(value -> name.equals(value.name)).findFirst().orElseThrow(() -> new KieEnumException("Failed to find MINING_FUNCTION with
Agree with you. We will probably test this on different level.

2020-02-17 16:59 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-compiler/kie-pmml-compiler-commons/src/main/java/org/kie/pmml/compiler/commons/utils/ModelUtils.java
> +        return model.getMiningSchema().getMiningFields().stream()
@jiripetrlik 
Hi! Just pushed tests for that class.

2020-02-18 09:02 UTC, mariofusco commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/exceptions/ExternalException.java
> +public class ExternalException extends Exception {
@gitgabrio Checked exception are an outdated concept, no JVM language other than Java support them and since Java 8 they're practically deprecated also in Java since they play horribly with lambdas. Checked exception are useless verbosity in the best case and plain evil in the worst one. Please remove ALL checked exception from this pull request. Thanks.

2020-02-18 09:05 UTC, mariofusco requested changes
Pull request is fine except for abuse of checked exceptions (and yes, even one single checked exception is an abuse). Please remove them all.

2020-02-18 09:11 UTC, mariofusco commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/functionals/FunctionUtils.java
> +        return new HashMap<K, V>() {{
Is this useful? Even if it is please change the implementation: you're implicitly creating a subclass of HashMap at each invocation in this way.

2020-02-18 09:11 UTC, mariofusco commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/interfaces/FunctionalWrapperFactory.java
> +            } catch (Exception e) {
Demonstration that checked exceptions are bogus.

2020-02-18 09:12 UTC, mariofusco commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/interfaces/ThrowingBiConsumer.java
> +public interface ThrowingBiConsumer<T, U, E extends Exception> {
At this point I want to die.

2020-02-18 09:14 UTC, mariofusco commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/model/KiePMMLExtension.java
> +    private String extender;
Should this be Serializable? If so you need an empty constructor. If not make all these fields final.

2020-02-18 09:30 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/model/KiePMMLExtension.java
> +    private String extender;
@mariofusco 
Fixed with last commit

2020-02-18 09:33 UTC, mariofusco commented on kie-pmml-new/kie-pmml-compiler/kie-pmml-compiler-api/src/main/java/org/kie/pmml/compiler/api/provider/ModelImplementationProvider.java
> +public interface ModelImplementationProvider<T extends Model, E extends KiePMMLModel> {
This generic doesn't seem to be useful since you cannot use it on the call site and then obliges you to add those [at]SuppressWarning annotation.

2020-02-18 09:33 UTC, mariofusco commented on kie-pmml-new/kie-pmml-compiler/kie-pmml-compiler-commons/src/main/java/org/kie/pmml/compiler/commons/implementations/ModelImplementationProviderFinderImpl.java
> +    @SuppressWarnings("rawtypes")
If you remove the generic on the ModelImplementationProvider as I suggested above you can get rid of this annotation.

2020-02-18 09:47 UTC, mariofusco approved these changes

2020-02-18 09:54 UTC, jiripetrlik approved these changes
@gitgabrio 
Thank you for all changes you made during the review process! It looks good to me. We will probably need to measure and check test coverage before adding to standard build and during adding new modules.

2020-02-18 10:00 UTC, danielezonca approved these changes

2020-02-18 10:31 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-compiler/kie-pmml-compiler-api/src/main/java/org/kie/pmml/compiler/api/provider/ModelImplementationProvider.java
> +public interface ModelImplementationProvider<T extends Model, E extends KiePMMLModel> {
@mariofusco 
Reason for the generic at interface signature is to allow inside actual implementations  (e.g.):
` public KiePMMLRegressionModel getKiePMMLModel(DataDictionary dataDictionary, RegressionModel model, Object kBuilder) ` (concrete types as returns and parameters)

I could not find a proper/clean way to achieve that putting generic definition to the method itself. Could you please suggest one, if it is doable ? Thx.

2020-02-18 11:15 UTC, gitgabrio commented
jenkins execute full downstream build

2020-02-18 13:27 UTC, baldimir commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/model/enums/INVALID_VALUE_TREATMENT_METHOD.java
> +        return Arrays.stream(INVALID_VALUE_TREATMENT_METHOD.values()).filter(value -> name.equals(value.name)).findFirst().orElseThrow(() -> new KieEnumException("Failed to find MINING_FUNCTION with
It is recommended that code has sufficient unit test coverage. What Jiri proposes is exactly that. "Hi Jiri. What would you like to test? Those are five basic java calls in chain" - exactly those 5 basic Java calls in a chain should be tested. In future, someone might change this so that it doesn't work correctly. Then we will miss the test. The code should have as big unit test coverage as possible. I know that it is sometimes a pain to write them, but they are useful, although they may not look like that.

2020-02-19 08:02 UTC, merged