KOGITO-1575 DMN assembler-free ikb-free DMNRuntime
apache/incubator-kie pull request #2831
Opened 2020-03-27 14:43 UTC by tarilabs

@hellowdan @lucamolteni 
/cc @etirelli

2020-03-27 15:21 UTC, lucamolteni requested changes

2020-03-27 15:21 UTC, lucamolteni commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/impl/DMNRuntimeKBWrappingIKB.java
> +                for (Entry<String, String> kv : kieBaseModel.getKModule().getConfigurationProperties().entrySet()) {
Can we replace this with stream API?

2020-03-27 16:49 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/impl/DMNRuntimeKBWrappingIKB.java
> +                for (Entry<String, String> kv : kieBaseModel.getKModule().getConfigurationProperties().entrySet()) {
Does it really give advantages?

```
                kieBaseModel.getKModule().getConfigurationProperties().entrySet().stream()
                .filter(kv -> kv.getKey() != null && kv.getKey().startsWith(DMNAssemblerService.DMN_RUNTIME_LISTENER_PREFIX))
                .forEach(kv -> {
                    if (ClassLoaderUtil.CAN_PLATFORM_CLASSLOAD) {
                        try {
                            DMNRuntimeEventListener runtimeListenerInstance = (DMNRuntimeEventListener) knowledgeBase.getRootClassLoader().loadClass(kv.getValue()).newInstance();
                            results.add(runtimeListenerInstance);
                        } catch (Exception e) {
                            logger.error("Cannot perform classloading of runtime listener: {}", kv, e);
                        }
                    } else {
                        logger.error("This platform does not support classloading of runtime listener: {}", kv);
                    }
                });
```

2020-03-27 16:51 UTC, tarilabs commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/impl/DMNRuntimeKBWrappingIKB.java
> +                for (Entry<String, String> kv : kieBaseModel.getKModule().getConfigurationProperties().entrySet()) {
or even the following, does it really give advantages?

```
                kieBaseModel.getKModule().getConfigurationProperties().entrySet().stream()
                .filter(kv -> kv.getKey() != null && kv.getKey().startsWith(DMNAssemblerService.DMN_RUNTIME_LISTENER_PREFIX))
                .map(kv -> {
                    if (ClassLoaderUtil.CAN_PLATFORM_CLASSLOAD) {
                        try {
                            DMNRuntimeEventListener runtimeListenerInstance = (DMNRuntimeEventListener) knowledgeBase.getRootClassLoader().loadClass(kv.getValue()).newInstance();
                            return runtimeListenerInstance;
                        } catch (Exception e) {
                            logger.error("Cannot perform classloading of runtime listener: {}", kv, e);
                        }
                    } else {
                        logger.error("This platform does not support classloading of runtime listener: {}", kv);
                    }
                    return null;
                })
                .filter(listener -> listener != null)
                .collect(Collectors.toList());
```

2020-03-30 07:56 UTC, hellowdan approved these changes

2020-03-30 09:44 UTC, lucamolteni approved these changes

2020-03-30 11:55 UTC, merged