Drools 5144
apache/incubator-kie pull request #2836
Opened 2020-04-01 07:23 UTC by gitgabrio

@danielezonca @mariofusco @jiripetrlik 

see https://issues.redhat.com/browse/DROOLS-5144

2020-04-01 10:55 UTC, jiripetrlik requested changes
@gitgabrio Thank you for your PR! I have few comments and suggestions.

2020-04-01 10:55 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models-archetype/pom.xml
> +        <configuration>
Can you please explain why it is good to change settings of this plugin.

2020-04-01 10:55 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Can you please describe the motivation behind "drooled" module? What is it for?

2020-04-01 10:55 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/executor/DrooledModelExecutor.java
> +            e.printStackTrace();
Please handle this exception properly.

2020-04-01 10:55 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/executor/DrooledModelExecutor.java
> +//    @Override
Is this this code commented out intentionally?

2020-04-01 10:55 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLTreeModelCompoundPredicateASTFactory.java
> +            case AND:
I would suggest to add the same implementation to all branches for readability.

2020-04-01 10:55 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLTreeModelFactory.java
> +            e.printStackTrace();
Please handle exception properly.

2020-04-01 10:55 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/test/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLTreeModelPredicateASTFactoryTest.java
> +    public void declareRuleFromPredicate() {
Seems like implementation is missing.

2020-04-01 10:55 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-evaluator/src/main/resources/org/kie/pmml/models/tree/evaluator/TreeModel.drl
> +        System.out.println("return " + toReturn);
Please remove debugging outputs.

2020-04-01 10:55 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-evaluator/src/main/resources/org/kie/pmml/models/tree/evaluator/TreeModel.drl
> +         System.out.println("return " + toReturn);
Please remove.

2020-04-01 10:55 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-evaluator/src/main/resources/org/kie/pmml/models/tree/evaluator/TreeModel.drl
> +//rule "Get Tree"
Is this commented out intentionally?

2020-04-01 10:55 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-evaluator/src/test/java/org/kie/pmml/models/tree/evaluator/TreeModelCompilationTest.java
> +            e.printStackTrace();
Please handle this exception properly.

2020-04-01 10:55 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-model/src/main/java/org/kie/pmml/models/tree/model/KiePMMLNode.java
> +                        break;
Can we avoid of using break here?

2020-04-01 10:55 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-model/src/main/java/org/kie/pmml/models/tree/model/enums/BOOLEAN_OPERATOR.java
> +        return Arrays.stream(BOOLEAN_OPERATOR.values()).filter(value -> name.equals(value.name)).findFirst().orElseThrow(() -> new KieEnumException("Failed to find MODEL_TYPE with name: " + name));
Please split this stream to multiple lines.

2020-04-01 10:55 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-model/src/main/java/org/kie/pmml/models/tree/model/enums/OPERATOR.java
> +        return Arrays.stream(OPERATOR.values()).filter(value -> name.equals(value.name)).findFirst().orElseThrow(() -> new KieEnumException("Failed to find MODEL_TYPE with name: " + name));
Please split to multiple lines.

2020-04-01 10:55 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-model/src/test/java/org/kie/pmml/models/tree/model/KiePMMLNodeTest.java
> +    http://dmg.org/pmml/v4-4/TreeModel.html
Please remove PMML from this file.

2020-04-01 10:55 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-model/src/test/java/org/kie/pmml/models/tree/model/predicates/KiePMMLCompoundPredicateTest.java
> +    // TODO {gcardosi} re-implement with native drools rules
It is possible to ignore unfinished tests using Ignore annotation. It is better because such tests will appear in junit statistics and we will not forget to finish them.

2020-04-01 10:55 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-model/src/test/java/org/kie/pmml/models/tree/model/predicates/KiePMMLSimplePredicateTest.java
> +    // TODO {gcardosi} re-implement with native drools rules
Please rather ignore unfinished tests.

2020-04-02 07:40 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models-archetype/pom.xml
> +        <configuration>
HI @jiripetrlik 
I made some changes here: 

1. (about eof) it was a to get rid of a warning during execution;
2. increase debug output to better understand what happen during execution
3. Replaced statically defined version with property-defined one (this is related to warnings that are generated by some script running in CI); to implement that modification, I also had to move resources to "filtered" resources folder

2020-04-02 07:42 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
@jiripetrlik 
All models using rule engine will have some common code (pls look at Drooled Executor and factories). Since I already know there will be more then one "rule-based" implementation, I've put such shared code in this module. All the rule-based implementations have to "depend" on this one. It will also allow me to manage common feature/behavior in one single place

2020-04-02 07:47 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/executor/DrooledModelExecutor.java
> +            e.printStackTrace();
@jiripetrlik 
TBH, this method is for development only - I'm not expecting rules to be dumped every time and I will remove it soon before merge (I'll add a TODO for this). Moreover, the only reasonable way I see to deal with it it would be to just ignore it, because I do not care at all if the "dump" does not work for some reason - what I'm concerned about is if the actual **execution** fails. Does this make sense? Do you have some suggestion?

2020-04-02 07:47 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/executor/DrooledModelExecutor.java
> +//    @Override
@jiripetrlik 
Rremoved - forgotten leftover

2020-04-02 07:50 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLTreeModelCompoundPredicateASTFactory.java
> +            case AND:
@jiripetrlik 
I do not follow you. **Surrogate** Compounds are actually dealt with as if they are a new "Node" - so the logic is completely different compared to the others

2020-04-02 07:51 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLTreeModelFactory.java
> +            e.printStackTrace();
@jiripetrlik 
See my previous answer - this snippet is to be completely removed

2020-04-02 07:54 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/test/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLTreeModelPredicateASTFactoryTest.java
> +    public void declareRuleFromPredicate() {
@jiripetrlik 
Yes - not sure if this Test class is actually needed at all - basically only specific behavior is an "instance of".

2020-04-02 07:58 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-evaluator/src/main/resources/org/kie/pmml/models/tree/evaluator/TreeModel.drl
> +         System.out.println("return " + toReturn);
@jiripetrlik 
Those drl files where leftover - deleted them

2020-04-02 07:58 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-evaluator/src/main/resources/org/kie/pmml/models/tree/evaluator/TreeModel.drl
> +//rule "Get Tree"
@jiripetrlik 
See above

2020-04-02 08:09 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-model/src/main/java/org/kie/pmml/models/tree/model/KiePMMLNode.java
> +                        break;
@jiripetrlik 
Removed this (and others) leftover classes

2020-04-02 08:15 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-model/src/main/java/org/kie/pmml/models/tree/model/enums/BOOLEAN_OPERATOR.java
> +        return Arrays.stream(BOOLEAN_OPERATOR.values()).filter(value -> name.equals(value.name)).findFirst().orElseThrow(() -> new KieEnumException("Failed to find MODEL_TYPE with name: " + name));
@jiripetrlik 
Done

2020-04-02 08:15 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-model/src/main/java/org/kie/pmml/models/tree/model/enums/OPERATOR.java
> +        return Arrays.stream(OPERATOR.values()).filter(value -> name.equals(value.name)).findFirst().orElseThrow(() -> new KieEnumException("Failed to find MODEL_TYPE with name: " + name));
@jiripetrlik 
Done

2020-04-02 08:16 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-model/src/test/java/org/kie/pmml/models/tree/model/KiePMMLNodeTest.java
> +    http://dmg.org/pmml/v4-4/TreeModel.html
@jiripetrlik 
Deleted file

2020-04-02 08:16 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-model/src/test/java/org/kie/pmml/models/tree/model/predicates/KiePMMLCompoundPredicateTest.java
> +    // TODO {gcardosi} re-implement with native drools rules
@jiripetrlik 
Deleted file

2020-04-02 08:16 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-model/src/test/java/org/kie/pmml/models/tree/model/predicates/KiePMMLSimplePredicateTest.java
> +    // TODO {gcardosi} re-implement with native drools rules
@jiripetrlik 
Deleted file

2020-04-02 14:47 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models-archetype/pom.xml
> +        <configuration>
@gitgabrio 
And do you plan to remove it before PR is ready to be merged?

2020-04-02 14:48 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
@gitgabrio Thank you for explanation.

2020-04-02 14:51 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/executor/DrooledModelExecutor.java
> +            e.printStackTrace();
@gitgabrio 
I think that if you plan to remove it before PR is ready it is not a problem. In general I think it is good to rethrow in RuntimeException.

2020-04-02 14:53 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLTreeModelCompoundPredicateASTFactory.java
> +            case AND:
I meant to put for all "cases" AND, OR, XOR the same call with break.

2020-04-02 14:57 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models-archetype/pom.xml
> +        <configuration>
@jiripetrlik 
Nope - this is meant to be the final (?) implementation (unless for bugs). Is there anything you would prefer to change?

2020-04-02 14:58 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/executor/DrooledModelExecutor.java
> +            e.printStackTrace();
:+1: 
Perfectly agree: my plan is to remove that development-only code

2020-04-03 08:36 UTC, lucamolteni requested changes

2020-04-03 08:36 UTC, lucamolteni commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/commons/factories/KiePMMLDescrLhsFactory.java
> +                constraintBuilder.append(operator);
This is the StringUtils.join logic and it's repeated a few times

2020-04-03 08:36 UTC, lucamolteni commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/commons/factories/KiePMMLDescrLhsFactory.java
> +            if (i > 0) {
StringUtils.join

2020-04-03 08:36 UTC, lucamolteni commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/commons/factories/KiePMMLDescrLhsFactory.java
> +                constraintBuilder.append(" || ");
StringUtils.join

2020-04-03 08:36 UTC, lucamolteni commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/commons/factories/KiePMMLDescrLhsFactory.java
> +                constraintBuilder.append(", ");
StringUtils.join

2020-04-03 08:36 UTC, lucamolteni commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/executor/DrooledModelExecutor.java
> +        // TODO {gcardosi} Dev debug only - to be removed
to be removed

2020-04-03 08:36 UTC, lucamolteni commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLTreeModelNodeASTFactory.java
> +//        if (predicate instanceof True) {
commmented code

2020-04-07 14:08 UTC, gitgabrio commented
@danielezonca @mariofusco @jiripetrlik

Pls take a look at it - ready for review/merge

2020-04-08 14:08 UTC, danielezonca reviewed
Can you please rename `Drooled` to `Drools` everywhere? :)

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/enums/StatusCode.java
> +    DONE("DONE"),
Can you add a small javadoc for each status to describe when it is used? It is not clear to me DONE vs OK/FAIL

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-evaluator/kie-pmml-evaluator-core/src/main/java/org/kie/pmml/evaluator/core/service/PMMLRuntimeImpl.java
> +                requestData.addRequestParam(fieldName, missingValueReplacement);
Is it possible to keep track of the fact that we are using default value for this parameter (a status field in `ParameterInfo` or something similar)?

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/pom.xml
> +  <name>KIE :: PMML :: Models :: Drooled</name>
What does `Drooled` mean?

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-compiler/kie-pmml-compiler-commons/src/main/java/org/kie/pmml/compiler/commons/utils/ModelUtils.java
> +        return getTargetFieldsTypeMap(dataDictionary, model).entrySet().iterator().next().getValue();
Can you explain this method? Why are you returning the first element? It is deterministic only because `getTargetFieldsTypeMap` use a `LinkedHasMap` that should be an implementation detail (maybe we can use a `SortedMap` to make it evident?)

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/ast/KiePMMLDrooledConstraint.java
> +public interface KiePMMLDrooledConstraint {
Javadoc?

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/ast/KiePMMLDrooledAST.java
> +    private final Queue<KiePMMLDrooledRule> rules;
Why `Queue`?

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/ast/KiePMMLDrooledRule.java
> +public class KiePMMLDrooledRule {
Can you please add a javadoc?
It is "drools-agnostic" so maybe we can remove Drools from the name?

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/ast/KiePMMLDrooledTarget.java
> +public interface KiePMMLDrooledTarget extends KiePMMLDrooledConstraint {
Javadoc?

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/ast/KiePMMLDrooledTypeField.java
> +public class KiePMMLDrooledTypeField {
Javadoc?
Do you use this?

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/executor/DrooledModelExecutor.java
> +        printGeneratedRules(drooledModel);
To be removed/refactored

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/executor/DrooledModelExecutor.java
> +        final AgendaEventListener agendaEventListener = new AgendaEventListener() {
Can you please move it to a static final field?

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/provider/DrooledModelProvider.java
> +    protected final KieServices kieServices;
It is not used

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/provider/DrooledModelProvider.java
> +    public E getKiePMMLModel(DataDictionary dataDictionary, T model, Object kBuilder) {
Can you please review `Object kBuilder`? Is it really needed?

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/tuples/KiePMMLOperatorValue.java
> +    public String toString() {
Can you please create a `asString()` or similar to produce an equivalent method without overload `toString` with a specific meaning

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/ast/KiePMMLFieldOperatorValue.java
> +    public String toString() {
Please verify that this `toString` is not used during code generation but only for logging purposes

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/executor/TreeModelImplementationProvider.java
> +public class TreeModelImplementationProvider extends DrooledModelProvider<TreeModel, KiePMMLTreeModel> {
If it is Drools specific please move to a `-drools` module

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLASTFactoryUtils.java
> +                break;
Please raise an exception like `new IllegalStateException("This should never happen")`

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLASTFactoryUtils.java
> +                    // noop
Same as above

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLASTFactoryUtils.java
> +                case XOR:
It is not possible to reach this code (look at the if at the beginning of the method), can you please review?

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLTreeModeAbstractPredicateASTFactory.java
> +    protected final Queue<KiePMMLDrooledRule> rules;
Why `Queue`?

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLTreeModelCompoundPredicateASTFactory.java
> +                break;
What if `Surrogate`?

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLTreeModelCompoundPredicateASTFactory.java
> +                break;
Can you please add a `default` case too?

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-evaluator/src/main/java/org/kie/pmml/models/tree/evaluator/PMMLTreeModelEvaluator.java
> +public class PMMLTreeModelEvaluator extends DrooledModelExecutor {
Can you please move this class inside a `-drools` module?

2020-04-08 14:08 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-model/src/main/java/org/kie/pmml/models/tree/model/KiePMMLTreeModel.java
> +public class KiePMMLTreeModel extends KiePMMLDrooledModel {
Can you please move to a `-drools` module?

2020-04-08 14:10 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/executor/DrooledModelExecutor.java
> +                .newKieSession();
@mariofusco 
Can you please double check this block? Is it the proper way to load them?
NOTE: we will need to review them for Kogito

2020-04-08 16:10 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-commons/src/main/java/org/kie/pmml/commons/enums/StatusCode.java
> +    DONE("DONE"),
Done

2020-04-08 16:10 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-evaluator/kie-pmml-evaluator-core/src/main/java/org/kie/pmml/evaluator/core/service/PMMLRuntimeImpl.java
> +                requestData.addRequestParam(fieldName, missingValueReplacement);
Done

2020-04-08 16:11 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-compiler/kie-pmml-compiler-commons/src/main/java/org/kie/pmml/compiler/commons/utils/ModelUtils.java
> +        return getTargetFieldsTypeMap(dataDictionary, model).entrySet().iterator().next().getValue();
DONE

2020-04-08 16:11 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/ast/KiePMMLDrooledConstraint.java
> +public interface KiePMMLDrooledConstraint {
Removed

2020-04-08 16:11 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/ast/KiePMMLDrooledTarget.java
> +public interface KiePMMLDrooledTarget extends KiePMMLDrooledConstraint {
Removed

2020-04-08 16:11 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/ast/KiePMMLDrooledTypeField.java
> +public class KiePMMLDrooledTypeField {
Removed

2020-04-08 16:11 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/executor/DrooledModelExecutor.java
> +        printGeneratedRules(drooledModel);
Removed

2020-04-08 16:11 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/provider/DrooledModelProvider.java
> +    protected final KieServices kieServices;
Removed

2020-04-08 16:11 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLASTFactoryUtils.java
> +                break;
Done

2020-04-08 16:11 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLASTFactoryUtils.java
> +                    // noop
Done

2020-04-08 16:11 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLASTFactoryUtils.java
> +                case XOR:
DONE

2020-04-08 16:11 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLTreeModelCompoundPredicateASTFactory.java
> +                break;
DONE

2020-04-08 16:11 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLTreeModelCompoundPredicateASTFactory.java
> +                break;
DONE

2020-04-09 09:22 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/factories/KiePMMLTreeModeAbstractPredicateASTFactory.java
> +    protected final Queue<KiePMMLDrooledRule> rules;
Replaced with List

2020-04-09 09:23 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-evaluator/src/main/java/org/kie/pmml/models/tree/evaluator/PMMLTreeModelEvaluator.java
> +public class PMMLTreeModelEvaluator extends DrooledModelExecutor {
DONE

2020-04-09 09:23 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-model/src/main/java/org/kie/pmml/models/tree/model/KiePMMLTreeModel.java
> +public class KiePMMLTreeModel extends KiePMMLDrooledModel {
DONE

2020-04-09 09:23 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/ast/KiePMMLDrooledAST.java
> +    private final Queue<KiePMMLDrooledRule> rules;
REplaced with List

2020-04-09 09:23 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/ast/KiePMMLDrooledRule.java
> +public class KiePMMLDrooledRule {
DONE

2020-04-09 09:28 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/executor/DrooledModelExecutor.java
> +        final AgendaEventListener agendaEventListener = new AgendaEventListener() {
DONE

2020-04-09 09:52 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/provider/DrooledModelProvider.java
> +    public E getKiePMMLModel(DataDictionary dataDictionary, T model, Object kBuilder) {
@danielezonca 
Yes, it is needed by the "Drools" implementations.

2020-04-09 09:52 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/tuples/KiePMMLOperatorValue.java
> +    public String toString() {
DONE

2020-04-09 09:53 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/src/main/java/org/kie/pmml/models/drooled/ast/KiePMMLFieldOperatorValue.java
> +    public String toString() {
DONE

2020-04-09 09:53 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-tree/kie-pmml-models-tree-compiler/src/main/java/org/kie/pmml/models/tree/compiler/executor/TreeModelImplementationProvider.java
> +public class TreeModelImplementationProvider extends DrooledModelProvider<TreeModel, KiePMMLTreeModel> {
DONE

2020-04-09 09:54 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drooled/pom.xml
> +  <name>KIE :: PMML :: Models :: Drooled</name>
Add description. Replaced with Drools

2020-04-10 15:34 UTC, danielezonca reviewed
Just minor comments and then it is fine for me :)

2020-04-10 15:34 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drools/kie-pmml-models-drools-common/src/main/java/org/kie/pmml/models/drools/executor/DroolsModelExecutor.java
> +    private static AgendaEventListener getAgendaEventListener() {
I would prefer to just keep the field and remove this method because nobody should use it. Wdyt?

2020-04-10 15:34 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drools/kie-pmml-models-drools-tree/kie-pmml-models-drools-tree-evaluator/src/test/java/org/kie/pmml/models/drools/tree/evaluator/CompoundPredicatesTreeTest.java
> +    private static final String TARGET_FIELD = "result"/* ""Predicted_result"*/;
Comment to remove

2020-04-10 15:34 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drools/kie-pmml-models-drools-tree/kie-pmml-models-drools-tree-evaluator/src/test/java/org/kie/pmml/models/drools/tree/evaluator/CompoundPredicatesTreeTest.java
> +//                {6, 6.5, 7.7, "classXorNode"},
Can you remove them?

2020-04-14 09:42 UTC, jiripetrlik requested changes
Hello @gitgabrio I have three comments to this PR:
- Please resolve conflicts in GIT
- Update poms to 7.37 snapshot
- I still see loads of debugging outputs when I run integration tests. Is this expected? Can you please remove unnecessary outputs

2020-04-14 10:01 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drools/kie-pmml-models-drools-tree/kie-pmml-models-drools-tree-evaluator/src/test/java/org/kie/pmml/models/drools/tree/evaluator/CompoundPredicatesTreeTest.java
> +//                {6, 6.5, 7.7, "classXorNode"},
@danielezonca 
Done

2020-04-14 10:01 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drools/kie-pmml-models-drools-tree/kie-pmml-models-drools-tree-evaluator/src/test/java/org/kie/pmml/models/drools/tree/evaluator/CompoundPredicatesTreeTest.java
> +    private static final String TARGET_FIELD = "result"/* ""Predicted_result"*/;
@danielezonca 
Done

2020-04-14 10:02 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drools/kie-pmml-models-drools-common/src/main/java/org/kie/pmml/models/drools/executor/DroolsModelExecutor.java
> +    private static AgendaEventListener getAgendaEventListener() {
@danielezonca 
Done
I took the chance to completely "hide" KieSession access/usage in a specific class.

2020-04-14 10:26 UTC, gitgabrio commented
> Hello @gitgabrio I have three comments to this PR:
> 
> * Please resolve conflicts in GIT
> * Update poms to 7.37 snapshot
> * I still see loads of debugging outputs when I run integration tests. Is this expected? Can you please remove unnecessary outputs

Hi @jiripetrlik 
I fixed the first two points. About the latter, I've lowered most of my log  to "trace" level, but still have a 17 MB log output - and most of it is coming from drools engine itself. If you want to avoid it,  I think only option is to provide a `simplelogger.properties` file to customize log level

2020-04-14 11:47 UTC, danielezonca approved these changes
Approving with minor comment

2020-04-14 11:47 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drools/kie-pmml-models-drools-common/src/main/java/org/kie/pmml/models/drools/utils/KiePMMLSessionUtils.java
> +    }
Can you please review this method? I don't like that it is named `add...` but the values to add are fields.
I would prefer one of the following:
- Use a field for `KieSession` too and rename the method like `init()`
- Add `pmml4Result` and `unwrappedInputParams` as parameters too
- Keep the method as it is but rename it as `initKieSession`

Wdyt?

2020-04-14 12:21 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drools/kie-pmml-models-drools-common/src/main/java/org/kie/pmml/models/drools/utils/KiePMMLSessionUtils.java
> +    }
@danielezonca 
For one reason or another none of the above suggestions satisfy me by themselves, but I think I get the point.
I've refactored/simplified the class a little bit: removed "state" of the class; put as much initialization as possible inside the constructor; etc.
I still keep the method name "addObjectsToSession" because I think it is exactly what the method does - "initKieSession" looks a little bit misleading with this refactoring.

2020-04-14 13:19 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models/kie-pmml-models-drools/kie-pmml-models-drools-common/src/main/java/org/kie/pmml/models/drools/utils/KiePMMLSessionUtils.java
> +    }
I had a look to method after the refactoring and I don't like that now the KieSession is created together with the builder but it is fine for now. We will probably have to change/adapt this code in the future so I would like not to spend other time on it now :)

2020-04-15 12:58 UTC, jiripetrlik approved these changes
@gitgabrio 
Thank you for all changes which you have made. I think it is ready for merge now!

2020-04-15 13:15 UTC, merged