Drools 5241 - Create archetype for PMML models with drool implementation
apache/incubator-kie pull request #2855
Opened 2020-04-15 15:12 UTC by gitgabrio

@danielezonca @jiripetrlik 

This PR is about create a specific archetype to generate modules for implementation using drools

2020-04-15 16:47 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models-drools-archetype/Readme.md
> +
Can you add some more new lines? :smile:

2020-04-15 16:47 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models-drools-archetype/src/main/resources/archetype-resources/__rootArtifactId__-evaluator/pom.xml
> +    <!-- TODO MOVE TO kie-pmml-new/pom.xml -->
I think it is better to add this step to the README instead of having it here. Wdyt?

2020-04-15 16:47 UTC, danielezonca commented on kie-pmml-new/kie-pmml-models-drools-archetype/src/main/resources/archetype-resources/__rootArtifactId__-evaluator/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Don't we have a `drools-core` dependency in this pom? I was expecting to have it

2020-04-16 07:22 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models-drools-archetype/src/main/resources/archetype-resources/__rootArtifactId__-evaluator/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
@danielezonca 
Not needed here.

2020-04-16 07:40 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models-drools-archetype/Readme.md
> +
@danielezonca 
Done

2020-04-16 07:41 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models-drools-archetype/src/main/resources/archetype-resources/__rootArtifactId__-evaluator/pom.xml
> +    <!-- TODO MOVE TO kie-pmml-new/pom.xml -->
@danielezonca 
Done

2020-04-16 07:41 UTC, gitgabrio commented
@danielezonca 
I've done required modifications. Could you please look at them ?

2020-04-16 07:57 UTC, danielezonca approved these changes
Thanks for the changes, it looks fine to me :+1:

2020-04-16 11:09 UTC, jiripetrlik requested changes
@gitgabrio Thank you for Maven archetype! I have few minor comments.

2020-04-16 11:09 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models-drools-archetype/pom.xml
> +    <maven.compiler.source>1.8</maven.compiler.source>
Isn't this inherited from parents?

2020-04-16 11:09 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models-drools-archetype/pom.xml
> +        <version>3.1.0</version>
I think it would be better to inherit version from parent or use plugin management or property instead of hard coded version.

2020-04-16 11:09 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models-drools-archetype/src/main/resources/archetype-resources/__rootArtifactId__-compiler/src/main/java/__packageModelName__/compiler/executor/__modelName__ModelImplementationProvider.java
> +* Copyright ${year} Red Hat, Inc. and/or its affiliates.
Is this Maven archetype intended only for RedHat? If not I think it would be better to leave it on user to write license and copyright information.

2020-04-16 11:09 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models-drools-archetype/src/main/resources/archetype-resources/__rootArtifactId__-compiler/src/main/java/__packageModelName__/compiler/factories/KiePMML__modelName__ModelFactory.java
> + * Copyright ${year} Red Hat, Inc. and/or its affiliates.
Please remove license and copyright template from archetype.

2020-04-16 11:09 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models-drools-archetype/src/main/resources/archetype-resources/__rootArtifactId__-compiler/src/test/java/__packageModelName__/drools/compiler/executor/__modelName__ModelImplementationProviderTest.java
> +    public void getKiePMMLModel() throws Exception {
I would suggest to let this test failed with some unimplemented exception. Or at least ignore it. Otherwise it will provide the false assumption that it is implemented and working.

2020-04-16 11:09 UTC, jiripetrlik commented on kie-pmml-new/kie-pmml-models-drools-archetype/src/main/resources/archetype-resources/__rootArtifactId__-evaluator/src/main/java/__packageModelName__/drools/evaluator/PMML__modelName__ModelEvaluator.java
> + * Copyright ${year} Red Hat, Inc. and/or its affiliates.
Please remove RedHat license and copyright template from archetype.

2020-04-16 11:12 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models-drools-archetype/src/main/resources/archetype-resources/__rootArtifactId__-compiler/src/main/java/__packageModelName__/compiler/executor/__modelName__ModelImplementationProvider.java
> +* Copyright ${year} Red Hat, Inc. and/or its affiliates.
@jiripetrlik 
Currently this is meant to be used by us to quickly create "stub" modules. And I would prefer to manually add license on every generated class :)

2020-04-16 11:13 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models-drools-archetype/src/main/resources/archetype-resources/__rootArtifactId__-compiler/src/main/java/__packageModelName__/compiler/factories/KiePMML__modelName__ModelFactory.java
> + * Copyright ${year} Red Hat, Inc. and/or its affiliates.
@jiripetrlik 
See previous answer

2020-04-16 12:04 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models-drools-archetype/pom.xml
> +        <version>3.1.0</version>
@jiripetrlik 
:+1:

2020-04-16 12:05 UTC, gitgabrio commented
@jiripetrlik 
I've done modifications (beside the license one). Could you please take a look again ?

2020-04-16 12:07 UTC, gitgabrio commented on kie-pmml-new/kie-pmml-models-drools-archetype/pom.xml
> +    <maven.compiler.source>1.8</maven.compiler.source>
@jiripetrlik 
:+1:

2020-04-16 13:58 UTC, jiripetrlik approved these changes
@gitgabrio Thank you! Looks good to me.

2020-04-16 14:12 UTC, gitgabrio commented
@danielezonca 
Could you pls merge this ? Thanks!

2020-04-20 08:53 UTC, merged