[JBPM-9129] Start process without triggering a start node
apache/incubator-kie pull request #2881
Opened 2020-05-04 08:34 UTC by elguardian

added new command to restart a process from where it left

2020-05-04 08:35 UTC, elguardian commented
depends on https://github.com/kiegroup/droolsjbpm-knowledge/pull/438

2020-05-20 14:46 UTC, krisv requested changes

2020-05-20 14:46 UTC, krisv commented on drools-core/src/main/java/org/drools/core/base/WrappedStatefulKnowledgeSessionForRHS.java
> +    public ProcessInstance startProcessFromNodeIds(String processId, Map<String, Object> params, String... nodeInstancesIds) {
Still seems to refer to nodeInstanceIds but I think these are just nodeIds (node definition ids).

2020-05-20 14:46 UTC, krisv commented on drools-core/src/main/java/org/drools/core/command/runtime/process/StartProcessFromNodeIdsCommand.java
> +    @XmlElementWrapper(name = "node-instance-id-list")
Same here, this class seem to refer to instance ids in many places, but they are definition ids I believe.

2020-05-21 09:37 UTC, elguardian commented on drools-core/src/main/java/org/drools/core/base/WrappedStatefulKnowledgeSessionForRHS.java
> +    public ProcessInstance startProcessFromNodeIds(String processId, Map<String, Object> params, String... nodeInstancesIds) {
done.

2020-05-21 09:38 UTC, elguardian commented on drools-core/src/main/java/org/drools/core/command/runtime/process/StartProcessFromNodeIdsCommand.java
> +    @XmlElementWrapper(name = "node-instance-id-list")
done

2020-05-21 10:50 UTC, gmunozfe commented on drools-core/src/main/java/org/drools/core/command/runtime/process/StartProcessFromNodeIdsCommand.java
> +    }
This is the same as parent but method name, that could be resolved by reflection or with a protected attribute

2020-05-21 10:50 UTC, gmunozfe commented on drools-ruleunit/src/main/java/org/drools/ruleunit/executor/RuleUnitSessionImpl.java
> +    public ProcessInstance startProcessFromNodeIds(String processId, Map<String, Object> params, String... nodeInstancesIds) {
Same comment as Kris here to be coherent, use _nodeIds_

2020-05-21 10:50 UTC, gmunozfe commented on drools-templates/src/test/java/org/drools/template/parser/ExternalSheetListenerTest.java
> +                public ProcessInstance startProcessFromNodeIds(String processId, Map<String, Object> params, String... nodeInstancesIds) {
and same here

2020-05-21 13:48 UTC, afalhambra requested changes
Small changes requested, but looks good to me

2020-05-21 13:48 UTC, afalhambra commented on drools-core/src/main/java/org/drools/core/command/runtime/process/StartProcessFromNodeIdsCommand.java
> + * Copyright 2010 Red Hat, Inc. and/or its affiliates.
Should be 2020
```suggestion
 * Copyright 2020 Red Hat, Inc. and/or its affiliates.
```

2020-05-21 13:48 UTC, afalhambra commented on drools-core/src/main/java/org/drools/core/command/runtime/process/StartProcessFromNodeIdsCommand.java
> +    }
Wonder if logging `nodeIds` list here could add some value when debugging? wdyt?

2020-05-22 08:08 UTC, elguardian commented on drools-core/src/main/java/org/drools/core/command/runtime/process/StartProcessFromNodeIdsCommand.java
> + * Copyright 2010 Red Hat, Inc. and/or its affiliates.
done

2020-05-22 08:09 UTC, elguardian commented on drools-core/src/main/java/org/drools/core/command/runtime/process/StartProcessFromNodeIdsCommand.java
> +    }
removed.

2020-05-22 08:09 UTC, elguardian commented on drools-ruleunit/src/main/java/org/drools/ruleunit/executor/RuleUnitSessionImpl.java
> +    public ProcessInstance startProcessFromNodeIds(String processId, Map<String, Object> params, String... nodeInstancesIds) {
done

2020-05-22 08:10 UTC, elguardian commented on drools-templates/src/test/java/org/drools/template/parser/ExternalSheetListenerTest.java
> +                public ProcessInstance startProcessFromNodeIds(String processId, Map<String, Object> params, String... nodeInstancesIds) {
done

2020-05-25 10:25 UTC, afalhambra approved these changes
Nice work!

2020-05-27 14:05 UTC, merged

2020-05-28 11:56 UTC, mareknovotny commented
@elguardian please fix compilation failure on CDB https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/drools-compile-downstream-build/1499/console
it was revealed in another PR FDB