[JBPM-9178] Immutable SpringBoot Deployment
apache/incubator-kie pull request #2931
Opened 2020-06-04 05:53 UTC by elguardian

2020-06-04 05:55 UTC, elguardian commented
depends on https://github.com/kiegroup/droolsjbpm-knowledge/pull/443 
https://github.com/kiegroup/kie-soup/pull/142
https://github.com/kiegroup/droolsjbpm-knowledge/pull/443

2020-06-13 00:47 UTC, mattdkerr approved these changes

2020-06-19 14:10 UTC, afalhambra requested changes
Overall looks good to me. I left some comments for you to review.

Also, test code coverage should reach 80% at least. Specially for the two following classes:

https://github.com/kiegroup/drools/blob/9a837e9d6293e8803416b08623f71f48e0ea3577/kie-ci/src/main/java/org/kie/scanner/KieModuleMetaDataImpl.java

and

https://github.com/kiegroup/drools/blob/9a837e9d6293e8803416b08623f71f48e0ea3577/drools-compiler/src/main/java/org/drools/compiler/kie/builder/impl/KieServicesImpl.java

2020-06-19 14:10 UTC, afalhambra commented on drools-compiler/src/main/java/org/drools/compiler/kie/builder/impl/ClasspathKieProject.java
> +                }
Not sure why we want to access to all parents for the classloader? We might get a SecurityException is some cases.

2020-06-19 14:10 UTC, afalhambra commented on drools-compiler/src/main/java/org/drools/compiler/compiler/io/memory/MemoryFileSystem.java
> +                CRC32 crc = new CRC32();
Why using CRC32 now? not sure about this change? Is this related to the issue itself or it's just an improvement of the same? can you please clarify?

2020-06-19 14:10 UTC, afalhambra commented on kie-ci/src/main/java/org/kie/scanner/KieModuleMetaDataImpl.java
> +    private final Set<URL> jars = new HashSet<>();
Should be changed to `Set<URI>` instead as per Sonar complain, just in case

2020-06-19 14:10 UTC, afalhambra commented on kie-ci/src/main/java/org/kie/scanner/KieModuleMetaDataImpl.java
> +                releasesId.add(releaseId);
Loop can be replaced with `Collections.addAll`

```suggestion
releasesId.addAll(kieModule.getPomModel().getDependencies(dependencyFilter));
```

2020-06-19 14:10 UTC, afalhambra commented on kie-ci/src/main/java/org/kie/scanner/KieModuleMetaDataImpl.java
> +        if (artifactLocation != null && artifactLocation.getArtifact().getExtension() != null && artifactLocation.getArtifact().getExtension().equals("jar")) {
`artifactLocation.getArtifact()` might be `null` due to:

https://github.com/kiegroup/kie-soup/blob/6a307c900c067c8fb4d312a8b9cc03f4e243bd2f/kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/DefaultArtifactResolver.java#L54

2020-06-19 14:10 UTC, afalhambra commented on kie-ci/src/main/java/org/kie/scanner/KieModuleMetaDataImpl.java
> +            if (artifactLocation.isClassPath()) {
`artifactLocation` might be `null` due to:

https://github.com/kiegroup/kie-soup/blob/6a307c900c067c8fb4d312a8b9cc03f4e243bd2f/kie-soup-maven-utils/kie-soup-maven-integration/src/main/java/org/appformer/maven/integration/DefaultArtifactResolver.java#L54

2020-06-19 14:10 UTC, afalhambra commented on kie-ci/src/main/java/org/kie/scanner/KieModuleMetaDataImpl.java
> +                }
Why not using the previous method to do this? 

https://github.com/kiegroup/drools/blob/8037cfba371213e74c3656228422079d09b1d9cb/drools-core/src/main/java/org/drools/core/util/IoUtils.java#L209

Is it only to keep on reading zip entries if those additional validations are met? why do we want this?

2020-06-23 07:42 UTC, elguardian commented on kie-ci/src/main/java/org/kie/scanner/KieModuleMetaDataImpl.java
> +                }
when you are reading within a file that method does not work. You need to support jar within a jar... The older method was not supporting that.

2020-06-23 07:47 UTC, elguardian commented on drools-compiler/src/main/java/org/drools/compiler/kie/builder/impl/ClasspathKieProject.java
> +                }
you need a security manager installed. Much of the code would not work in that case. We would need to setup properly in that case.

2020-06-23 08:49 UTC, elguardian commented on drools-compiler/src/main/java/org/drools/compiler/compiler/io/memory/MemoryFileSystem.java
> +                CRC32 crc = new CRC32();
removed

2020-06-23 09:01 UTC, elguardian commented on kie-ci/src/main/java/org/kie/scanner/KieModuleMetaDataImpl.java
> +                releasesId.add(releaseId);
ok

2020-06-23 09:01 UTC, elguardian commented on kie-ci/src/main/java/org/kie/scanner/KieModuleMetaDataImpl.java
> +            if (artifactLocation.isClassPath()) {
cool

2020-06-23 09:54 UTC, elguardian commented on kie-ci/src/main/java/org/kie/scanner/KieModuleMetaDataImpl.java
> +    private final Set<URL> jars = new HashSet<>();
not really, it is more convenient to set it as URL (we are using that anyway.

2020-06-23 09:54 UTC, elguardian commented on kie-ci/src/main/java/org/kie/scanner/KieModuleMetaDataImpl.java
> +        if (artifactLocation != null && artifactLocation.getArtifact().getExtension() != null && artifactLocation.getArtifact().getExtension().equals("jar")) {
done

2020-06-24 15:07 UTC, afalhambra requested changes
Some additional comments.

2020-06-24 15:07 UTC, afalhambra commented on kie-ci/src/main/java/org/kie/scanner/KieModuleMetaDataImpl.java
> +            releasesId.addAll(dependencies);
Do we really want to add all transitive dependencies? I guess user should carefully add them at their own risk, but we could end up having duplicate deps in different places and locations (BOOT-INF/lib and BOOT-INF/classes/KIE-INF/lib)

2020-06-24 15:07 UTC, afalhambra commented on kie-ci/src/main/java/org/kie/scanner/KieModuleMetaDataImpl.java
> +        log.info("ADD Artifact {} to {}", location, jars);
I would remove this log. It's better with the log used below, when the jar is actually added to the HashSet jars. Also it is not an artifact but an artifact location.

2020-06-24 15:07 UTC, afalhambra commented on kie-ci/src/main/java/org/kie/scanner/KieModuleMetaDataImpl.java
> +        if (artifactLocation != null && artifactLocation.getArtifact().getExtension() != null && artifactLocation.getArtifact().getExtension().equals("jar")) {
sorry I cannot see the change?

2020-06-25 06:27 UTC, elguardian commented on kie-ci/src/main/java/org/kie/scanner/KieModuleMetaDataImpl.java
> +            releasesId.addAll(dependencies);
yep you need them. Otherwise won't be available at classloader

2020-06-25 07:15 UTC, afalhambra commented on kie-ci/src/main/java/org/kie/scanner/KieModuleMetaDataImpl.java
> +            releasesId.addAll(dependencies);
just wondering - is it not possible to use the same location for all deps? like `BOOT-INF/lib` folder instead of having two different locations?

2020-06-26 07:02 UTC, elguardian commented on kie-ci/src/main/java/org/kie/scanner/KieModuleMetaDataImpl.java
> +        log.info("ADD Artifact {} to {}", location, jars);
ok. set as debug.

2020-08-04 14:51 UTC, elguardian commented
Jenkins retest this please.

2020-08-12 06:32 UTC, merged

2020-08-13 11:59 UTC, ederign commented
@elguardian looks like this commit is the root cause of https://issues.redhat.com/browse/DROOLS-5574 that is actually blocking BC. Did the CI pass before merge it?