Fix the implementation of the nn sum extended FEEL function for edge cases
apache/incubator-kie pull request #3012
Opened 2020-07-29 18:37 UTC by SimonRinguette

Fixed cases are:

- nn sum( [] ) => returned null, now returns 0
- nn sum( [null] ) => exception thrown, now returns 0
- nn sum( [null, null] ) => returned null, now returns 0

The BaseFEELFunction.java fix could also fix other cases where a list containing a single null element was used in a list.

2020-07-29 18:38 UTC, SimonRinguette commented
@tarilabs as discussed in an email discussion, here is the PR that fix the behaviour of the nn sum feel method to more closelly follow the sum feel method.

2020-07-30 07:11 UTC, tarilabs commented
Jenkins test again

2020-07-30 07:12 UTC, tarilabs commented
ok to test

2020-07-30 08:29 UTC, tarilabs commented
Jenkins execute compile downstream build

2020-07-30 08:46 UTC, tarilabs approved these changes
approving when green

2020-07-30 08:46 UTC, tarilabs commented on kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/KieFEELExtendedFunctionsTest.java
> +                { "nn sum( [ null, null ] )", new BigDecimal("0", MathContext.DECIMAL128), null },
ok

2020-07-30 08:59 UTC, tarilabs requested changes
sorry just to be clear @SimonRinguette 
this will make that
`nn sum([]) = 0`
while from the spec we have
`sum([]) = null`
just to confirm the different behaviour is what is expected, we shall review this in the thread with Bruce?

2020-07-30 13:00 UTC, SimonRinguette commented
@tarilabs This was because I was using a build that did not contain your https://issues.redhat.com/browse/DROOLS-5440 fix, updating my PR in a few minutes

2020-07-30 13:08 UTC, SimonRinguette commented
@tarilabs I forced pushed the commit to change the message.

While this fix nn sum([null]), i'm pretty sure that it also fixes other edge cases with method with multiple signatures that can receive a null list in the parameter and would fail similarly

2020-07-30 13:12 UTC, tarilabs approved these changes

2020-07-30 13:12 UTC, tarilabs commented on kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/KieFEELExtendedFunctionsTest.java
> +                { "nn sum( [ null, null ] )", null, null },
Consistent with `sum([]) = null` from DMN spec (v1.3) Table 75, good for me thanks!

2020-07-30 15:20 UTC, hellowdan approved these changes

2020-08-10 07:53 UTC, tarilabs commented on kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/KieFEELExtendedFunctionsTest.java
> +                { "nn sum( [ null, null ] )", null, null },
```suggestion
                { "nn sum( [] )", BigDecimal.ZERO, null },
                { "nn sum( [ null ] )", BigDecimal.ZERO, null },
                { "nn sum( [ null, null ] )", BigDecimal.ZERO, null },
```

2020-08-10 07:53 UTC, tarilabs requested changes
based on conversation

2020-08-24 19:01 UTC, SimonRinguette commented
@tarilabs Hopefully wrapping this one up... we have done some back and forth.

The PR is now back to the original Use Cases described in the issue as discussed between me / you / @etirelli and Bruce Silver in a separate email thread.

We decided to have nn sum([]) = 0 instead of nn sum([]) = null. nn sum([]) = null would be more aligned to the existing sum([]) = null FEEL function but the business requirement for this extension function is to ignore the notion of nulls and make the sum 0.

2020-08-25 07:31 UTC, tarilabs approved these changes

2020-08-25 07:31 UTC, tarilabs commented on kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/runtime/KieFEELExtendedFunctionsTest.java
> +                { "nn sum( [ null, null ] )", BigDecimal.ZERO, null },
👍  as discussed

2020-08-25 07:31 UTC, tarilabs commented
will ask for merge since this implements required changes https://github.com/kiegroup/drools/pull/3012#pullrequestreview-464019201 as discussed

2020-08-25 07:37 UTC, merged