[DROOLS-5780] descope ecj
apache/incubator-kie pull request #3237
Opened 2020-11-12 18:26 UTC by mariofusco

2020-11-12 18:26 UTC, mariofusco commented
jenkins execute fdb

2020-11-12 19:19 UTC, lucamolteni approved these changes

2020-11-13 15:30 UTC, mariofusco commented
jenkins execute fdb

2020-11-13 15:44 UTC, lucamolteni requested changes

2020-11-13 15:44 UTC, lucamolteni commented on drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/NativeJavaCompiler.java
> +                Field classesField = ClassLoader.class.getDeclaredField( "classes" );
Does this work in Java11/Native image?

2020-11-16 02:11 UTC, tkobayas commented
kie-dmn-validation failed to build on my end. (openjdk version "11.0.8" 2020-07-14 LTS)
```
[INFO] --- exec-maven-plugin:1.5.0:java (validation-bootstrap) @ kie-dmn-validation ---
...
java.lang.reflect.InvocationTargetException
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:294)
    at java.lang.Thread.run (Thread.java:834)
Caused by: java.lang.ExceptionInInitializerError
    at org.drools.mvel.MVELConstraintBuilder.createJavaDialectConfiguration (MVELConstraintBuilder.java:132)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.buildDialectConfigurationMap (KnowledgeBuilderConfigurationImpl.java:400)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.init (KnowledgeBuilderConfigurationImpl.java:243)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.init (KnowledgeBuilderConfigurationImpl.java:197)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.<init> (KnowledgeBuilderConfigurationImpl.java:165)
    at org.drools.compiler.kie.builder.impl.KieBuilderImpl.compileJavaClasses (KieBuilderImpl.java:717)
    at org.drools.compiler.kie.builder.impl.KieBuilderImpl.buildAll (KieBuilderImpl.java:244)
    at org.kie.dmn.validation.bootstrap.GenerateModel.generate (GenerateModel.java:64)
    at org.kie.dmn.validation.bootstrap.ValidationBootstrapMain.main (ValidationBootstrapMain.java:49)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:294)
    at java.lang.Thread.run (Thread.java:834)
Caused by: java.lang.RuntimeException: value '11.0.8' is not a valid language level
    at org.drools.compiler.compiler.JavaConfiguration.setJavaLanguageLevel (JavaConfiguration.java:156)
    at org.drools.compiler.compiler.JavaConfiguration.init (JavaConfiguration.java:131)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.buildDialectConfigurationMap (KnowledgeBuilderConfigurationImpl.java:401)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.init (KnowledgeBuilderConfigurationImpl.java:243)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.init (KnowledgeBuilderConfigurationImpl.java:197)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.<init> (KnowledgeBuilderConfigurationImpl.java:165)
    at org.drools.compiler.compiler.JavaConfiguration.<clinit> (JavaConfiguration.java:85)
    at org.drools.mvel.MVELConstraintBuilder.createJavaDialectConfiguration (MVELConstraintBuilder.java:132)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.buildDialectConfigurationMap (KnowledgeBuilderConfigurationImpl.java:400)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.init (KnowledgeBuilderConfigurationImpl.java:243)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.init (KnowledgeBuilderConfigurationImpl.java:197)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.<init> (KnowledgeBuilderConfigurationImpl.java:165)
    at org.drools.compiler.kie.builder.impl.KieBuilderImpl.compileJavaClasses (KieBuilderImpl.java:717)
    at org.drools.compiler.kie.builder.impl.KieBuilderImpl.buildAll (KieBuilderImpl.java:244)
    at org.kie.dmn.validation.bootstrap.GenerateModel.generate (GenerateModel.java:64)
    at org.kie.dmn.validation.bootstrap.ValidationBootstrapMain.main (ValidationBootstrapMain.java:49)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:294)
    at java.lang.Thread.run (Thread.java:834)
```

2020-11-16 09:29 UTC, mariofusco commented on drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/NativeJavaCompiler.java
> +                Field classesField = ClassLoader.class.getDeclaredField( "classes" );
This happens only at compile time, so I believe there shouldn't be any problem with the native image.

2020-11-16 10:47 UTC, danielezonca commented on drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java
>              return null;
It is a bit unrelated but why don't return `Optional<JavaCompiler>` if it can silently fail?

2020-11-16 10:47 UTC, danielezonca commented on drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java
>      public JavaCompiler loadCompiler( JavaConfiguration.CompilerType compilerType, String lngLevel ) {
What is the differences between `loadCompiler` and `createCompiler`? Both create it so it seems to be just an overload

2020-11-16 10:47 UTC, danielezonca commented on drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java
> +        if (lngLevel.startsWith( "1." )) { // avoid in memory compilation with JPMS
Why this hack?

2020-11-16 10:47 UTC, danielezonca commented on drools-ecj/pom.xml
> +    <name>Drools :: ECJ</name>
Do you think it makes sense to keep the shading of ecj in this pom? The original problem was to avoid clashing with GWT ecj version and this could still happen. Now with the descoping I think the shading should be preserved: if you want to avoid ECJ you can while if you explicitly add this dependency having it shaded or not should be the same. Wdyt?

2020-11-16 10:47 UTC, danielezonca commented on drools-ecj/pom.xml
> +    <name>Drools :: ECJ</name>
What about `drools-engine-classic`? Do we want to keep ecj in that "bundle"? As default?

2020-11-16 10:47 UTC, danielezonca commented on drools-ecj/pom.xml
> +    <name>Drools :: ECJ</name>
I'm worried that now we will not test ecj anymore at all because it is not the default and it is not explicitly declared/used anywhere as far as I can see.
Do you think it make sense to add ecj tests as parametrized junit? only some tests? the whole test suite?
I'm not sure we want to deprecate ecj or we just want to make it optional but we want to be sure everything still works
We can improve with other tickets, now I would like to understand the direction

2020-11-16 10:47 UTC, danielezonca commented on drools-compiler/src/main/java/org/drools/compiler/compiler/JavaConfiguration.java
> +            final String prop = this.conf.getChainedProperties().getProperty( JAVA_COMPILER_PROPERTY, hasEclipseCompiler() ? "ECLIPSE" : "NATIVE" );
We should document this behavior, personally I don't like a "dynamic" default based on classpath.
Is it for backward compatibility?
In any case, can you please add a `log.debug` with the selected value to make it easier to debug?
Something like
```java
log.debug("Selected compiler " + prop + " [drools.dialect.java.compiler:" + this.conf.getChainedProperties().getProperty( JAVA_COMPILER_PROPERTY, null) + ", hasEclipseCompiler:" + hasEclipseCompiler() + "]");
```

2020-11-16 10:47 UTC, danielezonca commented on drools-compiler/src/main/java/org/drools/compiler/compiler/JavaConfiguration.java
> +        javaCompiler.setSourceFolder("src/main/java/");
Is it possible to move this configuration as part of `DEFAULT_JAVA_CONFIGURATION`?

2020-11-16 10:47 UTC, danielezonca commented on drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/NativeJavaCompiler.java
> +        private List<JavaFileObject> findClassesIndexed(String packageName) {
What do you mean with "Indexed"?

2020-11-16 11:13 UTC, mariofusco commented on drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java
>      public JavaCompiler loadCompiler( JavaConfiguration.CompilerType compilerType, String lngLevel ) {
`createCompiler` is just an internal impl, I made it private.

2020-11-16 11:33 UTC, mariofusco commented on drools-compiler/src/main/java/org/drools/compiler/compiler/JavaConfiguration.java
> +            final String prop = this.conf.getChainedProperties().getProperty( JAVA_COMPILER_PROPERTY, hasEclipseCompiler() ? "ECLIPSE" : "NATIVE" );
The idea is that if you brought ecj in your classpath it is because you want to use it and then it makes it the default choice without the need of any further settings. I understand this behaviour is questionable and I'm open to discuss it.

2020-11-16 11:47 UTC, mariofusco commented on drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java
> +        if (lngLevel.startsWith( "1." )) { // avoid in memory compilation with JPMS
This is to force the native java compiler to work with a 1.8 source level (or less). If I make it run with 9+ (i.e. with JPMS) I get weird compilation errors like the following
`UNKNOWN (-1:-1) : module jdk.accessibility reads package  from both java.base and java.naming`
I spent quite a lot of time trying to figure out what's going on here but I'm clueless so far. I understand that this a ugly hack and something that I should fix asap. Also it is quite surprising that ecj seems not suffer of the same problem, but still I haven't been able yet to figure out why.

2020-11-16 11:53 UTC, mariofusco commented on drools-ecj/pom.xml
> +    <name>Drools :: ECJ</name>
I was hoping that making ecj optional would also make that shading no longer useful, which is also one of the main reason for this descoping, see also what's reported in original ticket https://issues.redhat.com/browse/DROOLS-5780
In essence the best way to overcome the problem is not using ecj at all, but yes, I agree that if a user brings the` drools-ecj` module in and wants to use it with GWT we should do the shading anyway. Let's discuss this.

2020-11-16 17:57 UTC, danielezonca commented
jenkins retest this please

2020-11-16 18:01 UTC, danielezonca commented on drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java
> +        if (lngLevel.startsWith( "1." )) { // avoid in memory compilation with JPMS
Does it mean that user will not be able to use >1.8 code in DRL until this is fixed?

2020-11-16 18:23 UTC, mariofusco commented on drools-ecj/pom.xml
> +    <name>Drools :: ECJ</name>
I will add a profile to test ecj.

2020-11-16 18:25 UTC, mariofusco commented on drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java
> +        if (lngLevel.startsWith( "1." )) { // avoid in memory compilation with JPMS
For now yes, I will avoid this for ecj.

2020-11-16 18:30 UTC, danielezonca commented on drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/NativeJavaCompiler.java
> +        private List<JavaFileObject> findClassesIndexed(String packageName) {
What about `findClassesFromPackage`?

2020-11-17 13:15 UTC, danielezonca approved these changes
Thanks for the PR, approving :+1:

2020-11-17 17:51 UTC, mariofusco commented
jenkins execute fdb

2020-11-18 01:46 UTC, tkobayas approved these changes

2020-11-18 10:57 UTC, mariofusco commented
jenkins execute fdb

2020-11-18 12:53 UTC, mariofusco commented
jenkins execute fdb

2020-11-18 12:53 UTC, mariofusco commented
jenkins retest this

2020-11-18 14:07 UTC, mariofusco commented
jenkins retest this

2020-11-18 17:17 UTC, mariofusco commented
jenkins execute fdb

2020-11-19 11:30 UTC, mariofusco commented
jenkins execute fdb

2020-11-20 08:24 UTC, mariofusco commented
The 2 failures

```
org.uberfire.java.nio.fs.file.SimpleUnixFileStoreTest.simpleTests

Error Message

expected:<81739[49747]2L> but was:<81739[68179]2L>

Stacktrace

org.junit.ComparisonFailure: expected:<81739[49747]2L> but was:<81739[68179]2L>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

and

```
org.kie.workbench.common.services.backend.builder.core.BuilderTest.testBuilderFixForBrokenKModule

Stacktrace

java.lang.NullPointerException
	at org.kie.workbench.common.services.backend.builder.core.ClassVerifier.verify(ClassVerifier.java:52)
	at org.kie.workbench.common.services.backend.builder.core.Builder.verifyClasses(Builder.java:292)
```

are clearly unrelated.

2020-11-20 08:26 UTC, merged