DROOLS-6014 DMN ANC refactor to avoid using DTableModel
apache/incubator-kie pull request #3375
Opened 2021-02-11 14:06 UTC by tarilabs

**JIRA**: https://issues.redhat.com/browse/DROOLS-6014

**referenced Pull Requests**: none

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2021-02-11 14:50 UTC, lucamolteni requested changes
Thanks for the PR, just a minor comment on a type

2021-02-11 14:50 UTC, lucamolteni commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/compiler/alphanetbased/AlphaNetDMNEvaluatorCompiler.java
> +        final Function<QName, Type> resolver = new DTQNameToTypeResolver(compiler, model, node.getSource(), decisionTable);
Why using a Function type instead of `DTQNameToTypeResolver`? tableCellParser.parseCells doesn't consume any other kind of function - please use directly the class (and rename .apply)

2021-02-11 15:54 UTC, lucamolteni approved these changes

2021-02-11 16:08 UTC, hellowdan approved these changes

2021-02-17 09:38 UTC, mariofusco approved these changes

2021-02-17 09:39 UTC, merged