[DROOLS-6492] 2nd incremental update causes misfiring of a rule with …
apache/incubator-kie pull request #3732
Opened 2021-07-15 07:41 UTC by tkobayas

…'from'

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6492

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2021-07-15 07:41 UTC, tkobayas commented
Jenkins run fdb

2021-07-15 09:16 UTC, tkobayas commented
On the 3rd run (= 2nd incremental update), FromNode.resultClass's ClassLoader is old so the list element objects don't match the resultClass.

Why this happens on the 3rd run? Because

- The 1st run : KnowledgePackageImpl doesn't have typeResolver.
- The 2nd run : KieBaseUpdaterImpl lets KnowledgePackageImpl create a ClassTypeResolver which caches classes in cachedImports.
- The 3rd run : KieBaseUpdaterImpl reuses the KnowledgeBaseImpl, KnowledgePackageImpl and the ClassTypeResolver.

TypeResolver.cachedImports may return a Class with an old ClassLoader but KieBaseUpdaterImpl calls kbuilder.rewireAllClassObjectTypes() to solve the classloader mismatch. The problem is that FromNode holds resultClass as a bare Class object which is not reached by wiring.

2021-07-15 09:34 UTC, mariofusco approved these changes

2021-07-16 07:02 UTC, hellowdan approved these changes

2021-07-16 07:15 UTC, tkobayas commented
FDB failure is not related
```
org.kie.karaf.itest.InstallFeaturesKarafIntegrationTest.testInstallFeature[13: jbpm-human-task]
```

2021-07-16 07:50 UTC, pibizza requested changes
This is clearly an integration test - we have to play with classloading and the effects require a network of objects in place to perform the test.

I have added two comments, but they are minor points.

2021-07-16 07:50 UTC, pibizza commented on drools-test-coverage/test-compiler-integration/src/test/java/org/drools/compiler/integrationtests/incrementalcompilation/MultipleIncrementalCompilationTest.java
> +        buildKjar(releaseId, personListSrc1);
I like this test a lot. There is a clear separation of the issue - different classloading - and the implementation details on how we arrive there.

2021-07-16 07:50 UTC, pibizza commented on drools-test-coverage/test-compiler-integration/src/test/java/org/drools/compiler/integrationtests/incrementalcompilation/MultipleIncrementalCompilationTest.java
> +        }
A minor point. Would it be possible to remove the if and use a parameter that is passed during the test? This would make the test cleaner. 

However this is a minor point.

2021-07-16 07:50 UTC, pibizza commented on drools-test-coverage/test-compiler-integration/src/test/java/org/drools/compiler/integrationtests/incrementalcompilation/MultipleIncrementalCompilationTest.java
> +        final KieSession ksession = ((InternalKieContainer) kieContainer).getKieSession(); // use the same ksession
Other minor point - since the real issue here is to reuse  the same ksession, could you just put it in a field of the test and reuse it in the method? This would remove the need to pass the kieContainer. 

If you instead want to be explicit that you are reusing the same ksession, I suggest putting the kSession in a local variable of the test and passing the kSession to the method runRules.

2021-07-16 07:51 UTC, merged

2021-07-16 08:11 UTC, tkobayas commented on drools-test-coverage/test-compiler-integration/src/test/java/org/drools/compiler/integrationtests/incrementalcompilation/MultipleIncrementalCompilationTest.java
> +        }
@pibizza Thanks, I think I will be able to add such a method in KieUtil.

2021-07-16 08:15 UTC, tkobayas commented on drools-test-coverage/test-compiler-integration/src/test/java/org/drools/compiler/integrationtests/incrementalcompilation/MultipleIncrementalCompilationTest.java
> +        final KieSession ksession = ((InternalKieContainer) kieContainer).getKieSession(); // use the same ksession
@pibizza Yes, it's a possible approach. But in this test, I'm simulating a kie-server use case (which was originally reported in https://issues.redhat.com/browse/RHDM-1781). Eventually it's the same ksession but kieContainer.getKieSession() is also a part of the integration test scenario.