[DROOLS-6430] Nested map access in RHS fails in exec-model
apache/incubator-kie pull request #3735
Opened 2021-07-19 09:58 UTC by tkobayas

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6430

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2021-07-20 00:28 UTC, tkobayas commented
Jenkins retest this

2021-07-20 02:24 UTC, tkobayas commented
Jenkins retest this

2021-07-20 10:00 UTC, lucamolteni requested changes

2021-07-20 10:00 UTC, lucamolteni commented on drools-model/drools-mvel-compiler/src/main/java/org/drools/mvelcompiler/ast/ListAccessExprT.java
> +                                return null;
are you sure about this null? I think you should do `flatMap -> Optional`

2021-07-21 07:16 UTC, lucamolteni commented on drools-model/drools-mvel-compiler/src/main/java/org/drools/mvelcompiler/ast/ListAccessExprT.java
> +                                return null;
I stand corrected that is useless

2021-07-21 09:18 UTC, tkobayas commented
Jenkins run fdb

2021-07-21 09:38 UTC, lucamolteni approved these changes

2021-07-21 11:16 UTC, hellowdan approved these changes

2021-07-23 07:11 UTC, mariofusco approved these changes

2021-07-23 07:12 UTC, merged