[DROOLS-6545] HalfBinary constraint with || And && causes StackOverfl…
apache/incubator-kie pull request #3786
Opened 2021-08-11 10:00 UTC by tkobayas

…owError

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6545

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2021-08-12 05:55 UTC, tkobayas commented
The github action test failures are not related to this PR:
```
kiegroup_drools/drools-persistence/drools-persistence-jpa/src/test/java/org/drools/persistence/timer/integrationtests/TimerAndCalendarTest.java:1553 | expected:<2> but was:<1>
```

2021-08-12 07:19 UTC, lucamolteni requested changes

2021-08-12 07:19 UTC, lucamolteni commented on drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/expressiontyper/ExpressionTyper.java
> +    public static Expression findLeftLeafOfNameExprTraversingParent(Node expression) {
Check if you can use `DrlxParseUtil.findRootNodeViaParent`

or instead `node.findAncestor()` which is the JavaParser method we could have used instead (but I didn't know of its existence at the time)

2021-08-16 08:58 UTC, tkobayas commented on drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/expressiontyper/ExpressionTyper.java
> +    public static Expression findLeftLeafOfNameExprTraversingParent(Node expression) {
Thank you for the suggestion, @lucamolteni 

`node.findAncestor()` seems to be a good fit so I rewrite the code with the method. Thanks! (`DrlxParseUtil.findRootNodeViaParent` doesn't fit because we want to traverse from closer parents, not jumping to the root parent. See `HalfBinaryTest.testNestedHalfBinaryOrAndAmpersand`)

2021-08-16 13:01 UTC, hellowdan approved these changes

2021-08-17 07:57 UTC, lucamolteni approved these changes

2021-08-17 14:07 UTC, danielezonca commented on drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/DrlxParseUtil.java
> +            Expression parentLeft = findLeftLeafOfNameExprTraversingParent( halfBinaryExpr );
@tkobayas 
I don't fully understand the fix: as far as I can see in the [Jira ticket](https://issues.redhat.com/browse/DROOLS-6545), the method `ExpressionTyper.toTypedExpressionRec` can produce a StackOverflow recursion in certain conditions (based on the input).
So I was expecting to see some change in that method to prevent (even throwing an IllegalArgumentException if necessary) it but as far as I can understand this fix introduces a new path that does a "preliminary" navigation/search to avoid to trigger this SO.

Said differently: is it possible to trigger the same SO invoking the existing `findLeftLeafOfNameExpr` function with a wrong param? If so I think we should fix this too.

2021-08-18 05:12 UTC, tkobayas commented on drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/DrlxParseUtil.java
> +            Expression parentLeft = findLeftLeafOfNameExprTraversingParent( halfBinaryExpr );
@danielezonca  Thank you for reviewing. Before the fix, `HalfBinaryTest.testHalfBinaryOrAndAmpersand` was executed like:
1. Parse binaryExpr `> 20  && < 30`
2. Call `toTypedExpression` for its `left`, which is `> 20`
3. Call `toTypedExpressionRec` for `> 20`
4. Call `trasformHalfBinaryToBinary` for `> 20`
5. Call `findLeftLeafOfNameExpr` for the parent `> 20 && < 30`
6. `findLeftLeafOfNameExpr` finds `> 20` as the left leaf
7. `trasformHalfBinaryToBinary` combines the left leaf `> 20` with the original HalfBinaryExpr into a BinaryExpr. It results in `> 20 > 20`. (Bad!)
8. Call `toTypedExpressionRec` for `> 20 > 20`
9. Call `toTypedExpressionRec` for its `left`, which is `> 20`
 -> loops from step 3 to step 9 (This time, the parent is `> 20 > 20`)

The fix is to traverse parents until it finds an Expr (which is not a HalfBinaryExpr) so that it can construct an expected BinaryExpr.

> So I was expecting to see some change in that method to prevent (even throwing an IllegalArgumentException if necessary) it but as far as I can understand this fix introduces a new path that does a "preliminary" navigation/search to avoid to trigger this SO.
> Said differently: is it possible to trigger the same SO invoking the existing findLeftLeafOfNameExpr function with a wrong param? If so I think we should fix this too.

`findLeftLeafOfNameExpr` alone doesn't trigger the SO. But as suggested, I added checks to prevent from StackOverflow in `toTypedExpressionRec`. Also expanded the test coverage to HalfPointFreeExpr cases.

Thanks!

2021-08-18 07:32 UTC, danielezonca approved these changes
Thanks for the PR 👍

2021-08-18 07:33 UTC, merged