[DROOLS-5826] fix PropertySpecificTest with executable model
apache/incubator-kie pull request #3844
Opened 2021-09-21 10:49 UTC by mariofusco

**JIRA**: https://issues.redhat.com/browse/DROOLS-5826

2021-09-21 12:36 UTC, lucamolteni requested changes

2021-09-21 12:36 UTC, lucamolteni commented on drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/visitor/pattern/PatternDSL.java
> +            prop = "!" + actualProp;
substring returns a new string, `prop` hasn't be changed so no need to reappend this

2021-09-21 12:36 UTC, lucamolteni commented on drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/visitor/pattern/PatternDSL.java
> +            if (raiseErrorForNonSettableOrDuplicatedProp && (settableWatchedProps.contains(actualProp) || settableWatchedProps.contains("!" + actualProp))) {
isn't `! + actualProp` `prop`?

2021-09-21 12:36 UTC, lucamolteni commented on drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/visitor/pattern/PatternDSL.java
> +        String actualProp = prop;
find better name for prop

2021-09-21 15:37 UTC, mariofusco commented on drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/visitor/pattern/PatternDSL.java
> +            prop = "!" + actualProp;
unfortunately it is necessary because of the trim(), to eventually turn `! prop` into `!prop`

2021-09-21 15:43 UTC, mariofusco commented on drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/visitor/pattern/PatternDSL.java
> +            if (raiseErrorForNonSettableOrDuplicatedProp && (settableWatchedProps.contains(actualProp) || settableWatchedProps.contains("!" + actualProp))) {
no, it is only if `prop` was negated. If it wasn't `prop` and `actualProp` are the same but I want to check if the set didn't already contain `!prop` while inserting `prop`.

2021-09-22 06:53 UTC, lucamolteni commented on drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/visitor/pattern/PatternDSL.java
> +            prop = "!" + actualProp;
Please rename it to `trimmedProperty` then

2021-09-22 13:43 UTC, mariofusco commented
@lucamolteni I refactored the variables names, please review again, thanks.

2021-09-22 14:32 UTC, lucamolteni approved these changes

2021-09-23 08:36 UTC, pibizza approved these changes
Minor comment on a TODO. Good for me otherwise.

2021-09-23 09:50 UTC, merged