[DROOLS-6869] implement Drools Quarkus extension
apache/incubator-kie pull request #4268
Opened 2022-03-18 15:20 UTC by mariofusco

**JIRA**: https://issues.redhat.com/browse/DROOLS-6869

2022-03-18 15:34 UTC, evacchi requested changes
minor comments

2022-03-18 15:34 UTC, evacchi commented on build-parent/pom.xml
> +        <version.io.quarkus>2.7.3.Final</version.io.quarkus>
we'll have to add drools to the tools pipelines @radtriste

2022-03-18 15:34 UTC, evacchi commented on drools-model/drools-model-project-codegen/src/main/java/org/drools/model/project/codegen/RuleCodegen.java
> +    public static RuleCodegen ofCollectedResources(DroolsModelBuildContext context, Collection<CollectedResource> resources) {
is it really necessary to bring this method (with all of its dependencies here) ? I tried to avoid it using `ofResources` directly instead :/

2022-03-18 15:34 UTC, evacchi commented on drools-quarkus-extension/drools-quarkus-deployment/src/main/java/org/drools/quarkus/deployment/DroolsAssetsProcessor.java
> +//            generatedFiles.add(new GeneratedFile(GeneratedFileType.SOURCE, HOT_RELOAD_SUPPORT_PATH + ".java", getHotReloadSupportSource()));
is this intended?

2022-03-18 15:34 UTC, evacchi commented on drools-quarkus-extension/drools-quarkus-deployment/src/main/java/org/drools/quarkus/deployment/DroolsQuarkusResourceUtils.java
> +        if (!context.hasClassAvailable(QuarkusKogitoBuildContext.QUARKUS_REST)) {
we should probably clean out the commented out code?

2022-03-18 15:34 UTC, evacchi commented on drools-quarkus-extension/drools-quarkus-deployment/src/main/java/org/drools/quarkus/deployment/InMemoryCompiler.java
> +public class InMemoryCompiler {
MEMO: IIRC there already is an In-Memory compiler here in Drools. We should probably reconsider using it now.

2022-03-18 15:34 UTC, evacchi commented on drools-model/drools-model-project-codegen/src/main/java/org/drools/model/project/codegen/io/CollectedResourceProducer.java
> +public class CollectedResourceProducer {
re: duplicate code. I tried to avoid having to duplicate this class here (just too keep the amount of duplication small). Is it really required?

2022-03-18 15:34 UTC, evacchi commented on drools-quarkus-extension/drools-quarkus/pom.xml
> +            <artifactId>drools-xml-support</artifactId>
let's add a JIRA to review the need for these dependencies in the runtime module.

The reason why we are adding them is that we need some build-time classes in the classloader that we use to process the user-mode classes, but in fact we should probably be using 2 distinct classloaders. Let's investigate this.

2022-03-18 15:55 UTC, kie-ci1 commented
**(tests) - drools job** `#379` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


**Test results:**
- PASSED: 20681
- FAILED: 0

Those are the test failures: none

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.drools/379/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-03-18T15:53:55.120Z] [INFO] |  |  |  \- org.jsoup:jsoup:jar:1.7.2:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |  |  \- org.apache.httpcomponents:httpclient:jar:4.5.13:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |  +- commons-io:commons-io:jar:2.11.0:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |  +- org.slf4j:jcl-over-slf4j:jar:1.7.30:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |  \- org.sonatype.plexus:plexus-cipher:jar:1.7:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] +- org.kie:kie-ci:jar:sources:8.19.0-SNAPSHOT:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] +- org.drools:drools-examples:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |  +- org.drools:drools-traits:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |  +- com.thoughtworks.xstream:xstream:jar:1.4.19:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |  |  \- io.github.x-stream:mxparser:jar:1.2.2:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |  |     \- xmlpull:xmlpull:jar:1.2.0:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |  +- com.miglayout:miglayout:jar:3.7.4:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |  +- com.google.code.gson:gson:jar:2.8.6:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |  \- com.google.guava:guava:jar:30.1.1-jre:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |     +- com.google.guava:failureaccess:jar:1.0.1:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |     +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |     +- com.google.code.findbugs:jsr305:jar:3.0.2:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |     +- org.checkerframework:checker-qual:jar:3.8.0:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |     +- com.google.errorprone:error_prone_annotations:jar:2.5.1:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] |     \- com.google.j2objc:j2objc-annotations:jar:1.3:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] +- org.drools:drools-examples:jar:sources:8.19.0-SNAPSHOT:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] +- org.kie:kie-api:jar:javadoc:8.19.0-SNAPSHOT:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] \- org.kie:kie-internal:jar:javadoc:8.19.0-SNAPSHOT:compile<br/>[2022-03-18T15:53:55.120Z] [INFO] ------------------------------------------------------------------------<br/>[2022-03-18T15:53:55.120Z] [INFO] Reactor Summary for Drools :: Parent 8.19.0-SNAPSHOT:<br/>[2022-03-18T15:53:55.120Z] [INFO] <br/>[2022-03-18T15:53:55.120Z] [INFO] Drools :: Parent ................................... SUCCESS [  6.327 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] KIE core BOM ....................................... SUCCESS [  0.014 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] Drools BOM (Bill Of Materials) ..................... SUCCESS [  0.009 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] Kie DMN BOM (Bill Of Materials) .................... SUCCESS [  0.009 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] Kie PMML BOM (Bill Of Materials) ................... SUCCESS [  0.009 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] Drools :: Bom Parent ............................... SUCCESS [  0.009 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] Drools :: Build Parent ............................. SUCCESS [  5.279 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] KIE :: Public API .................................. SUCCESS [  8.881 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] KIE :: Internal .................................... SUCCESS [  8.552 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] KIE :: Maven Archetypes ............................ SUCCESS [  0.048 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] KIE :: Drools Maven Archetype ...................... SUCCESS [  2.195 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] KIE :: Model Archetype ............................. SUCCESS [  1.662 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] KIE :: KJAR Archetype .............................. SUCCESS [  0.094 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] KIE :: Service Spring Boot Archetype ............... SUCCESS [  0.112 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] KIE :: Util ........................................ SUCCESS [  0.048 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] KIE :: Util :: Maven Support ....................... SUCCESS [  1.844 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] KIE :: Util :: Maven Integration ................... SUCCESS [  5.045 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] KIE :: Util :: XML supposrt ........................ SUCCESS [  1.830 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] KIE :: Memory Compiler ............................. SUCCESS [  4.094 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] Drools :: Rule Units :: Parent ..................... SUCCESS [  0.059 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] Drools :: Rule Units :: API ........................ SUCCESS [  1.920 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] Drools :: Wiring :: Parent ......................... SUCCESS [  0.050 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] Drools :: Wiring :: API ............................ SUCCESS [  2.072 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] Drools :: Wiring :: Static ......................... SUCCESS [  2.754 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] Drools :: Core ..................................... SUCCESS [ 18.752 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] Drools :: DRL AST .................................. SUCCESS [  3.414 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] Drools :: DRL :: Parser ............................ SUCCESS [  6.222 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] Drools :: DRL :: Extensions ........................ SUCCESS [  1.859 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] Drools :: Wiring :: Dynamic ........................ SUCCESS [  2.787 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] Drools :: KieSession ............................... SUCCESS [  8.638 s]<br/>[2022-03-18T15:53:55.120Z] [INFO] Drools :: ECJ ...................................... SUCCESS [  5.532 s]<br/>[2022-03-18T15:53:55.121Z] [INFO] KIE :: Test Utility Classes ........................ SUCCESS [  3.512 s]<br/>[2022-03-18T15:53:55.121Z] [INFO] Drools :: Compiler ................................. SUCCESS [  9.660 s]<br/>[2022-03-18T15:53:55.121Z] [INFO] Drools :: Model :: Parent .......................... SUCCESS [  0.039 s]<br/>[2022-03-18T15:53:55.121Z] [INFO] Drools :: Canonical Model .......................... SUCCESS [  6.648 s]<br/>[2022-03-18T15:53:55.121Z] [INFO] Drools :: XML Support .............................. SUCCESS [  4.997 s]<br/>[2022-03-18T15:53:55.121Z] [INFO] Drools :: MVEL Parser .............................. SUCCESS [  7.048 s]<br/>[2022-03-18T15:53:55.121Z] [INFO] Drools :: MVEL Compiler ............................ SUCCESS [  9.055 s]<br/>[2022-03-18T15:53:55.121Z] [INFO] Drools :: Truth Maintenance System ................. SUCCESS [  3.827 s]<br/>[2022-03-18T15:53:55.121Z] [INFO] Drools :: MVEL ..................................... SUCCESS [ 10.537 s]<br/>[2022-03-18T15:53:55.121Z] [INFO] Drools :: Model :: Compiler ........................ SUCCESS [01:16 min]<br/>[2022-03-18T15:53:55.121Z] [INFO] Drools :: Rule Units :: Implementation ............. SUCCESS [  4.156 s]<br/>[2022-03-18T15:53:55.121Z] [INFO] Drools :: Legacy Test Util ......................... SUCCESS [  3.661 s]<br/>[2022-03-18T15:53:55.121Z] [INFO] Drools :: Beliefs .................................. SUCCESS [  5.108 s]<br/>[2022-03-18T15:53:55.121Z] [IN [...]

2022-03-21 08:41 UTC, mariofusco commented on drools-quarkus-extension/drools-quarkus/pom.xml
> +            <artifactId>drools-xml-support</artifactId>
See https://issues.redhat.com/browse/DROOLS-6878

2022-03-21 08:47 UTC, mariofusco commented on drools-model/drools-model-project-codegen/src/main/java/org/drools/model/project/codegen/io/CollectedResourceProducer.java
> +public class CollectedResourceProducer {
@evacchi This code (like many other introduced both by your commit and then by this one) is only temporarily duplicated. I want to remove the corresponding one in Kogito and only use this. In particular I believe that this class, and the corresponding `ofCollectedResources` method [here](https://github.com/kiegroup/drools/pull/4268#discussion_r830108930), are necessary to discover, among the project's directories, the drools resource to be processed.

2022-03-21 08:47 UTC, mariofusco commented on drools-model/drools-model-project-codegen/src/main/java/org/drools/model/project/codegen/RuleCodegen.java
> +    public static RuleCodegen ofCollectedResources(DroolsModelBuildContext context, Collection<CollectedResource> resources) {
See https://github.com/kiegroup/drools/pull/4268#discussion_r830866413

2022-03-21 15:57 UTC, kie-ci1 commented
**(tests) - drools job** `#383` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


**Test results:**
- PASSED: 20681
- FAILED: 0

Those are the test failures: none

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.drools/383/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-03-21T15:55:55.708Z] [INFO] |  |  |  \- org.jsoup:jsoup:jar:1.7.2:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |  |  \- org.apache.httpcomponents:httpclient:jar:4.5.13:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |  +- commons-io:commons-io:jar:2.11.0:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |  +- org.slf4j:jcl-over-slf4j:jar:1.7.30:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |  \- org.sonatype.plexus:plexus-cipher:jar:1.7:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] +- org.kie:kie-ci:jar:sources:8.19.0-SNAPSHOT:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] +- org.drools:drools-examples:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |  +- org.drools:drools-traits:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |  +- com.thoughtworks.xstream:xstream:jar:1.4.19:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |  |  \- io.github.x-stream:mxparser:jar:1.2.2:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |  |     \- xmlpull:xmlpull:jar:1.2.0:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |  +- com.miglayout:miglayout:jar:3.7.4:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |  +- com.google.code.gson:gson:jar:2.8.6:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |  \- com.google.guava:guava:jar:30.1.1-jre:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |     +- com.google.guava:failureaccess:jar:1.0.1:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |     +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |     +- com.google.code.findbugs:jsr305:jar:3.0.2:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |     +- org.checkerframework:checker-qual:jar:3.8.0:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |     +- com.google.errorprone:error_prone_annotations:jar:2.5.1:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] |     \- com.google.j2objc:j2objc-annotations:jar:1.3:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] +- org.drools:drools-examples:jar:sources:8.19.0-SNAPSHOT:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] +- org.kie:kie-api:jar:javadoc:8.19.0-SNAPSHOT:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] \- org.kie:kie-internal:jar:javadoc:8.19.0-SNAPSHOT:compile<br/>[2022-03-21T15:55:55.708Z] [INFO] ------------------------------------------------------------------------<br/>[2022-03-21T15:55:55.708Z] [INFO] Reactor Summary for Drools :: Parent 8.19.0-SNAPSHOT:<br/>[2022-03-21T15:55:55.708Z] [INFO] <br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: Parent ................................... SUCCESS [  6.879 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] KIE core BOM ....................................... SUCCESS [  0.017 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools BOM (Bill Of Materials) ..................... SUCCESS [  0.014 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Kie DMN BOM (Bill Of Materials) .................... SUCCESS [  0.010 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Kie PMML BOM (Bill Of Materials) ................... SUCCESS [  0.008 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: Bom Parent ............................... SUCCESS [  0.009 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: Build Parent ............................. SUCCESS [  5.719 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] KIE :: Public API .................................. SUCCESS [  8.669 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] KIE :: Internal .................................... SUCCESS [  7.291 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] KIE :: Maven Archetypes ............................ SUCCESS [  0.053 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] KIE :: Drools Maven Archetype ...................... SUCCESS [  2.305 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] KIE :: Model Archetype ............................. SUCCESS [  1.773 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] KIE :: KJAR Archetype .............................. SUCCESS [  0.102 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] KIE :: Service Spring Boot Archetype ............... SUCCESS [  0.105 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] KIE :: Util ........................................ SUCCESS [  0.048 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] KIE :: Util :: Maven Support ....................... SUCCESS [  1.890 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] KIE :: Util :: Maven Integration ................... SUCCESS [  5.082 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] KIE :: Util :: XML supposrt ........................ SUCCESS [  1.993 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] KIE :: Memory Compiler ............................. SUCCESS [  4.379 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: Rule Units :: Parent ..................... SUCCESS [  0.068 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: Rule Units :: API ........................ SUCCESS [  2.050 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: Wiring :: Parent ......................... SUCCESS [  0.081 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: Wiring :: API ............................ SUCCESS [  2.237 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: Wiring :: Static ......................... SUCCESS [  2.943 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: Core ..................................... SUCCESS [ 19.746 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: DRL AST .................................. SUCCESS [  3.546 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: DRL :: Parser ............................ SUCCESS [  6.616 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: DRL :: Extensions ........................ SUCCESS [  1.986 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: Wiring :: Dynamic ........................ SUCCESS [  3.106 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: KieSession ............................... SUCCESS [  9.860 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: ECJ ...................................... SUCCESS [  5.640 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] KIE :: Test Utility Classes ........................ SUCCESS [  3.814 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: Compiler ................................. SUCCESS [ 10.039 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: Model :: Parent .......................... SUCCESS [  0.056 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: Canonical Model .......................... SUCCESS [  6.883 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: XML Support .............................. SUCCESS [  5.388 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: MVEL Parser .............................. SUCCESS [  7.427 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: MVEL Compiler ............................ SUCCESS [  9.768 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: Truth Maintenance System ................. SUCCESS [  4.125 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: MVEL ..................................... SUCCESS [ 10.937 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: Model :: Compiler ........................ SUCCESS [01:26 min]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: Rule Units :: Implementation ............. SUCCESS [  4.664 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: Legacy Test Util ......................... SUCCESS [  3.926 s]<br/>[2022-03-21T15:55:55.708Z] [INFO] Drools :: Beliefs .................................. SUCCESS [  5.587 s]<br/>[2022-03-21T15:55:55.708Z] [IN [...]

2022-03-21 16:18 UTC, evacchi approved these changes

2022-03-21 17:57 UTC, danielezonca commented on drools-model/drools-model-project-codegen/src/main/java/org/drools/model/project/codegen/GeneratedFile.java
> +    }
Why this method instead of a `contentsAsString()` without the path and the formatting? This method can only be used for test while a proper getter of contents as string might be reusable

2022-03-21 17:57 UTC, danielezonca commented on drools-model/drools-model-project-codegen/src/main/java/org/drools/model/project/codegen/RuleCodegen.java
> +    }
Dead code?

2022-03-21 17:57 UTC, danielezonca commented on drools-model/drools-model-project-codegen/src/main/java/org/drools/model/project/codegen/ProjectRuntimeGenerator.java
> +            clazz.addAnnotation("javax.enterprise.context.ApplicationScoped");
This works only in Quarkus, not in SpringBoot but the codepath is in common

2022-03-21 17:57 UTC, danielezonca commented on kie-api/src/main/java/org/kie/api/runtime/KieRuntimeBuilder.java
> +public interface KieRuntimeBuilder {
I would move this to a different module, we should use modularised API

2022-03-21 17:57 UTC, danielezonca commented on kie-maven-plugin/src/main/java/org/kie/maven/plugin/mojos/PackageKjarDependenciesMojo.java
> +                fos.close();
What about try-with-resource?

2022-03-21 17:57 UTC, danielezonca commented on drools-quarkus-extension/drools-quarkus/src/main/resources/META-INF/quarkus-extension.yaml
> +  guide: "https://quarkus.io/guides/kogito-drl"
We should release another guide

2022-03-21 17:57 UTC, danielezonca commented on drools-quarkus-extension/drools-quarkus/src/main/resources/META-INF/quarkus-extension.yaml
> +  - "business-automation"
I would propose a different category but no strong opinions

2022-03-21 17:57 UTC, danielezonca commented on drools-quarkus-extension/pom.xml
> +    <version.org.apache.maven>3.8.4</version.org.apache.maven>
Why is this necessary? Isn't the proposal to "scope" maven dependency in some specific module (i.e. maven support) so that we don't make "global" maven version assumption?

2022-03-21 17:57 UTC, danielezonca commented on drools-quarkus-extension/drools-quarkus/pom.xml
> +            <artifactId>quarkus-vertx-http-deployment-spi</artifactId>
Is it correct to depends on `deployment` module at runtime? It is an SPI module so it might be ok but I still find strange that this is a runtime requirement

2022-03-21 17:57 UTC, danielezonca commented on drools-quarkus-extension/drools-quarkus/pom.xml
> +        </dependency>
Same here. Runtime dependency for a codegen module?

2022-03-21 17:57 UTC, danielezonca commented on drools-quarkus-extension/drools-quarkus/pom.xml
> +    <dependencies>
I think you are missing `drools-engine` dependency, I don't expect quarkus users to add others dependencies in addition to this
https://imgflip.com/i/69h4he

2022-03-21 17:57 UTC, danielezonca commented on drools-quarkus-extension/drools-quarkus-deployment/src/main/java/org/drools/quarkus/deployment/io/GeneratedFileWriter.java
> +public class GeneratedFileWriter {
Is this used? I don't think we need (yet?) to check different types while writing. Are we already generating different types?

2022-03-21 17:57 UTC, danielezonca commented on drools-quarkus-extension/drools-quarkus-deployment/src/main/java/org/drools/quarkus/deployment/DroolsQuarkusResourceUtils.java
> +    static String getHotReloadSupportSource() {
We should revisit and provide a better fix for hot reload. Btw can you add also two additional integration test modules? One for dev mode testing using Quarkus API and one using the DevMojo (to trigger instrumentation issues)

2022-03-21 17:57 UTC, danielezonca commented on drools-quarkus-extension/drools-quarkus-deployment/src/main/java/org/drools/quarkus/deployment/DroolsGeneratedSourcesBuildItem.java
> +package org.drools.quarkus.deployment;
License

2022-03-21 17:57 UTC, danielezonca commented on drools-quarkus-extension/drools-quarkus-deployment/src/main/java/org/drools/quarkus/deployment/DroolsGeneratedSourcesBuildItem.java
> +public final class DroolsGeneratedSourcesBuildItem extends SimpleBuildItem {
I have mixed feeling to register as BuildItem generated sources. As far as I see this is only used to send the value from one method to another

2022-03-21 17:57 UTC, danielezonca commented on drools-quarkus-extension/drools-quarkus-deployment/src/main/java/org/drools/quarkus/deployment/DroolsGeneratedClassesBuildItem.java
> +    private final IndexView indexedClasses;
Is this index used?

2022-03-21 17:57 UTC, danielezonca commented on drools-quarkus-extension/drools-quarkus-deployment/src/main/java/org/drools/quarkus/deployment/DroolsAssetsProcessor.java
> +package org.drools.quarkus.deployment;
License

2022-03-21 17:57 UTC, danielezonca commented on drools-quarkus-extension/drools-quarkus-deployment/src/main/java/org/drools/quarkus/deployment/DroolsAssetsProcessor.java
> +    private DroolsGeneratedClassesBuildItem indexBuildItems(DroolsModelBuildContext context, Collection<GeneratedBeanBuildItem> buildItems) {
This can be probably removed

2022-03-21 17:57 UTC, danielezonca commented on drools-quarkus-extension/drools-quarkus-integration-test/pom.xml
> +        </dependency>
This should not be necessary

2022-03-21 17:57 UTC, danielezonca commented on drools-quarkus-extension/drools-quarkus-integration-test/pom.xml
> +        <!-- see https://github.com/apache/camel-quarkus/issues/2670 -->
This issue seems to be fixed and moreover related to camel-quarkus. Are there any other Quarkus known issue for this?

2022-03-21 17:57 UTC, danielezonca commented on drools-quarkus-extension/drools-quarkus-integration-test/pom.xml
> +        <quarkus.test.list.include>true</quarkus.test.list.include>
This is probably not used, as far as I remember this is part of how Kogito - Quarkus platform tests are packed

2022-03-21 18:40 UTC, mariofusco commented on drools-model/drools-model-project-codegen/src/main/java/org/drools/model/project/codegen/GeneratedFile.java
> +    }
I used this for debugging purposes. I believe it is useful to print a generated source together with its path.

2022-03-21 18:41 UTC, mariofusco commented on drools-model/drools-model-project-codegen/src/main/java/org/drools/model/project/codegen/RuleCodegen.java
> +    }
Yes removed, thanks.

2022-03-21 18:43 UTC, mariofusco commented on drools-model/drools-model-project-codegen/src/main/java/org/drools/model/project/codegen/ProjectRuntimeGenerator.java
> +            clazz.addAnnotation("javax.enterprise.context.ApplicationScoped");
For now I'm only supporting quarkus. It is not clear yet if in this extension we also want to support SpringBoot, but in case I'll fix it in my subsequent refactor.

2022-03-21 18:44 UTC, mariofusco commented on kie-api/src/main/java/org/kie/api/runtime/KieRuntimeBuilder.java
> +public interface KieRuntimeBuilder {
Which one? A module only for interface? Don't you think it should be part of `kie-api` together with `KieBase` and `KieSession` that it uses?

2022-03-21 18:46 UTC, mariofusco commented on kie-maven-plugin/src/main/java/org/kie/maven/plugin/mojos/PackageKjarDependenciesMojo.java
> +                fos.close();
Fixed.

2022-03-21 18:49 UTC, mariofusco commented on drools-quarkus-extension/pom.xml
> +    <version.org.apache.maven>3.8.4</version.org.apache.maven>
This is the maven version used by Quarkus with the older one (3.3.9) that we use in the rest of drools it doesn't work. Ideally I should bump the maven version used by the whole drools, but at the moment I'm not able to do this without breaking `kie-ci`.

2022-03-21 18:50 UTC, mariofusco commented on drools-quarkus-extension/drools-quarkus/pom.xml
> +            <artifactId>quarkus-vertx-http-deployment-spi</artifactId>
This is also what we did in Kogito and indeed this is wrong and I'm aware of this. Unfortunately if I remove it it breaks compilation of generated code. This needs to be investigate further and I opened a jira for it, see https://issues.redhat.com/browse/DROOLS-6878

2022-03-21 18:50 UTC, mariofusco commented on drools-quarkus-extension/drools-quarkus/pom.xml
> +        </dependency>
See above.

2022-03-21 18:52 UTC, mariofusco commented on drools-quarkus-extension/drools-quarkus-deployment/src/main/java/org/drools/quarkus/deployment/DroolsGeneratedSourcesBuildItem.java
> +package org.drools.quarkus.deployment;
Added.

2022-03-21 18:52 UTC, mariofusco commented on drools-quarkus-extension/drools-quarkus-deployment/src/main/java/org/drools/quarkus/deployment/DroolsAssetsProcessor.java
> +package org.drools.quarkus.deployment;
Added.

2022-03-21 18:53 UTC, mariofusco commented on drools-quarkus-extension/drools-quarkus-integration-test/pom.xml
> +        </dependency>
Removed.

2022-03-21 18:58 UTC, mariofusco commented on drools-quarkus-extension/drools-quarkus-integration-test/pom.xml
> +        <quarkus.test.list.include>true</quarkus.test.list.include>
Removed.

2022-03-21 19:05 UTC, kie-ci1 commented
**(tests) - kogito-runtimes job** `#386` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-runtimes/386/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-03-21T19:05:36.951Z] [INFO] Drools :: Quarkus Extension :: Runtime ............. SKIPPED<br/>[2022-03-21T19:05:36.951Z] [INFO] Drools :: Quarkus Extension :: Integration Test .... SKIPPED<br/>[2022-03-21T19:05:36.951Z] [INFO] ------------------------------------------------------------------------<br/>[2022-03-21T19:05:36.951Z] [INFO] BUILD FAILURE<br/>[2022-03-21T19:05:36.951Z] [INFO] ------------------------------------------------------------------------<br/>[2022-03-21T19:05:36.951Z] [INFO] Total time:  01:15 min<br/>[2022-03-21T19:05:36.951Z] [INFO] Finished at: 2022-03-21T15:05:36-04:00<br/>[2022-03-21T19:05:36.951Z] [INFO] ------------------------------------------------------------------------<br/>[2022-03-21T19:05:36.951Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project drools-canonical-model: Compilation failure: Compilation failure: <br/>[2022-03-21T19:05:36.951Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/view/ViewItem.java:[26,44] unchecked cast<br/>[2022-03-21T19:05:36.951Z] [ERROR]   required: org.drools.model.Variable<T><br/>[2022-03-21T19:05:36.951Z] [ERROR]   found:    org.drools.model.Variable<?><br/>[2022-03-21T19:05:36.951Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/Index.java:[81,76] unchecked call to compareTo(T) as a member of the raw type java.lang.Comparable<br/>[2022-03-21T19:05:36.951Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/Index.java:[83,76] unchecked call to compareTo(T) as a member of the raw type java.lang.Comparable<br/>[2022-03-21T19:05:36.951Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/Index.java:[85,76] unchecked call to compareTo(T) as a member of the raw type java.lang.Comparable<br/>[2022-03-21T19:05:36.951Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/Index.java:[87,76] unchecked call to compareTo(T) as a member of the raw type java.lang.Comparable<br/>[2022-03-21T19:05:36.951Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/functions/Block2.java:[40,26] unchecked call to execute(T1,T2) as a member of the raw type org.drools.model.functions.Block2<br/>[2022-03-21T19:05:36.951Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/QueryDef.java:[52,40] unchecked cast<br/>[2022-03-21T19:05:36.951Z] [ERROR]   required: org.drools.model.Variable<T><br/>[2022-03-21T19:05:36.951Z] [ERROR]   found:    org.drools.model.Variable<capture#1 of ?><br/>[2022-03-21T19:05:36.951Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/view/ExistentialExprViewItem.java:[28,14] unchecked method invocation: constructor <init> in class org.drools.model.view.AbstractExprViewItem is applied to given types<br/>[2022-03-21T19:05:36.951Z] [ERROR]   required: org.drools.model.Variable<T><br/>[2022-03-21T19:05:36.951Z] [ERROR]   found: org.drools.model.Variable<br/>[2022-03-21T19:05:36.951Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/view/ExistentialExprViewItem.java:[28,42] unchecked conversion<br/>[2022-03-21T19:05:36.951Z] [ERROR]   required: org.drools.model.Variable<T><br/>[2022-03-21T19:05:36.951Z] [ERROR]   found:    org.drools.model.Variable<br/>[2022-03-21T19:05:36.951Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/functions/Block23.java:[40,26] unchecked call to execute(T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22,T23) as a member of the raw type org.drools.model.functions.Block23<br/>[2022-03-21T19:05:36.951Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/view/CombinedExprViewItem.java:[31,14] unchecked method invocation: constructor <init> in class org.drools.model.view.AbstractExprViewItem is applied to given types<br/>[2022-03-21T19:05:36.951Z] [ERROR]   required: org.drools.model.Variable<T><br/>[2022-03-21T19:05:36.951Z] [ERROR]   found: org.drools.model.Variable<br/>[2022-03-21T19:05:36.952Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/view/CombinedExprViewItem.java:[31,34] unchecked conversion<br/>[2022-03-21T19:05:36.952Z] [ERROR]   required: org.drools.model.Variable<T><br/>[2022-03-21T19:05:36.952Z] [ERROR]   found:    org.drools.model.Variable<br/>[2022-03-21T19:05:36.952Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/view/CombinedExprViewItem.java:[50,58] unchecked conversion<br/>[2022-03-21T19:05:36.952Z] [ERROR]   required: org.drools.model.Variable<T><br/>[2022-03-21T19:05:36.952Z] [ERROR]   found:    org.drools.model.Variable<br/>[2022-03-21T19:05:36.952Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/view/BindViewItem1.java:[85,37] unchecked call to apply(T) as a member of the raw type org.drools.model.functions.Function1<br/>[2022-03-21T19:05:36.952Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/view/BindViewItem1.java:[89,37] unchecked call to apply(T) as a member of the raw type org.drools.model.functions.Function1<br/>[2022-03-21T19:05:36.952Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/functions/temporal/AbstractTemporalPredicate.java:[48,48] unchecked cast<br/>[2022-03-21T19:05:36.952Z] [ERROR]   required: T<br/>[2022-03-21T19:05:36.952Z] [ERROR]   found:    org.drools.model.functions.temporal.AbstractTemporalPredicate<br/>[2022-03-21T19:05:36.952Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/constraints/AbstractSingleConstraint.java:[93,20] unchecked c [...]

2022-03-21 19:58 UTC, kie-ci1 commented
**(tests) - kogito-examples job** `#385` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 450
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-examples/385/testReport/org.kie.kogito.examples.hr/DepartmentTest/Build_projects___testDepartmentUK/">Build projects / org.kie.kogito.examples.hr.DepartmentTest.testDepartmentUK</a></summary>
java.lang.RuntimeException: <br/>java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/>	[error]: Build step org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor#generateSources threw an exception: org.kie.kogito.codegen.rules.RuleCodegenError: Errors were generated during the code-generation process:<br/>java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.<br/><br/>	at org.kie.kogito.codegen.rules.DroolsModelBuilder.build(DroolsModelBuilder.java:76)<br/>	at org.kie.kogito.codegen.rules.RuleCodegen.internalGenerate(RuleCodegen.java:109)<br/>	at org.kie.kogito.codegen.core.AbstractGenerator.generate(AbstractGenerator.java:69)<br/>	at org.kie.kogito.codegen.core.ApplicationGenerator.lambda$generateComponents$0(ApplicationGenerator.java:97)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)<br/>	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)<br/>	at org.kie.kogito.codegen.core.ApplicationGenerator.generateComponents(ApplicationGenerator.java:99)<br/>	at org.kie.kogito.codegen.core.ApplicationGenerator.generate(ApplicationGenerator.java:74)<br/>	at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateFiles(KogitoAssetsProcessor.java:196)<br/>	at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateSources(KogitoAssetsProcessor.java:109)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)<br/>	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)<br/>	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/>	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/>	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/>	at java.base/java.lang.Thread.run(Thread.java:829)<br/>	at org.jboss.threads.JBossThread.run(JBossThread.java:501)<br/>Caused by: java.lang.IllegalStateException: java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.<br/>	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)<br/>	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)<br/>	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)<br/>	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)<br/>	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)<br/>	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)<br/>	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)<br/>	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:496)<br/>	at java.base/java.util.stream.IntPipeline.max(IntPipeline.java:459)<br/>	at org.drools.modelcompiler.builder.PackageModel.generateRulesInUnit(PackageModel.java:703)<br/>	at org.drools.modelcompiler.builder.PackageModel.lambda$getRulesSource$6(PackageModel.java:591)<br/>	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4698)<br/>	at org.drools.modelcompiler.builder.PackageModel.getRulesSource(PackageModel.java:582)<br/>	at org.drools.modelcompiler.builder.PackageModelWriter.<init>(PackageModelWriter.java:37)<br/>	at org.kie.kogito.codegen.rules.KogitoPackageSources.dumpSources(KogitoPackageSources.java:68)<br/>	at org.drools.modelcompiler.builder.ModelBuilderImpl.buildRules(ModelBuilderImpl.java:228)<br/>	at org.drools.modelcompiler.builder.ModelBuilderImpl.doSecondBuildStep(ModelBuilderImpl.java:119)<br/>	at org.drools.compiler.builder.impl.CompositeKnowledgeBuilderImpl.build(CompositeKnowledgeBuilderImpl.java:116)<br/>	at org.drools.compiler.builder.impl.CompositeKnowledgeBuilderImpl.build(CompositeKnowledgeBuilderImpl.java:100)<br/>	at org.kie.kogito.codegen.rules.DroolsModelBuilder.build(DroolsModelBuilder.java:70)<br/>	... 25 more<br/>Caused by: java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.<br/>	at com.github.javaparser.ast.Node.getData(Node.java:505)<br/>	at com.github.javaparser.ast.CompilationUnit.getPrinter(CompilationUnit.java:154)<br/>	at com.github.javaparser.ast.Node.lambda$getPrinter$1(Node.java:199)<br/>	at java.base/java.util.Optional.map(Optional.java:265)<br/>	at com.github.javaparser.ast.Node.getPrinter(Node.java:199)<br/>	at com.github.javaparser.ast.Node.toString(Node.java:322)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)<br/>	at java.base/java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2890)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)<br/>	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)<br/>	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)<br/>	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)<br/>	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)<br/>	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)<br/>	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)<br/>	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)<br/>	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)<br/>	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)<br/><br/>	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:631)<br/>	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:704)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:73)<br/>	at org.junit.jupiter.eng [...]

2022-03-22 10:49 UTC, danielezonca commented on drools-quarkus-extension/drools-quarkus/pom.xml
> +            <artifactId>drools-quarkus-deployment</artifactId>
This is wrong, deployment dependencies must stay at compile time

2022-03-23 08:54 UTC, mariofusco commented on drools-quarkus-extension/drools-quarkus-deployment/src/main/java/org/drools/quarkus/deployment/DroolsAssetsProcessor.java
> +    private DroolsGeneratedClassesBuildItem indexBuildItems(DroolsModelBuildContext context, Collection<GeneratedBeanBuildItem> buildItems) {
Done.

2022-03-23 15:21 UTC, mbiarnes commented
Jenkins retest this

2022-03-23 15:27 UTC, mareknovotny commented
ok to test

2022-03-23 15:36 UTC, mbiarnes commented
ok to test

2022-03-23 16:20 UTC, kie-ci1 commented
**(tests) - drools job** `#390` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.drools/390/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-03-23T16:20:02.291Z] 0	/home/jenkins/.cache<br/>[2022-03-23T16:20:02.291Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaweb-employee-rostering_ws-cleanup_1648052397972/bc/kiegroup_optaweb_employee_rostering/optaweb-employee-rostering/optaweb-employee-rostering-frontend/node_modules/@kie/lock-treatment-tool/node_modules/rxjs/add/operator/publish.js.map’: No such file or directory<br/>[2022-03-23T16:20:02.291Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaweb-employee-rostering_ws-cleanup_1648052397972/bc/kiegroup_optaweb_employee_rostering/optaweb-employee-rostering/optaweb-employee-rostering-frontend/node_modules/@kie/lock-treatment-tool/node_modules/rxjs/add/operator/publishBehavior.js.map’: No such file or directory<br/>[2022-03-23T16:20:02.292Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaweb-employee-rostering_ws-cleanup_1648052397972/bc/kiegroup_optaweb_employee_rostering/optaweb-employee-rostering/optaweb-employee-rostering-frontend/node_modules/@kie/lock-treatment-tool/node_modules/rxjs/add/operator/publishLast.js.map’: No such file or directory<br/>[2022-03-23T16:20:02.292Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaweb-employee-rostering_ws-cleanup_1648052397972/bc/kiegroup_optaweb_employee_rostering/optaweb-employee-rostering/optaweb-employee-rostering-frontend/node_modules/@kie/lock-treatment-tool/node_modules/rxjs/add/operator/publishReplay.js.map’: No such file or directory<br/>[2022-03-23T16:20:02.292Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaweb-employee-rostering_ws-cleanup_1648052397972/bc/kiegroup_optaweb_employee_rostering/optaweb-employee-rostering/optaweb-employee-rostering-frontend/node_modules/@kie/lock-treatment-tool/node_modules/rxjs/add/operator/race.js.map’: No such file or directory<br/>[2022-03-23T16:20:02.292Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaweb-employee-rostering_ws-cleanup_1648052397972/bc/kiegroup_optaweb_employee_rostering/optaweb-employee-rostering/optaweb-employee-rostering-frontend/node_modules/@kie/lock-treatment-tool/node_modules/rxjs/add/operator/reduce.js.map’: No such file or directory<br/>[2022-03-23T16:20:02.547Z] 874M	/home/jenkins/workspace<br/>[2022-03-23T16:20:02.547Z] 0	/home/jenkins/.pki<br/>[2022-03-23T16:20:02.547Z] 118M	/home/jenkins/tools<br/>[2022-03-23T16:20:02.547Z] 0	/home/jenkins/caches<br/>[2022-03-23T16:20:02.547Z] 562M	/home/jenkins/.npm<br/>[2022-03-23T16:20:02.547Z] 8.0K	/home/jenkins/.java<br/>[2022-03-23T16:20:02.547Z] 3.7G	/home/jenkins<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>Stage "Install build-chain tool" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-03-23T16:20:03.370Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.drools/390/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2022-03-23 16:21 UTC, kie-ci1 commented
**(tests) - kogito-examples job** `#390` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-examples/390/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-03-23T16:21:07.602Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaplanner-quickstarts_ws-cleanup_1648052463195/bc/kiegroup_optaplanner_quickstarts/optaplanner-quickstarts/build/optaplanner-distribution/target/optaplanner-distribution-8.19.0-SNAPSHOT/optaplanner-distribution-8.19.0-SNAPSHOT/examples/sources/data/projectjobscheduling/import/j30.mm/j3059_7.mm’: No such file or directory<br/>[2022-03-23T16:21:07.602Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaplanner-quickstarts_ws-cleanup_1648052463195/bc/kiegroup_optaplanner_quickstarts/optaplanner-quickstarts/build/optaplanner-distribution/target/optaplanner-distribution-8.19.0-SNAPSHOT/optaplanner-distribution-8.19.0-SNAPSHOT/examples/sources/data/projectjobscheduling/import/j30.mm/j3060_2.mm’: No such file or directory<br/>[2022-03-23T16:21:07.602Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaplanner-quickstarts_ws-cleanup_1648052463195/bc/kiegroup_optaplanner_quickstarts/optaplanner-quickstarts/build/optaplanner-distribution/target/optaplanner-distribution-8.19.0-SNAPSHOT/optaplanner-distribution-8.19.0-SNAPSHOT/examples/sources/data/projectjobscheduling/import/j30.mm/j3060_8.mm’: No such file or directory<br/>[2022-03-23T16:21:07.602Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaplanner-quickstarts_ws-cleanup_1648052463195/bc/kiegroup_optaplanner_quickstarts/optaplanner-quickstarts/build/optaplanner-distribution/target/optaplanner-distribution-8.19.0-SNAPSHOT/optaplanner-distribution-8.19.0-SNAPSHOT/examples/sources/data/projectjobscheduling/import/j30.mm/j3061_2.mm’: No such file or directory<br/>[2022-03-23T16:21:07.602Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaplanner-quickstarts_ws-cleanup_1648052463195/bc/kiegroup_optaplanner_quickstarts/optaplanner-quickstarts/build/optaplanner-distribution/target/optaplanner-distribution-8.19.0-SNAPSHOT/optaplanner-distribution-8.19.0-SNAPSHOT/examples/sources/data/projectjobscheduling/import/j30.mm/j3061_5.mm’: No such file or directory<br/>[2022-03-23T16:21:07.602Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaplanner-quickstarts_ws-cleanup_1648052463195/bc/kiegroup_optaplanner_quickstarts/optaplanner-quickstarts/build/optaplanner-distribution/target/optaplanner-distribution-8.19.0-SNAPSHOT/optaplanner-distribution-8.19.0-SNAPSHOT/examples/sources/data/projectjobscheduling/import/j30.mm/j3061_9.mm’: No such file or directory<br/>[2022-03-23T16:21:07.602Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaplanner-quickstarts_ws-cleanup_1648052463195/bc/kiegroup_optaplanner_quickstarts/optaplanner-quickstarts/build/optaplanner-distribution/target/optaplanner-distribution-8.19.0-SNAPSHOT/optaplanner-distribution-8.19.0-SNAPSHOT/examples/sources/data/projectjobscheduling/import/j30.mm/j3062_3.mm’: No such file or directory<br/>[2022-03-23T16:21:07.602Z] 1.1G	/home/jenkins/workspace<br/>[2022-03-23T16:21:07.602Z] 0	/home/jenkins/.pki<br/>[2022-03-23T16:21:07.602Z] 118M	/home/jenkins/tools<br/>[2022-03-23T16:21:07.602Z] 0	/home/jenkins/caches<br/>[2022-03-23T16:21:07.602Z] 24M	/home/jenkins/.npm<br/>[2022-03-23T16:21:07.602Z] 8.0K	/home/jenkins/.java<br/>[2022-03-23T16:21:07.602Z] 3.4G	/home/jenkins<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>Stage "Install build-chain tool" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-03-23T16:21:08.382Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-examples/390/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2022-03-23 16:26 UTC, kie-ci1 commented
**(tests) - kogito-runtimes job** `#393` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-runtimes/393/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-03-23T16:26:16.885Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaweb-vehicle-routing_ws-cleanup_1648052771364/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/.cache/babel-loader/cd8eb0c828ed9e88a1422b4cb5345a96.json’: No such file or directory<br/>[2022-03-23T16:26:16.885Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaweb-vehicle-routing_ws-cleanup_1648052771364/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/.cache/babel-loader/d73e56248133baa6a3565464ee2c9179.json’: No such file or directory<br/>[2022-03-23T16:26:16.885Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaweb-vehicle-routing_ws-cleanup_1648052771364/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/.cache/babel-loader/5eda2ffa73e2c6c5f4f11243e3ee1c4c.json’: No such file or directory<br/>[2022-03-23T16:26:16.885Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaweb-vehicle-routing_ws-cleanup_1648052771364/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/.cache/babel-loader/a3fe8c62dc3bfab145812e1db5221c7d.json’: No such file or directory<br/>[2022-03-23T16:26:16.885Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaweb-vehicle-routing_ws-cleanup_1648052771364/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/.cache/babel-loader/768fdc35a64f853ccb840e9c3c7a0dd5.json’: No such file or directory<br/>[2022-03-23T16:26:16.885Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.optaweb-vehicle-routing_ws-cleanup_1648052771364/bc/kiegroup_optaweb_vehicle_routing/optaweb-vehicle-routing/optaweb-vehicle-routing-frontend/node_modules/.cache/babel-loader/8ebda11304123ccd7a3f22c07ae639a9.json’: No such file or directory<br/>[2022-03-23T16:26:17.139Z] 533M	/home/jenkins/workspace<br/>[2022-03-23T16:26:17.139Z] 28K	/home/jenkins/.pki<br/>[2022-03-23T16:26:17.139Z] 118M	/home/jenkins/tools<br/>[2022-03-23T16:26:17.139Z] 0	/home/jenkins/caches<br/>[2022-03-23T16:26:17.139Z] 366M	/home/jenkins/.npm<br/>[2022-03-23T16:26:17.139Z] 0	/home/jenkins/.yarn<br/>[2022-03-23T16:26:17.139Z] 24K	/home/jenkins/.java<br/>[2022-03-23T16:26:17.140Z] 5.9G	/home/jenkins<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>Stage "Install build-chain tool" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-03-23T16:26:18.010Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-runtimes/393/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2022-03-23 16:38 UTC, kie-ci1 commented
**(tests) - kogito-runtimes job** `#390` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2573
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-runtimes/390/testReport/org.jbpm.bpmn2/ProcessFactoryTest/testBoundaryTimerTimeCycle/">org.jbpm.bpmn2.ProcessFactoryTest.testBoundaryTimerTimeCycle</a></summary>
java.util.ConcurrentModificationException<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1661)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)<br/>	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)<br/>	at org.jbpm.bpmn2.JbpmBpmn2TestCase.getNotTriggeredNodes(JbpmBpmn2TestCase.java:280)<br/>	at org.jbpm.bpmn2.JbpmBpmn2TestCase.assertNodeTriggered(JbpmBpmn2TestCase.java:242)<br/>	at org.jbpm.bpmn2.ProcessFactoryTest.testBoundaryTimerTimeCycle(ProcessFactoryTest.java:193)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)<br/>	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)<br/>	at org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:46)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrches [...]

2022-03-23 17:12 UTC, danielezonca commented on drools-drl-quarkus-extension/drools-drl-quarkus-deployment/src/main/java/org/drools/drl/quarkus/deployment/DroolsCompilationProvider.java
> +    private static final Set<String> MANAGED_EXTENSIONS = Collections.unmodifiableSet(new HashSet<>(Arrays.asList(".drl", ".xls", ".xlsx", ".csv")));
Isn't the "agreement" to use something like `drl.xls`? Do we plan to do with a following ticket?

2022-03-23 17:12 UTC, danielezonca commented on drools-drl-quarkus-extension/drools-drl-quarkus-deployment/src/main/java/org/drools/drl/quarkus/deployment/DroolsAssetsProcessor.java
> +        generatedBeanBuildItems.forEach(generatedBeans::produce);
This comment should be moved to the other line
```suggestion
        Collection<ResolvedDependency> dependencies = curateOutcomeBuildItem.getApplicationModel().getRuntimeDependencies();

        // build Java source code and register the generated beans
        Collection<GeneratedBeanBuildItem> generatedBeanBuildItems =
                compileGeneratedSources(context, dependencies, generatedFiles, liveReload.isLiveReload());
        generatedBeanBuildItems.forEach(generatedBeans::produce);
```

2022-03-23 17:12 UTC, danielezonca commented on drools-drl-quarkus-extension/drools-drl-quarkus-deployment/src/main/java/org/drools/drl/quarkus/deployment/DroolsQuarkusResourceUtils.java
> +                    System.getProperty("kogito.codegen.resources.directory", "target/generated-resources/kogito/"),
`kogito.codegen.source.directory`? I think it is a leftover

2022-03-23 17:12 UTC, danielezonca commented on drools-drl-quarkus-extension/drools-drl-quarkus-deployment/src/main/java/org/drools/drl/quarkus/deployment/DroolsQuarkusResourceUtils.java
> +                    "target/generated-sources/kogito/");
Same here `/kogito` folder

2022-03-23 17:12 UTC, danielezonca commented on drools-drl-quarkus-extension/drools-drl-quarkus-integration-test-hotreload/pom.xml
> +            </exclusions>
Why this exclusion? Who else is bringing in these classes?

2022-03-23 17:12 UTC, danielezonca commented on drools-drl-quarkus-extension/pom.xml
> +    <module>drools-drl-quarkus-integration-test-hotreload</module>
What about adding also an hot reload test using the devmode approach? We saw in the past that the "simple" hot reload test is not always reliable
https://github.com/kiegroup/kogito-runtimes/tree/main/quarkus/extensions/kogito-quarkus-extension/kogito-quarkus-integration-test-maven-devmode

Feel free to postpone to a different ticket of course

2022-03-23 17:12 UTC, danielezonca commented on drools-model/drools-model-project-codegen/src/main/java/org/drools/model/project/codegen/RuleCodegen.java
> -    @Deprecated
Are you sure? Is this flag still necessary?

2022-03-23 17:12 UTC, danielezonca commented on drools-model/drools-model-project-codegen/src/main/java/org/drools/model/project/codegen/context/AppPaths.java
> +        }
This is a nice change that we might port to kogito 🤔

2022-03-23 17:14 UTC, mariofusco commented on drools-drl-quarkus-extension/drools-drl-quarkus-deployment/src/main/java/org/drools/drl/quarkus/deployment/DroolsCompilationProvider.java
> +    private static final Set<String> MANAGED_EXTENSIONS = Collections.unmodifiableSet(new HashSet<>(Arrays.asList(".drl", ".xls", ".xlsx", ".csv")));
I opened a jira for that https://issues.redhat.com/browse/DROOLS-6880

2022-03-23 17:16 UTC, mariofusco commented on drools-drl-quarkus-extension/drools-drl-quarkus-integration-test-hotreload/pom.xml
> +            </exclusions>
Nobody but we have a check that prevent us to bring in classes with many `javax.` namespace including the one brought in this dependency.

2022-03-23 17:19 UTC, kie-ci1 commented
**(tests) - kogito-examples job** `#392` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 452
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-examples/392/testReport/org.acme.it/QueryAnswerServiceIT/Build_projects___queryAnswerProcessCycle/">Build projects / org.acme.it.QueryAnswerServiceIT.queryAnswerProcessCycle</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <400>.<br/><br/>	at org.acme.it.QueryAnswerServiceIT.queryAnswerProcessCycle(QueryAnswerServiceIT.java:89)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-examples/392/display/redirect

2022-03-23 17:21 UTC, kie-ci1 commented
**(tests) - kogito-examples job** `#391` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 452
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-examples/391/testReport/org.acme.it/QueryAnswerServiceIT/Build_projects___queryAnswerProcessCycle/">Build projects / org.acme.it.QueryAnswerServiceIT.queryAnswerProcessCycle</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <400>.<br/><br/>	at org.acme.it.QueryAnswerServiceIT.queryAnswerProcessCycle(QueryAnswerServiceIT.java:89)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-examples/391/display/redirect

2022-03-23 17:21 UTC, mariofusco commented on drools-model/drools-model-project-codegen/src/main/java/org/drools/model/project/codegen/context/AppPaths.java
> +        }
I'm hoping to reuse this class also in Kogito instead of keeping it duplicated.

2022-03-23 17:27 UTC, mariofusco commented on drools-model/drools-model-project-codegen/src/main/java/org/drools/model/project/codegen/RuleCodegen.java
> -    @Deprecated
It is necessary mostly for testing purposes. In this way it forces the executable model to generate one class per rule and we have a predictable number of classes, see `RuleCodegenTest`.

2022-03-23 17:27 UTC, mariofusco commented on drools-drl-quarkus-extension/drools-drl-quarkus-deployment/src/main/java/org/drools/drl/quarkus/deployment/DroolsAssetsProcessor.java
> +        generatedBeanBuildItems.forEach(generatedBeans::produce);
Fixed.

2022-03-23 18:40 UTC, kie-ci1 commented
**(tests) - kogito-apps job** `#391` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2705
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-apps/391/testReport/org.kie.kogito.index.messaging/PostgreSqlMessagingConsumerKafkaIT/testProcessInstanceEvent/">org.kie.kogito.index.messaging.PostgreSqlMessagingConsumerKafkaIT.testProcessInstanceEvent</a></summary>
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException<br/>Caused by: java.lang.reflect.InvocationTargetException<br/>Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource org.kie.kogito.testcontainers.quarkus.KafkaQuarkusTestResource@32e4793d<br/>Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource org.kie.kogito.testcontainers.quarkus.KafkaQuarkusTestResource@32e4793d<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Started Kafka API server.*'<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-apps/391/display/redirect

2022-03-24 07:49 UTC, merged

2022-04-06 15:23 UTC, radtriste commented on build-parent/pom.xml
> +        <version.io.quarkus>2.7.3.Final</version.io.quarkus>
well we need to create the update-quarkus job

2022-04-06 15:24 UTC, radtriste commented on build-parent/pom.xml
> +        <version.io.quarkus>2.7.3.Final</version.io.quarkus>
This would be similar to https://github.com/kiegroup/kogito-runtimes/blob/main/.ci/jenkins/dsl/jobs.groovy#L88

2022-04-06 15:25 UTC, radtriste commented on build-parent/pom.xml
> +        <version.io.quarkus>2.7.3.Final</version.io.quarkus>
something like

```groovy
KogitoJobUtils.createQuarkusUpdateToolsJob(this, 'drools', 'Drools', [
  modules: [ 'drools-build-parent' ],
  compare_deps_remote_poms: [ 'io.quarkus:quarkus-bom' ], // REVIEW should be added only if we need to sync the dependencies
  properties: [ 'version.io.quarkus'],
])
```