[DO-NOT-MERGE] [DROOLS-7006] Publish Antora docs as drools job
apache/incubator-kie pull request #4459
Opened 2022-06-14 06:23 UTC by tkobayas

This is really a **draft** PR. Currently, Drools 8 docs are not yet ready so we don't publish it yet. This PR is to ask reviews to confirm the approach to publish.

Please add if there are other suitable reviewers. Feel free to share your thoughts, concerns. Thanks!

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-7006

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel</b>
</details>

2022-06-14 06:30 UTC, tkobayas commented on .ci/jenkins/upload_doc_site.sh
> +rsync -Pavqr -e 'ssh -p 2222' --protocol=28 --delete-after target/website/docs/* drools@filemgmt-prod-sync.jboss.org:www_htdocs/drools/docs
This shell mimics https://github.com/tkobayas/drools-website/blob/main/scripts/rsync_website.sh
Instead of uploading directly under `www_htdocs/drools`, uploading the generated contents under `www_htdocs/drools/docs`.

Then, I will raise a PR for `drools-website` to add a link to it. (e.g. https://gist.github.com/tkobayas/fb63cec6341d2c1f354bc1f58a17a603)

2022-06-14 06:37 UTC, tkobayas commented on drools-docs/pom.xml
> +    <antora.playbook>antora-playbook-author.yml</antora.playbook>
Now I use `antora-playbook-author.yml` for this build.

`antora-playbook.yml` uses resources on github. Using github resources means it cannot use the antora.yml which is copied during this maven build. IMHO, using github resources is meaningful when when we want to build an external resources (for example, optaplanner-website builds resources on optaplanner/optaplanner-docs). In `drools-docs` case, we build its own resources in the maven build so `antora-playbook-author.yml` would be suitable.

WDYT?

2022-06-14 07:52 UTC, rsynek commented on drools-docs/pom.xml
> +    <antora.playbook>antora-playbook-author.yml</antora.playbook>
If both the content and the assembly are part of the same build, as they reside in the same repository on the same branch, I think this is a valid approach.

2022-06-15 06:53 UTC, tarilabs commented on .ci/jenkins/upload_doc_site.sh
> +rsync -Pavqr -e 'ssh -p 2222' --protocol=28 --delete-after target/website/docs/* drools@filemgmt-prod-sync.jboss.org:www_htdocs/drools/docs
Not entirely sure about this... imho what could be helpful, is something like the build pipeline which takes the `kiegroup/kie-docs`, build it, push it to filemgmt-prod.jboss.org under the correct docs directory and version directory.
/cc @radtriste @mbiarnes @danielezonca can you suggest relevant pointers how the `kiegroup/kie-docs` is published once it's built, please? Thank you!

2022-06-15 07:11 UTC, tkobayas commented on .ci/jenkins/upload_doc_site.sh
> +rsync -Pavqr -e 'ssh -p 2222' --protocol=28 --delete-after target/website/docs/* drools@filemgmt-prod-sync.jboss.org:www_htdocs/drools/docs
Hi @tarilabs  , this PR focuses on publishing Antora document-site. Uploading html/pdf docs (e.g. https://docs.drools.org/7.71.0.Final/drools-docs/html_single/index.html) will be dealt by another JIRA https://issues.redhat.com/browse/DROOLS-7005.

Per my understanding, Antora document-site is not published by `kie-docs` at the moment. Only `optaplanner-website` does.

https://www.optaplanner.org/docs/optaplanner/latest/planner-introduction/planner-introduction.html

2022-06-15 07:48 UTC, tarilabs commented on .ci/jenkins/upload_doc_site.sh
> +rsync -Pavqr -e 'ssh -p 2222' --protocol=28 --delete-after target/website/docs/* drools@filemgmt-prod-sync.jboss.org:www_htdocs/drools/docs
> Per my understanding, Antora document-site is not published by kie-docs at the moment. Only optaplanner-website does.

yes, but optaplanner-website builds the docs as part of the website build.
We should not mix these 2 separate concerns.
I believe it would be ideal Antora doc is built with Antora pipeline (as you are already doing).

The rsync highlighted here, I believe, should be instead replaced with rsync to filemgmt-prod.jboss.org under the correct docs directory and version directory, eventually (eg: I am not entirely sure the directory naming [`<version>/<format>`] per https://docs.drools.org is currently being handled here?)
Maybe I missed that, in that case please correct me and sorry :)

2022-06-15 08:47 UTC, tkobayas commented on .ci/jenkins/upload_doc_site.sh
> +rsync -Pavqr -e 'ssh -p 2222' --protocol=28 --delete-after target/website/docs/* drools@filemgmt-prod-sync.jboss.org:www_htdocs/drools/docs
Thank you, @tarilabs . I see your point. I'll take a further look (I'll be OOO tomorrow so my feedback may delay).

2022-06-20 05:19 UTC, tkobayas commented on drools-docs/pom.xml
> +    <antora.playbook>antora-playbook-author.yml</antora.playbook>
Thanks!

2022-06-20 05:25 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#125` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-runtimes/125/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
Loading library jenkins-pipeline-shared-libraries@main<br/>Attempting to resolve main from remote references...<br/> > git --version # timeout=10<br/> > git --version # 'git version 1.8.3.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh1719214341154441158.key<br/> > git ls-remote -h https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Found match: refs/heads/main revision 3861cd4159855705f35bed8f582b449882a83f75<br/>The recommended git tool is: NONE<br/>using credential kie-ci-user-key<br/> > git rev-parse --resolve-git-dir /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/drools.tests.downstream.kogito-runtimes/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 1.8.3.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/drools.tests.downstream.kogito-runtimes/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb@tmp/jenkins-gitclient-ssh7482810167788639715.key<br/> > git fetch --no-tags --progress https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision 3861cd4159855705f35bed8f582b449882a83f75 (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 3861cd4159855705f35bed8f582b449882a83f75 # timeout=10<br/>Commit message: "Markdown notification - Set URL link before logs (#195)"<br/> > git rev-list --no-walk 3861cd4159855705f35bed8f582b449882a83f75 # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Running on rhos-01-kie-psi-rhel7-xlarge-945 in /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci<br/>Cloning the remote Git repository<br/>Avoid second fetch<br/>Checking out Revision a5fb7dda7560a0c125b83f1a5436300330213c29 (origin/main)<br/>Commit message: "[main] Bump quarkus version to 2.10.0.Final (#503)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2022-06-20T05:24:57.787Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.34.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f a5fb7dda7560a0c125b83f1a5436300330213c29 # timeout=10<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-06-20T05:24:58.509Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2022-06-20T05:24:58.532Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2022-06-20T05:24:59.046Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-runtimes<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-06-20T05:24:59.076Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2022-06-20T05:24:59.355Z] + df -h<br/>[2022-06-20T05:24:59.356Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2022-06-20T05:24:59.356Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2022-06-20T05:24:59.356Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2022-06-20T05:24:59.356Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2022-06-20T05:24:59.356Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2022-06-20T05:24:59.356Z] /dev/vda1        80G   19G   62G  24% /<br/>[2022-06-20T05:24:59.356Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[2022-06-20T05:24:59.356Z] tmpfs           1.6G     0  1.6G   0% /run/user/0<br/>[Pipeline] echo<br/>[2022-06-20T05:24:59.390Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2022-06-20T05:24:59.669Z] + du -h -d1 /home/jenkins<br/>[2022-06-20T05:24:59.670Z] 4.0K	/home/jenkins/.ssh<br/>[2022-06-20T05:24:59.670Z] 0	/home/jenkins/go<br/>[2022-06-20T05:24:59.670Z] 8.0K	/home/jenkins/.vnc<br/>[2022-06-20T05:24:59.670Z] 12K	/home/jenkins/.m2<br/>[2022-06-20T05:24:59.670Z] 2.1G	/home/jenkins/git-repos<br/>[2022-06-20T05:24:59.670Z] 8.0K	/home/jenkins/.config<br/>[2022-06-20T05:24:59.670Z] 4.0K	/home/jenkins/.cekit<br/>[2022-06-20T05:24:59.670Z] 80M	/home/jenkins/virtenvs<br/>[2022-06-20T05:24:59.670Z] 36M	/home/jenkins/remoting<br/>[2022-06-20T05:24:59.670Z] 595M	/home/jenkins/.cache<br/>[2022-06-20T05:24:59.670Z] 2.4M	/home/jenkins/workspace<br/>[2022-06-20T05:24:59.670Z] 0	/home/jenkins/.pki<br/>[2022-06-20T05:24:59.670Z] 118M	/home/jenkins/tools<br/>[2022-06-20T05:24:59.670Z] 0	/home/jenkins/caches<br/>[2022-06-20T05:24:59.670Z] 90M	/home/jenkins/.npm<br/>[2022-06-20T05:24:59.670Z] 0	/home/jenkins/.yarn<br/>[2022-06-20T05:24:59.670Z] 3.0G	/home/jenkins<br/>[Pipeline] echo<br/>[2022-06-20T05:24:59.688Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2022-06-20T05:24:59.978Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-06-20T05:24:59.979Z] 0	/home/jenkins/workspace/KIE/main/compile<br/>[2022-06-20T05:24:59.979Z] 0	/home/jenkins/workspace/KIE/main<br/>[2022-06-20T05:24:59.979Z] 2.4M	/home/jenkins/workspace/KIE/kogito/main<br/>[2022-06-20T05:24:59.979Z] 2.4M	/home/jenkins/workspace/KIE/kogito<br/>[2022-06-20T05:24:59.979Z] 2.4M	/home/jenkins/workspace/KIE<br/>[2022-06-20T05:24:59.979Z] 2.4M	/home/jenkins/workspace<br/>[Pipeli [...]

2022-06-20 05:25 UTC, kie-ci3 commented
**(tests) - drools job** `#155` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.drools/155/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
 > git --version # 'git version 1.8.3.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --progress https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/>Checking out Revision a5fb7dda7560a0c125b83f1a5436300330213c29 (origin/main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f a5fb7dda7560a0c125b83f1a5436300330213c29 # timeout=10<br/>Commit message: "[main] Bump quarkus version to 2.10.0.Final (#503)"<br/> > git rev-list --no-walk e66cc1828395be707761ed0bef1740af46927e3a # timeout=10<br/>Loading library jenkins-pipeline-shared-libraries@main<br/>Attempting to resolve main from remote references...<br/> > git --version # timeout=10<br/> > git --version # 'git version 1.8.3.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh6883376869044980679.key<br/> > git ls-remote -h https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Found match: refs/heads/main revision 3861cd4159855705f35bed8f582b449882a83f75<br/>The recommended git tool is: NONE<br/>using credential kie-ci-user-key<br/> > git rev-parse --resolve-git-dir /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/drools.tests.drools/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 1.8.3.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/drools.tests.drools/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb@tmp/jenkins-gitclient-ssh8026210466195840161.key<br/> > git fetch --no-tags --progress https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision 3861cd4159855705f35bed8f582b449882a83f75 (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 3861cd4159855705f35bed8f582b449882a83f75 # timeout=10<br/>Commit message: "Markdown notification - Set URL link before logs (#195)"<br/> > git rev-list --no-walk 3861cd4159855705f35bed8f582b449882a83f75 # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Running on rhos-01-kie-psi-rhel7-xlarge-942 in /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.drools<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci<br/>Cloning the remote Git repository<br/>Avoid second fetch<br/>Checking out Revision a5fb7dda7560a0c125b83f1a5436300330213c29 (origin/main)<br/>Commit message: "[main] Bump quarkus version to 2.10.0.Final (#503)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2022-06-20T05:24:57.730Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[2022-06-20T05:24:57.831Z] Installing NodeJS from /var/lib/jenkins/caches/nodejs/LINUX/amd64/12.16.3.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3 on rhos-01-kie-psi-rhel7-xlarge-942<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.drools # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.34.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f a5fb7dda7560a0c125b83f1a5436300330213c29 # timeout=10<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-06-20T05:24:59.940Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2022-06-20T05:24:59.964Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2022-06-20T05:25:00.469Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.drools<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-06-20T05:25:00.499Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2022-06-20T05:25:00.792Z] + df -h<br/>[2022-06-20T05:25:00.792Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2022-06-20T05:25:00.792Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2022-06-20T05:25:00.792Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2022-06-20T05:25:00.792Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2022-06-20T05:25:00.792Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2022-06-20T05:25:00.792Z] /dev/vda1        80G   19G   62G  24% /<br/>[2022-06-20T05:25:00.792Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[2022-06-20T05:25:00.792Z] tmpfs           1.6G     0  1.6G   0% /run/user/0<br/>[Pipeline] echo<br/>[2022-06-20T05:25:00.811Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2022-06-20T05:25:01.088Z] + du -h -d1 /home/jenkins<br/>[2022-06-20T05:25:01.088Z] 4.0K	/home/jenkins/.ssh<br/>[2022-06-20T05:25:01.088Z] 0	/home/jenkins/go<br/>[2022-06-20T05:25:01.088Z] 8.0K	/home/jenkins/.vnc<br/>[2022-06-20T05:25:01.088Z] 19M	/home/jenkins/.m2<br/>[2022-06-20T05:25:01.088Z] 2.1G	/home/jenkins/git-repos<br/>[2022-06-20T05:25:01.088Z] 8.0K	/home/jenkins/.config<br/>[2022-06-20T05:25:01.088Z] 4.0K	/home/jenkins/.cekit<br/>[2022-06-20T05:25:01.088Z] 80M	/home/jenkins/virtenvs<br/>[2022-06-20T05:25:01.088Z] 31M	/home/jenkins/remoting<br/>[2022-06-20T05:25:01.088Z] 0	/home/jenkins/.cache<br/>[2022-06-20T05:25:01.088Z] 2.4M	/home/jenkins/workspace<br/>[2022-06-20T05:25:01.088Z] 0	/home/jenkins/.pki<br/>[2022-06-20T05:25:01. [...]

2022-06-20 05:25 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#123` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-examples/123/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
 > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 1.8.3.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/drools.tests.downstream.kogito-examples/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb@tmp/jenkins-gitclient-ssh7385401163419933794.key<br/> > git fetch --no-tags --progress https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision 3861cd4159855705f35bed8f582b449882a83f75 (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 3861cd4159855705f35bed8f582b449882a83f75 # timeout=10<br/>Commit message: "Markdown notification - Set URL link before logs (#195)"<br/> > git rev-list --no-walk 3861cd4159855705f35bed8f582b449882a83f75 # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Running on rhos-01-kie-psi-rhel7-xlarge-941 in /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-examples<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci<br/>Cloning the remote Git repository<br/>Avoid second fetch<br/>Checking out Revision a5fb7dda7560a0c125b83f1a5436300330213c29 (origin/main)<br/>Commit message: "[main] Bump quarkus version to 2.10.0.Final (#503)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2022-06-20T05:24:57.731Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[2022-06-20T05:24:57.830Z] Installing NodeJS from /var/lib/jenkins/caches/nodejs/LINUX/amd64/12.16.3.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3 on rhos-01-kie-psi-rhel7-xlarge-941<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-examples # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.34.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f a5fb7dda7560a0c125b83f1a5436300330213c29 # timeout=10<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-06-20T05:24:59.957Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2022-06-20T05:24:59.980Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2022-06-20T05:25:00.478Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-examples<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-06-20T05:25:00.507Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2022-06-20T05:25:00.800Z] + df -h<br/>[2022-06-20T05:25:00.800Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2022-06-20T05:25:00.800Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2022-06-20T05:25:00.800Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2022-06-20T05:25:00.800Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2022-06-20T05:25:00.800Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2022-06-20T05:25:00.800Z] /dev/vda1        80G   19G   62G  24% /<br/>[2022-06-20T05:25:00.801Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[2022-06-20T05:25:00.801Z] tmpfs           1.6G     0  1.6G   0% /run/user/0<br/>[Pipeline] echo<br/>[2022-06-20T05:25:00.820Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2022-06-20T05:25:01.099Z] + du -h -d1 /home/jenkins<br/>[2022-06-20T05:25:01.099Z] 4.0K	/home/jenkins/.ssh<br/>[2022-06-20T05:25:01.099Z] 0	/home/jenkins/go<br/>[2022-06-20T05:25:01.099Z] 8.0K	/home/jenkins/.vnc<br/>[2022-06-20T05:25:01.099Z] 19M	/home/jenkins/.m2<br/>[2022-06-20T05:25:01.099Z] 2.1G	/home/jenkins/git-repos<br/>[2022-06-20T05:25:01.099Z] 8.0K	/home/jenkins/.config<br/>[2022-06-20T05:25:01.099Z] 4.0K	/home/jenkins/.cekit<br/>[2022-06-20T05:25:01.099Z] 80M	/home/jenkins/virtenvs<br/>[2022-06-20T05:25:01.099Z] 31M	/home/jenkins/remoting<br/>[2022-06-20T05:25:01.099Z] 0	/home/jenkins/.cache<br/>[2022-06-20T05:25:01.099Z] 2.4M	/home/jenkins/workspace<br/>[2022-06-20T05:25:01.099Z] 0	/home/jenkins/.pki<br/>[2022-06-20T05:25:01.099Z] 0	/home/jenkins/caches<br/>[2022-06-20T05:25:01.099Z] 630M	/home/jenkins/.gradle<br/>[2022-06-20T05:25:01.099Z] 8.0K	/home/jenkins/.java<br/>[2022-06-20T05:25:01.099Z] 81M	/home/jenkins/tools<br/>[2022-06-20T05:25:01.099Z] 2.9G	/home/jenkins<br/>[Pipeline] echo<br/>[2022-06-20T05:25:01.118Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2022-06-20T05:25:01.393Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-06-20T05:25:01.394Z] 2.4M	/home/jenkins/workspace/KIE/kogito/main<br/>[2022-06-20T05:25:01.394Z] 2.4M	/home/jenkins/workspace/KIE/kogito<br/>[2022-06-20T05:25:01.394Z] 2.4M	/home/jenkins/workspace/KIE<br/>[2022-06-20T05:25:01.394Z] 2.4M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-06-20T05:25:01.719Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-06-20T05:25:01.810Z] [INFO] build-chain version recovered '2.3.34'<br/>[Pipeline] sh<br/>[2022-06-20T05:25:02.089Z] + npm install -g @kie/build-chain-action@2.3.34 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-06-20T05:25:10.209Z] /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3/bin/build-chain-action -> /home/jenkins/ [...]

2022-06-20 05:25 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#125` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/drools.tests.downstream.kogito-apps/125/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
using credential kie-ci-user-key<br/> > git rev-parse --resolve-git-dir /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/drools.tests.downstream.kogito-apps/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 1.8.3.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/drools.tests.downstream.kogito-apps/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb@tmp/jenkins-gitclient-ssh402538432605853593.key<br/> > git fetch --no-tags --progress https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision 3861cd4159855705f35bed8f582b449882a83f75 (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 3861cd4159855705f35bed8f582b449882a83f75 # timeout=10<br/>Commit message: "Markdown notification - Set URL link before logs (#195)"<br/> > git rev-list --no-walk 3861cd4159855705f35bed8f582b449882a83f75 # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Running on rhos-01-kie-psi-rhel7-xlarge-911 in /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-apps<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci<br/>Cloning the remote Git repository<br/>Avoid second fetch<br/>Checking out Revision a5fb7dda7560a0c125b83f1a5436300330213c29 (origin/main)<br/>Commit message: "[main] Bump quarkus version to 2.10.0.Final (#503)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2022-06-20T05:25:12.584Z] Timeout set to expire in 3 hr 30 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[2022-06-20T05:25:12.664Z] Installing NodeJS from /var/lib/jenkins/caches/nodejs/LINUX/amd64/12.16.3.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3 on rhos-01-kie-psi-rhel7-xlarge-911<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-apps # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.34.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f a5fb7dda7560a0c125b83f1a5436300330213c29 # timeout=10<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-06-20T05:25:14.775Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2022-06-20T05:25:14.814Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2022-06-20T05:25:15.315Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.downstream.kogito-apps<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-06-20T05:25:15.347Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2022-06-20T05:25:15.624Z] + df -h<br/>[2022-06-20T05:25:15.624Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2022-06-20T05:25:15.624Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2022-06-20T05:25:15.624Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2022-06-20T05:25:15.624Z] tmpfs           7.8G   25M  7.8G   1% /run<br/>[2022-06-20T05:25:15.624Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2022-06-20T05:25:15.624Z] /dev/vda1        80G   24G   57G  30% /<br/>[2022-06-20T05:25:15.624Z] tmpfs           1.6G  4.0K  1.6G   1% /run/user/1000<br/>[Pipeline] echo<br/>[2022-06-20T05:25:15.659Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2022-06-20T05:25:15.941Z] + du -h -d1 /home/jenkins<br/>[2022-06-20T05:25:15.942Z] 4.0K	/home/jenkins/.ssh<br/>[2022-06-20T05:25:15.942Z] 0	/home/jenkins/go<br/>[2022-06-20T05:25:15.942Z] 8.0K	/home/jenkins/.vnc<br/>[2022-06-20T05:25:15.942Z] 19M	/home/jenkins/.m2<br/>[2022-06-20T05:25:15.942Z] 2.1G	/home/jenkins/git-repos<br/>[2022-06-20T05:25:15.942Z] 56M	/home/jenkins/.config<br/>[2022-06-20T05:25:15.942Z] 4.0K	/home/jenkins/.cekit<br/>[2022-06-20T05:25:15.942Z] 80M	/home/jenkins/virtenvs<br/>[2022-06-20T05:25:15.942Z] 31M	/home/jenkins/remoting<br/>[2022-06-20T05:25:19.214Z] 2.1G	/home/jenkins/.cache<br/>[2022-06-20T05:25:19.214Z] 2.4M	/home/jenkins/workspace<br/>[2022-06-20T05:25:19.214Z] 28K	/home/jenkins/.pki<br/>[2022-06-20T05:25:19.214Z] 0	/home/jenkins/caches<br/>[2022-06-20T05:25:19.214Z] 0	/home/jenkins/.mozilla<br/>[2022-06-20T05:25:19.214Z] 8.0K	/home/jenkins/.java<br/>[2022-06-20T05:25:19.788Z] 595M	/home/jenkins/.npm<br/>[2022-06-20T05:25:19.788Z] 431M	/home/jenkins/.gradle<br/>[2022-06-20T05:25:19.788Z] 0	/home/jenkins/.yarn<br/>[2022-06-20T05:25:19.788Z] 81M	/home/jenkins/tools<br/>[2022-06-20T05:25:19.788Z] 5.4G	/home/jenkins<br/>[Pipeline] echo<br/>[2022-06-20T05:25:19.808Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2022-06-20T05:25:20.085Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-06-20T05:25:20.086Z] 4.0K	/home/jenkins/workspace/KIE/kogito/1.23.x<br/>[2022-06-20T05:25:20.086Z] 2.4M	/home/jenkins/workspace/KIE/kogito/main<br/>[2022-06-20T05:25:20.086Z] 2.4M	/home/jenkins/workspace/KIE/kogito<br/>[2022-06-20T05:25:20.086Z] 0	/home/jenkins/workspace/KIE/main/daily-build-jdk8<br/>[2022-06-20T05:25:20.086Z] 0	/home/jenkins/workspace/KIE/main<br/>[2022-06-20T05:25:20.086Z] 2.4M	/home/jenkins/workspace/KIE<br/>[2022-06-20T05:25:20.086Z] 2.4M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pip [...]

2022-06-20 05:38 UTC, tkobayas commented
Rebased to solve a conflict.

2022-06-20 05:40 UTC, tkobayas commented
Now I see that Drools 7 docs and binaries uploading is done by this script.

https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/main/script/release/10a_drools_upload_filemgmt.sh

So I move it to drools repo for Drools 8. I confirmed that the script works locally (ssh to my local machine instead of filemgmt-prod.jboss.org).

Uploaded structure is like this: (We will not upload SNAPSHOT version though)
```
.
├── docs_htdocs
│   └── drools
│       └── release
│           ├── 8.24.0-SNAPSHOT
│           │   ├── drools-docs
│           │   │   ├── docs-website
│           │   │   │   ├── drools
│           │   │   │   │   └── ...
│           │   │   │   ├── index.html
│           │   │   │   └── ...
│           │   │   ├── html_single
│           │   │   │   ├── index.html
│           │   │   │   ├── language-reference
│           │   │   │   │   └── ...
│           │   │   │   ├── rule-engine
│           │   │   │   │   └── ...
│           │   │   │   └── shared
│           │   │   │       └── ...
│           │   │   └── pdf
│           │   │       └── drools-docs.pdf
│           │   └── kie-api-javadoc
│           │       └── ...
│           └── latest -> 8.24.0-SNAPSHOT
└── downloads_htdocs
    └── drools
        └── release
            ├── 8.24.0-SNAPSHOT
            │   └── drools-distribution-8.24.0-SNAPSHOT.zip
            └── latest -> 8.24.0-SNAPSHOT
```

Do you think this is the right direction? @tarilabs @mariofusco @mbiarnes

2022-06-20 05:49 UTC, tkobayas commented on drools-docs/src/antora-template.yml
> +version: ~
We will upload the docs-website under versioned URL (e.g. https://docs.drools.org/8.30.0.Final/drools-docs/docs-website/) so specifying version in antora property will result in duplicate version name in URL (https://docs.drools.org/8.30.0.Final/drools-docs/docs-website/drools/8.30.0.Final/rule-engine). We can omit the version with `~`. See https://docs.antora.org/antora/latest/component-with-no-version/

2022-06-20 05:52 UTC, tkobayas commented on script/release/upload_filemgmt.sh
> +
If we want to merge this script for Drools 8 Beta (before GA), we should comment-out this part not to confuse users. In that case, **latest** should still point at Drools 7.

2022-06-21 14:04 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.deploy
> +                    if (isRelease()) {
I think the upload of docs should happen in the `Jenkinsfile.promote` file.
We want to perform the docs upload once everything is fine and so it should be after artifacts are released, not before IMO

2022-06-22 06:54 UTC, tkobayas commented on .ci/jenkins/Jenkinsfile.deploy
> +                    if (isRelease()) {
Thank you for the suggestion, @radtriste ! I moved the uploading operation from `Jenkinsfile.deploy` to `Jenkinsfile.promote` accordingly.

2022-06-22 09:57 UTC, radtriste approved these changes

2022-08-31 07:20 UTC, tkobayas commented
Rebased to keep up with latest changes

2022-09-02 03:55 UTC, tkobayas commented
Hi all, @radtriste @tarilabs @mariofusco @mbiarnes @rsynek 

I think it's a good time to merge this PR. When "Drools 8.28.0.Beta" will be released (at the end of this sprint), we will be able to confirm if this upload job (Antora docsite, javadoc, binary zip) works correctly. We will not yet link 8.28.0.Beta docs and binary from drools website because it's Beta.

Could you review and see if it's okay to merge? Thanks!

2022-09-02 06:09 UTC, rsynek approved these changes
LGTM; maybe the README needs to be a bit more clear about building the website.

2022-09-02 06:09 UTC, rsynek commented on drools-docs/README.adoc
> +This folder contains an antora playbook, `antora-playbook.yml` to generate documentation from the source of your locally installed drools project. You can build the website with `mvn clean install`.
I am not sure how to understand this paragraph. It talks about building the website via `mvn clean install`, while the next line does `npx antora antora-playbook.yml`.

2022-09-02 06:41 UTC, tarilabs approved these changes
LGTM I trust @radtriste judgement here as I admit I'm not very knowledgeable with Jenkins script, Tristan kindly merge on request of Toshiya if this look okay to you, thank you both!

2022-09-02 07:18 UTC, tkobayas commented on drools-docs/README.adoc
> +This folder contains an antora playbook, `antora-playbook.yml` to generate documentation from the source of your locally installed drools project. You can build the website with `mvn clean install`.
@rsynek Thank you for pointing that out. I think I should rewrite/simplify the README. I will work on it in a separated JIRA https://issues.redhat.com/browse/DROOLS-7141 Thanks!

2022-09-02 09:00 UTC, radtriste requested changes
Some changes needed into the promote file for test safety and jboss server authentication
I trust the upload shell script as I am not much aware for that

2022-09-02 09:00 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.promote
> +void uploadFileMgmt(String directory) {
Please add some check that we are on `kiegroup` author. So that if testing happens on a different author, then this is not executed
See https://github.com/kiegroup/optaplanner/blob/main/.ci/jenkins/Jenkinsfile.promote#L384 as an example

2022-09-02 09:00 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.promote
> +void uploadFileMgmt(String directory) {
also I think you will need the ssh key configured to access the jboss server for the upload (see example from optaplanner above)

2022-09-05 03:42 UTC, tkobayas commented on .ci/jenkins/Jenkinsfile.promote
> +void uploadFileMgmt(String directory) {
@radtriste Thank you very much for pointing that out! Fixed. Originally, `droolsjbpm-build-bootstrap` was using `sshagent` but this time I followed the optaplanner's approach `withCredentials`.

2022-09-05 09:37 UTC, radtriste approved these changes

2022-09-05 09:37 UTC, radtriste commented on .ci/jenkins/Jenkinsfile.promote
> +void uploadFileMgmt(String directory) {
lgtm

2022-09-06 06:41 UTC, mariofusco approved these changes

2022-09-08 07:29 UTC, radtriste approved these changes
Good for me for the pipeline

2022-09-08 08:17 UTC, tkobayas commented
Hi @mbiarnes ,

Could you kindly review from `upload_filemgmt.sh` perspective? This is ported from https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/main/script/release/10a_drools_upload_filemgmt.sh

I have tested the pipeline and the script with a Jenkins custom job and confirmed that docs and zip are uploaded expectedly. 

https://docs.drools.org/8.27.0.Beta/drools-docs/docs-website/drools/getting-started/index.html
https://download.jboss.org/drools/release/8.27.0.Beta/drools-distribution-8.27.0.Beta.zip

2022-09-09 09:02 UTC, mbiarnes approved these changes
LGTM

2022-09-09 09:03 UTC, tkobayas commented
Hi @radtriste , could you please merge this? Thanks!

2022-09-09 09:13 UTC, merged