[DROOLS-7039]  Fix ResourceHelpers
apache/incubator-kie pull request #4764
Opened 2022-10-20 13:37 UTC by gitgabrio

@mariofusco @pibizza 

Please note that most of the modifications are due to changed import. 

**JIRA**:

[link](https://issues.redhat.com/browse/DROOLS-7039)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel</b>

 - for <b>mandrel lts checks</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins run mandrel-lts</b>

- for a <b>specific mandrel lts check</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel-lts</b>
</details>

2022-10-21 08:53 UTC, mariofusco approved these changes

2022-10-21 13:11 UTC, pibizza requested changes
Some comments on test code. 
+1 for the removal of duplication.

2022-10-21 13:11 UTC, pibizza commented on drools-util/src/test/java/org/drools/util/FileUtilsTest.java
> +        assertThrows(RuntimeException.class, () -> FileUtils.getFile(NOTEXISTING_FILE));
```suggestion
        assertThatExceptionOfType(RuntimeException.class).isThrownBy () -> FileUtils.getFile(NOTEXISTING_FILE));
```

2022-10-21 13:11 UTC, pibizza commented on drools-util/src/test/java/org/drools/util/ResourceHelperTest.java
> +        assertThat(resources).anyMatch(elem -> elem.endsWith(TEST_FILE));
Join the two assertions.

2022-10-21 13:11 UTC, pibizza commented on drools-util/src/test/java/org/drools/util/ResourceHelperTest.java
> +    private void commonVerifyCollection(final Collection<File> toVerify, String expectedFile) {
Do not use optional parameters in common assertions. Have two separate assertions for the two cases. Also, since the assertions are small, I suggest inlining of the assertion method for clarity.

2022-10-21 13:11 UTC, pibizza commented on drools-util/src/test/java/org/drools/util/ResourceHelperTest.java
> +            assertThat(toVerify).allMatch(file -> file.exists() && file.getName().equals(expectedFile));
Join the assertions.

2022-10-21 14:52 UTC, gitgabrio commented on drools-util/src/test/java/org/drools/util/FileUtilsTest.java
> +        assertThrows(RuntimeException.class, () -> FileUtils.getFile(NOTEXISTING_FILE));
@pibizza 
done

2022-10-21 14:53 UTC, gitgabrio commented on drools-util/src/test/java/org/drools/util/ResourceHelperTest.java
> +        assertThat(resources).anyMatch(elem -> elem.endsWith(TEST_FILE));
@pibizza
done

2022-10-21 14:56 UTC, gitgabrio commented on drools-util/src/test/java/org/drools/util/ResourceHelperTest.java
> +    private void commonVerifyCollection(final Collection<File> toVerify, String expectedFile) {
@pibizza 
done

2022-10-21 14:56 UTC, gitgabrio commented on drools-util/src/test/java/org/drools/util/ResourceHelperTest.java
> +            assertThat(toVerify).allMatch(file -> file.exists() && file.getName().equals(expectedFile));
@pibizza
done

2022-10-24 08:34 UTC, pibizza approved these changes
Looks good to me

2022-10-24 09:28 UTC, gitgabrio commented
@danielezonca @mariofusco Hi! Could you please merge this, squashing commits? Thanks!

2022-10-24 09:33 UTC, danielezonca approved these changes

2022-10-24 09:33 UTC, merged