[DROOLS-7214] non-executable-model doesn't react to bind-only Map pro…
apache/incubator-kie pull request #4771
Opened 2022-10-26 09:17 UTC by tkobayas

…perty with map access operator

**Ports** 
This PR is for 7.x
Will do for 7.67.x
Will do for 7.67.x-blue
Will do for main

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-7214

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel</b>

 - for <b>mandrel lts checks</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins run mandrel-lts</b>

- for a <b>specific mandrel lts check</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] mandrel-lts</b>
</details>

2022-10-27 12:26 UTC, mariofusco approved these changes

2022-10-27 13:16 UTC, pibizza requested changes
Two minor comments re: naming of tests and creation of sttring. Good otherwise.

2022-10-27 13:16 UTC, pibizza commented on drools-core/src/main/java/org/drools/core/util/StringUtils.java
> +                return "" + c;
Since we are returning a one character string and using it to perform a comparison with a single char I suggest using a Char instead. As an alternative use String.valueOf(c) to create the string.

2022-10-27 13:16 UTC, pibizza commented on drools-model/drools-model-compiler/src/test/java/org/drools/modelcompiler/PropertyReactivityTest.java
> +    public void testBindOnlyProp() {
I suggest expanding the Prop into Property - people should just read the name of the test aloud and understand what is supposed to test. Also sooner or later we have to stop using the test prefix for test methods. It is redundant. So this test would be bindOnlyPropertyReacts.

2022-10-27 13:16 UTC, pibizza commented on drools-model/drools-model-compiler/src/test/java/org/drools/modelcompiler/PropertyReactivityTest.java
> +    public void testBindOnlyPropMap() {
AS above I suggest bindOnlyMapPropertyReacts

2022-10-27 13:16 UTC, pibizza commented on drools-model/drools-model-compiler/src/test/java/org/drools/modelcompiler/PropertyReactivityTest.java
> +    public void testBindOnlyPropMapAccessOperator() {
AS above I suggest bindOnlyMapPropertyWithAccessOperatorReacts

2022-10-27 13:16 UTC, pibizza commented on drools-model/drools-model-compiler/src/test/java/org/drools/modelcompiler/PropertyReactivityTest.java
> +    public void testBindOnlyPropListAccessOperator() {
AS above I suggest bindOnlyListPropertyWithAccessOperatorReacts

2022-10-28 05:30 UTC, tkobayas commented
@pibizza Thank you for the valuable inputs! All applied :)

2022-10-28 06:51 UTC, pibizza approved these changes
Looks good to me, thanks!

2022-10-28 07:40 UTC, tkobayas commented
Jenkins run cdb

2022-10-31 16:42 UTC, merged