Quarkus 3 CR1 setup
apache/incubator-kie pull request #5153
Opened 2023-04-04 11:45 UTC by radtriste

**Thank you for submitting this pull request**

**NOTE!:** Double check the target branch for this PR.
The default is `main` so it will target Drools 8 / Kogito.
If this PR is not strictly related to drools and kogito project in `drools.git`, it should probably target `7.x`as a branch

**Ports** If a forward-port or a backport is needed, paste the forward port PR here

[link](https://www.example.com)

**JIRA**: _(please edit the JIRA link if it exists)_

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

 - for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native-lts</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

2023-04-05 14:31 UTC, kie-ci3 commented
**(quarkus-3) - drools job** `#32` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/32/display/redirect

**Test results:**
- PASSED: 21299
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-05T14:30:03.941Z] [INFO] |  |  \- org.apache.commons:commons-lang3:jar:3.12.0:compile<br/>[2023-04-05T14:30:03.941Z] [INFO] |  +- org.apache.maven:maven-compat:jar:3.8.6:compile<br/>[2023-04-05T14:30:03.941Z] [INFO] |  |  \- org.apache.maven.wagon:wagon-provider-api:jar:3.5.1:compile<br/>[2023-04-05T14:30:03.941Z] [INFO] |  +- javax.inject:javax.inject:jar:1:compile<br/>[2023-04-05T14:30:03.941Z] [INFO] |  +- commons-io:commons-io:jar:2.11.0:compile<br/>[2023-04-05T14:30:03.941Z] [INFO] |  \- org.slf4j:jcl-over-slf4j:jar:1.7.30:runtime<br/>[2023-04-05T14:30:03.941Z] [INFO] +- org.kie:kie-ci:jar:sources:8.37.0-SNAPSHOT:compile<br/>[2023-04-05T14:30:03.941Z] [INFO] +- org.drools:drools-examples:jar:8.37.0-SNAPSHOT:compile<br/>[2023-04-05T14:30:03.941Z] [INFO] |  +- org.drools:drools-traits:jar:8.37.0-SNAPSHOT:compile<br/>[2023-04-05T14:30:03.941Z] [INFO] |  +- com.thoughtworks.xstream:xstream:jar:1.4.20:compile<br/>[2023-04-05T14:30:03.941Z] [INFO] |  |  \- io.github.x-stream:mxparser:jar:1.2.2:compile<br/>[2023-04-05T14:30:03.941Z] [INFO] |  |     \- xmlpull:xmlpull:jar:1.1.3.1:compile<br/>[2023-04-05T14:30:03.941Z] [INFO] |  +- com.miglayout:miglayout:jar:3.7.4:compile<br/>[2023-04-05T14:30:03.941Z] [INFO] |  +- ch.qos.logback:logback-classic:jar:1.2.9:compile<br/>[2023-04-05T14:30:03.941Z] [INFO] |  |  \- ch.qos.logback:logback-core:jar:1.2.9:compile<br/>[2023-04-05T14:30:03.941Z] [INFO] |  +- org.drools:drools-xml-support:jar:8.37.0-SNAPSHOT:compile<br/>[2023-04-05T14:30:03.942Z] [INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.14.2:compile<br/>[2023-04-05T14:30:03.942Z] [INFO] |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.14.2:compile<br/>[2023-04-05T14:30:03.942Z] [INFO] |     \- com.fasterxml.jackson.core:jackson-core:jar:2.14.2:compile<br/>[2023-04-05T14:30:03.942Z] [INFO] +- org.drools:drools-examples:jar:sources:8.37.0-SNAPSHOT:compile<br/>[2023-04-05T14:30:03.942Z] [INFO] +- org.kie:kie-api:jar:javadoc:8.37.0-SNAPSHOT:compile<br/>[2023-04-05T14:30:03.942Z] [INFO] \- org.kie:kie-internal:jar:javadoc:8.37.0-SNAPSHOT:compile<br/>[2023-04-05T14:30:03.942Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-05T14:30:03.942Z] [INFO] Reactor Summary for Drools :: Parent 8.37.0-SNAPSHOT:<br/>[2023-04-05T14:30:03.942Z] [INFO] <br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Parent ................................... SUCCESS [  8.144 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Build Parent ............................. SUCCESS [  6.025 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] KIE :: Public API .................................. SUCCESS [  8.644 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] KIE :: Internal .................................... SUCCESS [  7.401 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] KIE :: Util ........................................ SUCCESS [  0.045 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] KIE :: Util :: XML supposrt ........................ SUCCESS [  1.866 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Util ..................................... SUCCESS [  3.386 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] KIE :: Memory Compiler ............................. SUCCESS [  3.694 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Wiring :: Parent ......................... SUCCESS [  0.043 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Wiring :: API ............................ SUCCESS [  3.076 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Wiring :: Static ......................... SUCCESS [  2.430 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: IO ....................................... SUCCESS [  2.519 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Core ..................................... SUCCESS [ 36.944 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: DRL AST .................................. SUCCESS [  3.798 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: DRL :: Parser ............................ SUCCESS [  6.504 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: DRL :: Extensions ........................ SUCCESS [  1.728 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Wiring :: Dynamic ........................ SUCCESS [  2.640 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: KieSession ............................... SUCCESS [  5.500 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: ECJ ...................................... SUCCESS [  5.775 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] KIE :: Util :: Maven Support ....................... SUCCESS [  1.910 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] KIE :: Test Utility Classes ........................ SUCCESS [  3.588 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Compiler ................................. SUCCESS [  9.112 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Truth Maintenance System ................. SUCCESS [  3.804 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: MVEL ..................................... SUCCESS [  9.953 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Reliability .............................. SUCCESS [ 20.853 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] KIE core BOM ....................................... SUCCESS [  0.005 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools BOM (Bill Of Materials) ..................... SUCCESS [  0.004 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Efesto BOM (Bill Of Materials) ..................... SUCCESS [  0.004 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Kie DMN BOM (Bill Of Materials) .................... SUCCESS [  0.004 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Kie PMML BOM (Bill Of Materials) ................... SUCCESS [  0.004 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Bom Parent ............................... SUCCESS [  0.004 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] KIE :: Util :: Maven Integration ................... SUCCESS [  3.811 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Rule Units :: Parent ..................... SUCCESS [  0.030 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Rule Units :: API ........................ SUCCESS [  1.999 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Model :: Parent .......................... SUCCESS [  0.027 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Codegen :: Common ........................ SUCCESS [  2.095 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Canonical Model .......................... SUCCESS [  6.669 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Model :: Compiler ........................ SUCCESS [  4.915 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: MVEL Parser .............................. SUCCESS [  7.088 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: MVEL Compiler ............................ SUCCESS [  8.941 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Commands ................................. SUCCESS [  4.712 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: XML Support .............................. SUCCESS [  4.481 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Templates ................................ SUCCESS [  4.909 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Decision Tables .......................... SUCCESS [ 20.696 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Model :: Codegen ......................... SUCCESS [01:26 min]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Rule Units :: Implementation ............. SUCCESS [  6.773 s]<br/>[2023-04-05T14:30:03.942Z] [INFO] Drools :: Rule Units :: DSL .................. [...]

2023-04-06 08:17 UTC, kie-ci3 commented
**(quarkus-3) - drools job** `#34` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/34/display/redirect

**Test results:**
- PASSED: 2400
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-06T08:17:08.060Z] [INFO] KIE :: DRL :: Compilation :: Common ................ SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: DRL :: Runtime :: Common .................... SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: DRL :: Implementations ...................... SUCCESS [  0.026 s]<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: DRL :: MapInput ............................. SUCCESS [  0.025 s]<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: DRL :: MapInput :: Runtime .................. SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] Drools :: Scenario Simulation Integration Test ..... SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] Drools :: Metric Analysis .......................... SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] Drools :: Impact Analysis .......................... SUCCESS [  0.025 s]<br/>[2023-04-06T08:17:08.060Z] [INFO] Drools :: Impact Analysis :: Model ................. SUCCESS [  1.836 s]<br/>[2023-04-06T08:17:08.060Z] [INFO] Drools :: Impact Analysis :: Parser ................ SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] Drools :: Impact Analysis Graph .................... SUCCESS [  0.025 s]<br/>[2023-04-06T08:17:08.060Z] [INFO] Drools :: Impact Analysis Graph :: Common .......... SUCCESS [  1.933 s]<br/>[2023-04-06T08:17:08.060Z] [INFO] Drools :: Impact Analysis Graph :: Graphviz ........ SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] Drools :: Impact Analysis :: Integration Tests ..... SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] Drools :: ReteDiagram .............................. SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] Drools :: FastUtil ................................. SUCCESS [  3.063 s]<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Efesto :: Dependencies ...................... SUCCESS [  0.040 s]<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: DRL :: KieSession :: Local .................. SUCCESS [  0.024 s]<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: DRL :: KieSession :: Local :: Runtime ....... SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: DRL :: Tests ................................ SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: DRL :: Tests Without IndexFile .............. SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Decision Model Notation :: Internal utils for Validation bootstrap SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Decision Model Notation :: Validation ....... SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Decision Model Notation :: OpenAPI (OAS) utilities SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Decision Model Notation :: TCK .............. SUCCESS [  0.021 s]<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Decision Model Notation :: Legacy tests (previous DMN versions) SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Decision Model Notation :: Trisotech extensions support SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Decision Model Notation :: Signavio extensions support SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KiE :: Decision Model Notation - PMML Tests :: Parent SUCCESS [  0.022 s]<br/>[2023-04-06T08:17:08.060Z] [INFO] KiE :: Decision Model Notation - PMML Tests ........ SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KiE :: Decision Model Notation - PMML Trusty Tests . SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Decision Model Notation :: xls2dmn CLI Utility SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Decision Model Notation :: JSR-223 JQ ScriptEngine SUCCESS [  3.133 s]<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Decision Model Notation :: Core JSR-223 ..... SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Decision Model Notation :: ruleset2dmn parent SUCCESS [  0.023 s]<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Decision Model Notation :: ruleset2dmn utilities SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Decision Model Notation :: ruleset2dmn CLI .. SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: PMML :: Models :: Tests ..................... SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: PMML :: Models :: Regression :: Tests ....... SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: PMML :: Models :: Drools :: Tree :: Tests ... SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: PMML :: Models :: Drools :: Scorecard :: Tests SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: PMML :: Models :: Mining :: Tests ........... SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: PMML :: Models :: Tree :: Tests ............. SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: PMML :: Models :: Clustering :: Tests ....... SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: PMML :: Models :: Scorecard :: Tests ........ SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Maven Plugin ................................ SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Maven Archetypes ............................ SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Drools DMN engine Maven Archetype ........... SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Drools Maven Archetype with Executable Model and RuleUnit SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] KIE :: Drools Maven Archetype with Executable Model and traditional rule style SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] Drools :: Quarkus Extension ........................ SUCCESS [  0.023 s]<br/>[2023-04-06T08:17:08.060Z] [INFO] Drools :: Quarkus Extension :: Util :: Deployment .. SUCCESS [  4.763 s]<br/>[2023-04-06T08:17:08.060Z] [INFO] Drools :: Quarkus Extension :: Runtime ............. SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] Drools :: Quarkus Extension :: Deployment .......... SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] Drools :: Quarkus Extension :: Integration Test .... SKIPPED<br/>[2023-04-06T08:17:08.060Z] [INFO] Drools :: Quarkus Extension :: Integration Test :: Hotreload SKIPPED<br/>[2023-04-06T08:17:08.061Z] [INFO] Drools :: Quarkus Extension :: Integration Test with Rule Unit SKIPPED<br/>[2023-04-06T08:17:08.061Z] [INFO] Drools :: Quarkus Extension :: Quickstart Integration Test SKIPPED<br/>[2023-04-06T08:17:08.061Z] [INFO] Drools :: Quarkus Extension :: Examples ............ SUCCESS [  0.026 s]<br/>[2023-04-06T08:17:08.061Z] [INFO] Drools :: Quarkus Extension :: Examples :: Reactive  SKIPPED<br/>[2023-04-06T08:17:08.061Z] [INFO] Drools :: Quarkus Extension :: Examples :: Reactive  SKIPPED<br/>[2023-04-06T08:17:08.061Z] [INFO] Kie :: Jpmml Migration Recipe ...................... SUCCESS [ 47.535 s]<br/>[2023-04-06T08:17:08.061Z] [INFO] Drools documentation ............................... SUCCESS [ 16.629 s]<br/>[2023-04-06T08:17:08.061Z] [INFO] Drools distribution ................................ SKIPPED<br/>[2023-04-06T08:17:08.061Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-06T08:17:08.061Z] [INFO] BUILD FAILURE<br/>[2023-04-06T08:17:08.061Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-06T08:17:08.061Z] [INFO] Total time:  04:59 min<br/>[2023-04-06T08:17:08.061Z] [INFO] Finished at: 2023-04-06T04:17:06-04:00<br/>[2023-04-06T08:17:08.061Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-06T08:17:08.061Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project kie-test-util: Compilation failure: Compilation failure: <br/>[2023-04-06T08:17:08.061Z] [ERROR] /home/jenkins/workspace/KIE/drools/main/pullrequest.quarkus-3/drools.quarkus-3.droo [...]

2023-04-06 09:10 UTC, kie-ci3 commented
**(tests) - drools job** `#1212` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1212/display/redirect

**Test results:**
- PASSED: 21299
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1212/testReport/org.kie.pmml.evaluator.core/PMMLRuntimeContextImplTest/getFixedProbabilityMap/">org.kie.pmml.evaluator.core.PMMLRuntimeContextImplTest.getFixedProbabilityMap</a></summary>
bound must be positive
</details>

2023-04-06 09:19 UTC, gitgabrio requested changes
Hi @radtriste 
thanks for the PR, but TBH I would really like to avoid introducing this other "case" with the "CreateQuarkusDroolsMigration" class: IMO this setup is already too frail and complex to maintaint without adding something else

2023-04-06 14:38 UTC, kie-ci3 commented
**(quarkus-3) - drools job** `#38` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/38/display/redirect

**Test results:**
- PASSED: 2401
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-06T14:37:59.803Z] [INFO] KIE :: DRL :: Compilation :: Common ................ SKIPPED<br/>[2023-04-06T14:37:59.803Z] [INFO] KIE :: DRL :: Runtime :: Common .................... SKIPPED<br/>[2023-04-06T14:37:59.803Z] [INFO] KIE :: DRL :: Implementations ...................... SUCCESS [  0.023 s]<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: DRL :: MapInput ............................. SUCCESS [  0.023 s]<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: DRL :: MapInput :: Runtime .................. SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Scenario Simulation Integration Test ..... SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Metric Analysis .......................... SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Impact Analysis .......................... SUCCESS [  0.021 s]<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Impact Analysis :: Model ................. SUCCESS [  2.442 s]<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Impact Analysis :: Parser ................ SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Impact Analysis Graph .................... SUCCESS [  0.022 s]<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Impact Analysis Graph :: Common .......... SUCCESS [  2.739 s]<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Impact Analysis Graph :: Graphviz ........ SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Impact Analysis :: Integration Tests ..... SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: ReteDiagram .............................. SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: FastUtil ................................. SUCCESS [  3.633 s]<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Efesto :: Dependencies ...................... SUCCESS [  0.038 s]<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: DRL :: KieSession :: Local .................. SUCCESS [  0.024 s]<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: DRL :: KieSession :: Local :: Runtime ....... SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: DRL :: Tests ................................ SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: DRL :: Tests Without IndexFile .............. SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Decision Model Notation :: Internal utils for Validation bootstrap SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Decision Model Notation :: Validation ....... SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Decision Model Notation :: OpenAPI (OAS) utilities SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Decision Model Notation :: TCK .............. SUCCESS [  0.022 s]<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Decision Model Notation :: Legacy tests (previous DMN versions) SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Decision Model Notation :: Trisotech extensions support SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Decision Model Notation :: Signavio extensions support SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KiE :: Decision Model Notation - PMML Tests :: Parent SUCCESS [  0.022 s]<br/>[2023-04-06T14:37:59.804Z] [INFO] KiE :: Decision Model Notation - PMML Tests ........ SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KiE :: Decision Model Notation - PMML Trusty Tests . SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Decision Model Notation :: xls2dmn CLI Utility SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Decision Model Notation :: JSR-223 JQ ScriptEngine SUCCESS [  3.517 s]<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Decision Model Notation :: Core JSR-223 ..... SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Decision Model Notation :: ruleset2dmn parent SUCCESS [  0.022 s]<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Decision Model Notation :: ruleset2dmn utilities SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Decision Model Notation :: ruleset2dmn CLI .. SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: PMML :: Models :: Tests ..................... SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: PMML :: Models :: Regression :: Tests ....... SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: PMML :: Models :: Drools :: Tree :: Tests ... SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: PMML :: Models :: Drools :: Scorecard :: Tests SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: PMML :: Models :: Mining :: Tests ........... SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: PMML :: Models :: Tree :: Tests ............. SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: PMML :: Models :: Clustering :: Tests ....... SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: PMML :: Models :: Scorecard :: Tests ........ SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Maven Plugin ................................ SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Maven Archetypes ............................ SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Drools DMN engine Maven Archetype ........... SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Drools Maven Archetype with Executable Model and RuleUnit SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] KIE :: Drools Maven Archetype with Executable Model and traditional rule style SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Quarkus Extension ........................ SUCCESS [  0.023 s]<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Quarkus Extension :: Util :: Deployment .. SUCCESS [  5.777 s]<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Quarkus Extension :: Runtime ............. SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Quarkus Extension :: Deployment .......... SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Quarkus Extension :: Integration Test .... SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Quarkus Extension :: Integration Test :: Hotreload SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Quarkus Extension :: Integration Test with Rule Unit SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Quarkus Extension :: Quickstart Integration Test SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Quarkus Extension :: Examples ............ SUCCESS [  0.023 s]<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Quarkus Extension :: Examples :: Reactive  SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools :: Quarkus Extension :: Examples :: Reactive  SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] Kie :: Jpmml Migration Recipe ...................... SUCCESS [ 46.548 s]<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools documentation ............................... SUCCESS [ 16.232 s]<br/>[2023-04-06T14:37:59.804Z] [INFO] Drools distribution ................................ SKIPPED<br/>[2023-04-06T14:37:59.804Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-06T14:37:59.804Z] [INFO] BUILD FAILURE<br/>[2023-04-06T14:37:59.804Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-06T14:37:59.804Z] [INFO] Total time:  05:33 min<br/>[2023-04-06T14:37:59.804Z] [INFO] Finished at: 2023-04-06T10:37:59-04:00<br/>[2023-04-06T14:37:59.804Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-06T14:37:59.804Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project kie-test-util: Compilation failure: Compilation failure: <br/>[2023-04-06T14:37:59.804Z] [ERROR] /home/jenkins/workspace/KIE/drools/main/pullrequest.quarkus-3/drools.quarkus-3.droo [...]

2023-04-06 14:49 UTC, gitgabrio requested changes

2023-04-06 14:49 UTC, gitgabrio commented on .ci/environments/quarkus-3/quarkus3.yml
> +- org.openrewrite.maven.ChangeDependencyGroupIdAndArtifactId: {
hi @radtriste it seems the following four recipes seems the same... beside, it seems there is a version mismatch:

`Could not find artifact org.eclipse.parsson:parsson:jar:2.1.1 in mirror-central`

2023-04-07 08:02 UTC, radtriste commented
jenkins run drools quarkus-3

2023-04-07 08:12 UTC, kie-ci3 commented
**(quarkus-3) - drools job** `#43` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/43/display/redirect

**Test results:**
- PASSED: 2401
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-07T08:12:00.086Z] [INFO] KIE :: DRL :: Compilation :: Common ................ SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: DRL :: Runtime :: Common .................... SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: DRL :: Implementations ...................... SUCCESS [  0.026 s]<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: DRL :: MapInput ............................. SUCCESS [  0.025 s]<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: DRL :: MapInput :: Runtime .................. SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Scenario Simulation Integration Test ..... SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Metric Analysis .......................... SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Impact Analysis .......................... SUCCESS [  0.024 s]<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Impact Analysis :: Model ................. SUCCESS [  1.704 s]<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Impact Analysis :: Parser ................ SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Impact Analysis Graph .................... SUCCESS [  0.026 s]<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Impact Analysis Graph :: Common .......... SUCCESS [  1.818 s]<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Impact Analysis Graph :: Graphviz ........ SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Impact Analysis :: Integration Tests ..... SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: ReteDiagram .............................. SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: FastUtil ................................. SUCCESS [  2.958 s]<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Efesto :: Dependencies ...................... SUCCESS [  0.044 s]<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: DRL :: KieSession :: Local .................. SUCCESS [  0.025 s]<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: DRL :: KieSession :: Local :: Runtime ....... SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: DRL :: Tests ................................ SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: DRL :: Tests Without IndexFile .............. SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Decision Model Notation :: Internal utils for Validation bootstrap SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Decision Model Notation :: Validation ....... SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Decision Model Notation :: OpenAPI (OAS) utilities SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Decision Model Notation :: TCK .............. SUCCESS [  0.023 s]<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Decision Model Notation :: Legacy tests (previous DMN versions) SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Decision Model Notation :: Trisotech extensions support SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Decision Model Notation :: Signavio extensions support SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KiE :: Decision Model Notation - PMML Tests :: Parent SUCCESS [  0.023 s]<br/>[2023-04-07T08:12:00.086Z] [INFO] KiE :: Decision Model Notation - PMML Tests ........ SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KiE :: Decision Model Notation - PMML Trusty Tests . SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Decision Model Notation :: xls2dmn CLI Utility SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Decision Model Notation :: JSR-223 JQ ScriptEngine SUCCESS [  3.106 s]<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Decision Model Notation :: Core JSR-223 ..... SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Decision Model Notation :: ruleset2dmn parent SUCCESS [  0.025 s]<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Decision Model Notation :: ruleset2dmn utilities SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Decision Model Notation :: ruleset2dmn CLI .. SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: PMML :: Models :: Tests ..................... SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: PMML :: Models :: Regression :: Tests ....... SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: PMML :: Models :: Drools :: Tree :: Tests ... SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: PMML :: Models :: Drools :: Scorecard :: Tests SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: PMML :: Models :: Mining :: Tests ........... SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: PMML :: Models :: Tree :: Tests ............. SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: PMML :: Models :: Clustering :: Tests ....... SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: PMML :: Models :: Scorecard :: Tests ........ SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Maven Plugin ................................ SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Maven Archetypes ............................ SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Drools DMN engine Maven Archetype ........... SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Drools Maven Archetype with Executable Model and RuleUnit SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] KIE :: Drools Maven Archetype with Executable Model and traditional rule style SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Quarkus Extension ........................ SUCCESS [  0.025 s]<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Quarkus Extension :: Util :: Deployment .. SUCCESS [  5.002 s]<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Quarkus Extension :: Runtime ............. SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Quarkus Extension :: Deployment .......... SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Quarkus Extension :: Integration Test .... SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Quarkus Extension :: Integration Test :: Hotreload SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Quarkus Extension :: Integration Test with Rule Unit SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Quarkus Extension :: Quickstart Integration Test SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Quarkus Extension :: Examples ............ SUCCESS [  0.027 s]<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Quarkus Extension :: Examples :: Reactive  SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools :: Quarkus Extension :: Examples :: Reactive  SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] Kie :: Jpmml Migration Recipe ...................... SUCCESS [ 49.019 s]<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools documentation ............................... SUCCESS [ 15.757 s]<br/>[2023-04-07T08:12:00.086Z] [INFO] Drools distribution ................................ SKIPPED<br/>[2023-04-07T08:12:00.086Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-07T08:12:00.086Z] [INFO] BUILD FAILURE<br/>[2023-04-07T08:12:00.086Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-07T08:12:00.086Z] [INFO] Total time:  04:55 min<br/>[2023-04-07T08:12:00.086Z] [INFO] Finished at: 2023-04-07T04:11:59-04:00<br/>[2023-04-07T08:12:00.086Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-07T08:12:00.086Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project kie-test-util: Compilation failure: Compilation failure: <br/>[2023-04-07T08:12:00.086Z] [ERROR] /home/jenkins/workspace/KIE/drools/main/pullrequest.quarkus-3/drools.quarkus-3.droo [...]

2023-04-11 13:58 UTC, kie-ci3 commented
**(tests) - kogito-quarkus-examples job** `#440` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kogito-quarkus-examples/440/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-11T13:58:24.966Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-11T13:58:24.966Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-11T13:58:24.966Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-11T13:58:24.966Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-11T13:58:24.966Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-11T13:58:24.966Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-11T13:58:24.966Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-11T13:58:24.966Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-11T13:58:24.966Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-11T13:58:24.966Z] Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.drools:drools-bom:pom:8.37.0-SNAPSHOT<br/>[2023-04-11T13:58:24.966Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:415)<br/>[2023-04-11T13:58:24.966Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-04-11T13:58:24.966Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)<br/>[2023-04-11T13:58:24.966Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement (DefaultModelBuilder.java:1347)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:544)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-11T13:58:24.966Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-11T13:58:24.966Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-11T13:58:24.966Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-11T13:58:24.966Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-11T13:58:24.966Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-11T13:58:24.966Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-11T13:58:24.966Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-11T13:58:24.966Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-11T13:58:24.966Z] [ERROR]     'dependencies.dependency.version' for org.drools:drools-decisiontables:jar is missing. @ line 73, column 17<br/>[2023-04-11T13:58:24.966Z] [ERROR]   <br/>[2023-04-11T13:58:24.966Z] [ERROR]   The project org.kie.kogito.examples:kogito-travel-agency-example-basic:2.0.0-SNAPSHOT (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-quarkus-examples/bc/kiegroup_kogito-examples/kogito-quarkus-examples/kogito-travel-agency/basic/pom.xml) has 2 errors<br/>[2023-04-11T13:58:24.966Z] [ERROR]     Non-resolvable import POM: Could not find artifact org.drools:drools-bom:pom:8.37.0-SNAPSHOT @ line 41, column 19 -> [Help 2]<br/>[2023-04-11T13:58:24.966Z] org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact org.drools:drools-bom:pom:8.37.0-SNAPSHOT<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:196)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement (DefaultModelBuilder.java:1347)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:544)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-11T13:58:24.966Z]     at org.apache.maven.proje [...]

2023-04-11 14:15 UTC, kie-ci3 commented
**(tests) - kogito-springboot-examples job** `#439` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kogito-springboot-examples/439/display/redirect

**Test results:**
- PASSED: 130
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-11T14:15:34.428Z] [INFO] Results:<br/>[2023-04-11T14:15:34.428Z] [INFO] <br/>[2023-04-11T14:15:34.428Z] [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0<br/>[2023-04-11T14:15:34.428Z] [INFO] <br/>[2023-04-11T14:15:34.429Z] [INFO] <br/>[2023-04-11T14:15:34.429Z] [INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ ruleunit-springboot-example ---<br/>[2023-04-11T14:15:34.429Z] [INFO] Building jar: /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example.jar<br/>[2023-04-11T14:15:34.429Z] [INFO] <br/>[2023-04-11T14:15:34.429Z] [INFO] --- maven-jar-plugin:3.1.0:test-jar (test-jar) @ ruleunit-springboot-example ---<br/>[2023-04-11T14:15:34.429Z] [INFO] Building jar: /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-tests.jar<br/>[2023-04-11T14:15:34.429Z] [INFO] <br/>[2023-04-11T14:15:34.429Z] [INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ ruleunit-springboot-example ---<br/>[2023-04-11T14:15:34.429Z] [INFO] Building jar: /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-sources.jar<br/>[2023-04-11T14:15:34.429Z] [INFO] <br/>[2023-04-11T14:15:34.429Z] [INFO] --- maven-source-plugin:3.0.1:test-jar-no-fork (attach-test-sources) @ ruleunit-springboot-example ---<br/>[2023-04-11T14:15:34.429Z] [INFO] Building jar: /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-test-sources.jar<br/>[2023-04-11T14:15:34.429Z] [INFO] <br/>[2023-04-11T14:15:34.429Z] [INFO] --- spring-boot-maven-plugin:2.6.6:repackage (default) @ ruleunit-springboot-example ---<br/>[2023-04-11T14:15:34.429Z] [INFO] Replacing main artifact with repackaged archive<br/>[2023-04-11T14:15:34.429Z] [INFO] <br/>[2023-04-11T14:15:34.429Z] [INFO] --- maven-resources-plugin:2.5:copy-resources (add-it-resources) @ ruleunit-springboot-example ---<br/>[2023-04-11T14:15:34.429Z] [debug] execute contextualize<br/>[2023-04-11T14:15:34.429Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-04-11T14:15:34.429Z] [INFO] Copying 2 resources<br/>[2023-04-11T14:15:34.429Z] [INFO] <br/>[2023-04-11T14:15:34.429Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (integration-test) @ ruleunit-springboot-example ---<br/>[2023-04-11T14:15:34.429Z] [INFO] <br/>[2023-04-11T14:15:34.429Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (default) @ ruleunit-springboot-example ---<br/>[2023-04-11T14:15:34.429Z] [INFO] Skipping execution of surefire because it has already been run for this configuration<br/>[2023-04-11T14:15:34.429Z] [INFO] <br/>[2023-04-11T14:15:34.429Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (integration-test) @ ruleunit-springboot-example ---<br/>[2023-04-11T14:15:34.429Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/failsafe-reports<br/>[2023-04-11T14:15:34.429Z] [INFO] <br/>[2023-04-11T14:15:34.429Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (default) @ ruleunit-springboot-example ---<br/>[2023-04-11T14:15:34.429Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/failsafe-reports<br/>[2023-04-11T14:15:34.429Z] [INFO] <br/>[2023-04-11T14:15:34.429Z] [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ ruleunit-springboot-example ---<br/>[2023-04-11T14:15:34.429Z] [INFO] Installing /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example.jar to /home/jenkins/.m2/repository/org/kie/kogito/examples/ruleunit-springboot-example/2.0.0-SNAPSHOT/ruleunit-springboot-example-2.0.0-SNAPSHOT.jar<br/>[2023-04-11T14:15:34.429Z] [INFO] Installing /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/pom.xml to /home/jenkins/.m2/repository/org/kie/kogito/examples/ruleunit-springboot-example/2.0.0-SNAPSHOT/ruleunit-springboot-example-2.0.0-SNAPSHOT.pom<br/>[2023-04-11T14:15:34.429Z] [INFO] Installing /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-tests.jar to /home/jenkins/.m2/repository/org/kie/kogito/examples/ruleunit-springboot-example/2.0.0-SNAPSHOT/ruleunit-springboot-example-2.0.0-SNAPSHOT-tests.jar<br/>[2023-04-11T14:15:34.429Z] [INFO] Installing /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-sources.jar to /home/jenkins/.m2/repository/org/kie/kogito/examples/ruleunit-springboot-example/2.0.0-SNAPSHOT/ruleunit-springboot-example-2.0.0-SNAPSHOT-sources.jar<br/>[2023-04-11T14:15:34.429Z] [INFO] Installing /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-test-sources.jar to /home/jenkins/.m2/repository/org/kie/kogito/examples/ruleunit-springboot-example/2.0.0-SNAPSHOT/ruleunit-springboot-example-2.0.0-SNAPSHOT-test-sources.jar<br/>[2023-04-11T14:15:34.429Z] [INFO] <br/>[2023-04-11T14:15:34.429Z] [INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ ruleunit-springboot-example ---<br/>[2023-04-11T14:15:34.429Z] [INFO] org.kie.kogito.examples:ruleunit-springboot-example:jar:2.0.0-SNAPSHOT<br/>[2023-04-11T14:15:34.429Z] [INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:2.6.6:compile<br/>[2023-04-11T14:15:34.429Z] [INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.6.6:compile<br/>[2023-04-11T14:15:34.429Z] [INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.6.6:compile<br/>[2023-04-11T14:15:34.429Z] [INFO] |  |  |  \- org.springframework:spring-context:jar:5.3.18:compile<br/>[2023-04-11T14:15:34.429Z] [INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.6.6:compile<br/>[2023-04-11T14:15:34.429Z] [INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.6.6:compile<br/>[2023-04-11T14:15:34.429Z] [INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.9:compile<br/>[2023-04-11T14:15:34.429Z] [INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.9:compile<br/>[2023-04-11T14:15:34.429Z] [INFO] |  |  |  +- org.apache.logging.log4j:log [...]

2023-04-11 14:17 UTC, kie-ci3 commented
**(tests) - serverless-workflow-examples job** `#441` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.serverless-workflow-examples/441/display/redirect

**Test results:**
- PASSED: 78
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-11T14:17:38.487Z] [INFO] |  |  +- org.kie.kogito:kogito-timer:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  \- org.kie.kogito:kogito-pmml-api-dependencies:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |     +- org.kie:kie-pmml-evaluator-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |     |  \- org.kie:kie-pmml-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |     |     \- org.apache.commons:commons-math3:jar:3.4.1:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |     \- org.kie:kie-pmml-commons:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |        \- org.apache.commons:commons-text:jar:1.10.0:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  +- org.kie.kogito:kogito-codegen-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  +- com.github.javaparser:javaparser-core:jar:3.24.2:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  \- org.drools:drools-codegen-common:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  +- org.kie.kogito:kogito-codegen-core:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  +- org.kie.kogito:kogito-events-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  \- org.drools:drools-io:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |     \- org.drools:drools-util:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  +- io.quarkus:quarkus-elytron-security-properties-file:jar:2.16.5.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  +- io.quarkus:quarkus-elytron-security:jar:2.16.5.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  \- io.quarkus:quarkus-elytron-security-common:jar:2.16.5.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  +- org.wildfly.security:wildfly-elytron-auth-server:jar:1.20.1.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-auth:jar:1.20.1.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-base:jar:1.20.1.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-credential:jar:1.20.1.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  |  +- org.wildfly.security:wildfly-elytron-asn1:jar:1.20.1.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  |  +- org.wildfly.security:wildfly-elytron-keystore:jar:1.20.1.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  |  |  \- org.wildfly.security:wildfly-elytron-x500-cert:jar:1.20.1.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  |  |     +- org.wildfly.security:wildfly-elytron-x500-cert-util:jar:1.20.1.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  |  |     \- org.apache.sshd:sshd-common:jar:2.9.2:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  |  \- org.wildfly.security:wildfly-elytron-provider-util:jar:1.20.1.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-permission:jar:1.20.1.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-util:jar:1.20.1.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  \- org.wildfly.security:wildfly-elytron-x500:jar:1.20.1.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  +- org.wildfly.security:wildfly-elytron-password-impl:jar:1.20.1.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  +- org.wildfly.security:wildfly-elytron-realm:jar:1.20.1.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  \- org.wildfly.security:wildfly-elytron-encryption:jar:1.20.1.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  +- io.quarkus:quarkus-security:jar:2.16.5.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  +- jakarta.security.jacc:jakarta.security.jacc-api:jar:1.6.1:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  \- jakarta.security.auth.message:jakarta.security.auth.message-api:jar:1.1.3:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  \- org.kie:efesto-dependencies:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |     +- org.kie:efesto-common-utils:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |     +- org.kie:efesto-common-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |     |  \- org.kie:kie-memory-compiler:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |     +- org.kie:efesto-common-core:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |     +- org.kie:efesto-compilation-manager-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |     +- org.kie:efesto-compilation-manager-core:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |     +- org.kie:efesto-runtime-manager-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |     +- org.kie:efesto-runtime-manager-core:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |     \- org.assertj:assertj-core:jar:3.23.1:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |        \- net.bytebuddy:byte-buddy:jar:1.12.18:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] +- io.quarkus:quarkus-webjars-locator:jar:2.16.5.Final:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] +- org.webjars:bootstrap:jar:5.1.3:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  \- org.webjars:popper.js:jar:2.9.3:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] +- org.webjars:jquery:jar:3.6.0:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] +- io.quarkus:quarkus-junit5:jar:2.16.5.Final:test<br/>[2023-04-11T14:17:38.487Z] [INFO] |  +- io.quarkus:quarkus-bootstrap-core:jar:2.16.5.Final:test<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-app-model:jar:2.16.5.Final:test<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  \- io.smallrye.common:smallrye-common-io:jar:1.13.2:compile<br/>[2023-04-11T14:17:38.487Z] [INFO] |  +- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.5:test<br/>[2023-04-11T14:17:38.487Z] [INFO] |  +- io.quarkus:quarkus-test-common:jar:2.16.5.Final:test<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  +- io.quarkus:quarkus-core-deployment:jar:2.16.5.Final:test<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  +- org.aesh:readline:jar:2.2:test<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  |  \- org.fusesource.jansi:jansi:jar:1.18:test<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  +- org.aesh:aesh:jar:2.7:test<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  +- org.ow2.asm:asm-commons:jar:9.4:test<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  +- io.quarkus:quarkus-class-change-agent:jar:2.16.5.Final:test<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  +- io.quarkus:quarkus-devtools-utilities:jar:2.16.5.Final:test<br/>[2023-04-11T14:17:38.487Z] [INFO] |  |  |  +- io.quarkus:quarkus-builder:jar:2.16.5.Final:test<br/>[2023-04-11T14:17:38.488Z] [INFO] |  |  |  \- org.junit.platform:junit-platform-launcher:jar:1.9.2:test<br/>[2023-04-11T14:17:38.488Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-maven-resolver:jar:2.16.5.Final:test<br/>[2023-04-11T14:17:38.488Z] [INFO] |  |  |  +- org.apache.maven:maven-embedder:jar:3.8.6:test<br/>[2023-04-11T14:17:38.488Z] [INFO] |  |  |  |  +- org.apache.maven:maven-settings:jar:3.8.6:test<br/>[2023-04-11T14:17:38.488Z] [INFO] |  |  |  |  +- org.apache.maven:maven-core:jar:3.8.6:test<br/>[2023-04-11T14:17:38.488Z] [INFO] |   [...]

2023-04-11 14:23 UTC, kie-ci3 commented
**(quarkus-3) - drools job** `#47` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/47/display/redirect

**Test results:**
- PASSED: 21303
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-11T14:21:06.633Z] [INFO] |  |     \- xmlpull:xmlpull:jar:1.1.3.1:compile<br/>[2023-04-11T14:21:06.633Z] [INFO] |  +- com.miglayout:miglayout:jar:3.7.4:compile<br/>[2023-04-11T14:21:06.633Z] [INFO] |  +- ch.qos.logback:logback-classic:jar:1.2.9:compile<br/>[2023-04-11T14:21:06.633Z] [INFO] |  |  \- ch.qos.logback:logback-core:jar:1.2.9:compile<br/>[2023-04-11T14:21:06.633Z] [INFO] |  +- org.drools:drools-xml-support:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:21:06.633Z] [INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.14.2:compile<br/>[2023-04-11T14:21:06.634Z] [INFO] |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.14.2:compile<br/>[2023-04-11T14:21:06.634Z] [INFO] |     \- com.fasterxml.jackson.core:jackson-core:jar:2.14.2:compile<br/>[2023-04-11T14:21:06.634Z] [INFO] +- org.drools:drools-examples:jar:sources:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:21:06.634Z] [INFO] +- org.kie:kie-api:jar:javadoc:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:21:06.634Z] [INFO] \- org.kie:kie-internal:jar:javadoc:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T14:21:06.634Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-11T14:21:06.634Z] [INFO] Reactor Summary for Drools :: Parent 8.38.0-SNAPSHOT:<br/>[2023-04-11T14:21:06.634Z] [INFO] <br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Parent ................................... SUCCESS [  7.572 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Build Parent ............................. SUCCESS [  5.911 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] KIE :: Public API .................................. SUCCESS [  8.699 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] KIE :: Internal .................................... SUCCESS [  7.417 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] KIE :: Util ........................................ SUCCESS [  0.044 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] KIE :: Util :: XML supposrt ........................ SUCCESS [  2.055 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Util ..................................... SUCCESS [  3.733 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] KIE :: Memory Compiler ............................. SUCCESS [  3.890 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Wiring :: Parent ......................... SUCCESS [  0.042 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Wiring :: API ............................ SUCCESS [  3.417 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Wiring :: Static ......................... SUCCESS [  2.928 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: IO ....................................... SUCCESS [  2.872 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Core ..................................... SUCCESS [ 32.154 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: DRL AST .................................. SUCCESS [  3.926 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: DRL :: Parser ............................ SUCCESS [  6.753 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: DRL :: Extensions ........................ SUCCESS [  1.975 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Wiring :: Dynamic ........................ SUCCESS [  2.677 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: KieSession ............................... SUCCESS [  5.636 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: ECJ ...................................... SUCCESS [  5.139 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] KIE :: Util :: Maven Support ....................... SUCCESS [  2.314 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] KIE :: Test Utility Classes ........................ SUCCESS [  3.173 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Compiler ................................. SUCCESS [  9.243 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Truth Maintenance System ................. SUCCESS [  3.729 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: MVEL ..................................... SUCCESS [  9.184 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Reliability .............................. SUCCESS [ 20.027 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] KIE core BOM ....................................... SUCCESS [  0.006 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools BOM (Bill Of Materials) ..................... SUCCESS [  0.006 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Efesto BOM (Bill Of Materials) ..................... SUCCESS [  0.004 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Kie DMN BOM (Bill Of Materials) .................... SUCCESS [  0.004 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Kie PMML BOM (Bill Of Materials) ................... SUCCESS [  0.004 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Bom Parent ............................... SUCCESS [  0.004 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] KIE :: Util :: Maven Integration ................... SUCCESS [  3.690 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Rule Units :: Parent ..................... SUCCESS [  0.033 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Rule Units :: API ........................ SUCCESS [  2.090 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Model :: Parent .......................... SUCCESS [  0.030 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Codegen :: Common ........................ SUCCESS [  2.141 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Canonical Model .......................... SUCCESS [  6.928 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Model :: Compiler ........................ SUCCESS [  5.184 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: MVEL Parser .............................. SUCCESS [  7.389 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: MVEL Compiler ............................ SUCCESS [  9.431 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Commands ................................. SUCCESS [  4.979 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: XML Support .............................. SUCCESS [  4.742 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Templates ................................ SUCCESS [  5.056 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Decision Tables .......................... SUCCESS [ 12.079 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Model :: Codegen ......................... SUCCESS [01:30 min]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Rule Units :: Implementation ............. SUCCESS [  6.923 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Rule Units :: DSL ........................ SUCCESS [  4.566 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Rule Units :: Engine ..................... SUCCESS [  0.039 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Legacy Test Util ......................... SUCCESS [  2.186 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Beliefs .................................. SUCCESS [  5.023 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Serialization :: Protobuf ................ SUCCESS [ 17.366 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools Persistence projects ........................ SUCCESS [  0.028 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Persistence :: API ....................... SUCCESS [  2.202 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Persistence :: JPA ....................... SUCCESS [ 27.557 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Traits ................................... SUCCESS [ 29.316 s]<br/>[2023-04-11T14:21:06.634Z] [INFO] Drools :: Verifier ................................. SUCCESS [  0.025 s]<br/ [...]

2023-04-11 14:48 UTC, kie-ci3 commented
**(tests) - kogito-quarkus-examples job** `#441` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kogito-quarkus-examples/441/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-11T14:48:36.264Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-11T14:48:36.264Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-11T14:48:36.264Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-11T14:48:36.264Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-11T14:48:36.264Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-11T14:48:36.264Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-11T14:48:36.264Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-11T14:48:36.264Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-11T14:48:36.264Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-11T14:48:36.264Z] Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.drools:drools-bom:pom:8.37.0-SNAPSHOT<br/>[2023-04-11T14:48:36.264Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:415)<br/>[2023-04-11T14:48:36.264Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-04-11T14:48:36.264Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)<br/>[2023-04-11T14:48:36.264Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement (DefaultModelBuilder.java:1347)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:544)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-11T14:48:36.264Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-11T14:48:36.264Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-11T14:48:36.264Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-11T14:48:36.264Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-11T14:48:36.265Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-11T14:48:36.265Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-11T14:48:36.265Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-11T14:48:36.265Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-11T14:48:36.265Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-11T14:48:36.265Z] [ERROR]     'dependencies.dependency.version' for org.drools:drools-decisiontables:jar is missing. @ line 73, column 17<br/>[2023-04-11T14:48:36.265Z] [ERROR]   <br/>[2023-04-11T14:48:36.265Z] [ERROR]   The project org.kie.kogito.examples:kogito-travel-agency-example-basic:2.0.0-SNAPSHOT (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-quarkus-examples/bc/kiegroup_kogito-examples/kogito-quarkus-examples/kogito-travel-agency/basic/pom.xml) has 2 errors<br/>[2023-04-11T14:48:36.265Z] [ERROR]     Non-resolvable import POM: Could not find artifact org.drools:drools-bom:pom:8.37.0-SNAPSHOT @ line 41, column 19 -> [Help 2]<br/>[2023-04-11T14:48:36.265Z] org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact org.drools:drools-bom:pom:8.37.0-SNAPSHOT<br/>[2023-04-11T14:48:36.265Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:196)<br/>[2023-04-11T14:48:36.265Z]     at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement (DefaultModelBuilder.java:1347)<br/>[2023-04-11T14:48:36.265Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:544)<br/>[2023-04-11T14:48:36.265Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-11T14:48:36.265Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-11T14:48:36.265Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-11T14:48:36.265Z]     at org.apache.maven.proje [...]

2023-04-11 15:06 UTC, kie-ci3 commented
**(tests) - kogito-springboot-examples job** `#440` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kogito-springboot-examples/440/display/redirect

**Test results:**
- PASSED: 130
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-11T15:06:28.695Z] [INFO] Results:<br/>[2023-04-11T15:06:28.695Z] [INFO] <br/>[2023-04-11T15:06:28.695Z] [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0<br/>[2023-04-11T15:06:28.695Z] [INFO] <br/>[2023-04-11T15:06:28.695Z] [INFO] <br/>[2023-04-11T15:06:28.695Z] [INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ ruleunit-springboot-example ---<br/>[2023-04-11T15:06:28.695Z] [INFO] Building jar: /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example.jar<br/>[2023-04-11T15:06:28.695Z] [INFO] <br/>[2023-04-11T15:06:28.695Z] [INFO] --- maven-jar-plugin:3.1.0:test-jar (test-jar) @ ruleunit-springboot-example ---<br/>[2023-04-11T15:06:28.695Z] [INFO] Building jar: /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-tests.jar<br/>[2023-04-11T15:06:28.695Z] [INFO] <br/>[2023-04-11T15:06:28.695Z] [INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ ruleunit-springboot-example ---<br/>[2023-04-11T15:06:28.695Z] [INFO] Building jar: /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-sources.jar<br/>[2023-04-11T15:06:28.695Z] [INFO] <br/>[2023-04-11T15:06:28.695Z] [INFO] --- maven-source-plugin:3.0.1:test-jar-no-fork (attach-test-sources) @ ruleunit-springboot-example ---<br/>[2023-04-11T15:06:28.695Z] [INFO] Building jar: /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-test-sources.jar<br/>[2023-04-11T15:06:28.695Z] [INFO] <br/>[2023-04-11T15:06:28.695Z] [INFO] --- spring-boot-maven-plugin:2.6.6:repackage (default) @ ruleunit-springboot-example ---<br/>[2023-04-11T15:06:28.695Z] [INFO] Replacing main artifact with repackaged archive<br/>[2023-04-11T15:06:28.695Z] [INFO] <br/>[2023-04-11T15:06:28.695Z] [INFO] --- maven-resources-plugin:2.5:copy-resources (add-it-resources) @ ruleunit-springboot-example ---<br/>[2023-04-11T15:06:28.695Z] [debug] execute contextualize<br/>[2023-04-11T15:06:28.695Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-04-11T15:06:28.695Z] [INFO] Copying 2 resources<br/>[2023-04-11T15:06:28.695Z] [INFO] <br/>[2023-04-11T15:06:28.695Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (integration-test) @ ruleunit-springboot-example ---<br/>[2023-04-11T15:06:28.695Z] [INFO] <br/>[2023-04-11T15:06:28.695Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (default) @ ruleunit-springboot-example ---<br/>[2023-04-11T15:06:28.695Z] [INFO] Skipping execution of surefire because it has already been run for this configuration<br/>[2023-04-11T15:06:28.695Z] [INFO] <br/>[2023-04-11T15:06:28.695Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (integration-test) @ ruleunit-springboot-example ---<br/>[2023-04-11T15:06:28.695Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/failsafe-reports<br/>[2023-04-11T15:06:28.695Z] [INFO] <br/>[2023-04-11T15:06:28.695Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (default) @ ruleunit-springboot-example ---<br/>[2023-04-11T15:06:28.695Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/failsafe-reports<br/>[2023-04-11T15:06:28.695Z] [INFO] <br/>[2023-04-11T15:06:28.695Z] [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ ruleunit-springboot-example ---<br/>[2023-04-11T15:06:28.695Z] [INFO] Installing /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example.jar to /home/jenkins/.m2/repository/org/kie/kogito/examples/ruleunit-springboot-example/2.0.0-SNAPSHOT/ruleunit-springboot-example-2.0.0-SNAPSHOT.jar<br/>[2023-04-11T15:06:28.695Z] [INFO] Installing /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/pom.xml to /home/jenkins/.m2/repository/org/kie/kogito/examples/ruleunit-springboot-example/2.0.0-SNAPSHOT/ruleunit-springboot-example-2.0.0-SNAPSHOT.pom<br/>[2023-04-11T15:06:28.695Z] [INFO] Installing /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-tests.jar to /home/jenkins/.m2/repository/org/kie/kogito/examples/ruleunit-springboot-example/2.0.0-SNAPSHOT/ruleunit-springboot-example-2.0.0-SNAPSHOT-tests.jar<br/>[2023-04-11T15:06:28.696Z] [INFO] Installing /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-sources.jar to /home/jenkins/.m2/repository/org/kie/kogito/examples/ruleunit-springboot-example/2.0.0-SNAPSHOT/ruleunit-springboot-example-2.0.0-SNAPSHOT-sources.jar<br/>[2023-04-11T15:06:28.696Z] [INFO] Installing /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-test-sources.jar to /home/jenkins/.m2/repository/org/kie/kogito/examples/ruleunit-springboot-example/2.0.0-SNAPSHOT/ruleunit-springboot-example-2.0.0-SNAPSHOT-test-sources.jar<br/>[2023-04-11T15:06:28.696Z] [INFO] <br/>[2023-04-11T15:06:28.696Z] [INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ ruleunit-springboot-example ---<br/>[2023-04-11T15:06:28.696Z] [INFO] org.kie.kogito.examples:ruleunit-springboot-example:jar:2.0.0-SNAPSHOT<br/>[2023-04-11T15:06:28.696Z] [INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:2.6.6:compile<br/>[2023-04-11T15:06:28.696Z] [INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.6.6:compile<br/>[2023-04-11T15:06:28.696Z] [INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.6.6:compile<br/>[2023-04-11T15:06:28.696Z] [INFO] |  |  |  \- org.springframework:spring-context:jar:5.3.18:compile<br/>[2023-04-11T15:06:28.696Z] [INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.6.6:compile<br/>[2023-04-11T15:06:28.696Z] [INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.6.6:compile<br/>[2023-04-11T15:06:28.696Z] [INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.9:compile<br/>[2023-04-11T15:06:28.696Z] [INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.9:compile<br/>[2023-04-11T15:06:28.696Z] [INFO] |  |  |  +- org.apache.logging.log4j:log [...]

2023-04-11 15:12 UTC, kie-ci3 commented
**(quarkus-3) - drools job** `#48` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/48/display/redirect

**Test results:**
- PASSED: 21303
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-11T15:10:07.240Z] [INFO] |  |  \- org.apache.commons:commons-lang3:jar:3.12.0:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] |  +- org.apache.maven:maven-compat:jar:3.8.6:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] |  |  \- org.apache.maven.wagon:wagon-provider-api:jar:3.5.1:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] |  +- javax.inject:javax.inject:jar:1:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] |  +- commons-io:commons-io:jar:2.11.0:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] |  \- org.slf4j:jcl-over-slf4j:jar:1.7.30:runtime<br/>[2023-04-11T15:10:07.240Z] [INFO] +- org.kie:kie-ci:jar:sources:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] +- org.drools:drools-examples:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] |  +- org.drools:drools-traits:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] |  +- com.thoughtworks.xstream:xstream:jar:1.4.20:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] |  |  \- io.github.x-stream:mxparser:jar:1.2.2:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] |  |     \- xmlpull:xmlpull:jar:1.1.3.1:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] |  +- com.miglayout:miglayout:jar:3.7.4:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] |  +- ch.qos.logback:logback-classic:jar:1.2.9:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] |  |  \- ch.qos.logback:logback-core:jar:1.2.9:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] |  +- org.drools:drools-xml-support:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.14.2:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.14.2:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] |     \- com.fasterxml.jackson.core:jackson-core:jar:2.14.2:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] +- org.drools:drools-examples:jar:sources:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] +- org.kie:kie-api:jar:javadoc:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] \- org.kie:kie-internal:jar:javadoc:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:10:07.240Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-11T15:10:07.240Z] [INFO] Reactor Summary for Drools :: Parent 8.38.0-SNAPSHOT:<br/>[2023-04-11T15:10:07.240Z] [INFO] <br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Parent ................................... SUCCESS [  7.230 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Build Parent ............................. SUCCESS [  5.239 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] KIE :: Public API .................................. SUCCESS [  8.857 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] KIE :: Internal .................................... SUCCESS [  7.405 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] KIE :: Util ........................................ SUCCESS [  0.046 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] KIE :: Util :: XML supposrt ........................ SUCCESS [  1.854 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Util ..................................... SUCCESS [  3.606 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] KIE :: Memory Compiler ............................. SUCCESS [  3.761 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Wiring :: Parent ......................... SUCCESS [  0.053 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Wiring :: API ............................ SUCCESS [  3.082 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Wiring :: Static ......................... SUCCESS [  2.622 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: IO ....................................... SUCCESS [  2.184 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Core ..................................... SUCCESS [ 35.068 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: DRL AST .................................. SUCCESS [  3.765 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: DRL :: Parser ............................ SUCCESS [  6.275 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: DRL :: Extensions ........................ SUCCESS [  1.686 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Wiring :: Dynamic ........................ SUCCESS [  2.588 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: KieSession ............................... SUCCESS [  5.457 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: ECJ ...................................... SUCCESS [  5.317 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] KIE :: Util :: Maven Support ....................... SUCCESS [  1.756 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] KIE :: Test Utility Classes ........................ SUCCESS [  3.322 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Compiler ................................. SUCCESS [  9.037 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Truth Maintenance System ................. SUCCESS [  3.731 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: MVEL ..................................... SUCCESS [ 10.304 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Reliability .............................. SUCCESS [ 25.585 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] KIE core BOM ....................................... SUCCESS [  0.007 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools BOM (Bill Of Materials) ..................... SUCCESS [  0.007 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Efesto BOM (Bill Of Materials) ..................... SUCCESS [  0.006 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Kie DMN BOM (Bill Of Materials) .................... SUCCESS [  0.005 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Kie PMML BOM (Bill Of Materials) ................... SUCCESS [  0.006 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Bom Parent ............................... SUCCESS [  0.005 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] KIE :: Util :: Maven Integration ................... SUCCESS [  4.324 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Rule Units :: Parent ..................... SUCCESS [  0.030 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Rule Units :: API ........................ SUCCESS [  2.275 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Model :: Parent .......................... SUCCESS [  0.034 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Codegen :: Common ........................ SUCCESS [  2.268 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Canonical Model .......................... SUCCESS [  7.059 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Model :: Compiler ........................ SUCCESS [  5.121 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: MVEL Parser .............................. SUCCESS [  7.806 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: MVEL Compiler ............................ SUCCESS [  9.419 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Commands ................................. SUCCESS [  5.260 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: XML Support .............................. SUCCESS [  4.725 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Templates ................................ SUCCESS [  4.843 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Decision Tables .......................... SUCCESS [ 21.432 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Model :: Codegen ......................... SUCCESS [01:33 min]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Rule Units :: Implementation ............. SUCCESS [  7.101 s]<br/>[2023-04-11T15:10:07.240Z] [INFO] Drools :: Rule Units :: DSL .................. [...]

2023-04-11 15:14 UTC, kie-ci3 commented
**(tests) - serverless-workflow-examples job** `#442` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.serverless-workflow-examples/442/display/redirect

**Test results:**
- PASSED: 78
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-11T15:14:13.018Z] [INFO] |  |  +- org.kie.kogito:kogito-timer:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  \- org.kie.kogito:kogito-pmml-api-dependencies:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |     +- org.kie:kie-pmml-evaluator-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |     |  \- org.kie:kie-pmml-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |     |     \- org.apache.commons:commons-math3:jar:3.4.1:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |     \- org.kie:kie-pmml-commons:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |        \- org.apache.commons:commons-text:jar:1.10.0:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  +- org.kie.kogito:kogito-codegen-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  +- com.github.javaparser:javaparser-core:jar:3.24.2:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  \- org.drools:drools-codegen-common:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  +- org.kie.kogito:kogito-codegen-core:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  +- org.kie.kogito:kogito-events-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  \- org.drools:drools-io:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |     \- org.drools:drools-util:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  +- io.quarkus:quarkus-elytron-security-properties-file:jar:2.16.5.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  +- io.quarkus:quarkus-elytron-security:jar:2.16.5.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  \- io.quarkus:quarkus-elytron-security-common:jar:2.16.5.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  +- org.wildfly.security:wildfly-elytron-auth-server:jar:1.20.1.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-auth:jar:1.20.1.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-base:jar:1.20.1.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-credential:jar:1.20.1.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  |  +- org.wildfly.security:wildfly-elytron-asn1:jar:1.20.1.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  |  +- org.wildfly.security:wildfly-elytron-keystore:jar:1.20.1.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  |  |  \- org.wildfly.security:wildfly-elytron-x500-cert:jar:1.20.1.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  |  |     +- org.wildfly.security:wildfly-elytron-x500-cert-util:jar:1.20.1.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  |  |     \- org.apache.sshd:sshd-common:jar:2.9.2:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  |  \- org.wildfly.security:wildfly-elytron-provider-util:jar:1.20.1.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-permission:jar:1.20.1.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-util:jar:1.20.1.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  \- org.wildfly.security:wildfly-elytron-x500:jar:1.20.1.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  +- org.wildfly.security:wildfly-elytron-password-impl:jar:1.20.1.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  +- org.wildfly.security:wildfly-elytron-realm:jar:1.20.1.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  \- org.wildfly.security:wildfly-elytron-encryption:jar:1.20.1.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  +- io.quarkus:quarkus-security:jar:2.16.5.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  +- jakarta.security.jacc:jakarta.security.jacc-api:jar:1.6.1:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  \- jakarta.security.auth.message:jakarta.security.auth.message-api:jar:1.1.3:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  \- org.kie:efesto-dependencies:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |     +- org.kie:efesto-common-utils:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |     +- org.kie:efesto-common-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |     |  \- org.kie:kie-memory-compiler:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |     +- org.kie:efesto-common-core:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |     +- org.kie:efesto-compilation-manager-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |     +- org.kie:efesto-compilation-manager-core:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |     +- org.kie:efesto-runtime-manager-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |     +- org.kie:efesto-runtime-manager-core:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |     \- org.assertj:assertj-core:jar:3.23.1:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |        \- net.bytebuddy:byte-buddy:jar:1.12.18:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] +- io.quarkus:quarkus-webjars-locator:jar:2.16.5.Final:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] +- org.webjars:bootstrap:jar:5.1.3:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  \- org.webjars:popper.js:jar:2.9.3:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] +- org.webjars:jquery:jar:3.6.0:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] +- io.quarkus:quarkus-junit5:jar:2.16.5.Final:test<br/>[2023-04-11T15:14:13.018Z] [INFO] |  +- io.quarkus:quarkus-bootstrap-core:jar:2.16.5.Final:test<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-app-model:jar:2.16.5.Final:test<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  \- io.smallrye.common:smallrye-common-io:jar:1.13.2:compile<br/>[2023-04-11T15:14:13.018Z] [INFO] |  +- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.5:test<br/>[2023-04-11T15:14:13.018Z] [INFO] |  +- io.quarkus:quarkus-test-common:jar:2.16.5.Final:test<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  +- io.quarkus:quarkus-core-deployment:jar:2.16.5.Final:test<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  +- org.aesh:readline:jar:2.2:test<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  |  \- org.fusesource.jansi:jansi:jar:1.18:test<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  +- org.aesh:aesh:jar:2.7:test<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  +- org.ow2.asm:asm-commons:jar:9.4:test<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  +- io.quarkus:quarkus-class-change-agent:jar:2.16.5.Final:test<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  +- io.quarkus:quarkus-devtools-utilities:jar:2.16.5.Final:test<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  +- io.quarkus:quarkus-builder:jar:2.16.5.Final:test<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  \- org.junit.platform:junit-platform-launcher:jar:1.9.2:test<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-maven-resolver:jar:2.16.5.Final:test<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  +- org.apache.maven:maven-embedder:jar:3.8.6:test<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  |  +- org.apache.maven:maven-settings:jar:3.8.6:test<br/>[2023-04-11T15:14:13.018Z] [INFO] |  |  |  |  +- org.apache.maven:maven-core:jar:3.8.6:test<br/>[2023-04-11T15:14:13.018Z] [INFO] |   [...]

2023-04-12 08:24 UTC, kie-ci3 commented
**(tests) - kogito-quarkus-examples job** `#443` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kogito-quarkus-examples/443/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-12T08:24:35.683Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-12T08:24:35.683Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-12T08:24:35.683Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-12T08:24:35.683Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-12T08:24:35.683Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-12T08:24:35.683Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-12T08:24:35.683Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-12T08:24:35.683Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-12T08:24:35.683Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-12T08:24:35.683Z] Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.drools:drools-bom:pom:8.37.0-SNAPSHOT<br/>[2023-04-12T08:24:35.683Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:415)<br/>[2023-04-12T08:24:35.683Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-04-12T08:24:35.683Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)<br/>[2023-04-12T08:24:35.683Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement (DefaultModelBuilder.java:1347)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:544)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-12T08:24:35.683Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-12T08:24:35.683Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-12T08:24:35.683Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-12T08:24:35.683Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-12T08:24:35.683Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-12T08:24:35.683Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-12T08:24:35.683Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-12T08:24:35.683Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-12T08:24:35.683Z] [ERROR]     'dependencies.dependency.version' for org.drools:drools-decisiontables:jar is missing. @ line 73, column 17<br/>[2023-04-12T08:24:35.683Z] [ERROR]   <br/>[2023-04-12T08:24:35.683Z] [ERROR]   The project org.kie.kogito.examples:kogito-travel-agency-example-basic:2.0.0-SNAPSHOT (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-quarkus-examples/bc/kiegroup_kogito-examples/kogito-quarkus-examples/kogito-travel-agency/basic/pom.xml) has 2 errors<br/>[2023-04-12T08:24:35.683Z] [ERROR]     Non-resolvable import POM: Could not find artifact org.drools:drools-bom:pom:8.37.0-SNAPSHOT @ line 41, column 19 -> [Help 2]<br/>[2023-04-12T08:24:35.683Z] org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact org.drools:drools-bom:pom:8.37.0-SNAPSHOT<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:196)<br/>[2023-04-12T08:24:35.683Z]     at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement (DefaultModelBuilder.java:1347)<br/>[2023-04-12T08:24:35.684Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:544)<br/>[2023-04-12T08:24:35.684Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-12T08:24:35.684Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-12T08:24:35.684Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-12T08:24:35.684Z]     at org.apache.maven.proje [...]

2023-04-12 08:44 UTC, kie-ci3 commented
**(tests) - serverless-workflow-examples job** `#444` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.serverless-workflow-examples/444/display/redirect

**Test results:**
- PASSED: 78
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-12T08:44:49.986Z] [INFO] |  |  +- org.kie.kogito:kogito-timer:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  \- org.kie.kogito:kogito-pmml-api-dependencies:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |     +- org.kie:kie-pmml-evaluator-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |     |  \- org.kie:kie-pmml-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |     |     \- org.apache.commons:commons-math3:jar:3.4.1:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |     \- org.kie:kie-pmml-commons:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |        \- org.apache.commons:commons-text:jar:1.10.0:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  +- org.kie.kogito:kogito-codegen-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  +- com.github.javaparser:javaparser-core:jar:3.24.2:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  \- org.drools:drools-codegen-common:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  +- org.kie.kogito:kogito-codegen-core:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  +- org.kie.kogito:kogito-events-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  \- org.drools:drools-io:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |     \- org.drools:drools-util:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  +- io.quarkus:quarkus-elytron-security-properties-file:jar:2.16.5.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  +- io.quarkus:quarkus-elytron-security:jar:2.16.5.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  |  \- io.quarkus:quarkus-elytron-security-common:jar:2.16.5.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  +- org.wildfly.security:wildfly-elytron-auth-server:jar:1.20.1.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-auth:jar:1.20.1.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-base:jar:1.20.1.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-credential:jar:1.20.1.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  |  |  +- org.wildfly.security:wildfly-elytron-asn1:jar:1.20.1.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  |  |  +- org.wildfly.security:wildfly-elytron-keystore:jar:1.20.1.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  |  |  |  \- org.wildfly.security:wildfly-elytron-x500-cert:jar:1.20.1.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  |  |  |     +- org.wildfly.security:wildfly-elytron-x500-cert-util:jar:1.20.1.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  |  |  |     \- org.apache.sshd:sshd-common:jar:2.9.2:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  |  |  \- org.wildfly.security:wildfly-elytron-provider-util:jar:1.20.1.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-permission:jar:1.20.1.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-util:jar:1.20.1.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  |  \- org.wildfly.security:wildfly-elytron-x500:jar:1.20.1.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  +- org.wildfly.security:wildfly-elytron-password-impl:jar:1.20.1.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  +- org.wildfly.security:wildfly-elytron-realm:jar:1.20.1.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  |  \- org.wildfly.security:wildfly-elytron-encryption:jar:1.20.1.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  +- io.quarkus:quarkus-security:jar:2.16.5.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  +- jakarta.security.jacc:jakarta.security.jacc-api:jar:1.6.1:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  \- jakarta.security.auth.message:jakarta.security.auth.message-api:jar:1.1.3:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  \- org.kie:efesto-dependencies:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |     +- org.kie:efesto-common-utils:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |     +- org.kie:efesto-common-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |     |  \- org.kie:kie-memory-compiler:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |     +- org.kie:efesto-common-core:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |     +- org.kie:efesto-compilation-manager-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |     +- org.kie:efesto-compilation-manager-core:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |     +- org.kie:efesto-runtime-manager-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |     +- org.kie:efesto-runtime-manager-core:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |     \- org.assertj:assertj-core:jar:3.23.1:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |        \- net.bytebuddy:byte-buddy:jar:1.12.18:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] +- io.quarkus:quarkus-webjars-locator:jar:2.16.5.Final:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] +- org.webjars:bootstrap:jar:5.1.3:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  \- org.webjars:popper.js:jar:2.9.3:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] +- org.webjars:jquery:jar:3.6.0:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] +- io.quarkus:quarkus-junit5:jar:2.16.5.Final:test<br/>[2023-04-12T08:44:49.986Z] [INFO] |  +- io.quarkus:quarkus-bootstrap-core:jar:2.16.5.Final:test<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-app-model:jar:2.16.5.Final:test<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  \- io.smallrye.common:smallrye-common-io:jar:1.13.2:compile<br/>[2023-04-12T08:44:49.986Z] [INFO] |  +- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.5:test<br/>[2023-04-12T08:44:49.986Z] [INFO] |  +- io.quarkus:quarkus-test-common:jar:2.16.5.Final:test<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  +- io.quarkus:quarkus-core-deployment:jar:2.16.5.Final:test<br/>[2023-04-12T08:44:49.986Z] [INFO] |  |  |  +- org.aesh:readline:jar:2.2:test<br/>[2023-04-12T08:44:49.987Z] [INFO] |  |  |  |  \- org.fusesource.jansi:jansi:jar:1.18:test<br/>[2023-04-12T08:44:49.987Z] [INFO] |  |  |  +- org.aesh:aesh:jar:2.7:test<br/>[2023-04-12T08:44:49.987Z] [INFO] |  |  |  +- org.ow2.asm:asm-commons:jar:9.4:test<br/>[2023-04-12T08:44:49.987Z] [INFO] |  |  |  +- io.quarkus:quarkus-class-change-agent:jar:2.16.5.Final:test<br/>[2023-04-12T08:44:49.987Z] [INFO] |  |  |  +- io.quarkus:quarkus-devtools-utilities:jar:2.16.5.Final:test<br/>[2023-04-12T08:44:49.987Z] [INFO] |  |  |  +- io.quarkus:quarkus-builder:jar:2.16.5.Final:test<br/>[2023-04-12T08:44:49.987Z] [INFO] |  |  |  \- org.junit.platform:junit-platform-launcher:jar:1.9.2:test<br/>[2023-04-12T08:44:49.987Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-maven-resolver:jar:2.16.5.Final:test<br/>[2023-04-12T08:44:49.987Z] [INFO] |  |  |  +- org.apache.maven:maven-embedder:jar:3.8.6:test<br/>[2023-04-12T08:44:49.987Z] [INFO] |  |  |  |  +- org.apache.maven:maven-settings:jar:3.8.6:test<br/>[2023-04-12T08:44:49.987Z] [INFO] |  |  |  |  +- org.apache.maven:maven-core:jar:3.8.6:test<br/>[2023-04-12T08:44:49.987Z] [INFO] |   [...]

2023-04-12 08:46 UTC, kie-ci3 commented
**(tests) - kogito-springboot-examples job** `#442` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kogito-springboot-examples/442/display/redirect

**Test results:**
- PASSED: 130
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-12T08:46:46.968Z] [INFO] Results:<br/>[2023-04-12T08:46:46.968Z] [INFO] <br/>[2023-04-12T08:46:46.968Z] [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0<br/>[2023-04-12T08:46:46.968Z] [INFO] <br/>[2023-04-12T08:46:46.968Z] [INFO] <br/>[2023-04-12T08:46:46.968Z] [INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ ruleunit-springboot-example ---<br/>[2023-04-12T08:46:46.968Z] [INFO] Building jar: /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example.jar<br/>[2023-04-12T08:46:46.968Z] [INFO] <br/>[2023-04-12T08:46:46.968Z] [INFO] --- maven-jar-plugin:3.1.0:test-jar (test-jar) @ ruleunit-springboot-example ---<br/>[2023-04-12T08:46:46.968Z] [INFO] Building jar: /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-tests.jar<br/>[2023-04-12T08:46:46.968Z] [INFO] <br/>[2023-04-12T08:46:46.968Z] [INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ ruleunit-springboot-example ---<br/>[2023-04-12T08:46:46.968Z] [INFO] Building jar: /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-sources.jar<br/>[2023-04-12T08:46:46.968Z] [INFO] <br/>[2023-04-12T08:46:46.968Z] [INFO] --- maven-source-plugin:3.0.1:test-jar-no-fork (attach-test-sources) @ ruleunit-springboot-example ---<br/>[2023-04-12T08:46:46.968Z] [INFO] Building jar: /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-test-sources.jar<br/>[2023-04-12T08:46:46.968Z] [INFO] <br/>[2023-04-12T08:46:46.968Z] [INFO] --- spring-boot-maven-plugin:2.6.6:repackage (default) @ ruleunit-springboot-example ---<br/>[2023-04-12T08:46:46.968Z] [INFO] Replacing main artifact with repackaged archive<br/>[2023-04-12T08:46:46.968Z] [INFO] <br/>[2023-04-12T08:46:46.968Z] [INFO] --- maven-resources-plugin:2.5:copy-resources (add-it-resources) @ ruleunit-springboot-example ---<br/>[2023-04-12T08:46:46.968Z] [debug] execute contextualize<br/>[2023-04-12T08:46:46.968Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-04-12T08:46:46.968Z] [INFO] Copying 2 resources<br/>[2023-04-12T08:46:46.968Z] [INFO] <br/>[2023-04-12T08:46:46.968Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (integration-test) @ ruleunit-springboot-example ---<br/>[2023-04-12T08:46:46.968Z] [INFO] <br/>[2023-04-12T08:46:46.968Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (default) @ ruleunit-springboot-example ---<br/>[2023-04-12T08:46:46.968Z] [INFO] Skipping execution of surefire because it has already been run for this configuration<br/>[2023-04-12T08:46:46.968Z] [INFO] <br/>[2023-04-12T08:46:46.968Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (integration-test) @ ruleunit-springboot-example ---<br/>[2023-04-12T08:46:46.968Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/failsafe-reports<br/>[2023-04-12T08:46:46.968Z] [INFO] <br/>[2023-04-12T08:46:46.968Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (default) @ ruleunit-springboot-example ---<br/>[2023-04-12T08:46:46.968Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/failsafe-reports<br/>[2023-04-12T08:46:46.968Z] [INFO] <br/>[2023-04-12T08:46:46.968Z] [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ ruleunit-springboot-example ---<br/>[2023-04-12T08:46:46.968Z] [INFO] Installing /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example.jar to /home/jenkins/.m2/repository/org/kie/kogito/examples/ruleunit-springboot-example/2.0.0-SNAPSHOT/ruleunit-springboot-example-2.0.0-SNAPSHOT.jar<br/>[2023-04-12T08:46:46.968Z] [INFO] Installing /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/pom.xml to /home/jenkins/.m2/repository/org/kie/kogito/examples/ruleunit-springboot-example/2.0.0-SNAPSHOT/ruleunit-springboot-example-2.0.0-SNAPSHOT.pom<br/>[2023-04-12T08:46:46.968Z] [INFO] Installing /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-tests.jar to /home/jenkins/.m2/repository/org/kie/kogito/examples/ruleunit-springboot-example/2.0.0-SNAPSHOT/ruleunit-springboot-example-2.0.0-SNAPSHOT-tests.jar<br/>[2023-04-12T08:46:46.968Z] [INFO] Installing /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-sources.jar to /home/jenkins/.m2/repository/org/kie/kogito/examples/ruleunit-springboot-example/2.0.0-SNAPSHOT/ruleunit-springboot-example-2.0.0-SNAPSHOT-sources.jar<br/>[2023-04-12T08:46:46.968Z] [INFO] Installing /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-test-sources.jar to /home/jenkins/.m2/repository/org/kie/kogito/examples/ruleunit-springboot-example/2.0.0-SNAPSHOT/ruleunit-springboot-example-2.0.0-SNAPSHOT-test-sources.jar<br/>[2023-04-12T08:46:46.968Z] [INFO] <br/>[2023-04-12T08:46:46.968Z] [INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ ruleunit-springboot-example ---<br/>[2023-04-12T08:46:46.968Z] [INFO] org.kie.kogito.examples:ruleunit-springboot-example:jar:2.0.0-SNAPSHOT<br/>[2023-04-12T08:46:46.968Z] [INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:2.6.6:compile<br/>[2023-04-12T08:46:46.968Z] [INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.6.6:compile<br/>[2023-04-12T08:46:46.968Z] [INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.6.6:compile<br/>[2023-04-12T08:46:46.968Z] [INFO] |  |  |  \- org.springframework:spring-context:jar:5.3.18:compile<br/>[2023-04-12T08:46:46.968Z] [INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.6.6:compile<br/>[2023-04-12T08:46:46.968Z] [INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.6.6:compile<br/>[2023-04-12T08:46:46.968Z] [INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.9:compile<br/>[2023-04-12T08:46:46.968Z] [INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.9:compile<br/>[2023-04-12T08:46:46.968Z] [INFO] |  |  |  +- org.apache.logging.log4j:log [...]

2023-04-12 08:51 UTC, kie-ci3 commented
**(quarkus-3) - drools job** `#50` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/50/display/redirect

**Test results:**
- PASSED: 21304
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-12T08:48:48.903Z] [INFO] |  |  \- org.apache.commons:commons-lang3:jar:3.12.0:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] |  +- org.apache.maven:maven-compat:jar:3.8.6:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] |  |  \- org.apache.maven.wagon:wagon-provider-api:jar:3.5.1:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] |  +- javax.inject:javax.inject:jar:1:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] |  +- commons-io:commons-io:jar:2.11.0:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] |  \- org.slf4j:jcl-over-slf4j:jar:1.7.30:runtime<br/>[2023-04-12T08:48:48.903Z] [INFO] +- org.kie:kie-ci:jar:sources:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] +- org.drools:drools-examples:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] |  +- org.drools:drools-traits:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] |  +- com.thoughtworks.xstream:xstream:jar:1.4.20:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] |  |  \- io.github.x-stream:mxparser:jar:1.2.2:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] |  |     \- xmlpull:xmlpull:jar:1.1.3.1:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] |  +- com.miglayout:miglayout:jar:3.7.4:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] |  +- ch.qos.logback:logback-classic:jar:1.2.9:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] |  |  \- ch.qos.logback:logback-core:jar:1.2.9:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] |  +- org.drools:drools-xml-support:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.14.2:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.14.2:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] |     \- com.fasterxml.jackson.core:jackson-core:jar:2.14.2:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] +- org.drools:drools-examples:jar:sources:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] +- org.kie:kie-api:jar:javadoc:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] \- org.kie:kie-internal:jar:javadoc:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T08:48:48.903Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-12T08:48:48.903Z] [INFO] Reactor Summary for Drools :: Parent 8.38.0-SNAPSHOT:<br/>[2023-04-12T08:48:48.903Z] [INFO] <br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Parent ................................... SUCCESS [  6.772 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Build Parent ............................. SUCCESS [  5.260 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] KIE :: Public API .................................. SUCCESS [  8.680 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] KIE :: Internal .................................... SUCCESS [  7.134 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] KIE :: Util ........................................ SUCCESS [  0.041 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] KIE :: Util :: XML supposrt ........................ SUCCESS [  1.805 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Util ..................................... SUCCESS [  3.501 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] KIE :: Memory Compiler ............................. SUCCESS [  3.627 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Wiring :: Parent ......................... SUCCESS [  0.042 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Wiring :: API ............................ SUCCESS [  2.696 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Wiring :: Static ......................... SUCCESS [  2.413 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: IO ....................................... SUCCESS [  2.006 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Core ..................................... SUCCESS [ 34.877 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: DRL AST .................................. SUCCESS [  3.447 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: DRL :: Parser ............................ SUCCESS [  5.860 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: DRL :: Extensions ........................ SUCCESS [  1.590 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Wiring :: Dynamic ........................ SUCCESS [  2.460 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: KieSession ............................... SUCCESS [  5.088 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: ECJ ...................................... SUCCESS [  4.739 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] KIE :: Util :: Maven Support ....................... SUCCESS [  1.802 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] KIE :: Test Utility Classes ........................ SUCCESS [  3.027 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Compiler ................................. SUCCESS [  8.375 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Truth Maintenance System ................. SUCCESS [  3.568 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: MVEL ..................................... SUCCESS [  9.354 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Reliability .............................. SUCCESS [ 19.944 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] KIE core BOM ....................................... SUCCESS [  0.006 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools BOM (Bill Of Materials) ..................... SUCCESS [  0.005 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Efesto BOM (Bill Of Materials) ..................... SUCCESS [  0.005 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Kie DMN BOM (Bill Of Materials) .................... SUCCESS [  0.005 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Kie PMML BOM (Bill Of Materials) ................... SUCCESS [  0.005 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Bom Parent ............................... SUCCESS [  0.004 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] KIE :: Util :: Maven Integration ................... SUCCESS [  3.681 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Rule Units :: Parent ..................... SUCCESS [  0.027 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Rule Units :: API ........................ SUCCESS [  2.020 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Model :: Parent .......................... SUCCESS [  0.029 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Codegen :: Common ........................ SUCCESS [  1.939 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Canonical Model .......................... SUCCESS [  6.453 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Model :: Compiler ........................ SUCCESS [  4.725 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: MVEL Parser .............................. SUCCESS [  7.071 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: MVEL Compiler ............................ SUCCESS [  8.838 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Commands ................................. SUCCESS [  4.561 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: XML Support .............................. SUCCESS [  4.345 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Templates ................................ SUCCESS [  4.782 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Decision Tables .......................... SUCCESS [ 20.349 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Model :: Codegen ......................... SUCCESS [01:23 min]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Rule Units :: Implementation ............. SUCCESS [  6.183 s]<br/>[2023-04-12T08:48:48.903Z] [INFO] Drools :: Rule Units :: DSL .................. [...]

2023-04-14 09:06 UTC, kie-ci3 commented
**(quarkus-3) - drools job** `#56` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/56/display/redirect

**Test results:**
- PASSED: 21304
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-14T09:05:07.087Z] [INFO] |  |  \- org.apache.maven.wagon:wagon-provider-api:jar:3.5.1:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] |  +- javax.inject:javax.inject:jar:1:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] |  +- commons-io:commons-io:jar:2.11.0:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] |  \- org.slf4j:jcl-over-slf4j:jar:1.7.30:runtime<br/>[2023-04-14T09:05:07.087Z] [INFO] +- org.kie:kie-ci:jar:sources:8.38.0-SNAPSHOT:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] +- org.drools:drools-examples:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] |  +- org.drools:drools-traits:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] |  +- com.thoughtworks.xstream:xstream:jar:1.4.20:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] |  |  \- io.github.x-stream:mxparser:jar:1.2.2:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] |  |     \- xmlpull:xmlpull:jar:1.1.3.1:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] |  +- com.miglayout:miglayout:jar:3.7.4:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] |  +- ch.qos.logback:logback-classic:jar:1.2.9:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] |  |  \- ch.qos.logback:logback-core:jar:1.2.9:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] |  +- org.drools:drools-xml-support:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.14.2:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.14.2:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] |     \- com.fasterxml.jackson.core:jackson-core:jar:2.14.2:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] +- org.drools:drools-examples:jar:sources:8.38.0-SNAPSHOT:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] +- org.kie:kie-api:jar:javadoc:8.38.0-SNAPSHOT:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] \- org.kie:kie-internal:jar:javadoc:8.38.0-SNAPSHOT:compile<br/>[2023-04-14T09:05:07.087Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-14T09:05:07.087Z] [INFO] Reactor Summary for Drools :: Parent 8.38.0-SNAPSHOT:<br/>[2023-04-14T09:05:07.087Z] [INFO] <br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Parent ................................... SUCCESS [  7.839 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Build Parent ............................. SUCCESS [  5.426 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] KIE :: Public API .................................. SUCCESS [  8.240 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] KIE :: Internal .................................... SUCCESS [  7.233 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] KIE :: Util ........................................ SUCCESS [  0.044 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] KIE :: Util :: XML supposrt ........................ SUCCESS [  1.727 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Util ..................................... SUCCESS [  3.537 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] KIE :: Memory Compiler ............................. SUCCESS [  3.723 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Wiring :: Parent ......................... SUCCESS [  0.042 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Wiring :: API ............................ SUCCESS [  2.775 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Wiring :: Static ......................... SUCCESS [  2.398 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: IO ....................................... SUCCESS [  2.007 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Core ..................................... SUCCESS [ 32.273 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: DRL AST .................................. SUCCESS [  3.503 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: DRL :: Parser ............................ SUCCESS [  6.028 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: DRL :: Extensions ........................ SUCCESS [  1.717 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Wiring :: Dynamic ........................ SUCCESS [  2.605 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: KieSession ............................... SUCCESS [  5.461 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: ECJ ...................................... SUCCESS [  5.331 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] KIE :: Util :: Maven Support ....................... SUCCESS [  1.976 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] KIE :: Test Utility Classes ........................ SUCCESS [  3.385 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Compiler ................................. SUCCESS [  9.598 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Reliability .............................. SUCCESS [  0.041 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Reliability :: Core ...................... SUCCESS [  2.488 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Truth Maintenance System ................. SUCCESS [  3.832 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: MVEL ..................................... SUCCESS [  9.928 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Reliability :: Infinispan ................ SUCCESS [ 22.196 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] KIE core BOM ....................................... SUCCESS [  0.006 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools BOM (Bill Of Materials) ..................... SUCCESS [  0.006 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Efesto BOM (Bill Of Materials) ..................... SUCCESS [  0.004 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Kie DMN BOM (Bill Of Materials) .................... SUCCESS [  0.004 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Kie PMML BOM (Bill Of Materials) ................... SUCCESS [  0.004 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Bom Parent ............................... SUCCESS [  0.003 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] KIE :: Util :: Maven Integration ................... SUCCESS [  3.958 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Rule Units :: Parent ..................... SUCCESS [  0.029 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Rule Units :: API ........................ SUCCESS [  1.919 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Model :: Parent .......................... SUCCESS [  0.028 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Codegen :: Common ........................ SUCCESS [  1.971 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Canonical Model .......................... SUCCESS [  6.648 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Model :: Compiler ........................ SUCCESS [  4.987 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: MVEL Parser .............................. SUCCESS [  7.437 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: MVEL Compiler ............................ SUCCESS [  9.501 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Commands ................................. SUCCESS [  4.995 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: XML Support .............................. SUCCESS [  5.027 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Templates ................................ SUCCESS [  4.806 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Decision Tables .......................... SUCCESS [ 20.606 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Model :: Codegen ......................... SUCCESS [01:30 min]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Rule Units :: Implementation ............. SUCCESS [  6.856 s]<br/>[2023-04-14T09:05:07.087Z] [INFO] Drools :: Rule  [...]

2023-04-14 09:07 UTC, kie-ci3 commented
**(quarkus-3) - drools job** `#57` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/57/display/redirect

**Test results:**
- PASSED: 21304
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-14T09:05:36.600Z] [INFO] |  |  \- org.apache.maven.wagon:wagon-provider-api:jar:3.5.1:compile<br/>[2023-04-14T09:05:36.600Z] [INFO] |  +- javax.inject:javax.inject:jar:1:compile<br/>[2023-04-14T09:05:36.600Z] [INFO] |  +- commons-io:commons-io:jar:2.11.0:compile<br/>[2023-04-14T09:05:36.600Z] [INFO] |  \- org.slf4j:jcl-over-slf4j:jar:1.7.30:runtime<br/>[2023-04-14T09:05:36.600Z] [INFO] +- org.kie:kie-ci:jar:sources:8.38.0-SNAPSHOT:compile<br/>[2023-04-14T09:05:36.600Z] [INFO] +- org.drools:drools-examples:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-14T09:05:36.600Z] [INFO] |  +- org.drools:drools-traits:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-14T09:05:36.600Z] [INFO] |  +- com.thoughtworks.xstream:xstream:jar:1.4.20:compile<br/>[2023-04-14T09:05:36.600Z] [INFO] |  |  \- io.github.x-stream:mxparser:jar:1.2.2:compile<br/>[2023-04-14T09:05:36.600Z] [INFO] |  |     \- xmlpull:xmlpull:jar:1.1.3.1:compile<br/>[2023-04-14T09:05:36.600Z] [INFO] |  +- com.miglayout:miglayout:jar:3.7.4:compile<br/>[2023-04-14T09:05:36.601Z] [INFO] |  +- ch.qos.logback:logback-classic:jar:1.2.9:compile<br/>[2023-04-14T09:05:36.601Z] [INFO] |  |  \- ch.qos.logback:logback-core:jar:1.2.9:compile<br/>[2023-04-14T09:05:36.601Z] [INFO] |  +- org.drools:drools-xml-support:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-14T09:05:36.601Z] [INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.14.2:compile<br/>[2023-04-14T09:05:36.601Z] [INFO] |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.14.2:compile<br/>[2023-04-14T09:05:36.601Z] [INFO] |     \- com.fasterxml.jackson.core:jackson-core:jar:2.14.2:compile<br/>[2023-04-14T09:05:36.601Z] [INFO] +- org.drools:drools-examples:jar:sources:8.38.0-SNAPSHOT:compile<br/>[2023-04-14T09:05:36.601Z] [INFO] +- org.kie:kie-api:jar:javadoc:8.38.0-SNAPSHOT:compile<br/>[2023-04-14T09:05:36.601Z] [INFO] \- org.kie:kie-internal:jar:javadoc:8.38.0-SNAPSHOT:compile<br/>[2023-04-14T09:05:36.601Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-14T09:05:36.601Z] [INFO] Reactor Summary for Drools :: Parent 8.38.0-SNAPSHOT:<br/>[2023-04-14T09:05:36.601Z] [INFO] <br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Parent ................................... SUCCESS [  6.981 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Build Parent ............................. SUCCESS [  5.008 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] KIE :: Public API .................................. SUCCESS [  8.269 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] KIE :: Internal .................................... SUCCESS [  7.181 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] KIE :: Util ........................................ SUCCESS [  0.042 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] KIE :: Util :: XML supposrt ........................ SUCCESS [  1.732 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Util ..................................... SUCCESS [  3.368 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] KIE :: Memory Compiler ............................. SUCCESS [  3.470 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Wiring :: Parent ......................... SUCCESS [  0.040 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Wiring :: API ............................ SUCCESS [  2.628 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Wiring :: Static ......................... SUCCESS [  2.257 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: IO ....................................... SUCCESS [  1.944 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Core ..................................... SUCCESS [ 30.733 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: DRL AST .................................. SUCCESS [  3.494 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: DRL :: Parser ............................ SUCCESS [  6.156 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: DRL :: Extensions ........................ SUCCESS [  1.623 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Wiring :: Dynamic ........................ SUCCESS [  2.466 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: KieSession ............................... SUCCESS [  5.314 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: ECJ ...................................... SUCCESS [  4.890 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] KIE :: Util :: Maven Support ....................... SUCCESS [  1.672 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] KIE :: Test Utility Classes ........................ SUCCESS [  3.139 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Compiler ................................. SUCCESS [  8.677 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Reliability .............................. SUCCESS [  0.029 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Reliability :: Core ...................... SUCCESS [  2.301 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Truth Maintenance System ................. SUCCESS [  3.546 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: MVEL ..................................... SUCCESS [  9.857 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Reliability :: Infinispan ................ SUCCESS [ 21.694 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] KIE core BOM ....................................... SUCCESS [  0.006 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools BOM (Bill Of Materials) ..................... SUCCESS [  0.004 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Efesto BOM (Bill Of Materials) ..................... SUCCESS [  0.004 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Kie DMN BOM (Bill Of Materials) .................... SUCCESS [  0.004 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Kie PMML BOM (Bill Of Materials) ................... SUCCESS [  0.004 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Bom Parent ............................... SUCCESS [  0.004 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] KIE :: Util :: Maven Integration ................... SUCCESS [  3.491 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Rule Units :: Parent ..................... SUCCESS [  0.027 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Rule Units :: API ........................ SUCCESS [  1.785 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Model :: Parent .......................... SUCCESS [  0.028 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Codegen :: Common ........................ SUCCESS [  1.827 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Canonical Model .......................... SUCCESS [  6.357 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Model :: Compiler ........................ SUCCESS [  4.674 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: MVEL Parser .............................. SUCCESS [  6.952 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: MVEL Compiler ............................ SUCCESS [  8.680 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Commands ................................. SUCCESS [  4.569 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: XML Support .............................. SUCCESS [  4.260 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Templates ................................ SUCCESS [  4.489 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Decision Tables .......................... SUCCESS [ 20.092 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Model :: Codegen ......................... SUCCESS [01:23 min]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Rule Units :: Implementation ............. SUCCESS [  6.213 s]<br/>[2023-04-14T09:05:36.601Z] [INFO] Drools :: Rule  [...]

2023-04-14 12:21 UTC, kie-ci3 commented
**(quarkus-3) - drools job** `#58` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/58/display/redirect

**Test results:**
- PASSED: 2466
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-14T12:21:42.322Z] [INFO] Drools :: Templates ................................ SKIPPED<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools :: Decision Tables .......................... SKIPPED<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools :: Model :: Codegen ......................... SKIPPED<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools :: Rule Units :: Implementation ............. SKIPPED<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools :: Rule Units :: DSL ........................ SKIPPED<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools :: Rule Units :: Engine ..................... SKIPPED<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools :: Legacy Test Util ......................... SKIPPED<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools :: Beliefs .................................. SKIPPED<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools :: Serialization :: Protobuf ................ SKIPPED<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools Persistence projects ........................ SUCCESS [  0.054 s]<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools :: Persistence :: API ....................... SKIPPED<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools :: Persistence :: JPA ....................... SKIPPED<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools :: Traits ................................... SKIPPED<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools :: Verifier ................................. SUCCESS [  0.029 s]<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools Workbench - Verifier Api .................... SUCCESS [  1.990 s]<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools :: Verifier DRL ............................. SKIPPED<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools Workbench - Verifier Core ................... SUCCESS [  8.461 s]<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools examples .................................... SKIPPED<br/>[2023-04-14T12:21:42.322Z] [INFO] KIE :: CI .......................................... SKIPPED<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools :: Engine :: Classic ........................ SKIPPED<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools :: API examples ............................. SUCCESS [  0.024 s]<br/>[2023-04-14T12:21:42.322Z] [INFO] Drools :: API examples :: Default KieSession ....... SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: API examples :: Named KieSession ......... SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: API examples :: KieBase Inclusion ........ SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: API examples :: Default KieSession From File SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: API examples :: Named KieSession from File SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: API examples :: KieModule from Multiple Files SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: examples :: KieFileSystemExample ......... SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: API examples :: KieModuleModel Example ... SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: API examples :: KieContainer from KieRepo  SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: API examples :: Multiple KieBases ........ SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: API examples :: Reactive KieSession ...... SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Test Coverage ............................ SUCCESS [  0.024 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Test Coverage :: Standalone reproducers .. SUCCESS [  0.023 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Parent SUCCESS [  0.024 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Domain SUCCESS [  1.502 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: KJar SUCCESS [  0.042 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Tests SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Parent SUCCESS [  0.026 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Domain SUCCESS [  1.583 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: KJar SUCCESS [  0.049 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Tests SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Test Coverage :: Test Suite .............. SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Engine ................................... SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Alpha Network Compiler ................... SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Test Coverage :: Compiler integration tests SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Test Coverage :: Integration tests without mvel SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Test Coverage :: Integration tests without TMS SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Test Coverage :: Integration tests without xml SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Test Coverage :: Integration tests with Rule Units Parent SUCCESS [  0.028 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Test Coverage :: Jar for Integration tests with Rule Units SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Test Coverage :: Integration tests with Rule Units SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Scenario Simulation Parent ............... SUCCESS [  0.027 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Drools :: Scenario Simulation API .................. SUCCESS [  4.392 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] KIE :: Decision Model Notation ..................... SUCCESS [  0.026 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] KIE :: Decision Model Notation :: Model ............ SUCCESS [  6.032 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Efesto ............................................. SUCCESS [  1.700 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Efesto :: Core ..................................... SUCCESS [  0.035 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Efesto :: Common :: Api ............................ SUCCESS [  4.344 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] KIE :: Decision Model Notation :: API .............. SUCCESS [  2.424 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] KIE :: Decision Model Notation :: FEEL ............. SKIPPED<br/>[2023-04-14T12:21:42.323Z] [INFO] KIE :: Decision Model Notation :: Backend .......... SUCCESS [  8.357 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Efesto :: Compilation :: Manager ................... SUCCESS [  0.034 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Efesto :: Compilation :: Manager :: Api ............ SUCCESS [  3.171 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Efesto :: Common :: Core ........................... SUCCESS [  3.409 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Efesto :: Compilation :: Manager :: Core ........... SUCCESS [  4.046 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Efesto :: Runtime :: Manager ....................... SUCCESS [  0.031 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Efesto :: Runtime :: Manager :: Api ................ SUCCESS [  2.935 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Efesto :: Runtime :: Manager :: Core ............... SUCCESS [  4.004 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] Efesto :: Common :: Utils .......................... SUCCESS [  1.890 s]<br/>[2023-04-14T12:21:42.323Z] [INFO] KIE :: PMML ....................................... [...]

2023-04-14 12:36 UTC, kie-ci3 commented
**(quarkus-3) - drools job** `#59` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/59/display/redirect

**Test results:**
- PASSED: 2466
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-14T12:36:33.324Z] [INFO] Drools :: Templates ................................ SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Decision Tables .......................... SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Model :: Codegen ......................... SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Rule Units :: Implementation ............. SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Rule Units :: DSL ........................ SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Rule Units :: Engine ..................... SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Legacy Test Util ......................... SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Beliefs .................................. SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Serialization :: Protobuf ................ SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools Persistence projects ........................ SUCCESS [  0.027 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Persistence :: API ....................... SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Persistence :: JPA ....................... SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Traits ................................... SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Verifier ................................. SUCCESS [  0.026 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools Workbench - Verifier Api .................... SUCCESS [  2.036 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Verifier DRL ............................. SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools Workbench - Verifier Core ................... SUCCESS [  8.873 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools examples .................................... SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] KIE :: CI .......................................... SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Engine :: Classic ........................ SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: API examples ............................. SUCCESS [  0.027 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: API examples :: Default KieSession ....... SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: API examples :: Named KieSession ......... SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: API examples :: KieBase Inclusion ........ SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: API examples :: Default KieSession From File SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: API examples :: Named KieSession from File SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: API examples :: KieModule from Multiple Files SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: examples :: KieFileSystemExample ......... SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: API examples :: KieModuleModel Example ... SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: API examples :: KieContainer from KieRepo  SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: API examples :: Multiple KieBases ........ SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: API examples :: Reactive KieSession ...... SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Test Coverage ............................ SUCCESS [  0.027 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Test Coverage :: Standalone reproducers .. SUCCESS [  0.026 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Parent SUCCESS [  0.025 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Domain SUCCESS [  1.647 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: KJar SUCCESS [  0.050 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Tests SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Parent SUCCESS [  0.028 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Domain SUCCESS [  1.627 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: KJar SUCCESS [  0.045 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Tests SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Test Coverage :: Test Suite .............. SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Engine ................................... SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Alpha Network Compiler ................... SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Test Coverage :: Compiler integration tests SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Test Coverage :: Integration tests without mvel SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Test Coverage :: Integration tests without TMS SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Test Coverage :: Integration tests without xml SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Test Coverage :: Integration tests with Rule Units Parent SUCCESS [  0.024 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Test Coverage :: Jar for Integration tests with Rule Units SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Test Coverage :: Integration tests with Rule Units SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Scenario Simulation Parent ............... SUCCESS [  0.026 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Drools :: Scenario Simulation API .................. SUCCESS [  4.532 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] KIE :: Decision Model Notation ..................... SUCCESS [  0.029 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] KIE :: Decision Model Notation :: Model ............ SUCCESS [  5.631 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Efesto ............................................. SUCCESS [  1.671 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Efesto :: Core ..................................... SUCCESS [  0.034 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Efesto :: Common :: Api ............................ SUCCESS [  4.418 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] KIE :: Decision Model Notation :: API .............. SUCCESS [  2.399 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] KIE :: Decision Model Notation :: FEEL ............. SKIPPED<br/>[2023-04-14T12:36:33.324Z] [INFO] KIE :: Decision Model Notation :: Backend .......... SUCCESS [  8.444 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Efesto :: Compilation :: Manager ................... SUCCESS [  0.033 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Efesto :: Compilation :: Manager :: Api ............ SUCCESS [  3.024 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Efesto :: Common :: Core ........................... SUCCESS [  3.453 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Efesto :: Compilation :: Manager :: Core ........... SUCCESS [  4.239 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Efesto :: Runtime :: Manager ....................... SUCCESS [  0.037 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Efesto :: Runtime :: Manager :: Api ................ SUCCESS [  3.176 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Efesto :: Runtime :: Manager :: Core ............... SUCCESS [  4.119 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] Efesto :: Common :: Utils .......................... SUCCESS [  2.017 s]<br/>[2023-04-14T12:36:33.324Z] [INFO] KIE :: PMML ....................................... [...]

2023-04-14 13:55 UTC, kie-ci3 commented
**(quarkus-3) - drools job** `#60` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/60/display/redirect

**Test results:**
- PASSED: 21289
- FAILED: 15

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/60/testReport/org.drools.reliability.infinispan/CachePersistenceTest/ksessionDispose_shouldRemoveCache{Strategy}[1]/">org.drools.reliability.infinispan.CachePersistenceTest.ksessionDispose_shouldRemoveCache{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/60/testReport/org.drools.reliability.infinispan/CachePersistenceTest/removeAllSessionCaches_shouldRemoveAllSessionCachesEvenAfterFailover{Strategy}[1]/">org.drools.reliability.infinispan.CachePersistenceTest.removeAllSessionCaches_shouldRemoveAllSessionCachesEvenAfterFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/60/testReport/org.drools.reliability.infinispan/CachePersistenceTest/reliableSessionCounter_shouldNotHaveTheSameIdAsPreviousKsession{Strategy}[1]/">org.drools.reliability.infinispan.CachePersistenceTest.reliableSessionCounter_shouldNotHaveTheSameIdAsPreviousKsession{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/60/testReport/org.drools.reliability.infinispan/CachePersistenceTest/missingDispose_shouldNotReuseOrphanedCache{Strategy}[1]/">org.drools.reliability.infinispan.CachePersistenceTest.missingDispose_shouldNotReuseOrphanedCache{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/60/testReport/org.drools.reliability.infinispan/EmbeddedCacheManagerTest/removeAllSessionCaches_shouldLeaveNonSessionCache/">org.drools.reliability.infinispan.EmbeddedCacheManagerTest.removeAllSessionCaches_shouldLeaveNonSessionCache</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/60/testReport/org.drools.reliability.infinispan/EmbeddedCacheManagerTest/removeCachesBySessionId_shouldRemoveSpecifiedCacheOnly/">org.drools.reliability.infinispan.EmbeddedCacheManagerTest.removeCachesBySessionId_shouldRemoveSpecifiedCacheOnly</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/60/testReport/org.drools.reliability.infinispan/ReliabilityCepTest/insertAdvanceInsertFailoverFire_shouldRecoverFromFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityCepTest.insertAdvanceInsertFailoverFire_shouldRecoverFromFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/60/testReport/org.drools.reliability.infinispan/ReliabilityTest/createAndUseOfNonReliableSession_shouldWorkNormally/">org.drools.reliability.infinispan.ReliabilityTest.createAndUseOfNonReliableSession_shouldWorkNormally</a></summary>
org.drools.reliability.core.CacheManagerFactory: Provider org.drools.reliability.infinispan.InfinispanCacheManagerFactory could not be instantiated
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/60/testReport/org.drools.reliability.infinispan/ReliabilityTest/insertFireInsertFailoverInsertFire_shouldMatchFactInsertedBeforeFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.insertFireInsertFailoverInsertFire_shouldMatchFactInsertedBeforeFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/60/testReport/org.drools.reliability.infinispan/ReliabilityTest/deleteBeforeFailover_shouldRecoverFromFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.deleteBeforeFailover_shouldRecoverFromFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/60/testReport/org.drools.reliability.infinispan/ReliabilityTest/insertFireFailoverInsertFire_shouldNotRepeatFiredMatch{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.insertFireFailoverInsertFire_shouldNotRepeatFiredMatch{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/60/testReport/org.drools.reliability.infinispan/ReliabilityTest/insertFailoverInsertFire_shouldRecoverFromFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.insertFailoverInsertFire_shouldRecoverFromFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/60/testReport/org.drools.reliability.infinispan/ReliabilityTest/updateBeforeFailover_shouldRecoverFromFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.updateBeforeFailover_shouldRecoverFromFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/60/testReport/org.drools.reliability.infinispan/ReliabilityTest/updateByObjectBeforeFailover_shouldMatchUpdatedFact{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.updateByObjectBeforeFailover_shouldMatchUpdatedFact{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.cor [...]

2023-04-14 14:48 UTC, kie-ci3 commented
**(quarkus-3) - drools job** `#61` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/61/display/redirect

**Test results:**
- PASSED: 21289
- FAILED: 15

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/61/testReport/org.drools.reliability.infinispan/CachePersistenceTest/ksessionDispose_shouldRemoveCache{Strategy}[1]/">org.drools.reliability.infinispan.CachePersistenceTest.ksessionDispose_shouldRemoveCache{Strategy}[1]</a></summary>
org.drools.reliability.core.CacheManagerFactory: Provider org.drools.reliability.infinispan.InfinispanCacheManagerFactory could not be instantiated
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/61/testReport/org.drools.reliability.infinispan/CachePersistenceTest/removeAllSessionCaches_shouldRemoveAllSessionCachesEvenAfterFailover{Strategy}[1]/">org.drools.reliability.infinispan.CachePersistenceTest.removeAllSessionCaches_shouldRemoveAllSessionCachesEvenAfterFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/61/testReport/org.drools.reliability.infinispan/CachePersistenceTest/reliableSessionCounter_shouldNotHaveTheSameIdAsPreviousKsession{Strategy}[1]/">org.drools.reliability.infinispan.CachePersistenceTest.reliableSessionCounter_shouldNotHaveTheSameIdAsPreviousKsession{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/61/testReport/org.drools.reliability.infinispan/CachePersistenceTest/missingDispose_shouldNotReuseOrphanedCache{Strategy}[1]/">org.drools.reliability.infinispan.CachePersistenceTest.missingDispose_shouldNotReuseOrphanedCache{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/61/testReport/org.drools.reliability.infinispan/EmbeddedCacheManagerTest/removeAllSessionCaches_shouldLeaveNonSessionCache/">org.drools.reliability.infinispan.EmbeddedCacheManagerTest.removeAllSessionCaches_shouldLeaveNonSessionCache</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/61/testReport/org.drools.reliability.infinispan/EmbeddedCacheManagerTest/removeCachesBySessionId_shouldRemoveSpecifiedCacheOnly/">org.drools.reliability.infinispan.EmbeddedCacheManagerTest.removeCachesBySessionId_shouldRemoveSpecifiedCacheOnly</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/61/testReport/org.drools.reliability.infinispan/ReliabilityCepTest/insertAdvanceInsertFailoverFire_shouldRecoverFromFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityCepTest.insertAdvanceInsertFailoverFire_shouldRecoverFromFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/61/testReport/org.drools.reliability.infinispan/ReliabilityTest/createAndUseOfNonReliableSession_shouldWorkNormally/">org.drools.reliability.infinispan.ReliabilityTest.createAndUseOfNonReliableSession_shouldWorkNormally</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/61/testReport/org.drools.reliability.infinispan/ReliabilityTest/insertFireInsertFailoverInsertFire_shouldMatchFactInsertedBeforeFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.insertFireInsertFailoverInsertFire_shouldMatchFactInsertedBeforeFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/61/testReport/org.drools.reliability.infinispan/ReliabilityTest/deleteBeforeFailover_shouldRecoverFromFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.deleteBeforeFailover_shouldRecoverFromFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/61/testReport/org.drools.reliability.infinispan/ReliabilityTest/insertFireFailoverInsertFire_shouldNotRepeatFiredMatch{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.insertFireFailoverInsertFire_shouldNotRepeatFiredMatch{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/61/testReport/org.drools.reliability.infinispan/ReliabilityTest/insertFailoverInsertFire_shouldRecoverFromFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.insertFailoverInsertFire_shouldRecoverFromFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/61/testReport/org.drools.reliability.infinispan/ReliabilityTest/updateBeforeFailover_shouldRecoverFromFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.updateBeforeFailover_shouldRecoverFromFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/61/testReport/org.drools.reliability.infinispan/ReliabilityTest/updateByObjectBeforeFailover_shouldMatchUpdatedFact{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.updateByObjectBeforeFailover_shouldMatchUpdatedFact{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.cor [...]

2023-04-14 18:54 UTC, kie-ci3 commented
**(quarkus-3) - drools job** `#64` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/64/display/redirect

**Test results:**
- PASSED: 21289
- FAILED: 15

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/64/testReport/org.drools.reliability.infinispan/CachePersistenceTest/ksessionDispose_shouldRemoveCache{Strategy}[1]/">org.drools.reliability.infinispan.CachePersistenceTest.ksessionDispose_shouldRemoveCache{Strategy}[1]</a></summary>
org.drools.reliability.core.CacheManagerFactory: Provider org.drools.reliability.infinispan.InfinispanCacheManagerFactory could not be instantiated
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/64/testReport/org.drools.reliability.infinispan/CachePersistenceTest/removeAllSessionCaches_shouldRemoveAllSessionCachesEvenAfterFailover{Strategy}[1]/">org.drools.reliability.infinispan.CachePersistenceTest.removeAllSessionCaches_shouldRemoveAllSessionCachesEvenAfterFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/64/testReport/org.drools.reliability.infinispan/CachePersistenceTest/reliableSessionCounter_shouldNotHaveTheSameIdAsPreviousKsession{Strategy}[1]/">org.drools.reliability.infinispan.CachePersistenceTest.reliableSessionCounter_shouldNotHaveTheSameIdAsPreviousKsession{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/64/testReport/org.drools.reliability.infinispan/CachePersistenceTest/missingDispose_shouldNotReuseOrphanedCache{Strategy}[1]/">org.drools.reliability.infinispan.CachePersistenceTest.missingDispose_shouldNotReuseOrphanedCache{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/64/testReport/org.drools.reliability.infinispan/EmbeddedCacheManagerTest/removeAllSessionCaches_shouldLeaveNonSessionCache/">org.drools.reliability.infinispan.EmbeddedCacheManagerTest.removeAllSessionCaches_shouldLeaveNonSessionCache</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/64/testReport/org.drools.reliability.infinispan/EmbeddedCacheManagerTest/removeCachesBySessionId_shouldRemoveSpecifiedCacheOnly/">org.drools.reliability.infinispan.EmbeddedCacheManagerTest.removeCachesBySessionId_shouldRemoveSpecifiedCacheOnly</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/64/testReport/org.drools.reliability.infinispan/ReliabilityCepTest/insertAdvanceInsertFailoverFire_shouldRecoverFromFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityCepTest.insertAdvanceInsertFailoverFire_shouldRecoverFromFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/64/testReport/org.drools.reliability.infinispan/ReliabilityTest/createAndUseOfNonReliableSession_shouldWorkNormally/">org.drools.reliability.infinispan.ReliabilityTest.createAndUseOfNonReliableSession_shouldWorkNormally</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/64/testReport/org.drools.reliability.infinispan/ReliabilityTest/insertFireInsertFailoverInsertFire_shouldMatchFactInsertedBeforeFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.insertFireInsertFailoverInsertFire_shouldMatchFactInsertedBeforeFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/64/testReport/org.drools.reliability.infinispan/ReliabilityTest/deleteBeforeFailover_shouldRecoverFromFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.deleteBeforeFailover_shouldRecoverFromFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/64/testReport/org.drools.reliability.infinispan/ReliabilityTest/insertFireFailoverInsertFire_shouldNotRepeatFiredMatch{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.insertFireFailoverInsertFire_shouldNotRepeatFiredMatch{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/64/testReport/org.drools.reliability.infinispan/ReliabilityTest/insertFailoverInsertFire_shouldRecoverFromFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.insertFailoverInsertFire_shouldRecoverFromFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/64/testReport/org.drools.reliability.infinispan/ReliabilityTest/updateBeforeFailover_shouldRecoverFromFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.updateBeforeFailover_shouldRecoverFromFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/64/testReport/org.drools.reliability.infinispan/ReliabilityTest/updateByObjectBeforeFailover_shouldMatchUpdatedFact{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.updateByObjectBeforeFailover_shouldMatchUpdatedFact{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.cor [...]

2023-04-14 19:27 UTC, kie-ci3 commented
**(quarkus-3) - drools job** `#65` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/65/display/redirect

**Test results:**
- PASSED: 21289
- FAILED: 15

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/65/testReport/org.drools.reliability.infinispan/CachePersistenceTest/ksessionDispose_shouldRemoveCache{Strategy}[1]/">org.drools.reliability.infinispan.CachePersistenceTest.ksessionDispose_shouldRemoveCache{Strategy}[1]</a></summary>
org.drools.reliability.core.CacheManagerFactory: Provider org.drools.reliability.infinispan.InfinispanCacheManagerFactory could not be instantiated
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/65/testReport/org.drools.reliability.infinispan/CachePersistenceTest/removeAllSessionCaches_shouldRemoveAllSessionCachesEvenAfterFailover{Strategy}[1]/">org.drools.reliability.infinispan.CachePersistenceTest.removeAllSessionCaches_shouldRemoveAllSessionCachesEvenAfterFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/65/testReport/org.drools.reliability.infinispan/CachePersistenceTest/reliableSessionCounter_shouldNotHaveTheSameIdAsPreviousKsession{Strategy}[1]/">org.drools.reliability.infinispan.CachePersistenceTest.reliableSessionCounter_shouldNotHaveTheSameIdAsPreviousKsession{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/65/testReport/org.drools.reliability.infinispan/CachePersistenceTest/missingDispose_shouldNotReuseOrphanedCache{Strategy}[1]/">org.drools.reliability.infinispan.CachePersistenceTest.missingDispose_shouldNotReuseOrphanedCache{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/65/testReport/org.drools.reliability.infinispan/EmbeddedCacheManagerTest/removeAllSessionCaches_shouldLeaveNonSessionCache/">org.drools.reliability.infinispan.EmbeddedCacheManagerTest.removeAllSessionCaches_shouldLeaveNonSessionCache</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/65/testReport/org.drools.reliability.infinispan/EmbeddedCacheManagerTest/removeCachesBySessionId_shouldRemoveSpecifiedCacheOnly/">org.drools.reliability.infinispan.EmbeddedCacheManagerTest.removeCachesBySessionId_shouldRemoveSpecifiedCacheOnly</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/65/testReport/org.drools.reliability.infinispan/ReliabilityCepTest/insertAdvanceInsertFailoverFire_shouldRecoverFromFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityCepTest.insertAdvanceInsertFailoverFire_shouldRecoverFromFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/65/testReport/org.drools.reliability.infinispan/ReliabilityTest/createAndUseOfNonReliableSession_shouldWorkNormally/">org.drools.reliability.infinispan.ReliabilityTest.createAndUseOfNonReliableSession_shouldWorkNormally</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/65/testReport/org.drools.reliability.infinispan/ReliabilityTest/insertFireInsertFailoverInsertFire_shouldMatchFactInsertedBeforeFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.insertFireInsertFailoverInsertFire_shouldMatchFactInsertedBeforeFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/65/testReport/org.drools.reliability.infinispan/ReliabilityTest/deleteBeforeFailover_shouldRecoverFromFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.deleteBeforeFailover_shouldRecoverFromFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/65/testReport/org.drools.reliability.infinispan/ReliabilityTest/insertFireFailoverInsertFire_shouldNotRepeatFiredMatch{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.insertFireFailoverInsertFire_shouldNotRepeatFiredMatch{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/65/testReport/org.drools.reliability.infinispan/ReliabilityTest/insertFailoverInsertFire_shouldRecoverFromFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.insertFailoverInsertFire_shouldRecoverFromFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/65/testReport/org.drools.reliability.infinispan/ReliabilityTest/updateBeforeFailover_shouldRecoverFromFailover{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.updateBeforeFailover_shouldRecoverFromFailover{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.core.CacheManagerFactory$Holder
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest.quarkus-3/job/drools.quarkus-3.drools/65/testReport/org.drools.reliability.infinispan/ReliabilityTest/updateByObjectBeforeFailover_shouldMatchUpdatedFact{Strategy}[1]/">org.drools.reliability.infinispan.ReliabilityTest.updateByObjectBeforeFailover_shouldMatchUpdatedFact{Strategy}[1]</a></summary>
Could not initialize class org.drools.reliability.cor [...]

2023-04-17 07:36 UTC, radtriste commented
Issue in Infinispan tests due to https://issues.redhat.com/browse/ISPN-14512
Added patch https://github.com/kiegroup/drools/pull/5153/commits/18ef47f90bcae29957dedcc42fdc11c2af8fcdaa

2023-04-17 08:48 UTC, gitgabrio approved these changes
Thanks @radtriste LGTM

2023-04-17 10:01 UTC, mariofusco approved these changes

2023-04-17 12:21 UTC, merged