[kie-issues#273] Remove use of Drools 5.5.0.Final from kie-ci tests
apache/incubator-kie pull request #5240
Opened 2023-05-19 14:41 UTC by baldimir

Fixes https://github.com/kiegroup/kie-issues/issues/273

In kie-ci tests there was old drools-core 5.5.0.Final used on various places. This PR removes the uses and replaces them with usage of custom jars that are built for test purposes during the kie-ci build, using the Maven invoker plugin (therefore are not directly part of the main reactor build). 

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

 - for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native-lts</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

2023-05-19 14:44 UTC, baldimir commented
I am sorry for the formatting changes in one of the changed files. If someone will need that reverted, please let me know.

2023-05-19 15:42 UTC, kie-ci4 commented
**(tests) - drools job** `#1371` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dfull -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/drools -u https://github.com/kiegroup/drools/pull/5240 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1371/display/redirect

**Test results:**
- PASSED: 21433
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1371/testReport/org.kie.scanner/KieModuleMetaDataTest/testKieModuleMetaDataForDependenciesInMemory/">org.kie.scanner.KieModuleMetaDataTest.testKieModuleMetaDataForDependenciesInMemory</a></summary>
expected:<[2]> but was:<[3]>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1371/testReport/org.kie.scanner/KieModuleMetaDataTest/testKieModuleMetaData/">org.kie.scanner.KieModuleMetaDataTest.testKieModuleMetaData</a></summary>
expected:<[2]> but was:<[3]>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1371/testReport/org.kie.scanner/KieModuleMetaDataTest/testKieModuleMetaDataWithoutTestDependencies/">org.kie.scanner.KieModuleMetaDataTest.testKieModuleMetaDataWithoutTestDependencies</a></summary>
expected:<[2]> but was:<[3]>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1371/testReport/org.kie.scanner/KieModuleMetaDataTest/testKieModuleMetaDataInMemoryWithTypeDeclaration/">org.kie.scanner.KieModuleMetaDataTest.testKieModuleMetaDataInMemoryWithTypeDeclaration</a></summary>
expected:<[2]> but was:<[3]>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1371/testReport/org.kie.scanner/KieModuleMetaDataTest/testKieModuleMetaDataInMemoryWithJavaClass/">org.kie.scanner.KieModuleMetaDataTest.testKieModuleMetaDataInMemoryWithJavaClass</a></summary>
expected:<[2]> but was:<[3]>
</details>

2023-05-19 15:43 UTC, kie-ci4 commented
**(tests) - drools job** `#1372` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dfull -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/drools -u https://github.com/kiegroup/drools/pull/5240 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1372/display/redirect

**Test results:**
- PASSED: 21433
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1372/testReport/org.kie.scanner/KieModuleMetaDataTest/testKieModuleMetaDataForDependenciesInMemory/">org.kie.scanner.KieModuleMetaDataTest.testKieModuleMetaDataForDependenciesInMemory</a></summary>
expected:<[2]> but was:<[3]>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1372/testReport/org.kie.scanner/KieModuleMetaDataTest/testKieModuleMetaData/">org.kie.scanner.KieModuleMetaDataTest.testKieModuleMetaData</a></summary>
expected:<[2]> but was:<[3]>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1372/testReport/org.kie.scanner/KieModuleMetaDataTest/testKieModuleMetaDataWithoutTestDependencies/">org.kie.scanner.KieModuleMetaDataTest.testKieModuleMetaDataWithoutTestDependencies</a></summary>
expected:<[2]> but was:<[3]>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1372/testReport/org.kie.scanner/KieModuleMetaDataTest/testKieModuleMetaDataInMemoryWithTypeDeclaration/">org.kie.scanner.KieModuleMetaDataTest.testKieModuleMetaDataInMemoryWithTypeDeclaration</a></summary>
expected:<[2]> but was:<[3]>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1372/testReport/org.kie.scanner/KieModuleMetaDataTest/testKieModuleMetaDataInMemoryWithJavaClass/">org.kie.scanner.KieModuleMetaDataTest.testKieModuleMetaDataInMemoryWithJavaClass</a></summary>
expected:<[2]> but was:<[3]>
</details>

2023-05-19 15:52 UTC, kie-ci4 commented
**(tests) - drools job** `#1373` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dfull -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/drools -u https://github.com/kiegroup/drools/pull/5240 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1373/display/redirect

**Test results:**
- PASSED: 21433
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1373/testReport/org.kie.scanner/KieModuleMetaDataTest/testKieModuleMetaDataForDependenciesInMemory/">org.kie.scanner.KieModuleMetaDataTest.testKieModuleMetaDataForDependenciesInMemory</a></summary>
expected:<[2]> but was:<[3]>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1373/testReport/org.kie.scanner/KieModuleMetaDataTest/testKieModuleMetaData/">org.kie.scanner.KieModuleMetaDataTest.testKieModuleMetaData</a></summary>
expected:<[2]> but was:<[3]>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1373/testReport/org.kie.scanner/KieModuleMetaDataTest/testKieModuleMetaDataWithoutTestDependencies/">org.kie.scanner.KieModuleMetaDataTest.testKieModuleMetaDataWithoutTestDependencies</a></summary>
expected:<[2]> but was:<[3]>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1373/testReport/org.kie.scanner/KieModuleMetaDataTest/testKieModuleMetaDataInMemoryWithTypeDeclaration/">org.kie.scanner.KieModuleMetaDataTest.testKieModuleMetaDataInMemoryWithTypeDeclaration</a></summary>
expected:<[2]> but was:<[3]>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1373/testReport/org.kie.scanner/KieModuleMetaDataTest/testKieModuleMetaDataInMemoryWithJavaClass/">org.kie.scanner.KieModuleMetaDataTest.testKieModuleMetaDataInMemoryWithJavaClass</a></summary>
expected:<[2]> but was:<[3]>
</details>

2023-05-22 06:26 UTC, baldimir commented
Tests were passing for me locally. Will check what is causing the problems in teh CI checks. Moving to Draft.

2023-05-22 07:26 UTC, mareknovotny commented on kie-ci/src/test/java/org/kie/scanner/KieModuleMetaDataTest.java
> +                "        <version>4.11</version>\n" +
we already uses newer version of junit, even this is a test we could get what we have in build parent? https://github.com/kiegroup/drools/blob/main/build-parent/pom.xml#L62

2023-05-22 07:28 UTC, mareknovotny commented on kie-ci/src/test/java/org/kie/scanner/KieModuleMetaDataTest.java
> +                "        <version>4.11</version>\n" +
btw in different file you already hardcoded newer version anyway https://github.com/kiegroup/drools/pull/5240/files#diff-cc8e166aa92398460e8cd3b47a52e5fe3bc72454b3e4dbfb131dfef7f064339dR30

2023-05-22 07:28 UTC, mareknovotny requested changes
please unify also junit versions in test pom files

2023-05-22 07:29 UTC, baldimir commented on kie-ci/src/test/java/org/kie/scanner/KieModuleMetaDataTest.java
> +                "        <version>4.11</version>\n" +
I will change it so the version is taken from the property.

2023-05-22 08:18 UTC, baldimir commented on kie-ci/src/test/java/org/kie/scanner/KieModuleMetaDataTest.java
> +                "        <version>4.11</version>\n" +
Fixed the version in the class. Now it is aligned with what is in the build-parent pom. Unfortunately same doesn't work in the test kjar. Looks like KieScanner doesn't handle well when there is a version property so I had to leave the hardcoded one there (but aligned with the version in the build-parent bom).

2023-05-22 08:21 UTC, kie-ci4 commented
**(tests) - kogito-springboot-examples job** `#589` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/drools/pull/5240 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kogito-springboot-examples/589/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-22T08:21:45.583Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-22T08:21:45.583Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-22T08:21:45.583Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-22T08:21:45.583Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-22T08:21:45.583Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-22T08:21:45.583Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-22T08:21:45.583Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-22T08:21:45.583Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-22T08:21:45.583Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-22T08:21:45.583Z] [ERROR]   <br/>[2023-05-22T08:21:45.583Z] [ERROR]   The project org.kie.kogito.examples:kogito-examples:2.0.0-SNAPSHOT (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/pom.xml) has 1 error<br/>[2023-05-22T08:21:45.583Z] [ERROR]     Non-resolvable parent POM for org.kie.kogito.examples:kogito-examples:2.0.0-SNAPSHOT: Could not find artifact org.kie.kogito:kogito-build-no-bom-parent:pom:2.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 7, column 11 -> [Help 2]<br/>[2023-05-22T08:21:45.583Z] org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact org.kie.kogito:kogito-build-no-bom-parent:pom:2.0.0-SNAPSHOT<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:196)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:242)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally (DefaultModelBuilder.java:1150)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParent (DefaultModelBuilder.java:916)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:361)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:267)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:448)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:414)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:377)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-22T08:21:45.583Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-22T08:21:45.583Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-22T08:21:45.583Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-22T08:21:45.583Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-22T08:21:45.583Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-22T08:21:45.583Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-22T08:21:45.583Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-22T08:21:45.583Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-22T08:21:45.583Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.kie.kogito:kogito-build-no-bom-parent:pom:2.0.0-SNAPSHOT<br/>[2023-05-22T08:21:45.583Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:425)<br/>[2023-05-22T08:21:45.583Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-05-22T08:21:45.583Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)<br/>[2023-05-22T08:21:45.583Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:242)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally (DefaultModelBuilder.java:1150)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParent (DefaultModelBuilder.java:916)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:361)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:267)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:448)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:414)<br/>[2023-05-22T08:21:45.583Z]     at org.apache.maven.project.DefaultProjectBuilder.bui [...]

2023-05-22 08:21 UTC, kie-ci4 commented
**(tests) - kogito-quarkus-examples job** `#591` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/drools/pull/5240 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kogito-quarkus-examples/591/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-22T08:21:45.561Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-22T08:21:45.561Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-22T08:21:45.561Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-22T08:21:45.561Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-22T08:21:45.561Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-22T08:21:45.561Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-22T08:21:45.561Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-22T08:21:45.561Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-22T08:21:45.561Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-22T08:21:45.561Z] [ERROR]   <br/>[2023-05-22T08:21:45.561Z] [ERROR]   The project org.kie.kogito.examples:kogito-examples:2.0.0-SNAPSHOT (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-quarkus-examples/bc/kiegroup_kogito-examples/pom.xml) has 1 error<br/>[2023-05-22T08:21:45.561Z] [ERROR]     Non-resolvable parent POM for org.kie.kogito.examples:kogito-examples:2.0.0-SNAPSHOT: Could not find artifact org.kie.kogito:kogito-build-no-bom-parent:pom:2.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 7, column 11 -> [Help 2]<br/>[2023-05-22T08:21:45.561Z] org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact org.kie.kogito:kogito-build-no-bom-parent:pom:2.0.0-SNAPSHOT<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:196)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:242)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally (DefaultModelBuilder.java:1150)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParent (DefaultModelBuilder.java:916)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:361)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:267)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:448)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:414)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:377)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-22T08:21:45.561Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-22T08:21:45.561Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-22T08:21:45.561Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-22T08:21:45.561Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-22T08:21:45.561Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-22T08:21:45.561Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-22T08:21:45.561Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-22T08:21:45.561Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-22T08:21:45.562Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-22T08:21:45.562Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.kie.kogito:kogito-build-no-bom-parent:pom:2.0.0-SNAPSHOT<br/>[2023-05-22T08:21:45.562Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:425)<br/>[2023-05-22T08:21:45.562Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-05-22T08:21:45.562Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)<br/>[2023-05-22T08:21:45.562Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)<br/>[2023-05-22T08:21:45.562Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)<br/>[2023-05-22T08:21:45.562Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:242)<br/>[2023-05-22T08:21:45.562Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally (DefaultModelBuilder.java:1150)<br/>[2023-05-22T08:21:45.562Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParent (DefaultModelBuilder.java:916)<br/>[2023-05-22T08:21:45.562Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:361)<br/>[2023-05-22T08:21:45.562Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:267)<br/>[2023-05-22T08:21:45.562Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:448)<br/>[2023-05-22T08:21:45.562Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:414)<br/>[2023-05-22T08:21:45.562Z]     at org.apache.maven.project.DefaultProjectBuilder.build (Defau [...]

2023-05-22 08:22 UTC, kie-ci4 commented
**(tests) - serverless-workflow-examples job** `#591` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/drools/pull/5240 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.serverless-workflow-examples/591/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-22T08:22:05.222Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-22T08:22:05.222Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-22T08:22:05.222Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-22T08:22:05.222Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-22T08:22:05.222Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-22T08:22:05.222Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-22T08:22:05.222Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-22T08:22:05.222Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-22T08:22:05.222Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-22T08:22:05.222Z] [ERROR]   <br/>[2023-05-22T08:22:05.222Z] [ERROR]   The project org.kie.kogito.examples:kogito-examples:2.0.0-SNAPSHOT (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.serverless-workflow-examples/bc/kiegroup_kogito-examples/pom.xml) has 1 error<br/>[2023-05-22T08:22:05.222Z] [ERROR]     Non-resolvable parent POM for org.kie.kogito.examples:kogito-examples:2.0.0-SNAPSHOT: Could not find artifact org.kie.kogito:kogito-build-no-bom-parent:pom:2.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 7, column 11 -> [Help 2]<br/>[2023-05-22T08:22:05.222Z] org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact org.kie.kogito:kogito-build-no-bom-parent:pom:2.0.0-SNAPSHOT<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:196)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:242)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally (DefaultModelBuilder.java:1150)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParent (DefaultModelBuilder.java:916)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:361)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:267)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:448)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:414)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:377)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-22T08:22:05.222Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-22T08:22:05.222Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-22T08:22:05.222Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-22T08:22:05.222Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-22T08:22:05.222Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-22T08:22:05.222Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-22T08:22:05.222Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-22T08:22:05.222Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-22T08:22:05.222Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.kie.kogito:kogito-build-no-bom-parent:pom:2.0.0-SNAPSHOT<br/>[2023-05-22T08:22:05.222Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:425)<br/>[2023-05-22T08:22:05.222Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-05-22T08:22:05.222Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)<br/>[2023-05-22T08:22:05.222Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:242)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally (DefaultModelBuilder.java:1150)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParent (DefaultModelBuilder.java:916)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:361)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:267)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:448)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:414)<br/>[2023-05-22T08:22:05.222Z]     at org.apache.maven.project.DefaultProjectBuild [...]

2023-05-22 08:22 UTC, kie-ci4 commented
**(tests) - kogito-apps job** `#1353` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/drools/pull/5240 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kogito-apps/1353/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-22T08:22:31.083Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-22T08:22:31.083Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-22T08:22:31.083Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-22T08:22:31.083Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-22T08:22:31.083Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-22T08:22:31.083Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-22T08:22:31.083Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-22T08:22:31.083Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-22T08:22:31.083Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-22T08:22:31.083Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.kie:kie-pmml-bom:pom:8.39.0-SNAPSHOT<br/>[2023-05-22T08:22:31.083Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:425)<br/>[2023-05-22T08:22:31.083Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-05-22T08:22:31.083Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)<br/>[2023-05-22T08:22:31.083Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement (DefaultModelBuilder.java:1347)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:544)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:454)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement (DefaultModelBuilder.java:1381)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:544)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-22T08:22:31.083Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-22T08:22:31.083Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-22T08:22:31.083Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-22T08:22:31.083Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-22T08:22:31.083Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-22T08:22:31.083Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-22T08:22:31.083Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-22T08:22:31.083Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-22T08:22:31.083Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-22T08:22:31.083Z] Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.kie:kie-pmml-bom:pom:8.39.0-SNAPSHOT<br/>[2023-05-22T08:22:31.083Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:415)<br/>[2023-05-22T08:22:31.083Z]     at org.eclipse.aether.internal.im [...]

2023-05-22 08:22 UTC, kie-ci4 commented
**(tests) - kogito-runtimes job** `#1339` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/kogito-runtimes -u https://github.com/kiegroup/drools/pull/5240 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kogito-runtimes/1339/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-22T08:22:32.150Z] Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.kie:kie-pmml-bom:pom:8.39.0-SNAPSHOT<br/>[2023-05-22T08:22:32.150Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:415)<br/>[2023-05-22T08:22:32.150Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-05-22T08:22:32.150Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)<br/>[2023-05-22T08:22:32.150Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)<br/>[2023-05-22T08:22:32.150Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)<br/>[2023-05-22T08:22:32.150Z]     at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement (DefaultModelBuilder.java:1347)<br/>[2023-05-22T08:22:32.150Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:544)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:454)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement (DefaultModelBuilder.java:1381)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:544)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-22T08:22:32.151Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-22T08:22:32.151Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-22T08:22:32.151Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-22T08:22:32.151Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-22T08:22:32.151Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-22T08:22:32.151Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-22T08:22:32.151Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-22T08:22:32.151Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-22T08:22:32.151Z] [ERROR]     'dependencies.dependency.version' for org.drools:drools-model-compiler:jar is missing. @ line 123, column 17<br/>[2023-05-22T08:22:32.151Z] [ERROR]     'dependencies.dependency.version' for org.drools:drools-decisiontables:jar is missing. @ line 147, column 17<br/>[2023-05-22T08:22:32.151Z] [ERROR]   <br/>[2023-05-22T08:22:32.151Z] [ERROR]   The project org.kie.kogito:kogito-addons-springboot-messaging-it:2.0.0-SNAPSHOT (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_kogito-runtimes/springboot/addons/messaging/integration-tests/pom.xml) has 4 errors<br/>[2023-05-22T08:22:32.151Z] [ERROR]     Non-resolvable import POM: Could not find artifact org.kie:kie-pmml-bom:pom:8.39.0-SNAPSHOT @ org.kie.kogito:kogito-kie-bom:2.0.0-SNAPSHOT, /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-runtimes/bc/kiegroup_kogito-runtimes/kogito-build/kogito-kie-bom/pom.xml, line 47, column 19 -> [Help 2]<br/>[2023-05-22T08:22:32.151Z] org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact org.kie:kie-pmml-bom:pom:8.39.0-SNAPSHOT<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:196)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement (DefaultModelBuilder.java:1347)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:544)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:454)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement (DefaultModelBuilder.java:1381)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:544)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-05-22T08:22:32.151Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphB [...]

2023-05-22 11:48 UTC, baldimir commented
The failures look unrelated. I did only tests changes in kie-ci so those shouldn't affect those failing checks. All three Drools builds are green.

2023-05-24 07:51 UTC, mareknovotny approved these changes

2023-05-26 10:15 UTC, mariofusco approved these changes

2023-05-30 12:46 UTC, gitgabrio commented
@kiegroup/gatekeepers

Could you please merge this, squashing commits? Thanks!

2023-05-30 14:07 UTC, merged