[kie-issues#339] Fix Blocker and Critical Bugs reported by Sonar
apache/incubator-kie pull request #5303
Opened 2023-06-13 14:26 UTC by baldimir

Fixes https://github.com/kiegroup/kie-issues/issues/339

Fixes Blocker and Critical things reported by Sonar: 
- BayesInstance: Fixed unsafe Random instance. 
- ConfFileUtils: Close stream with try-with-resources. 
- HomeAlertsBean: Close RuleUnit with try-with-resources.
- SessionUnit: Close RuleUnit with try-with-resources.
- PersisterHelper: Close Stream with try-with-resources. 
- KiePMMLClusteringModel: Throw an exception when dividing by zero. 
+ some tests fixes. 

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

 - for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native-lts</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

2023-06-13 14:29 UTC, gitgabrio requested changes

2023-06-13 14:29 UTC, gitgabrio commented on kie-pmml-trusty/kie-pmml-models/kie-pmml-models-clustering/kie-pmml-models-clustering-model/src/main/java/org/kie/pmml/models/clustering/model/KiePMMLClusteringModel.java
> +            throw new RuntimeException("Division by 0! Denumerator value is 0.");
@baldimir Please replace `RuntimeException` with `KiePMMLException`

2023-06-13 14:31 UTC, baldimir commented on kie-pmml-trusty/kie-pmml-models/kie-pmml-models-clustering/kie-pmml-models-clustering-model/src/main/java/org/kie/pmml/models/clustering/model/KiePMMLClusteringModel.java
> +            throw new RuntimeException("Division by 0! Denumerator value is 0.");
Fixed.

2023-06-13 14:37 UTC, kie-ci4 commented
**(tests) - serverless-workflow-examples job** `#683` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/drools/pull/5303 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.serverless-workflow-examples/683/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-13T14:37:06.284Z] [INFO] Drools :: Engine :: Classic ........................ SUCCESS [  0.025 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: API examples ............................. SUCCESS [  0.013 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: API examples :: Default KieSession ....... SUCCESS [  0.146 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: API examples :: Named KieSession ......... SUCCESS [  0.118 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: API examples :: KieBase Inclusion ........ SUCCESS [  0.120 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: API examples :: Default KieSession From File SUCCESS [  0.120 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: API examples :: Named KieSession from File SUCCESS [  0.164 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: API examples :: KieModule from Multiple Files SUCCESS [  0.148 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: examples :: KieFileSystemExample ......... SUCCESS [  0.138 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: API examples :: KieModuleModel Example ... SUCCESS [  0.136 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: API examples :: KieContainer from KieRepo  SUCCESS [  0.194 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: API examples :: Multiple KieBases ........ SUCCESS [  0.094 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: API examples :: Reactive KieSession ...... SUCCESS [  0.139 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Test Coverage ............................ SUCCESS [  0.011 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Test Coverage :: Standalone reproducers .. SUCCESS [  0.010 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Parent SUCCESS [  0.009 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Domain SUCCESS [  0.055 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: KJar SUCCESS [  0.028 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Tests SUCCESS [  0.185 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Parent SUCCESS [  0.010 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Domain SUCCESS [  0.052 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: KJar SUCCESS [  0.027 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Tests SUCCESS [  0.139 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Test Coverage :: Test Suite .............. SUCCESS [  0.936 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Engine ................................... SUCCESS [  0.018 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Alpha Network Compiler ................... SUCCESS [  0.356 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Test Coverage :: Compiler integration tests SUCCESS [ 11.128 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Test Coverage :: Integration tests without mvel SUCCESS [  0.179 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Test Coverage :: Integration tests without TMS SUCCESS [  0.107 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Test Coverage :: Integration tests without xml SUCCESS [  0.099 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Test Coverage :: Integration tests with Rule Units Parent SUCCESS [  0.008 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Test Coverage :: Jar for Integration tests with Rule Units SUCCESS [  1.622 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Test Coverage :: Integration tests with Rule Units SUCCESS [  0.155 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Scenario Simulation Parent ............... SUCCESS [  0.009 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Drools :: Scenario Simulation API .................. SUCCESS [  0.342 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] KIE :: Decision Model Notation ..................... SUCCESS [  0.008 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] KIE :: Decision Model Notation :: Model ............ SUCCESS [  1.005 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Efesto ............................................. SUCCESS [  6.013 s]<br/>[2023-06-13T14:37:06.284Z] [INFO] Efesto :: Core ..................................... SUCCESS [  0.017 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] Efesto :: Common :: Api ............................ SUCCESS [  1.228 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] KIE :: Decision Model Notation :: API .............. SUCCESS [  0.096 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] KIE :: Decision Model Notation :: FEEL ............. SUCCESS [  8.063 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] KIE :: Decision Model Notation :: Backend .......... SUCCESS [  1.023 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] Efesto :: Compilation :: Manager ................... SUCCESS [  0.016 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] Efesto :: Compilation :: Manager :: Api ............ SUCCESS [  0.479 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] Efesto :: Common :: Core ........................... SUCCESS [  0.471 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] Efesto :: Compilation :: Manager :: Core ........... SUCCESS [  0.455 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] Efesto :: Runtime :: Manager ....................... SUCCESS [  0.016 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] Efesto :: Runtime :: Manager :: Api ................ SUCCESS [  0.316 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] Efesto :: Runtime :: Manager :: Core ............... SUCCESS [  0.456 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] Efesto :: Common :: Utils .......................... SUCCESS [  0.105 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] KIE :: PMML ........................................ SUCCESS [  0.015 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] KIE :: PMML :: API ................................. SUCCESS [  0.730 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] KIE :: PMML :: Commons ............................. SUCCESS [  1.137 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] KIE :: PMML :: Compiler ............................ SUCCESS [  0.017 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] KIE :: PMML :: Compiler :: API ..................... SUCCESS [  1.029 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] KIE :: PMML :: Compiler :: Commons ................. SUCCESS [  1.795 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] KIE :: PMML :: Compiler :: Core .................... SUCCESS [  0.485 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] KIE :: PMML :: Evaluator ........................... SUCCESS [  0.015 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] KIE :: PMML :: Evaluator :: API .................... SUCCESS [  0.069 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] KIE :: PMML :: Evaluator :: Core ................... SUCCESS [  0.635 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] KIE :: PMML :: Models .............................. SUCCESS [  0.014 s]<br/>[2023-06-13T14:37:06.285Z] [INFO] KIE :: PMML :: Models :: Regression ................ SUCCESS [  0.014 s [...]

2023-06-13 14:42 UTC, baldimir commented
Fixed the failure, sorry for the missed import.

2023-06-13 14:42 UTC, kie-ci4 commented
**(tests) - kogito-springboot-examples job** `#680` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/drools/pull/5303 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kogito-springboot-examples/680/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-13T14:42:05.571Z] [INFO] Drools :: Engine :: Classic ........................ SUCCESS [  0.020 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: API examples ............................. SUCCESS [  0.009 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: API examples :: Default KieSession ....... SUCCESS [  0.130 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: API examples :: Named KieSession ......... SUCCESS [  0.108 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: API examples :: KieBase Inclusion ........ SUCCESS [  0.102 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: API examples :: Default KieSession From File SUCCESS [  0.118 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: API examples :: Named KieSession from File SUCCESS [  0.127 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: API examples :: KieModule from Multiple Files SUCCESS [  0.148 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: examples :: KieFileSystemExample ......... SUCCESS [  0.144 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: API examples :: KieModuleModel Example ... SUCCESS [  0.140 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: API examples :: KieContainer from KieRepo  SUCCESS [  0.194 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: API examples :: Multiple KieBases ........ SUCCESS [  0.083 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: API examples :: Reactive KieSession ...... SUCCESS [  0.112 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: Test Coverage ............................ SUCCESS [  0.009 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: Test Coverage :: Standalone reproducers .. SUCCESS [  0.008 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Parent SUCCESS [  0.009 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Domain SUCCESS [  0.046 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: KJar SUCCESS [  0.023 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Tests SUCCESS [  0.141 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Parent SUCCESS [  0.009 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Domain SUCCESS [  0.040 s]<br/>[2023-06-13T14:42:05.571Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: KJar SUCCESS [  0.079 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Tests SUCCESS [  0.160 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Drools :: Test Coverage :: Test Suite .............. SUCCESS [  0.888 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Drools :: Engine ................................... SUCCESS [  0.017 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Drools :: Alpha Network Compiler ................... SUCCESS [  0.345 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Drools :: Test Coverage :: Compiler integration tests SUCCESS [ 11.310 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Drools :: Test Coverage :: Integration tests without mvel SUCCESS [  0.149 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Drools :: Test Coverage :: Integration tests without TMS SUCCESS [  0.104 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Drools :: Test Coverage :: Integration tests without xml SUCCESS [  0.094 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Drools :: Test Coverage :: Integration tests with Rule Units Parent SUCCESS [  0.009 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Drools :: Test Coverage :: Jar for Integration tests with Rule Units SUCCESS [  1.327 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Drools :: Test Coverage :: Integration tests with Rule Units SUCCESS [  0.137 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Drools :: Scenario Simulation Parent ............... SUCCESS [  0.008 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Drools :: Scenario Simulation API .................. SUCCESS [  0.327 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] KIE :: Decision Model Notation ..................... SUCCESS [  0.008 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] KIE :: Decision Model Notation :: Model ............ SUCCESS [  0.990 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Efesto ............................................. SUCCESS [  5.592 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Efesto :: Core ..................................... SUCCESS [  0.014 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Efesto :: Common :: Api ............................ SUCCESS [  1.047 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] KIE :: Decision Model Notation :: API .............. SUCCESS [  0.102 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] KIE :: Decision Model Notation :: FEEL ............. SUCCESS [  7.965 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] KIE :: Decision Model Notation :: Backend .......... SUCCESS [  0.840 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Efesto :: Compilation :: Manager ................... SUCCESS [  0.013 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Efesto :: Compilation :: Manager :: Api ............ SUCCESS [  0.470 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Efesto :: Common :: Core ........................... SUCCESS [  0.626 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Efesto :: Compilation :: Manager :: Core ........... SUCCESS [  0.427 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Efesto :: Runtime :: Manager ....................... SUCCESS [  0.015 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Efesto :: Runtime :: Manager :: Api ................ SUCCESS [  0.286 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Efesto :: Runtime :: Manager :: Core ............... SUCCESS [  0.371 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] Efesto :: Common :: Utils .......................... SUCCESS [  0.162 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] KIE :: PMML ........................................ SUCCESS [  0.016 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] KIE :: PMML :: API ................................. SUCCESS [  0.671 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] KIE :: PMML :: Commons ............................. SUCCESS [  1.167 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] KIE :: PMML :: Compiler ............................ SUCCESS [  0.017 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] KIE :: PMML :: Compiler :: API ..................... SUCCESS [  0.955 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] KIE :: PMML :: Compiler :: Commons ................. SUCCESS [  1.605 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] KIE :: PMML :: Compiler :: Core .................... SUCCESS [  0.477 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] KIE :: PMML :: Evaluator ........................... SUCCESS [  0.014 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] KIE :: PMML :: Evaluator :: API .................... SUCCESS [  0.064 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] KIE :: PMML :: Evaluator :: Core ................... SUCCESS [  0.689 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] KIE :: PMML :: Models .............................. SUCCESS [  0.015 s]<br/>[2023-06-13T14:42:05.572Z] [INFO] KIE :: PMML :: Models :: Regression ................ SUCCESS [  0.015 s]<br [...]

2023-06-13 14:42 UTC, kie-ci4 commented
**(tests) - kogito-runtimes job** `#1430` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/kogito-runtimes -u https://github.com/kiegroup/drools/pull/5303 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kogito-runtimes/1430/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-13T14:42:06.730Z] [INFO] Drools :: Engine :: Classic ........................ SUCCESS [  0.021 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: API examples ............................. SUCCESS [  0.010 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: API examples :: Default KieSession ....... SUCCESS [  0.118 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: API examples :: Named KieSession ......... SUCCESS [  0.173 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: API examples :: KieBase Inclusion ........ SUCCESS [  0.126 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: API examples :: Default KieSession From File SUCCESS [  0.149 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: API examples :: Named KieSession from File SUCCESS [  0.142 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: API examples :: KieModule from Multiple Files SUCCESS [  0.135 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: examples :: KieFileSystemExample ......... SUCCESS [  0.175 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: API examples :: KieModuleModel Example ... SUCCESS [  0.204 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: API examples :: KieContainer from KieRepo  SUCCESS [  0.174 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: API examples :: Multiple KieBases ........ SUCCESS [  0.108 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: API examples :: Reactive KieSession ...... SUCCESS [  0.128 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Test Coverage ............................ SUCCESS [  0.010 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Test Coverage :: Standalone reproducers .. SUCCESS [  0.008 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Parent SUCCESS [  0.009 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Domain SUCCESS [  0.047 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: KJar SUCCESS [  0.025 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Tests SUCCESS [  0.146 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Parent SUCCESS [  0.009 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Domain SUCCESS [  0.046 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: KJar SUCCESS [  0.025 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Tests SUCCESS [  0.165 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Test Coverage :: Test Suite .............. SUCCESS [  0.919 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Engine ................................... SUCCESS [  0.018 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Alpha Network Compiler ................... SUCCESS [  0.330 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Test Coverage :: Compiler integration tests SUCCESS [ 11.155 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Test Coverage :: Integration tests without mvel SUCCESS [  0.162 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Test Coverage :: Integration tests without TMS SUCCESS [  0.107 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Test Coverage :: Integration tests without xml SUCCESS [  0.102 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Test Coverage :: Integration tests with Rule Units Parent SUCCESS [  0.010 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Test Coverage :: Jar for Integration tests with Rule Units SUCCESS [  1.416 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Test Coverage :: Integration tests with Rule Units SUCCESS [  0.186 s]<br/>[2023-06-13T14:42:06.730Z] [INFO] Drools :: Scenario Simulation Parent ............... SUCCESS [  0.054 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] Drools :: Scenario Simulation API .................. SUCCESS [  0.362 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] KIE :: Decision Model Notation ..................... SUCCESS [  0.012 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] KIE :: Decision Model Notation :: Model ............ SUCCESS [  0.942 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] Efesto ............................................. SUCCESS [  5.827 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] Efesto :: Core ..................................... SUCCESS [  0.018 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] Efesto :: Common :: Api ............................ SUCCESS [  1.136 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] KIE :: Decision Model Notation :: API .............. SUCCESS [  0.101 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] KIE :: Decision Model Notation :: FEEL ............. SUCCESS [  7.930 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] KIE :: Decision Model Notation :: Backend .......... SUCCESS [  0.912 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] Efesto :: Compilation :: Manager ................... SUCCESS [  0.017 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] Efesto :: Compilation :: Manager :: Api ............ SUCCESS [  0.442 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] Efesto :: Common :: Core ........................... SUCCESS [  0.506 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] Efesto :: Compilation :: Manager :: Core ........... SUCCESS [  0.452 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] Efesto :: Runtime :: Manager ....................... SUCCESS [  0.016 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] Efesto :: Runtime :: Manager :: Api ................ SUCCESS [  0.351 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] Efesto :: Runtime :: Manager :: Core ............... SUCCESS [  0.387 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] Efesto :: Common :: Utils .......................... SUCCESS [  0.104 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] KIE :: PMML ........................................ SUCCESS [  0.015 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] KIE :: PMML :: API ................................. SUCCESS [  0.687 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] KIE :: PMML :: Commons ............................. SUCCESS [  1.117 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] KIE :: PMML :: Compiler ............................ SUCCESS [  0.017 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] KIE :: PMML :: Compiler :: API ..................... SUCCESS [  0.917 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] KIE :: PMML :: Compiler :: Commons ................. SUCCESS [  1.700 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] KIE :: PMML :: Compiler :: Core .................... SUCCESS [  0.536 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] KIE :: PMML :: Evaluator ........................... SUCCESS [  0.014 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] KIE :: PMML :: Evaluator :: API .................... SUCCESS [  0.078 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] KIE :: PMML :: Evaluator :: Core ................... SUCCESS [  0.680 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] KIE :: PMML :: Models .............................. SUCCESS [  0.014 s]<br/>[2023-06-13T14:42:06.731Z] [INFO] KIE :: PMML :: Models :: Regression ................ SUCCESS [  0.016 s]<br/>[2023-06-13T14:42: [...]

2023-06-13 14:42 UTC, kie-ci4 commented
**(tests) - kogito-quarkus-examples job** `#684` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/drools/pull/5303 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kogito-quarkus-examples/684/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-13T14:42:14.401Z] [INFO] Drools :: Engine :: Classic ........................ SUCCESS [  0.017 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: API examples ............................. SUCCESS [  0.008 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: API examples :: Default KieSession ....... SUCCESS [  0.114 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: API examples :: Named KieSession ......... SUCCESS [  0.109 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: API examples :: KieBase Inclusion ........ SUCCESS [  0.111 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: API examples :: Default KieSession From File SUCCESS [  0.124 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: API examples :: Named KieSession from File SUCCESS [  0.121 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: API examples :: KieModule from Multiple Files SUCCESS [  0.117 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: examples :: KieFileSystemExample ......... SUCCESS [  0.132 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: API examples :: KieModuleModel Example ... SUCCESS [  0.197 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: API examples :: KieContainer from KieRepo  SUCCESS [  0.169 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: API examples :: Multiple KieBases ........ SUCCESS [  0.095 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: API examples :: Reactive KieSession ...... SUCCESS [  0.116 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Test Coverage ............................ SUCCESS [  0.009 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Test Coverage :: Standalone reproducers .. SUCCESS [  0.008 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Parent SUCCESS [  0.009 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Domain SUCCESS [  0.041 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: KJar SUCCESS [  0.022 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Tests SUCCESS [  0.134 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Parent SUCCESS [  0.009 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Domain SUCCESS [  0.043 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: KJar SUCCESS [  0.021 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Tests SUCCESS [  0.126 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Test Coverage :: Test Suite .............. SUCCESS [  0.880 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Engine ................................... SUCCESS [  0.018 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Alpha Network Compiler ................... SUCCESS [  0.375 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Test Coverage :: Compiler integration tests SUCCESS [ 10.940 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Test Coverage :: Integration tests without mvel SUCCESS [  0.171 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Test Coverage :: Integration tests without TMS SUCCESS [  0.106 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Test Coverage :: Integration tests without xml SUCCESS [  0.096 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Test Coverage :: Integration tests with Rule Units Parent SUCCESS [  0.008 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Test Coverage :: Jar for Integration tests with Rule Units SUCCESS [  1.543 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Test Coverage :: Integration tests with Rule Units SUCCESS [  0.139 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Scenario Simulation Parent ............... SUCCESS [  0.009 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Drools :: Scenario Simulation API .................. SUCCESS [  0.341 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] KIE :: Decision Model Notation ..................... SUCCESS [  0.009 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] KIE :: Decision Model Notation :: Model ............ SUCCESS [  1.125 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Efesto ............................................. SUCCESS [  5.819 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Efesto :: Core ..................................... SUCCESS [  0.014 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Efesto :: Common :: Api ............................ SUCCESS [  1.044 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] KIE :: Decision Model Notation :: API .............. SUCCESS [  0.094 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] KIE :: Decision Model Notation :: FEEL ............. SUCCESS [  7.484 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] KIE :: Decision Model Notation :: Backend .......... SUCCESS [  0.862 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Efesto :: Compilation :: Manager ................... SUCCESS [  0.015 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Efesto :: Compilation :: Manager :: Api ............ SUCCESS [  0.417 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Efesto :: Common :: Core ........................... SUCCESS [  0.553 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Efesto :: Compilation :: Manager :: Core ........... SUCCESS [  0.462 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Efesto :: Runtime :: Manager ....................... SUCCESS [  0.013 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Efesto :: Runtime :: Manager :: Api ................ SUCCESS [  0.342 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Efesto :: Runtime :: Manager :: Core ............... SUCCESS [  0.368 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] Efesto :: Common :: Utils .......................... SUCCESS [  0.095 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] KIE :: PMML ........................................ SUCCESS [  0.012 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] KIE :: PMML :: API ................................. SUCCESS [  0.702 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] KIE :: PMML :: Commons ............................. SUCCESS [  1.114 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] KIE :: PMML :: Compiler ............................ SUCCESS [  0.014 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] KIE :: PMML :: Compiler :: API ..................... SUCCESS [  1.005 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] KIE :: PMML :: Compiler :: Commons ................. SUCCESS [  1.633 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] KIE :: PMML :: Compiler :: Core .................... SUCCESS [  0.493 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] KIE :: PMML :: Evaluator ........................... SUCCESS [  0.048 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] KIE :: PMML :: Evaluator :: API .................... SUCCESS [  0.065 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] KIE :: PMML :: Evaluator :: Core ................... SUCCESS [  0.626 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] KIE :: PMML :: Models .............................. SUCCESS [  0.013 s]<br/>[2023-06-13T14:42:14.401Z] [INFO] KIE :: PMML :: Models :: Regression ................ SUCCESS [  0.014 s]<br/>[202 [...]

2023-06-13 14:42 UTC, kie-ci4 commented
**(tests) - kogito-apps job** `#1448` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/drools/pull/5303 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kogito-apps/1448/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-13T14:42:20.300Z] [INFO] Drools :: Engine :: Classic ........................ SUCCESS [  0.020 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: API examples ............................. SUCCESS [  0.010 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: API examples :: Default KieSession ....... SUCCESS [  0.121 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: API examples :: Named KieSession ......... SUCCESS [  0.117 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: API examples :: KieBase Inclusion ........ SUCCESS [  0.127 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: API examples :: Default KieSession From File SUCCESS [  0.167 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: API examples :: Named KieSession from File SUCCESS [  0.145 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: API examples :: KieModule from Multiple Files SUCCESS [  0.200 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: examples :: KieFileSystemExample ......... SUCCESS [  0.172 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: API examples :: KieModuleModel Example ... SUCCESS [  0.141 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: API examples :: KieContainer from KieRepo  SUCCESS [  0.193 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: API examples :: Multiple KieBases ........ SUCCESS [  0.115 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: API examples :: Reactive KieSession ...... SUCCESS [  0.143 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Test Coverage ............................ SUCCESS [  0.010 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Test Coverage :: Standalone reproducers .. SUCCESS [  0.010 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Parent SUCCESS [  0.011 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Domain SUCCESS [  0.058 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: KJar SUCCESS [  0.031 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Tests SUCCESS [  0.155 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Parent SUCCESS [  0.010 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Domain SUCCESS [  0.107 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: KJar SUCCESS [  0.029 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Tests SUCCESS [  0.165 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Test Coverage :: Test Suite .............. SUCCESS [  0.972 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Engine ................................... SUCCESS [  0.020 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Alpha Network Compiler ................... SUCCESS [  0.363 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Test Coverage :: Compiler integration tests SUCCESS [ 11.608 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Test Coverage :: Integration tests without mvel SUCCESS [  0.165 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Test Coverage :: Integration tests without TMS SUCCESS [  0.116 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Test Coverage :: Integration tests without xml SUCCESS [  0.102 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Test Coverage :: Integration tests with Rule Units Parent SUCCESS [  0.010 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Test Coverage :: Jar for Integration tests with Rule Units SUCCESS [  1.557 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Test Coverage :: Integration tests with Rule Units SUCCESS [  0.162 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Scenario Simulation Parent ............... SUCCESS [  0.010 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Drools :: Scenario Simulation API .................. SUCCESS [  0.397 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] KIE :: Decision Model Notation ..................... SUCCESS [  0.011 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] KIE :: Decision Model Notation :: Model ............ SUCCESS [  1.205 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Efesto ............................................. SUCCESS [  5.734 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Efesto :: Core ..................................... SUCCESS [  0.016 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Efesto :: Common :: Api ............................ SUCCESS [  1.119 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] KIE :: Decision Model Notation :: API .............. SUCCESS [  0.103 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] KIE :: Decision Model Notation :: FEEL ............. SUCCESS [  7.840 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] KIE :: Decision Model Notation :: Backend .......... SUCCESS [  1.013 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Efesto :: Compilation :: Manager ................... SUCCESS [  0.019 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Efesto :: Compilation :: Manager :: Api ............ SUCCESS [  0.661 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Efesto :: Common :: Core ........................... SUCCESS [  0.442 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Efesto :: Compilation :: Manager :: Core ........... SUCCESS [  0.470 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Efesto :: Runtime :: Manager ....................... SUCCESS [  0.015 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Efesto :: Runtime :: Manager :: Api ................ SUCCESS [  0.317 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Efesto :: Runtime :: Manager :: Core ............... SUCCESS [  0.480 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] Efesto :: Common :: Utils .......................... SUCCESS [  0.099 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] KIE :: PMML ........................................ SUCCESS [  0.014 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] KIE :: PMML :: API ................................. SUCCESS [  0.655 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] KIE :: PMML :: Commons ............................. SUCCESS [  1.083 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] KIE :: PMML :: Compiler ............................ SUCCESS [  0.016 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] KIE :: PMML :: Compiler :: API ..................... SUCCESS [  0.945 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] KIE :: PMML :: Compiler :: Commons ................. SUCCESS [  1.654 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] KIE :: PMML :: Compiler :: Core .................... SUCCESS [  0.502 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] KIE :: PMML :: Evaluator ........................... SUCCESS [  0.015 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] KIE :: PMML :: Evaluator :: API .................... SUCCESS [  0.067 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] KIE :: PMML :: Evaluator :: Core ................... SUCCESS [  0.734 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] KIE :: PMML :: Models .............................. SUCCESS [  0.015 s]<br/>[2023-06-13T14:42:20.300Z] [INFO] KIE :: PMML :: Models :: Regression ................ SUCCESS [  0.019 s]<br/>[2023-06-13T14:42:20.300Z] [IN [...]

2023-06-13 15:17 UTC, kie-ci4 commented
**(tests) - drools job** `#1466` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-Dfull -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/drools -u https://github.com/kiegroup/drools/pull/5303 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1466/display/redirect

**Test results:**
- PASSED: 21368
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.drools/1466/testReport/org.kie.maven.plugin.it/kie-maven-plugin-test-kjar-12/kie_maven_plugin_test_kjar_12/">org.kie.maven.plugin.it.kie-maven-plugin-test-kjar-12.kie-maven-plugin-test-kjar-12</a></summary>
The build exited with code 1. See /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.drools/bc/kiegroup_drools/kie-maven-plugin/target/it/kie-maven-plugin-test-kjar-12/build.log for details.
</details>

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-06-13T15:15:47.110Z] [INFO] Drools :: API examples :: KieModule from Multiple Files SUCCESS [  5.346 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: examples :: KieFileSystemExample ......... SUCCESS [  4.920 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: API examples :: KieModuleModel Example ... SUCCESS [  6.033 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: API examples :: KieContainer from KieRepo  SUCCESS [ 11.777 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: API examples :: Multiple KieBases ........ SUCCESS [  3.853 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: API examples :: Reactive KieSession ...... SUCCESS [  5.719 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Test Coverage ............................ SUCCESS [  0.028 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Test Coverage :: Standalone reproducers .. SUCCESS [  0.026 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Parent SUCCESS [  0.067 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Domain SUCCESS [  1.887 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: KJar SUCCESS [  0.043 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Test Coverage :: KIE-CI with Domain classes :: Tests SUCCESS [  7.607 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Parent SUCCESS [  0.030 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Domain SUCCESS [  1.730 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: KJar SUCCESS [  0.044 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Test Coverage :: KIE-CI without Domain classes :: Tests SUCCESS [  6.393 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Test Coverage :: Test Suite .............. SUCCESS [01:27 min]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Engine ................................... SUCCESS [  0.057 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Alpha Network Compiler ................... SUCCESS [ 43.252 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Test Coverage :: Compiler integration tests SUCCESS [04:20 min]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Test Coverage :: Integration tests without mvel SUCCESS [  5.725 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Test Coverage :: Integration tests without TMS SUCCESS [  4.866 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Test Coverage :: Integration tests without xml SUCCESS [  4.599 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Test Coverage :: Integration tests with Rule Units Parent SUCCESS [  0.028 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Test Coverage :: Jar for Integration tests with Rule Units SUCCESS [  5.981 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Test Coverage :: Integration tests with Rule Units SUCCESS [  5.357 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Scenario Simulation Parent ............... SUCCESS [  0.065 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Drools :: Scenario Simulation API .................. SUCCESS [  4.430 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] KIE :: Decision Model Notation ..................... SUCCESS [  0.025 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] KIE :: Decision Model Notation :: Model ............ SUCCESS [  6.894 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Efesto ............................................. SUCCESS [  6.453 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Efesto :: Core ..................................... SUCCESS [  0.042 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Efesto :: Common :: Api ............................ SUCCESS [  4.633 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] KIE :: Decision Model Notation :: API .............. SUCCESS [  2.425 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] KIE :: Decision Model Notation :: FEEL ............. SUCCESS [01:24 min]<br/>[2023-06-13T15:15:47.110Z] [INFO] KIE :: Decision Model Notation :: Backend .......... SUCCESS [  9.852 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Efesto :: Compilation :: Manager ................... SUCCESS [  0.090 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Efesto :: Compilation :: Manager :: Api ............ SUCCESS [  3.170 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Efesto :: Common :: Core ........................... SUCCESS [  3.466 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Efesto :: Compilation :: Manager :: Core ........... SUCCESS [  3.694 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Efesto :: Runtime :: Manager ....................... SUCCESS [  0.053 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Efesto :: Runtime :: Manager :: Api ................ SUCCESS [  3.081 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Efesto :: Runtime :: Manager :: Core ............... SUCCESS [  3.523 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] Efesto :: Common :: Utils .......................... SUCCESS [  2.068 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] KIE :: PMML ........................................ SUCCESS [  0.041 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] KIE :: PMML :: API ................................. SUCCESS [  5.531 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] KIE :: PMML :: Commons ............................. SUCCESS [  6.343 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] KIE :: PMML :: Compiler ............................ SUCCESS [  0.041 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] KIE :: PMML :: Compiler :: API ..................... SUCCESS [  4.797 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] KIE :: PMML :: Compiler :: Commons ................. SUCCESS [ 14.434 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] KIE :: PMML :: Compiler :: Core .................... SUCCESS [  5.534 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] KIE :: PMML :: Evaluator ........................... SUCCESS [  0.042 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] KIE :: PMML :: Evaluator :: API .................... SUCCESS [  2.029 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] KIE :: PMML :: Evaluator :: Core ................... SUCCESS [  5.968 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] KIE :: PMML :: Models .............................. SUCCESS [  0.041 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] KIE :: PMML :: Models :: Regression ................ SUCCESS [  0.041 s]<br/>[2023-06-13T15:15:47.110Z] [INFO] KIE :: PMML :: Models :: Regression :: Model ....... SUCCESS [  4.613 s]<br/>[2023-06-13T15:15:47.110Z] [INFO [...]

2023-06-14 06:36 UTC, baldimir commented
The fail in OptaPlanner looks unrelated. Could you please doublecheck @mariofusco @danielezonca?

2023-06-14 06:41 UTC, pibizza reviewed
Hi Tibor, thank you for the patch, very good to address these long standing Sonar Issues.
I have added minor comments on assertj.

2023-06-14 06:41 UTC, pibizza commented on drools-test-coverage/test-compiler-integration/src/test/java/org/drools/compiler/integrationtests/drl/DrlSpecificFeaturesTest.java
> +        } else {
use static imports for the asserj Assertions

2023-06-14 06:41 UTC, pibizza commented on drools-test-coverage/test-compiler-integration/src/test/java/org/drools/mvel/integrationtests/DynamicRulesTest.java
use static imports for the asserj Assertions

2023-06-14 06:41 UTC, pibizza commented on drools-verifier/drools-verifier-drl/src/test/java/org/drools/verifier/jarloader/VerifierMapBackedClassLoaderTest.java
>      }
You can assert that all the keys are present with a single assert.

2023-06-14 06:52 UTC, baldimir commented on drools-test-coverage/test-compiler-integration/src/test/java/org/drools/compiler/integrationtests/drl/DrlSpecificFeaturesTest.java
> +        } else {
Fixed.

2023-06-14 06:52 UTC, baldimir commented on drools-test-coverage/test-compiler-integration/src/test/java/org/drools/mvel/integrationtests/DynamicRulesTest.java
Fixed.

2023-06-14 06:52 UTC, baldimir commented on drools-verifier/drools-verifier-drl/src/test/java/org/drools/verifier/jarloader/VerifierMapBackedClassLoaderTest.java
>      }
Fixed.

2023-06-14 09:09 UTC, gitgabrio commented on drools-beliefs/src/main/java/org/drools/beliefs/bayes/BayesInstance.java
> +                    Random rand = SecureRandom.getInstanceStrong();
@baldimir 
IINW, this could raise the same sonar complaints, since the `Random` is not a class member: am I wrong ?

2023-06-14 09:14 UTC, gitgabrio reviewed
See above questions

2023-06-14 09:14 UTC, gitgabrio commented on drools-test-coverage/test-suite/src/test/java/org/drools/testcoverage/functional/KieContainerDefaultsTest.java
> +            assertThat(secondKSession).isNotInstanceOf(StatelessKieSession.class);
@baldimir 
It seems this change a bit the scope of the test: previous version was checking for equality of bojects, but noiw it check only the type

2023-06-14 10:16 UTC, baldimir commented on drools-test-coverage/test-suite/src/test/java/org/drools/testcoverage/functional/KieContainerDefaultsTest.java
> +            assertThat(secondKSession).isNotInstanceOf(StatelessKieSession.class);
The previous assert was doing equality checks on instances of different types (checking if KieSession instance is equal to StatelessKieSession instance), so it was always passing. The classes have nothing in common as far as parent classes or interfaces go. I tried, by guessing the original meaning of the assert, changing the assert to something more meaningful. From the original assert it looks to me that it was supposed to check that the second session is not a stateless session, therefore I changed the assert to instanceOf check.

2023-06-14 10:20 UTC, baldimir commented on drools-beliefs/src/main/java/org/drools/beliefs/bayes/BayesInstance.java
> +                    Random rand = SecureRandom.getInstanceStrong();
Fixed

2023-06-14 10:55 UTC, kie-ci4 commented
**(tests) - serverless-workflow-examples job** `#691` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/drools/pull/5303 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.serverless-workflow-examples/691/display/redirect

**Test results:**
- PASSED: 79
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.serverless-workflow-examples/691/testReport/org.kie.kogito.examples/DataIndexRestIT/testDataIndexRest/">org.kie.kogito.examples.DataIndexRestIT.testDataIndexRest</a></summary>
1 expectation failed.<br/>JSON path data.ProcessInstances[0].state doesn't match.<br/>Expected: is "COMPLETED"<br/>  Actual: ACTIVE<br/>
</details>

2023-06-14 11:26 UTC, baldimir commented
Jenkins run serverless-workflow-examples tests

2023-06-14 12:00 UTC, kie-ci4 commented
**(tests) - serverless-workflow-examples job** `#692` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/drools/pull/5303 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.serverless-workflow-examples/692/display/redirect

**Test results:**
- PASSED: 79
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.serverless-workflow-examples/692/testReport/org.kie.kogito.examples/DataIndexRestIT/testDataIndexRest/">org.kie.kogito.examples.DataIndexRestIT.testDataIndexRest</a></summary>
1 expectation failed.<br/>JSON path data.ProcessInstances[0].state doesn't match.<br/>Expected: is "COMPLETED"<br/>  Actual: ACTIVE<br/>
</details>

2023-06-14 12:14 UTC, baldimir commented
Jenkins run serverless-workflow-examples tests

2023-06-14 12:25 UTC, pibizza approved these changes

2023-06-14 12:42 UTC, baldimir commented
I analyzed the failed checks, here is a summary - to me it looks like the failures are unrelated to my changes: 
- OptaPlanner fails also in other PRs. 
- kogito-apps passed on Jenkins, failed tests in GitHub check due to Container startup failed - Failed to pull image
- kogito-runtimes passed on Jenkins, faied tests in GitHub check due to failures with Python environment setup
- Drools passed on Jenkins, fail in GitHub check because when building documentation, there was an error: Could not extract archive: '/home/runner/.m2/repository/com/github/eirslett/node/16.2.0/node-16.2.0-linux-x64.tar.gz'
- Windows build GitHub action - timeout in TimerAndCalendarFireUntilHaltTest

2023-06-14 13:08 UTC, danielezonca commented
It looks like there are `ubuntu` images not available https://github.com/actions/runner-images#available-images I don't know if this has impact on stability for GHA.
![image](https://github.com/kiegroup/drools/assets/244607/b1918f3a-db60-4477-bf00-8be5c68527d5)

In theory it should only have impact on the time to find an available runner but I don't know the details of how GH runners work

2023-06-14 13:19 UTC, baldimir commented
@danielezonca thanks, may be related. Do you think this is ready to merge please? Or should I do more changes?

2023-06-14 14:46 UTC, porcelli commented on drools-test-coverage/test-suite/src/test/java/org/drools/testcoverage/functional/KieContainerDefaultsTest.java
> +            assertThat(secondKSession).isNotInstanceOf(StatelessKieSession.class);
agree with @baldimir

2023-06-14 14:46 UTC, porcelli approved these changes

2023-06-14 14:57 UTC, baldimir commented
@kiegroup/gatekeepers Could anyone merge this if it is fine please?

2023-06-14 15:42 UTC, tarilabs commented
merging as requested in https://github.com/kiegroup/drools/pull/5303#issuecomment-1591118614 after having read https://github.com/kiegroup/drools/pull/5303#issuecomment-1591177358

proceeding as requested.

2023-06-14 15:42 UTC, merged