[kie-issues#394] Unnecessary warning when DRL file is placed in BOOT-INF/classes directory
apache/incubator-kie pull request #5410
Opened 2023-07-27 12:50 UTC by baldimir

Fixes https://github.com/kiegroup/kie-issues/issues/394.

This change fixes the check of BOOT-INF/classes folder. It is not easily testable, so there is no new test for this as part of this PR. I filed a [new issue](https://github.com/kiegroup/kie-issues/issues/395) to properly extend the test coverate to test this scenario. 

**referenced Pull Requests**: 

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for a <b>full downstream build</b> 
  - for <b>jenkins</b> job: please add comment: <b>Jenkins run fdb</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

- <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

- <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native</b>

 - for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [drools|kogito-runtimes|kogito-apps|kogito-examples] native-lts</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

2023-07-27 12:57 UTC, gitgabrio commented on drools-compiler/src/main/java/org/drools/compiler/kie/builder/impl/KieBuilderImpl.java
> +        String packageNameFromFolder = getRelativePackageName(folderNameForFile.replace( '/', '.' ));
THanks @baldimir . Could you please replace `/` with the filesystem separator ? We have fixed that in a lot of different places, and wherever possible I think it is better

2023-07-27 12:58 UTC, gitgabrio requested changes
Thansk for the PR. I would like to ask one minor fix

2023-07-27 13:24 UTC, kie-ci4 commented
**(tests) - serverless-workflow-examples job** `#793` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/drools/pull/5410 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.serverless-workflow-examples/793/display/redirect

**Test results:**
- PASSED: 80
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-07-27T13:24:47.050Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-07-27T13:24:47.050Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-07-27T13:24:47.050Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-07-27T13:24:47.050Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-07-27T13:24:47.050Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-07-27T13:24:47.050Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-07-27T13:24:47.050Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-07-27T13:24:47.050Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-07-27T13:24:47.050Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-07-27T13:24:47.050Z] Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.kie.kogito:kogito-addons-quarkus-serverless-workflow-python:jar:2.0.0-SNAPSHOT<br/>[2023-07-27T13:24:47.050Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:357)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:207)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:243)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:401)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:347)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-07-27T13:24:47.050Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-07-27T13:24:47.050Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-07-27T13:24:47.050Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-07-27T13:24:47.050Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-07-27T13:24:47.050Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-07-27T13:24:47.050Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-07-27T13:24:47.050Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-07-27T13:24:47.050Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-07-27T13:24:47.050Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.kie.kogito:kogito-addons-quarkus-serverless-workflow-python:jar:2.0.0-SNAPSHOT<br/>[2023-07-27T13:24:47.050Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:425)<br/>[2023-07-27T13:24:47.050Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-07-27T13:24:47.050Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:340)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:207)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:243)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:401)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:347)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-07-27T13:24:47.050Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-07-27T13:24:47.051Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-07-27T13:24:47.051Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-07-27T13:24:47.051Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-07-27T13:24:47.051Z]     at org.apache.maven.DefaultMaven.doExecute (Default [...]

2023-07-27 13:52 UTC, kie-ci4 commented
**(tests) - kogito-apps job** `#1555` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/drools/main/.ci/buildchain-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/drools/pull/5410 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/drools/job/main/job/pullrequest/job/drools.tests.downstream.kogito-apps/1555/display/redirect

**Test results:**
- PASSED: 1560
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at Object.act (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at wrapAct (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/node_modules/.pnpm/@wojtekmaj+enzyme-adapter-react-17@0.8.0_enzyme@3.11.0_react-dom@17.0.2_react@17.0.2/node_modules/@wojtekmaj/enzyme-adapter-react-17/src/ReactSeventeenAdapter.js:336:13)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at Object.render (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/node_modules/.pnpm/@wojtekmaj+enzyme-adapter-react-17@0.8.0_enzyme@3.11.0_react-dom@17.0.2_react@17.0.2/node_modules/@wojtekmaj/enzyme-adapter-react-17/src/ReactSeventeenAdapter.js:407:16)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at new ReactWrapper (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/node_modules/.pnpm/enzyme@3.11.0/node_modules/enzyme/src/ReactWrapper.js:115:16)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at mount (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/node_modules/.pnpm/enzyme@3.11.0/node_modules/enzyme/src/mount.js:10:10)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at Object.<anonymous> (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/packages/form-displayer/src/envelope/components/ErrorBoundary/tests/ErrorBoundary.test.tsx:46:26)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at Object.asyncJestTest (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/node_modules/.pnpm/jest-jasmine2@26.6.3/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/node_modules/.pnpm/jest-jasmine2@26.6.3/node_modules/jest-jasmine2/build/queueRunner.js:45:12<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at new Promise (<anonymous>)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at mapper (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/node_modules/.pnpm/jest-jasmine2@26.6.3/node_modules/jest-jasmine2/build/queueRunner.js:28:19)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at /home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/node_modules/.pnpm/jest-jasmine2@26.6.3/node_modules/jest-jasmine2/build/queueRunner.js:75:41 Error: test error!<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at Component (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/packages/form-displayer/src/envelope/components/ErrorBoundary/tests/ErrorBoundary.test.tsx:25:9)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at renderWithHooks (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:14985:18)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at mountIndeterminateComponent (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:17811:13)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at apply (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:19049:16)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at HTMLUnknownElement.callCallback (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom.development.js:3945:14)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at HTMLUnknownElement.callTheUserObjectsOperation (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/node_modules/.pnpm/jsdom@16.7.0/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at innerInvokeEventListeners (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/node_modules/.pnpm/jsdom@16.7.0/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at invokeEventListeners (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/node_modules/.pnpm/jsdom@16.7.0/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at HTMLUnknownElementImpl._dispatch (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/node_modules/.pnpm/jsdom@16.7.0/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at HTMLUnknownElementImpl.dispatchEvent (/home/jenkins/workspace/KIE/drools/main/pullrequest/drools.tests.downstream.kogito-apps/bc/kiegroup_kogito-apps/ui-packages/node_modules/.pnpm/jsdom@16.7.0/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)<br/>[2023-07-27T13:45:02.947Z] [INFO] packages/form-displayer test:coverage:           at HTMLUnknownElement.dispatc [...]

2023-07-27 14:02 UTC, wojtekmaj commented
Lmao, console logs called me here. GitHub should fix that :D 

Since I'm already here, please have a read: https://dev.to/wojtekmaj/enzyme-is-dead-now-what-ekl

2023-07-27 14:03 UTC, baldimir commented
@wojtekmaj sorry for that :))) Thank you, will read that.

2023-07-27 14:35 UTC, mariofusco commented on drools-compiler/src/main/java/org/drools/compiler/kie/builder/impl/KieBuilderImpl.java
> +        String packageNameFromFolder = getRelativePackageName(folderNameForFile.replace( '/', '.' ));
@gitgabrio I'm not sure this is necessary, this is handling InternalResource so the separator should be already normalized with a '/'.

2023-07-27 14:35 UTC, mariofusco approved these changes

2023-08-01 07:43 UTC, baldimir commented on drools-compiler/src/main/java/org/drools/compiler/kie/builder/impl/KieBuilderImpl.java
> +        String packageNameFromFolder = getRelativePackageName(folderNameForFile.replace( '/', '.' ));
Yes, I thought the same. As far as I remember, KieMemoryFileSystem works internally with "/".

2023-08-01 14:03 UTC, gitgabrio commented on drools-compiler/src/main/java/org/drools/compiler/kie/builder/impl/KieBuilderImpl.java
> +        String packageNameFromFolder = getRelativePackageName(folderNameForFile.replace( '/', '.' ));
Hi @mariofusco @baldimir - please bear with me 🙏 😄 
It may very well as you say, currently. 
My concern is that the method itself is "generic", and nothing prevent that an unexpected code path, now or in the future, will get there with different separator.
IMO currently the method works only by a series of hidden side-effects.
If it is possible to use my suggestion here, I think that method would be more robust.

Side-note: I just noticed
`int lastSep = fileName.lastIndexOf( "/" );`
at line 372, with the same issue.
The whole point of this discussion is that if all those methods are guaranteed to work ONLY with un underlying `KieMemoryFileSystem`, then this should be enforced as much as possible: does this make sense ?

(One sort of "hack" could be to add a `KieMemoryFileSystem` parameter to ththe involeved methods - even if unused - to be sure that this method get's invoked ONLY when there is an underlying `KieMemoryFileSystem`.)

2023-08-03 06:48 UTC, baldimir commented on drools-compiler/src/main/java/org/drools/compiler/kie/builder/impl/KieBuilderImpl.java
> +        String packageNameFromFolder = getRelativePackageName(folderNameForFile.replace( '/', '.' ));
Changing the separator here may actually break things. Because if the KIE memory file system uses "/" everywhere internally, and we start working with the OS dependant separator there, the replace method would stop working on e.g. Windows. If we want to do a review of file separators, I would advice to do it in a separate issue, because it would be a much more complex task than changing it only here. Would that be ok please? Currently all tests pass on Windows, except a random failure reported in MBeans test (which is random because it doesn't show up in the backported PRs and the tests and the code around are pretty much the same there as far as I know).

2023-08-03 07:15 UTC, gitgabrio commented on drools-compiler/src/main/java/org/drools/compiler/kie/builder/impl/KieBuilderImpl.java
> +        String packageNameFromFolder = getRelativePackageName(folderNameForFile.replace( '/', '.' ));
Thanks @baldimir.
fine for me

2023-08-03 07:16 UTC, gitgabrio approved these changes

2023-08-03 07:57 UTC, merged

2023-08-22 13:04 UTC, hellowdan commented
Hi @baldimir @mariofusco . Just a quick question: shouldn't this PR be merged into the 7.x branch as well?