[kie-issues#511] Migrate from jboss-parent to apache parent pom.
apache/incubator-kie pull request #5530
Opened 2023-09-19 13:12 UTC by baldimir

This is part of an effort from issue https://github.com/kiegroup/kie-issues/issues/511. 

- Changes root parent pom from jboss-parent to apache parent pom.xml. 
- Fixes the build by adding missing Java module names. 
- Aligns version property names with apache parent pom. 
- Adds missing version properties. 
- Adds JavaDoc plugin configuration so the JavaDoc generation is the same as before the migration. 

Sorry for some formatting changes, the formatting was wrong in those files.

2023-09-20 14:43 UTC, porcelli requested changes

2023-09-20 14:43 UTC, porcelli commented on drools-drl-quarkus-extension/drools-drl-quarkus/pom.xml
isn't anything missing here?

2023-09-20 14:43 UTC, porcelli commented on efesto/efesto-dependencies/pom.xml
> +    <skip.jdepend>false</skip.jdepend>
why this change from true to false?

2023-09-21 10:13 UTC, baldimir commented on efesto/efesto-dependencies/pom.xml
> +    <skip.jdepend>false</skip.jdepend>
Oh my mistake, I will fix.

2023-09-21 10:18 UTC, baldimir commented on drools-drl-quarkus-extension/drools-drl-quarkus/pom.xml
I will revert this file, as there are only formatting changes.

2023-09-21 10:21 UTC, baldimir commented
@porcelli I added fixes based on your comments. Please rereview.

2023-09-21 10:24 UTC, porcelli approved these changes
lgtm!

2023-09-21 11:12 UTC, jstastny-cz approved these changes
Looks good to me.

2023-09-21 11:52 UTC, mariofusco approved these changes

2023-09-22 11:58 UTC, merged