[kie-issues#745] Handle lists and maps in method calls and constructors in drools-mvel-compiler
apache/incubator-kie pull request #5617
Opened 2023-12-06 11:06 UTC by baldimir

Fixes https://github.com/apache/incubator-kie-issues/issues/745. 

- Adds maps and lists handling to drools-mvel-compiler. 
- Adds a collection type coercion for mvel empty list and map expression ambiguity ([] can be an empty list but also an empty map).

2023-12-06 15:56 UTC, lucamolteni requested changes

2023-12-06 15:56 UTC, lucamolteni commented on drools-model/drools-mvel-compiler/src/main/java/org/drools/mvelcompiler/MethodCallExprVisitor.java
> +            resolveMethodResult = MethodResolutionUtils.resolveMethodWithEmptyCollectionArguments(n, mvelCompilerContext, resolveMethodResult.b, arguments, emptyCollectionArgumentIndexes);
Can you please add unit tests in `drools-mvel-compiler` module covering this case?

2023-12-06 15:56 UTC, lucamolteni commented on drools-model/drools-mvel-compiler/src/main/java/org/drools/mvelcompiler/util/MethodResolutionUtils.java
> +        final int indexesListSize = emptyListArgumentIndexes.size();
Add unit tests for this method as well

2023-12-07 15:05 UTC, baldimir commented on drools-model/drools-mvel-compiler/src/main/java/org/drools/mvelcompiler/MethodCallExprVisitor.java
> +            resolveMethodResult = MethodResolutionUtils.resolveMethodWithEmptyCollectionArguments(n, mvelCompilerContext, resolveMethodResult.b, arguments, emptyCollectionArgumentIndexes);
Added.

2023-12-07 15:05 UTC, baldimir commented on drools-model/drools-mvel-compiler/src/main/java/org/drools/mvelcompiler/util/MethodResolutionUtils.java
> +        final int indexesListSize = emptyListArgumentIndexes.size();
Added.

2023-12-14 13:53 UTC, lucamolteni approved these changes

2023-12-15 09:42 UTC, gitgabrio approved these changes

2023-12-15 14:05 UTC, merged