Refactor Left and Right Tuples aligned with Super Cache improvements #5648
apache/incubator-kie pull request #5649
Opened 2024-01-12 16:24 UTC by mdproctor

More detail in the opened issue #5648.
https://github.com/apache/incubator-kie-drools/issues/5648

2024-01-15 07:59 UTC, mariofusco commented on bom/drools-bom/pom.xml
> +        <artifactId>drools-sivparvismagna</artifactId>
What is this new module? I don't see it in your pull request (and the name is very cryptic). If this is a leftover can you please remove this?

2024-01-15 07:59 UTC, mariofusco commented on pom.xml
> +        <!--module>drools-sicparvismagna</module-->
Please remove.

2024-01-15 07:59 UTC, mariofusco commented on pom.xml
> +        <module>drools-sivparvismagna</module>
Not existing new module, please remove.

2024-01-15 08:04 UTC, mariofusco commented on drools-base/src/main/java/org/drools/core/reteoo/ObjectTypeNodeId.java
> +package org.drools.core.reteoo;
Missing Apache header.

2024-01-15 09:00 UTC, mariofusco commented on drools-core/src/main/java/org/drools/core/common/NodeMemories.java
> +            System.out.println("pause");
Remove this `System.out`

2024-01-15 09:13 UTC, mariofusco commented on drools-core/src/main/java/org/drools/core/common/SuperCacheFixer.java
> +        switch (((BaseNode) s).getType()) {
Unnecessary cast.

2024-01-15 09:13 UTC, mariofusco commented on drools-core/src/main/java/org/drools/core/common/SuperCacheFixer.java
> +        switch (((BaseNode) s).getType()) {
Unnecessary cast.

2024-01-15 09:14 UTC, mariofusco commented on drools-core/src/main/java/org/drools/core/common/SuperCacheFixer.java
> +        switch (((BaseNode) n).getType()) {
Unnecessary cast.

2024-01-15 09:14 UTC, mariofusco commented on drools-core/src/main/java/org/drools/core/common/SuperCacheFixer.java
> +        switch (((BaseNode)n).getType()) {
Unnecessary cast.

2024-01-15 09:14 UTC, mariofusco commented on drools-core/src/main/java/org/drools/core/common/SuperCacheFixer.java
> +        switch (((BaseNode) s).getType()) {
Unnecessary cast.

2024-01-15 09:14 UTC, mariofusco commented on drools-core/src/main/java/org/drools/core/common/SuperCacheFixer.java
> +        switch (((BaseNode) s).getType()) {
Unnecessary cast.

2024-01-15 09:14 UTC, mariofusco commented on drools-core/src/main/java/org/drools/core/common/SuperCacheFixer.java
> +        switch (((BaseNode) s).getType()) {
Unnecessary cast.

2024-01-15 09:14 UTC, mariofusco commented on drools-core/src/main/java/org/drools/core/common/SuperCacheFixer.java
> +        switch (((BaseNode) s).getType()) {
Unnecessary cast.

2024-01-15 09:16 UTC, mariofusco commented on drools-core/src/main/java/org/drools/core/common/SuperCacheFixer.java
> +        switch (n.getType()) {
Wouldn't be better to collapse these 2 subsequent switches into a single one?

2024-01-15 09:17 UTC, mariofusco commented on drools-core/src/main/java/org/drools/core/common/SuperCacheFixer.java
> +        switch (o.getType()) {
Wouldn't be better to collapse these 2 subsequent switches into a single one?

2024-01-15 09:17 UTC, mariofusco commented on drools-core/src/main/java/org/drools/core/common/SuperCacheFixer.java
> +        switch (((BaseNode) s).getType()) {
Unnecessary cast.

2024-01-15 09:18 UTC, mariofusco commented on drools-core/src/main/java/org/drools/core/common/SuperCacheFixer.java
> +        switch (((BaseNode) t.getSink()).getType()) {
Unnecessary cast.

2024-01-15 09:18 UTC, mariofusco commented on drools-core/src/main/java/org/drools/core/common/SuperCacheFixer.java
> +        switch (((BaseNode)n).getType()) {
Unnecessary cast.

2024-01-15 09:54 UTC, mariofusco commented on drools-core/src/main/java/org/drools/core/reteoo/BetaMemory.java
> +public interface BetaMemory<C> {
Is it necessary to introduce this interface? Maybe I'm missing something but I see only one implementation.

2024-01-15 10:20 UTC, mariofusco requested changes
Great work, thanks for this refactor, it's much cleaner now. Please only review my comments, especially the ones on the unnecessary new module declaration.

2024-01-15 14:36 UTC, mdproctor commented on bom/drools-bom/pom.xml
> +        <artifactId>drools-sivparvismagna</artifactId>
Oh that is a mistake, let me fix that :) didn't realis that was still in there.

2024-01-15 14:36 UTC, mdproctor commented on drools-core/src/main/java/org/drools/core/common/SuperCacheFixer.java
> +        switch (((BaseNode) s).getType()) {
I thought this was needed, when working against interfaces -  to avoid potential super cache issues?

2024-01-15 23:34 UTC, mdproctor commented on drools-core/src/main/java/org/drools/core/reteoo/BetaMemory.java
> +public interface BetaMemory<C> {
Sorry, this was related to some work I did initially. I can revert for now. I wanted to move stuff out of core and avoid bringing too much into -base.

2024-01-16 00:32 UTC, mdproctor commented on drools-core/src/main/java/org/drools/core/common/SuperCacheFixer.java
> +        switch (o.getType()) {
That is not possible because we don't know the concrete type of getLeftTupleSource(), so it needs a second switch. However, this is only true if performance is improved via the concrete cast. If this cast adds no perf value, it can be removed.

2024-01-16 07:26 UTC, mariofusco approved these changes

2024-01-16 07:59 UTC, tkobayas commented
Benchmark result:
```
ConcurrentUpdateLeftTupleBenchmark

* without PR

Benchmark                                (factsNr)  (joinsNr)  (rulesNr)  Mode  Cnt     Score     Error  Units
ConcurrentUpdateLeftTupleBenchmark.test         15          3         32    ss   20  3101.654 ± 276.084  ms/op

* with PR

Benchmark                                (factsNr)  (joinsNr)  (rulesNr)  Mode  Cnt     Score     Error  Units
ConcurrentUpdateLeftTupleBenchmark.test         15          3         32    ss   20  2797.595 ± 283.705  ms/op


ConcurrentUpdateRightTupleBenchmark

* without PR

Benchmark                                 (factsNr)  (joinsNr)  (rulesNr)  Mode  Cnt     Score     Error  Units
ConcurrentUpdateRightTupleBenchmark.test         15          3         32    ss   20  5597.697 ± 262.842  ms/op

* with PR

Benchmark                                 (factsNr)  (joinsNr)  (rulesNr)  Mode  Cnt     Score     Error  Units
ConcurrentUpdateRightTupleBenchmark.test         15          3         32    ss   20  5481.104 ± 235.062  ms/op
```

2024-01-16 07:59 UTC, tkobayas approved these changes

2024-01-17 04:22 UTC, tkobayas commented
type pollution report (omitting types count less than 10000)
* ConcurrentUpdateLeftTupleBenchmark

== without PR
```
--------------------------
1:	org.drools.core.reteoo.NotNode
Count:	83205982
Types:
	org.drools.core.reteoo.LeftTupleSinkNode
	org.drools.core.reteoo.LeftTupleSink
	org.drools.core.reteoo.ObjectSinkNode
	org.drools.core.common.MemoryFactory
Traces:
	org.drools.core.reteoo.SingleLeftTupleSinkAdapter.getFirstLeftTupleSink(SingleLeftTupleSinkAdapter.java:67)
		class: org.drools.core.reteoo.LeftTupleSinkNode
		count: 41860897
	org.drools.core.reteoo.LeftTuple.getTupleSink(LeftTuple.java:361)
		class: org.drools.core.reteoo.LeftTupleSink
		count: 41344435
	org.drools.core.reteoo.CompositeObjectSinkAdapter.propagateAssertObject(CompositeObjectSinkAdapter.java:599)
		class: org.drools.core.reteoo.ObjectSinkNode
		count: 452
	org.drools.core.reteoo.CompositeObjectSinkAdapter.addObjectSink(CompositeObjectSinkAdapter.java:196)
		class: org.drools.core.reteoo.ObjectSinkNode
		count: 96
	org.drools.core.common.BaseNode.initMemoryId(BaseNode.java:99)
		class: org.drools.core.common.MemoryFactory
		count: 95
	org.drools.core.reteoo.CompositeObjectSinkAdapter.getSinks(CompositeObjectSinkAdapter.java:854)
		class: org.drools.core.reteoo.ObjectSinkNode
		count: 7
--------------------------
2:	org.drools.tms.agenda.TruthMaintenanceSystemRuleTerminalNodeLeftTuple
Count:	4069573
Types:
	org.drools.core.rule.consequence.InternalMatch
	org.drools.core.reteoo.Tuple
Traces:
	org.drools.core.phreak.RuleExecutor.getNextTuple(RuleExecutor.java:198)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 2016240
	org.drools.core.util.index.TupleList.removeFirst(TupleList.java:152)
		class: org.drools.core.reteoo.Tuple
		count: 2015803
	org.drools.core.phreak.RuleExecutor.fire(RuleExecutor.java:143)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 15151
	org.drools.core.phreak.PhreakRuleTerminalNode.doLeftTupleInsert(PhreakRuleTerminalNode.java:114)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 13121
	org.drools.core.phreak.RuleExecutor.addLeftTuple(RuleExecutor.java:289)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 9226
	org.drools.mvel.asm.ConsequenceGenerator.generate(ConsequenceGenerator.java:45)
		class: org.drools.core.reteoo.Tuple
		count: 32
--------------------------
```

== with PR (pr5649 "Added missing headers" commit)
```
--------------------------
1:	org.drools.tms.agenda.TruthMaintenanceSystemRuleTerminalNodeLeftTuple
Count:	3029318
Types:
	org.drools.core.rule.consequence.InternalMatch
	org.drools.core.util.DoubleLinkedEntry
	org.drools.core.reteoo.Tuple
Traces:
	org.drools.core.util.LinkedList.removeFirst(LinkedList.java:197)
		class: org.drools.core.util.DoubleLinkedEntry
		count: 1497283
	org.drools.core.phreak.RuleExecutor.getNextTuple(RuleExecutor.java:199)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 1362485
	org.drools.core.phreak.PhreakRuleTerminalNode.doLeftTupleInsert(PhreakRuleTerminalNode.java:115)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 89743
	org.drools.core.phreak.RuleExecutor.fire(RuleExecutor.java:144)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 79775
	org.drools.mvel.asm.ConsequenceGenerator.generate(ConsequenceGenerator.java:45)
		class: org.drools.core.reteoo.Tuple
		count: 32
--------------------------
2:	org.drools.core.reteoo.BetaMemoryImpl
Count:	87889
Types:
	org.drools.core.common.Memory
	org.drools.core.reteoo.BetaMemory
	org.drools.core.util.DoubleLinkedEntry
Traces:
	org.drools.core.reteoo.BetaNode.getBetaMemoryFromRightInput(BetaNode.java:654)
		class: org.drools.core.reteoo.BetaMemory
		count: 40561
	org.drools.core.common.ConcurrentNodeMemories.getNodeMemory(ConcurrentNodeMemories.java:91)
		class: org.drools.core.common.Memory
		count: 39438
	org.drools.core.util.AbstractLinkedListNode.setNext(AbstractLinkedListNode.java:30)
		class: org.drools.core.util.DoubleLinkedEntry
		count: 3561
	org.drools.core.phreak.LazyPhreakBuilder.createSegmentMemory(LazyPhreakBuilder.java:1468)
		class: org.drools.core.common.Memory
		count: 3070
	org.drools.core.reteoo.BetaNode.createMemory(BetaNode.java:533)
		class: org.drools.core.common.Memory
		count: 1258
	org.drools.core.phreak.RuleNetworkEvaluator.innerEval(RuleNetworkEvaluator.java:362)
		class: org.drools.core.common.Memory
		count: 1
--------------------------
```

==  with PR (pr5649 "minor semplifications" commit)
```
--------------------------
1:	org.drools.tms.agenda.TruthMaintenanceSystemRuleTerminalNodeLeftTuple
Count:	3130495
Types:
	org.drools.core.rule.consequence.InternalMatch
	org.drools.core.util.DoubleLinkedEntry
	org.drools.core.reteoo.Tuple
Traces:
	org.drools.core.phreak.RuleExecutor.getNextTuple(RuleExecutor.java:199)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 1544318
	org.drools.core.util.LinkedList.removeFirst(LinkedList.java:197)
		class: org.drools.core.util.DoubleLinkedEntry
		count: 1449059
	org.drools.core.phreak.PhreakRuleTerminalNode.doLeftTupleInsert(PhreakRuleTerminalNode.java:115)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 85686
	org.drools.core.phreak.RuleExecutor.fire(RuleExecutor.java:144)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 51400
	org.drools.mvel.asm.ConsequenceGenerator.generate(ConsequenceGenerator.java:45)
		class: org.drools.core.reteoo.Tuple
		count: 32
--------------------------
```

2024-01-17 04:23 UTC, tkobayas commented
* ConcurrentUpdateRightTupleBenchmark

== without PR
```
--------------------------
1:	org.drools.tms.agenda.TruthMaintenanceSystemRuleTerminalNodeLeftTuple
Count:	3804433
Types:
	org.drools.core.reteoo.Tuple
	org.drools.core.rule.consequence.InternalMatch
Traces:
	org.drools.core.util.index.TupleList.removeFirst(TupleList.java:152)
		class: org.drools.core.reteoo.Tuple
		count: 1917615
	org.drools.core.phreak.RuleExecutor.getNextTuple(RuleExecutor.java:198)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 1767759
	org.drools.core.phreak.RuleExecutor.fire(RuleExecutor.java:143)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 67069
	org.drools.core.phreak.PhreakRuleTerminalNode.doLeftTupleInsert(PhreakRuleTerminalNode.java:114)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 32121
	org.drools.core.phreak.RuleExecutor.addLeftTuple(RuleExecutor.java:289)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 19837
	org.drools.mvel.asm.ConsequenceGenerator.generate(ConsequenceGenerator.java:45)
		class: org.drools.core.reteoo.Tuple
		count: 32
--------------------------
2:	org.drools.core.reteoo.JoinNode
Count:	359517
Types:
	org.drools.core.reteoo.ObjectSinkNode
	org.drools.core.reteoo.LeftTupleSinkNode
	org.drools.core.common.MemoryFactory
Traces:
	org.drools.core.reteoo.CompositeObjectSinkAdapter.propagateModifyObject(CompositeObjectSinkAdapter.java:670)
		class: org.drools.core.reteoo.ObjectSinkNode
		count: 203013
	org.drools.core.reteoo.LeftTuple.toFactHandles(LeftTuple.java:424)
		class: org.drools.core.reteoo.LeftTupleSinkNode
		count: 154308
	org.drools.core.reteoo.SingleLeftTupleSinkAdapter.getFirstLeftTupleSink(SingleLeftTupleSinkAdapter.java:67)
		class: org.drools.core.reteoo.LeftTupleSinkNode
		count: 1931
	org.drools.core.reteoo.CompositeObjectSinkAdapter.addObjectSink(CompositeObjectSinkAdapter.java:196)
		class: org.drools.core.reteoo.ObjectSinkNode
		count: 96
	org.drools.core.common.BaseNode.initMemoryId(BaseNode.java:99)
		class: org.drools.core.common.MemoryFactory
		count: 95
	org.drools.core.reteoo.CompositeObjectSinkAdapter.propagateAssertObject(CompositeObjectSinkAdapter.java:599)
		class: org.drools.core.reteoo.ObjectSinkNode
		count: 69
	org.drools.core.reteoo.CompositeObjectSinkAdapter.getSinks(CompositeObjectSinkAdapter.java:854)
		class: org.drools.core.reteoo.ObjectSinkNode
		count: 5
--------------------------
```

== with PR (pr5649 "Added missing headers" commit)
```
--------------------------
1:	org.drools.tms.agenda.TruthMaintenanceSystemRuleTerminalNodeLeftTuple
Count:	3823320
Types:
	org.drools.core.util.DoubleLinkedEntry
	org.drools.core.rule.consequence.InternalMatch
	org.drools.core.reteoo.Tuple
Traces:
	org.drools.core.util.LinkedList.removeFirst(LinkedList.java:197)
		class: org.drools.core.util.DoubleLinkedEntry
		count: 1914022
	org.drools.core.phreak.RuleExecutor.getNextTuple(RuleExecutor.java:199)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 1762549
	org.drools.core.phreak.RuleExecutor.fire(RuleExecutor.java:144)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 89180
	org.drools.core.phreak.PhreakRuleTerminalNode.doLeftTupleInsert(PhreakRuleTerminalNode.java:115)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 57537
	org.drools.mvel.asm.ConsequenceGenerator.generate(ConsequenceGenerator.java:45)
		class: org.drools.core.reteoo.Tuple
		count: 32
--------------------------
2:	org.drools.core.reteoo.JoinNode
Count:	162346
Types:
	org.drools.core.reteoo.ObjectSinkNode
	org.drools.core.reteoo.LeftTupleSinkNode
	org.drools.core.common.MemoryFactory
Traces:
	org.drools.core.reteoo.CompositeObjectSinkAdapter.propagateModifyObject(CompositeObjectSinkAdapter.java:670)
		class: org.drools.core.reteoo.ObjectSinkNode
		count: 91535
	org.drools.core.reteoo.TupleImpl.toFactHandles(TupleImpl.java:282)
		class: org.drools.core.reteoo.LeftTupleSinkNode
		count: 70620
	org.drools.core.reteoo.CompositeObjectSinkAdapter.addObjectSink(CompositeObjectSinkAdapter.java:196)
		class: org.drools.core.reteoo.ObjectSinkNode
		count: 96
	org.drools.core.common.BaseNode.initMemoryId(BaseNode.java:100)
		class: org.drools.core.common.MemoryFactory
		count: 95
--------------------------
3:	org.drools.core.reteoo.BetaMemoryImpl
Count:	86988
Types:
	org.drools.core.common.Memory
	org.drools.core.reteoo.BetaMemory
	org.drools.core.util.DoubleLinkedEntry
Traces:
	org.drools.core.reteoo.BetaNode.getBetaMemoryFromRightInput(BetaNode.java:654)
		class: org.drools.core.reteoo.BetaMemory
		count: 41145
	org.drools.core.common.ConcurrentNodeMemories.getNodeMemory(ConcurrentNodeMemories.java:91)
		class: org.drools.core.common.Memory
		count: 38228
	org.drools.core.util.AbstractLinkedListNode.setNext(AbstractLinkedListNode.java:30)
		class: org.drools.core.util.DoubleLinkedEntry
		count: 3530
	org.drools.core.phreak.LazyPhreakBuilder.createSegmentMemory(LazyPhreakBuilder.java:1468)
		class: org.drools.core.common.Memory
		count: 2969
	org.drools.core.reteoo.BetaNode.createMemory(BetaNode.java:533)
		class: org.drools.core.common.Memory
		count: 1113
	org.drools.core.phreak.RuleNetworkEvaluator.innerEval(RuleNetworkEvaluator.java:362)
		class: org.drools.core.common.Memory
		count: 3
--------------------------
```

== with PR (pr5649 "minor semplifications" commit)
```
--------------------------
1:	org.drools.tms.agenda.TruthMaintenanceSystemRuleTerminalNodeLeftTuple
Count:	3630033
Types:
	org.drools.core.util.DoubleLinkedEntry
	org.drools.core.rule.consequence.InternalMatch
	org.drools.core.reteoo.Tuple
Traces:
	org.drools.core.util.LinkedList.removeFirst(LinkedList.java:197)
		class: org.drools.core.util.DoubleLinkedEntry
		count: 1836328
	org.drools.core.phreak.RuleExecutor.getNextTuple(RuleExecutor.java:199)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 1660350
	org.drools.core.phreak.RuleExecutor.fire(RuleExecutor.java:144)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 79263
	org.drools.core.phreak.PhreakRuleTerminalNode.doLeftTupleInsert(PhreakRuleTerminalNode.java:115)
		class: org.drools.core.rule.consequence.InternalMatch
		count: 54060
	org.drools.mvel.asm.ConsequenceGenerator.generate(ConsequenceGenerator.java:45)
		class: org.drools.core.reteoo.Tuple
		count: 32
--------------------------
2:	org.drools.core.reteoo.JoinNode
Count:	108901
Types:
	org.drools.core.reteoo.ObjectSinkNode
	org.drools.core.reteoo.LeftTupleSinkNode
	org.drools.core.common.MemoryFactory
Traces:
	org.drools.core.reteoo.CompositeObjectSinkAdapter.propagateModifyObject(CompositeObjectSinkAdapter.java:670)
		class: org.drools.core.reteoo.ObjectSinkNode
		count: 59360
	org.drools.core.reteoo.TupleImpl.toFactHandles(TupleImpl.java:282)
		class: org.drools.core.reteoo.LeftTupleSinkNode
		count: 49350
	org.drools.core.reteoo.CompositeObjectSinkAdapter.addObjectSink(CompositeObjectSinkAdapter.java:196)
		class: org.drools.core.reteoo.ObjectSinkNode
		count: 96
	org.drools.core.common.BaseNode.initMemoryId(BaseNode.java:100)
		class: org.drools.core.common.MemoryFactory
		count: 95
--------------------------
```

2024-01-17 07:43 UTC, merged