[kie-issues#903] Add reflect-config.json files related to drools-commands.
apache/incubator-kie pull request #5671
Opened 2024-02-02 15:09 UTC by baldimir

Fixes https://github.com/apache/incubator-kie-issues/issues/903.

2024-02-02 15:46 UTC, yesamer approved these changes

2024-02-05 07:56 UTC, mariofusco approved these changes

2024-02-05 08:05 UTC, gitgabrio requested changes
thanks @baldimir 
THose changes seems fine, but we need a test to verify
1) they does not break anything
2) that solve the issue they are required for

Could you please create a kogito-example that makes use of such classes and pair with this PR ? THanks

2024-02-07 10:01 UTC, baldimir commented
After discussion with Gabriele, I am merging this.

2024-02-07 10:01 UTC, merged