[kie-issues#1330] `context` and `context merge` missing functionalities
apache/incubator-kie pull request #5997
Opened 2024-06-19 09:49 UTC by yesamer

According to the TCK tests, `context` and `context merge` are missing the following functionalities:

- `context` should throw an error when providing objects with the same keys
- `context` and `context merge` should be invocable with a single element

2024-06-19 10:57 UTC, gitgabrio commented
@yesamer @baldimir 
I'm not 100% sure of the underlying problem.
From the spec, I see that both `context`and `context merge` requires a `list` of contexts.
I agree that the list could contain only one single item, but regardless the dmn model should define it as list, e.g.

`[context_parameter]` instead of `context_parameter`.

WIth this fix, we are basically
1. create a new "method" that accept a single element (not defined by DMN spec)
2. behind the scene, invoke the correct one, with a single-element list.

If my understanding is correct, it would mean that users could create an invalid model, that works only with our implementation.

Does this make sense ? Am I wrong on some assumption ?

2024-06-19 11:48 UTC, yesamer commented
@gitgabrio I agree with you, but the point is that the TCK tests expect that kind of behavior. That means other vendors that successfully perform the TCK tests already implemented that. So, the alternative to merging this PR is to raise this point to the TCK meeting and double-check if those tests are correct or not, considering that the specs don't define those methods specifically.

2024-06-19 11:53 UTC, gitgabrio commented
> @gitgabrio I agree with you, but the point is that the TCK tests expect that kind of behavior. That means other vendors that successfully perform the TCK tests already implemented that. So, the alternative to merging this PR is to raise this point to the TCK meeting and double-check if those tests are correct or not, considering that the specs don't define those methods specifically.

Yup, exactly. 
IIUC the process, those tests does not comes from the committee itself, but from the tck group that, again IIUC, does not have any real ownership on the specs.
If those tests does not reflect the actual spec, then they are invalid, and I'm not sure why they are there and why, if, that behavior has been implemented. 
If all the above is true, IMO, those tests (and all the others that does not reflect the actual spec) should be deleted.

2024-06-19 11:57 UTC, yesamer commented
Ok, let's put this on hold and raise the point at the TCK meeting

2024-06-19 12:40 UTC, kie-ci3 commented
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/5997 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5997/1/display/redirect

**Test results:**
- PASSED: 22041
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5997/1/testReport/org.kie.dmn.feel.runtime/KieFEELExtendedFunctionsTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[153]/">org.kie.dmn.feel.runtime.KieFEELExtendedFunctionsTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[153]</a></summary>
[Evaluating: 'context([{key: "name", value: "John Doe"},{"key": "age", "value": null}])'] <br/>expected: null<br/> but was: {"age"=null, "name"="John Doe"}
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5997/1/testReport/org.kie.dmn.feel.runtime/KieFEELExtendedFunctionsTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[154]/">org.kie.dmn.feel.runtime.KieFEELExtendedFunctionsTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[154]</a></summary>
[Evaluating: 'context([{key: "name", value: "John Doe"},{"key": "age", "value": null}])'] <br/>expected: null<br/> but was: {"age"=null, "name"="John Doe"}
</details>

2024-06-20 18:15 UTC, kie-ci3 commented
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/5997 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5997/3/display/redirect

**Test results:**
- PASSED: 22047
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5997/3/testReport/org.kie.dmn.signavio.feel.runtime/FEELExtendedFunctionsTest/instanceTest(String,_Object,_Severity)[324]/">org.kie.dmn.signavio.feel.runtime.FEELExtendedFunctionsTest.instanceTest(String, Object, Severity)[324]</a></summary>
[Evaluating: 'concat("abc")'] <br/>expected: "abc"<br/> but was: null
</details>

2024-06-21 07:27 UTC, baldimir commented
Is this ready for review after the discussions? The coercion from list with a single item to single item and vice versa is defined in the spec in 10.3.2.9.4 Type conversions. The TCK tests are valid.

2024-06-21 11:33 UTC, yesamer commented
@baldimir Still a WIP

2024-06-21 12:54 UTC, kie-ci3 commented
**PR job** `#5` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/5997 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5997/5/display/redirect

**Test results:**
- PASSED: 22138
- FAILED: 48

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5997/5/testReport/org.kie.dmn.core/DMNRuntimeTest/ex61(boolean)[1]/">org.kie.dmn.core.DMNRuntimeTest.ex61(boolean)[1]</a></summary>
[Message [id=0, level=ERROR, path=Ex_6_1.dmn, line=159, column=-1<br/>   text=DMN: FEEL ERROR while evaluating literal expression 'sum(NBA Pacific.bonus points)': The parameter 'list', in function sum(), an element in the list is not a number. (DMN id: _decisionbonuspointsliteralexpression, FEEL expression evaluation error) ]<br/>Message [id=0, level=ERROR, path=Ex_6_1.dmn, line=103, column=-1<br/>   text=DMN: FEEL ERROR while evaluating literal expression 'mean(NBA Pacific.wins)': The parameter 'list', in function mean(), unable to sum the elements which is required to calculate the mean. (DMN id: _5d95b79e-1500-4206-95c3-123831f7aabe, FEEL expression evaluation error) ]] <br/>Expecting value to be false but was true
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-5997/5/testReport/org.kie.dmn.core.v1_4/DMN14specificTest/dMNv14Ch11Example2(VariantTestConf)[1]/">org.kie.dmn.core.v1_4.DMN14specificTest.dMNv14Ch11Example2(VariantTestConf)[1]</a></summary>
[Message [id=0, level=ERROR, path=Recommended Loan Products.dmn, line=1056, column=-1<br/>   text=DMN: FEEL ERROR while evaluating literal expression 'sum([Loan Info.Qualifying Monthly Payment, Propert... [string clipped after 50 chars, total length is 155]': The parameter 'list', in function sum(), an element in the list is not a number. (DMN id: _f0f68868-ef1c-455d-a438-fd91c7378b16, FEEL expression evaluation error) ]<br/>Message [id=0, level=ERROR, path=Recommended Loan Products.dmn, line=1053, column=-1<br/>   text=DMN: Error evaluating context extry 'Housing Expense' on context 'Eligibility Parameters' (DMN id: _d4558837-ad20-4ed3-8099-e5142be3797c, Error evaluating context or context entry) ]<br/>Message [id=0, level=WARNING, path=Recommended Loan Products.dmn, line=452, column=-1<br/>   text=DMN: No rule matched for decision table 'Min Credit Score' and no default values were defined. Setting result to null. (DMN id: _a6e2c692-4a0c-4385-bbc3-7280e94a8760, FEEL expression evaluation error) ]<br/>Message [id=0, level=ERROR, path=Recommended Loan Products.dmn, line=827, column=-1<br/>   text=DMN: Unrecoverable error evaluating context extry 'Required Credit Score' on context 'Eligibility': Cannot invoke "Object.toString()" because "r" is null (DMN id: _fbf39f7b-79c3-470c-82ff-62d685f1f297, Error evaluating context or context entry) ]<br/>Message [id=0, level=ERROR, path=Recommended Loan Products.dmn, line=1056, column=-1<br/>   text=DMN: FEEL ERROR while evaluating literal expression 'sum([Loan Info.Qualifying Monthly Payment, Propert... [string clipped after 50 chars, total length is 155]': The parameter 'list', in function sum(), an element in the list is not a number. (DMN id: _f0f68868-ef1c-455d-a438-fd91c7378b16, FEEL expression evaluation error) ]<br/>Message [id=0, level=ERROR, path=Recommended Loan Products.dmn, line=1053, column=-1<br/>   text=DMN: Error evaluating context extry 'Housing Expense' on context 'Eligibility Parameters' (DMN id: _d4558837-ad20-4ed3-8099-e5142be3797c, Error evaluating context or context entry) ]<br/>Message [id=0, level=WARNING, path=Recommended Loan Products.dmn, line=452, column=-1<br/>   text=DMN: No rule matched for decision table 'Min Credit Score' and no default values were defined. Setting result to null. (DMN id: _a6e2c692-4a0c-4385-bbc3-7280e94a8760, FEEL expression evaluation error) ]<br/>Message [id=0, level=ERROR, path=Recommended Loan Products.dmn, line=827, column=-1<br/>   text=DMN: Unrecoverable error evaluating context extry 'Required Credit Score' on context 'Eligibility': Cannot invoke "Object.toString()" because "r" is null (DMN id: _fbf39f7b-79c3-470c-82ff-62d685f1f297, Error evaluating context or context entry) ]<br/>Message [id=0, level=ERROR, path=Recommended Loan Products.dmn, line=1056, column=-1<br/>   text=DMN: FEEL ERROR while evaluating literal expression 'sum([Loan Info.Qualifying Monthly Payment, Propert... [string clipped after 50 chars, total length is 155]': The parameter 'list', in function sum(), an element in the list is not a number. (DMN id: _f0f68868-ef1c-455d-a438-fd91c7378b16, FEEL expression evaluation error) ]<br/>Message [id=0, level=ERROR, path=Recommended Loan Products.dmn, line=1053, column=-1<br/>   text=DMN: Error evaluating context extry 'Housing Expense' on context 'Eligibility Parameters' (DMN id: _d4558837-ad20-4ed3-8099-e5142be3797c, Error evaluating context or context entry) ]<br/>Message [id=0, level=WARNING, path=Recommended Loan Products.dmn, line=452, column=-1<br/>   text=DMN: No rule matched for decision table 'Min Credit Score' and no default values were defined. Setting result to null. (DMN id: _a6e2c692-4a0c-4385-bbc3-7280e94a8760, FEEL expression evaluation error) ]<br/>Message [id=0, level=ERROR, path=Recommended Loan Products.dmn, line=827, column=-1<br/>   text=DMN: Unrecoverable error evaluating context extry 'Required Credit Score' on context 'Eligibility': Cannot invoke "Object.toString()" because "r" is null (DMN id: _fbf39f7b-79c3-470c-82ff-62d685f1f297, Error evaluating context or context entry) ]<br/>Message [id=0, level=ERROR, path=Recommended Loan Products.dmn, line=1056, column=-1<br/>   text=DMN: FEEL ERROR while evaluating literal expression 'sum([Loan Info.Qualifying Monthly Payment, Propert... [string clipped after 50 chars, total length is 155]': The parameter 'list', in function sum(), an element in the list is not a number. (DMN id: _f0f68868-ef1c-455d-a438-fd91c7378b16, FEEL expression evaluation error) ]<br/>Message [id=0, level=ERROR, path=Recommended Loan Products.dmn, line=1053, column=-1<br/>   text=DMN: Error evaluating context extry 'Housing Expense' on context 'Eligibility Parameters' (DMN id: _d4558837-ad20-4ed3-8099-e5142be3797c, Error evaluating context or context entry) ]<br/>Message [id=0, level=WARNING, path=Recommended Loan Products.dmn, line=452, column=-1<br/>   text=DMN: No rule matched for decision table 'Min Credit Score' and no default values were defined. Setting result to null. (DMN id: _a6e2c692-4a0c-4385-bbc3-7280e94a8760, FEEL expression evaluation error) ]<br/>Message [id=0, level=ERROR, path=Recommended Loan Products.dmn, line=827, column=-1<br/>   text=DMN: Unrecoverable error evaluating context extry 'Required Credit Score' on context 'Eligibility': Cannot invoke "Object.toString()" because "r" is null (DMN id: _fbf39f7b-79c3-470c-82ff-62d685f1f297, Error evaluating context or context entry) ]<br/>Message [id=0, level=ERROR, path=Recommended Loan Products.dmn, line=1056, column=-1<br/>   text=DMN: FEEL ERROR while evaluating literal expression 'sum([Loan Info.Qualifying Monthly Payment, Propert... [string clipped after 50 chars, total length is 155]': The parameter 'list', in function sum(), an element in the list is not a number. (DMN id: _f0f68868-ef1c-455d-a438-fd91c7378b16, FEEL expression evaluation error) ]<br/>Message  [...]

2024-06-27 07:52 UTC, baldimir approved these changes

2024-06-27 09:20 UTC, yesamer commented
@gitgabrio @baldimir Ready to be reviewed

2024-06-27 11:02 UTC, gitgabrio requested changes
HI @yesamer 
You may be right, but it seems to me there are too many changes for this feature.

2024-06-27 11:02 UTC, gitgabrio commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/compiler/profiles/ExtendedDMNProfileTest.java
> +    private final EvenFunction evenFunction = EvenFunction.INSTANCE;
Hi @yesamer 
This class does not make sense to me:
1. it does not test any "profile" at all
2. it just tests a bunch of functions, most of which are not even extended, and that are already tested by themselves
Could you please double check and put those functions tests to specific test classes ?

2024-06-27 11:02 UTC, gitgabrio commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/AllFunction.java
> -    public FEELFnResult<Boolean> invoke(@ParameterName( "list" ) Boolean single) {
are you sure of that removeal ? IIUC, this would invalidate `all(true|false)`, and I'm not sure if this is expected or not

2024-06-27 11:02 UTC, gitgabrio commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/AnyFunction.java
> -    public FEELFnResult<Boolean> invoke(@ParameterName( "list" ) Boolean single) {
see above comment

2024-06-27 11:02 UTC, gitgabrio commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/BaseFEELFunction.java
> +        if ( !pnames.isEmpty() ) {
😄

2024-06-27 11:02 UTC, gitgabrio commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/BaseFEELFunction.java
> +                        cm.setActualParams(coercedParams.get(), CandidateMethod.ParameterTypesStatus.COERCED);
let's discuss of that, I would need to understand exactly reason and consequences

2024-06-27 11:02 UTC, gitgabrio commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/BaseFEELFunction.java
> +            cm.setActualParams( newParams , CandidateMethod.ParameterTypesStatus.VARIABLE_PARAMETER_FUNCTION_CALL );
as above

2024-07-17 08:18 UTC, gitgabrio approved these changes
Thx @yesamer LGTM!

2024-07-17 12:19 UTC, merged