Kie issues#1448 - matches() function wrongly behaves - negation syntax translation
apache/incubator-kie pull request #6083
Opened 2024-09-13 12:01 UTC by bncriju

Fixes https://github.com/apache/incubator-kie-issues/issues/1448

**Thank you for submitting this pull request**

**NOTE!:** Double-check the target branch for this PR.
The default is `main` so it will target Drools 8 / Kogito.

**Ports** If a forward-port or a backport is needed, paste the forward port PR here

* [link](https://www.example.com)

**Issue**: _(please edit the GitHub Issues link if it exists)_

* [link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request and downstream checks</b>  
  - Push a new commit to the PR. An empty commit would be enough.

- for a <b>full downstream build</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- for <b>Jenkins PR check only</b>
  - If you are an ASF committer for KIE podling, login to Jenkins (https://ci-builds.apache.org/job/KIE/job/drools/), go to the specific PR job, and click on `Build Now` button.
</details>

2024-09-13 14:56 UTC, kie-ci3 commented
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-drools -u https://github.com/apache/incubator-kie-drools/pull/6083 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6083/1/display/redirect

**Test results:**
- PASSED: 22320
- FAILED: 31

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6083/1/testReport/org.kie.dmn.feel.documentation/ADocFEELExamplesTest/test/">org.kie.dmn.feel.documentation.ADocFEELExamplesTest.test</a></summary>
Cannot invoke "java.net.URL.toURI()" because "resource" is null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6083/1/testReport/org.kie.dmn.feel.documentation/FromSpecificationNotInAdocTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[21]/">org.kie.dmn.feel.documentation.FromSpecificationNotInAdocTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[21]</a></summary>
[Evaluating: 'matches("foobar", "^fo*b") = true'] <br/>expected: true<br/> but was: false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6083/1/testReport/org.kie.dmn.feel.documentation/FromSpecificationNotInAdocTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[22]/">org.kie.dmn.feel.documentation.FromSpecificationNotInAdocTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[22]</a></summary>
[Evaluating: 'matches("foobar", "^fo*b") = true'] <br/>expected: true<br/> but was: false
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6083/1/testReport/org.kie.dmn.feel.runtime/FEELFunctionsTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[3]/">org.kie.dmn.feel.runtime.FEELFunctionsTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[3]</a></summary>
[Evaluating: 'replace( "  foo   bar zed  ", "^(\s)+|(\s)+$|\s+(?=\s)", "" )'] <br/>expected: "foo bar zed"<br/> but was: null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6083/1/testReport/org.kie.dmn.feel.runtime/FEELFunctionsTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[4]/">org.kie.dmn.feel.runtime.FEELFunctionsTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[4]</a></summary>
[Evaluating: 'replace( "  foo   bar zed  ", "^(\s)+|(\s)+$|\s+(?=\s)", "" )'] <br/>expected: "foo bar zed"<br/> but was: null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6083/1/testReport/org.kie.dmn.feel.runtime/FEELFunctionsTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[71]/">org.kie.dmn.feel.runtime.FEELFunctionsTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[71]</a></summary>
[Evaluating: 'matches("foo", "[a-z]{3}")'] <br/>expected: true<br/> but was: null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6083/1/testReport/org.kie.dmn.feel.runtime/FEELFunctionsTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[72]/">org.kie.dmn.feel.runtime.FEELFunctionsTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[72]</a></summary>
[Evaluating: 'matches("foo", "[a-z]{3}")'] <br/>expected: true<br/> but was: null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6083/1/testReport/org.kie.dmn.feel.runtime/FEELFunctionsTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[73]/">org.kie.dmn.feel.runtime.FEELFunctionsTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[73]</a></summary>
[Evaluating: 'matches("banana", "[a-z]{3}")'] <br/>expected: true<br/> but was: null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6083/1/testReport/org.kie.dmn.feel.runtime/FEELFunctionsTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[74]/">org.kie.dmn.feel.runtime.FEELFunctionsTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[74]</a></summary>
[Evaluating: 'matches("banana", "[a-z]{3}")'] <br/>expected: true<br/> but was: null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6083/1/testReport/org.kie.dmn.feel.runtime/FEELFunctionsTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[75]/">org.kie.dmn.feel.runtime.FEELFunctionsTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[75]</a></summary>
[Evaluating: 'matches("two \n lines", "two.*lines")'] <br/>expected: false<br/> but was: null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6083/1/testReport/org.kie.dmn.feel.runtime/FEELFunctionsTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[76]/">org.kie.dmn.feel.runtime.FEELFunctionsTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[76]</a></summary>
[Evaluating: 'matches("two \n lines", "two.*lines")'] <br/>expected: false<br/> but was: null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6083/1/testReport/org.kie.dmn.feel.runtime/FEELFunctionsTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[79]/">org.kie.dmn.feel.runtime.FEELFunctionsTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[79]</a></summary>
[Evaluating: 'matches("one\ntwo\nthree", "^two$")'] <br/>expected: false<br/> but was: null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6083/1/testReport/org.kie.dmn.feel.runtime/FEELFunctionsTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[80]/">org.kie.dmn.feel.runtime.FEELFunctionsTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[80]</a></summary>
[Evaluating: 'matches("one\ntwo\nthree", "^two$")'] <br/>expected: false<br/> but was: null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6083/1/testReport/org.kie.dmn.feel.runtime/FEELFunctionsTest/instanceTest(String,_Object,_Severity,_FEEL_TARGET,_Boolean,_FEELDialect)[83]/">org.kie.dmn.feel.runtime.FEELFunctionsTest.instanceTest(String, Object, Severity, FEEL_TARGET, Boolean, FEELDialect)[83]</a></summary>
[Evaluating: 'matches("FoO", "foo")'] <br/>expected: false<br/> but was: null
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/drools/job/main/job/pullrequest_jobs/job/drools-pr/job/PR-6083/1/testReport/org.kie.dmn.feel.runtime/FEELFunctionsTest/in [...]

2024-09-16 09:34 UTC, yesamer requested changes
@bncriju Thank you for your PR! After @gitgabrio and I analyzed your changes, we discovered more parts of the code that require to be improved. So, we agreed to open a new PR based on your PR to apply the adjustments.

2024-09-16 09:34 UTC, yesamer commented on kie-dmn/kie-dmn-feel/pom.xml
> +    </dependency>
@bncriju I guess this is not required

2024-09-16 09:34 UTC, yesamer commented on kie-dmn/kie-dmn-feel/pom.xml
> +        <directory>${project.basedir}/../</directory>
@bncriju I guess this change is not required

2024-09-16 09:34 UTC, yesamer commented on kie-dmn/kie-dmn-feel/src/main/java/org/kie/dmn/feel/runtime/functions/MatchesFunction.java
> +    public FEELFnResult<Boolean> FEELFnResult(@ParameterName("input") String input, @ParameterName("pattern") String pattern) {
@bncriju Wrong method name

2024-09-16 09:38 UTC, yesamer commented
Superseded by https://github.com/apache/incubator-kie-drools/pull/6085

2024-09-16 09:38 UTC, closed without merging

2024-09-16 09:39 UTC, pibizza requested changes
Make the tests without reused variables. either separate tests or make them just parametric.

2024-09-16 09:39 UTC, pibizza commented on kie-dmn/kie-dmn-feel/src/test/java/org/kie/dmn/feel/util/XQueryImplUtilTest.java
> +        assertThat(retrieved).isNotNull().isEqualTo(expected);
One general comment. Do not reuse variables. Either separate the tests or make a parametric test. a test should be quite simple and very easy to read.