[incubator-kie-issues-1616] notice file for drools is not correct
apache/incubator-kie pull request #6153
Opened 2024-11-15 05:54 UTC by tkobayas

**Issue**: 

* https://github.com/apache/incubator-kie-issues/issues/1616

- `NOTICE` file contains only Apache KIE. Bundled third-party components don't have their own `NOTICE` file. So nothing to add.
- We don't have third-party binary components with `NOTICE` file, so `NOTICE-BINARY` is removed
- The previous content of `NOTICE-BINARY` is moved to `DISCLAIMER-BINARY` (mimicking https://github.com/apache/incubator-stormcrawler/blob/stormcrawler-3.1.0/DISCLAIMER-BINARIES.txt) 
- `LICENSE` has list of bundled third-party components with their license and file paths
- `LICENSE` has list of bundled binary third-party components with their license and file paths
- `licenses` directory contains LICENSE files of the bundled third-party components
- `licenses-binary` directory contains LICENSE files of the bundled binary third-party components

2024-11-15 06:28 UTC, tkobayas commented
@LightGuard , as mentioned in https://github.com/apache/incubator-kie-issues/issues/1616#issuecomment-2475705022

> maybe, it would be best to get your mentors and possibly other IPMC members to review the PRs for license changes

Could you involve someone from IPMC for review?

2024-11-15 07:18 UTC, mariofusco approved these changes

2024-11-15 18:42 UTC, LightGuard commented
@pjfanning would you mind taking a look at this, please?

2024-11-15 18:44 UTC, LightGuard commented
@davsclaus and @oscerd it would be good to get your review here too.

2024-11-15 18:58 UTC, LightGuard requested changes
My understanding from [the ASF release policy document](https://www.apache.org/legal/release-policy.html#license-file), we should be okay including the licenses as is done in this pull request. I think it is more common to see it in one single file, but it is also okay to have it in a different file, with a pointer (which I think we need to add).

> When a package bundles code under several licenses, the LICENSE file MUST contain details of all these licenses. For each component which is not Apache licensed, details of the component MUST be appended to the LICENSE file. The component license itself MUST either be appended or else stored elsewhere in the package with a pointer to it from the LICENSE file, e.g. if the license is long.

2024-11-15 18:58 UTC, LightGuard commented on DISCLAIMER-BINARY
> +drools-docs/ui-bundle/ui-bundle.zip : antora ui-bundle resources. For example, js and svg. See LICENSE-BINARY file
I'm wondering if we drop the docs stuff from the releases all together. @porcelli what do you think?

2024-11-15 18:58 UTC, LightGuard commented on LICENSE-BINARY
> +Mozilla Public License 2.0
Shouldn't we be including the license text here too, or at the very least a link to the license?

2024-11-15 19:25 UTC, porcelli commented
would love to hear your feedback here @pjfanning

2024-11-15 19:31 UTC, pjfanning commented on LICENSE
> +drools-docs/supplemental-ui/css/search.css
can you include the text of any non Apache Licenses?

2024-11-15 19:32 UTC, pjfanning commented on LICENSE-BINARY
> +Mozilla Public License 2.0
yes - any non Apache license - we need its text including any customisations like copyright statements

2024-11-15 19:34 UTC, porcelli reviewed
this looks very good, however I'd love to hear from @pjfanning - as I'm not experienced to properly evaluate

2024-11-15 19:37 UTC, porcelli commented on LICENSE
> +drools-docs/supplemental-ui/css/search.css
@pjfanning you mean copy here the whole license text from the file? basically a copy-n-paste from here https://www.mozilla.org/en-US/MPL/2.0/

2024-11-15 19:38 UTC, porcelli commented on LICENSE
> +drools-docs/supplemental-ui/css/search.css
@pjfanning note that part of this PR we have other files like LICENSE-search-ui.txt - so you suggest we remove those files and add everything here?

2024-11-15 19:39 UTC, pjfanning commented on LICENSE
> +drools-docs/supplemental-ui/css/search.css
if you are not including the text directly here - you will need to provide the location of the file to check.

I'm not sure having separate files will be popular.

In most ASF source releases, we have one LICENSE file and maybe one directory with 3rd party licenses.

KIE source release has many subdirs - with different git repos in each subdir, each with its own license - and now these subdirs can have more subdirs with 3rd party libraries. This level of splitting up of the license data is kind of unprecedented.

2024-11-15 19:44 UTC, porcelli commented on LICENSE
> +drools-docs/supplemental-ui/css/search.css
@pjfanning do you happen to have an example of license that has more than one license? sorry to insist and bother... but I'm trying to be assertive and avoid a RC5 :D

2024-11-15 19:48 UTC, LightGuard commented
https://github.com/apache/tomee/blob/main/LICENSE

2024-11-15 21:38 UTC, porcelli requested changes
great job @tkobayas, thank you for digging into this! 

however based on @pjfanning input, we need make this slightly better

2024-11-16 00:24 UTC, pjfanning commented on LICENSE-BINARY
> +Mozilla Public License 2.0
could we please list the files that are affected by these licenses?

I found:
incubator-kie-drools/drools-docs/supplemental-ui/css/search.css
incubator-kie-drools/drools-docs/supplemental-ui/js/search-ui.js

2024-11-18 03:43 UTC, tkobayas commented on DISCLAIMER-BINARY
> +drools-docs/ui-bundle/ui-bundle.zip : antora ui-bundle resources. For example, js and svg. See LICENSE-BINARY file
+1 for dropping `drools-docs` by the release CI, so we can reduce license concerns and avoid future issues.

2024-11-18 04:04 UTC, tkobayas commented
Move `LICENSE-*.txt` files into `LICENSE` / `LICENSE-BINARY` files. Affected file paths are listed. Following https://github.com/apache/tomee/blob/main/LICENSE style.

I hope this addresses the suggested points. Please review, thanks! @pjfanning @porcelli @LightGuard

2024-11-18 08:46 UTC, tkobayas commented on LICENSE
> + copyright notice and book citation attached."
I fixed one more issue, which was pointed at in https://lists.apache.org/thread/nrq50szwx37doopb23wyq33v0t3bbccg . `CsvLineParser.java` has this copyright, so removed Apache license header. This statement doesn't seem to meet with known licenses, but I think it fits in the `LICENSE` file. Let me know if this should be handled in another way.

FYI) http://tpop.awl.com/ no longer exists.

2024-11-18 09:31 UTC, pjfanning commented on LICENSE
> + copyright notice and book citation attached."
This could cause some trouble. I found the book online but I couldn't find any reference to this permission bit.
https://kremlin.cc/rob.pdf

We might need to bring this up on the legal discussion JIRA. https://issues.apache.org/jira/projects/LEGAL/issues

In the end of the day, the path of least resistance might be to find another CSV parser. E.g. commons-csv

2024-11-18 09:54 UTC, tkobayas commented on LICENSE
> + copyright notice and book citation attached."
Thank you for the suggestion, @pjfanning 

I have found this statement in this store site ( https://www.informit.com/store/practice-of-programming-9780201615869 ). Click "Downloads" tab. It contains the statement `You may use this code for any purpose, as long as you leave the copyright notice and book citation attached.`.

Shall I open a JIRA in https://issues.apache.org/jira/projects/LEGAL/issues ?

2024-11-18 10:08 UTC, pjfanning commented on LICENSE
> + copyright notice and book citation attached."
Could you raise the JIRA? Finding the statement on that web site is very helpful though.

2024-11-18 10:27 UTC, porcelli commented on NOTICE
> -
@pjfanning it's not entirely clear to me, but isn't expected that the CSV parser copyright info moved here? (or it's ok to be on LICENSE file)

2024-11-18 10:32 UTC, pjfanning commented on NOTICE
> -
My experience has been bad with the cases like this where the code is not explicitly licensed or explicitly placed in the public domain. If https://www.apache.org/legal/resolved.html or existing LEGAL JIRAs don't cover it, it is best to get it checked by the Legal team.

2024-11-18 10:37 UTC, porcelli commented on NOTICE
> -
k, but as this would be a big enough change for the immediate 10.0.0 release... I'd assume this wouldn't be a blocker... 
In the meantime.. I'm just wondering if the NOTICE file wouldn't be more appropriated to host the copyright? As this seems to be a good example to relocated copyright.

2024-11-18 10:42 UTC, pjfanning commented on NOTICE
> -
I think we can open the LEGAL issue but press on. It is probably not a blocker to wait for the agreed answer.
The LICENSE needs to mention this usage so I'm not sure it is that useful to also include the copyright in the NOTICE but others might have another opinion.

2024-11-18 10:56 UTC, porcelli commented
@tkobayas I don't think the -BINARY files are needed in current form. As it only covers the search-ui thing that is used only by the docs module, which we don't distribute in any binary format.

@pjfanning thoughts?

2024-11-18 11:16 UTC, tkobayas commented
@porcelli Thanks. Probably I misunderstood the purpose of `*-BINARY` file. `ui-bundle.zip` exists in `apache-kie-10.0.0-incubating-sources.zip`, so I should write its license in `LICENSE` file rather than `LICENSE-BINARY`. Okay? @porcelli @pjfanning

2024-11-18 11:29 UTC, tkobayas commented on LICENSE
> + copyright notice and book citation attached."
@pjfanning @porcelli I filed https://issues.apache.org/jira/browse/LEGAL-689 Feel free to add comments on it.

2024-11-18 11:35 UTC, pjfanning commented
> @porcelli Thanks. Probably I misunderstood the purpose of `*-BINARY` file. `ui-bundle.zip` exists in `apache-kie-10.0.0-incubating-sources.zip`, so I should write its license in `LICENSE` file rather than `LICENSE-BINARY`. Okay? @porcelli @pjfanning

* the zip is a problem - we shouldn't have binary files in the source release
* can we unzip the file and check it the underlying files?

2024-11-18 11:53 UTC, tkobayas commented
> can we unzip the file and check it the underlying files?
```
$ unzip ui-bundle.zip 
Archive:  ui-bundle.zip
   creating: css/
   creating: font/
   creating: helpers/
   creating: img/
   creating: js/
   creating: layouts/
   creating: partials/
  inflating: css/site.css            
  inflating: font/roboto-latin-400.woff  
  inflating: font/roboto-latin-400.woff2  
  inflating: font/roboto-latin-400italic.woff  
  inflating: font/roboto-latin-400italic.woff2  
  inflating: font/roboto-latin-500.woff  
  inflating: font/roboto-latin-500.woff2  
  inflating: font/roboto-latin-500italic.woff  
  inflating: font/roboto-latin-500italic.woff2  
  inflating: font/roboto-mono-latin-400.woff  
  inflating: font/roboto-mono-latin-400.woff2  
  inflating: font/roboto-mono-latin-500.woff  
  inflating: font/roboto-mono-latin-500.woff2  
  inflating: helpers/and.js          
  inflating: helpers/detag.js        
  inflating: helpers/eq.js           
  inflating: helpers/increment.js    
  inflating: helpers/ne.js           
  inflating: helpers/not.js          
  inflating: helpers/or.js           
  inflating: helpers/relativize.js   
  inflating: helpers/year.js         
  inflating: img/back.svg            
  inflating: img/caret.svg           
  inflating: img/chevron.svg         
  inflating: img/home-o.svg          
  inflating: img/home.svg            
  inflating: img/menu.svg            
  inflating: img/octicons-16.svg     
  inflating: js/site.js              
   creating: js/vendor/
  inflating: layouts/404.hbs         
  inflating: layouts/default.hbs     
  inflating: partials/article-404.hbs  
  inflating: partials/article.hbs    
  inflating: partials/body.hbs       
  inflating: partials/breadcrumbs.hbs  
  inflating: partials/footer-content.hbs  
  inflating: partials/footer-scripts.hbs  
  inflating: partials/footer.hbs     
  inflating: partials/head-icons.hbs  
  inflating: partials/head-info.hbs  
  inflating: partials/head-meta.hbs  
  inflating: partials/head-prelude.hbs  
  inflating: partials/head-scripts.hbs  
  inflating: partials/head-styles.hbs  
  inflating: partials/head-title.hbs  
  inflating: partials/head.hbs       
  inflating: partials/header-content.hbs  
  inflating: partials/header-scripts.hbs  
  inflating: partials/header.hbs     
  inflating: partials/main.hbs       
  inflating: partials/nav-explore.hbs  
  inflating: partials/nav-menu.hbs   
  inflating: partials/nav-toggle.hbs  
  inflating: partials/nav-tree.hbs   
  inflating: partials/nav.hbs        
  inflating: partials/page-versions.hbs  
  inflating: partials/pagination.hbs  
  inflating: partials/toc.hbs        
  inflating: partials/toolbar.hbs    
  inflating: js/vendor/highlight.js 
```
ui-bundle.zip contains javascript, svg, font, css, hbs (html template). I wrote that in `DISCLAIMER-BINARY`.

> the zip is a problem - we shouldn't have binary files in the source release

Is this a blocker to the 10.0.0 release? @pjfanning 

If no, we would drop the `drools-docs` module from the source code distribution for the next release.
If yes, still I think it's better to drop the `drools-docs` module from the source code distribution for 10.0.x...

2024-11-18 12:15 UTC, pjfanning commented
> > can we unzip the file and check it the underlying files?
> 
> ```
> $ unzip ui-bundle.zip 
> Archive:  ui-bundle.zip
>    creating: css/
>    creating: font/
>    creating: helpers/
>    creating: img/
>    creating: js/
>    creating: layouts/
>    creating: partials/
>   inflating: css/site.css            
>   inflating: font/roboto-latin-400.woff  
>   inflating: font/roboto-latin-400.woff2  
>   inflating: font/roboto-latin-400italic.woff  
>   inflating: font/roboto-latin-400italic.woff2  
>   inflating: font/roboto-latin-500.woff  
>   inflating: font/roboto-latin-500.woff2  
>   inflating: font/roboto-latin-500italic.woff  
>   inflating: font/roboto-latin-500italic.woff2  
>   inflating: font/roboto-mono-latin-400.woff  
>   inflating: font/roboto-mono-latin-400.woff2  
>   inflating: font/roboto-mono-latin-500.woff  
>   inflating: font/roboto-mono-latin-500.woff2  
>   inflating: helpers/and.js          
>   inflating: helpers/detag.js        
>   inflating: helpers/eq.js           
>   inflating: helpers/increment.js    
>   inflating: helpers/ne.js           
>   inflating: helpers/not.js          
>   inflating: helpers/or.js           
>   inflating: helpers/relativize.js   
>   inflating: helpers/year.js         
>   inflating: img/back.svg            
>   inflating: img/caret.svg           
>   inflating: img/chevron.svg         
>   inflating: img/home-o.svg          
>   inflating: img/home.svg            
>   inflating: img/menu.svg            
>   inflating: img/octicons-16.svg     
>   inflating: js/site.js              
>    creating: js/vendor/
>   inflating: layouts/404.hbs         
>   inflating: layouts/default.hbs     
>   inflating: partials/article-404.hbs  
>   inflating: partials/article.hbs    
>   inflating: partials/body.hbs       
>   inflating: partials/breadcrumbs.hbs  
>   inflating: partials/footer-content.hbs  
>   inflating: partials/footer-scripts.hbs  
>   inflating: partials/footer.hbs     
>   inflating: partials/head-icons.hbs  
>   inflating: partials/head-info.hbs  
>   inflating: partials/head-meta.hbs  
>   inflating: partials/head-prelude.hbs  
>   inflating: partials/head-scripts.hbs  
>   inflating: partials/head-styles.hbs  
>   inflating: partials/head-title.hbs  
>   inflating: partials/head.hbs       
>   inflating: partials/header-content.hbs  
>   inflating: partials/header-scripts.hbs  
>   inflating: partials/header.hbs     
>   inflating: partials/main.hbs       
>   inflating: partials/nav-explore.hbs  
>   inflating: partials/nav-menu.hbs   
>   inflating: partials/nav-toggle.hbs  
>   inflating: partials/nav-tree.hbs   
>   inflating: partials/nav.hbs        
>   inflating: partials/page-versions.hbs  
>   inflating: partials/pagination.hbs  
>   inflating: partials/toc.hbs        
>   inflating: partials/toolbar.hbs    
>   inflating: js/vendor/highlight.js 
> ```
> 
> ui-bundle.zip contains javascript, svg, font, css, hbs (html template)
> 
> > the zip is a problem - we shouldn't have binary files in the source release
> 
> Is this a blocker to the 10.0.0 release? @pjfanning
> 
> If no, we would drop the `drools-docs` module from the source code distribution for the next release. If yes, still I think it's better to drop the `drools-docs` module from the source code distribution for 10.0.x...

Can we exclude it from the sources zip and come back later? It could easily attract a -1 vote by including it. And in longer run, it needs to be removed and the various source files in the archive should be checked in explicitly. If you need to zip thm up when you are building from source, that's ok - that should be easy to add to your build scripting.

2024-11-18 13:42 UTC, tkobayas commented
Okay, I removed `drools-docs` related licenses, as we will not have `drools-docs` module in source distributions. Now it's much cleaner.

For 10.0.x, I'll raise a PR to remove `drools-docs` -> https://github.com/apache/incubator-kie-drools/pull/6155
For later releases, I will check with CI experts to exclude `drools-docs` by the release CI job.
Is it fine? @porcelli

2024-11-18 14:22 UTC, tkobayas commented
https://issues.apache.org/jira/browse/LEGAL-689
```
Justin Mclean:
I would just note the file and statement in the LICENSE file
```
So the current PR seems to be good.

2024-11-18 14:25 UTC, tkobayas commented
@pjfanning @LightGuard @porcelli If this PR is in a good shape under the current situation, please approve and merge, thanks!

2024-11-18 14:53 UTC, porcelli approved these changes

2024-11-18 14:53 UTC, merged