#1708 - Replace original implementation and remove copyright info from license file
apache/incubator-kie pull request #6195
Opened 2024-12-12 20:09 UTC by porcelli

Closes: https://github.com/apache/incubator-kie-issues/issues/1708

2024-12-13 05:39 UTC, tkobayas approved these changes
Thank you!

2024-12-13 05:40 UTC, tkobayas commented
kogito-apps GHA test failure can be ignored as it's being worked on.

2024-12-13 06:35 UTC, jomarko requested changes
Thank you for the PR @porcelli . Always good to see we are able to simplify the codebase we maintain.

I have some comments and questions before merge.

2024-12-13 06:35 UTC, jomarko commented on LICENSE
> - for drools-decisiontables/src/main/java/org/drools/decisiontable/parser/csv/CsvLineParser.java
Please, update also https://github.com/apache/incubator-kie-drools/blob/main/.rat-excludes, we need to remove the entry `CsvLineParsrer`  from there

2024-12-13 06:35 UTC, jomarko commented on drools-decisiontables/src/main/java/org/drools/decisiontable/parser/csv/CsvLineParser.java
> +            return fields;
In past, we used often `Collections.singletoneList`, what is your opinion about:
```
        if (line.isEmpty()) {
            return Collections.singletonList("");
        }
```

2024-12-13 06:35 UTC, jomarko commented on drools-decisiontables/src/main/java/org/drools/decisiontable/parser/csv/CsvLineParser.java
> +        this.delimiter = delimiter;
Do we want to keep this constructor? I was not able to find its usage, to me it seems we use only the default one.

2024-12-13 11:16 UTC, mariofusco approved these changes

2024-12-13 18:10 UTC, porcelli commented on drools-decisiontables/src/main/java/org/drools/decisiontable/parser/csv/CsvLineParser.java
> +        this.delimiter = delimiter;
good point, I wasn't completely sure and that's why cheated and sent this way so to have the CI tell me that if in the codebase we had this used somehow :)

2024-12-13 18:10 UTC, porcelli commented on drools-decisiontables/src/main/java/org/drools/decisiontable/parser/csv/CsvLineParser.java
> +            return fields;
sure, I'll adjust

2024-12-13 18:11 UTC, porcelli commented on LICENSE
> - for drools-decisiontables/src/main/java/org/drools/decisiontable/parser/csv/CsvLineParser.java
good catch

2024-12-16 09:34 UTC, jomarko approved these changes
Thank you for updates @porcelli

2024-12-16 11:43 UTC, merged