[Incubator kie issues#1619]Correctly manage execution of invalid models
apache/incubator-kie pull request #6200
Opened 2024-12-17 06:25 UTC by AthiraHari77

Fixes [https://github.com/apache/incubator-kie-issues/issues/1619]

In this PR, Decision models are validated to ensure correctness, and both valid and invalid decisions are identified and handled accordingly. In the event of an exception, a valid status is returned to reflect the error state accurately.

**Thank you for submitting this pull request**

**NOTE!:** Double-check the target branch for this PR.
The default is `main` so it will target Drools 8 / Kogito.

**Ports** If a forward-port or a backport is needed, paste the forward port PR here

* [link](https://www.example.com)

**Issue**: _(please edit the GitHub Issues link if it exists)_

* [link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request and downstream checks</b>  
  - Push a new commit to the PR. An empty commit would be enough.

- for a <b>full downstream build</b>
  - for <b>github actions</b> job: add the label `run_fdb`

- for <b>Jenkins PR check only</b>
  - If you are an ASF committer for KIE podling, login to Jenkins (https://ci-builds.apache.org/job/KIE/job/drools/), go to the specific PR job, and click on `Build Now` button.
</details>

2024-12-17 08:53 UTC, yesamer requested changes

2024-12-17 08:53 UTC, yesamer commented on kie-dmn/kie-dmn-test-resources/src/test/resources/valid_models/DMNv1_5/MultipleDecision.dmn
> +<?xml version="1.0" encoding="UTF-8" ?>
@AthiraHari77 Please add the Apache legal header in all the DMN files you introduced

2024-12-17 09:04 UTC, AthiraHari77 commented on kie-dmn/kie-dmn-test-resources/src/test/resources/valid_models/DMNv1_5/MultipleDecision.dmn
> +<?xml version="1.0" encoding="UTF-8" ?>
@yesamer Updated Apache legal header in all the DMN files

2024-12-17 10:14 UTC, yesamer commented on kie-dmn/kie-dmn-test-resources/src/test/resources/valid_models/DMNv1_5/MultipleDecision.dmn
> +<definitions xmlns="https://www.omg.org/spec/DMN/20230324/MODEL/" expressionLanguage="https://www.omg.org/spec/DMN/20230324/FEEL/" namespace="https://kie.org/dmn/_CADD03FC-4ABD-46D2-B631-E7FDE384D6D7
@AthiraHari77 License header is still missing here

2024-12-17 10:21 UTC, pibizza commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/internal/utils/DMNRuntimeBuilderTest.java
> +        assertThatThrownBy(() -> dmnRuntime.evaluateByName(dmnModel, context, "Can Drive"))
I would go for the more readable assertThatIllegalStateExceptionIsThrownBy(.... Consider this also in the other tests.

2024-12-17 15:55 UTC, AthiraHari77 commented on kie-dmn/kie-dmn-test-resources/src/test/resources/valid_models/DMNv1_5/MultipleDecision.dmn
> +<definitions xmlns="https://www.omg.org/spec/DMN/20230324/MODEL/" expressionLanguage="https://www.omg.org/spec/DMN/20230324/FEEL/" namespace="https://kie.org/dmn/_CADD03FC-4ABD-46D2-B631-E7FDE384D6D7
@yesamer I have updated here as well

2024-12-17 15:56 UTC, AthiraHari77 commented on kie-dmn/kie-dmn-core/src/test/java/org/kie/dmn/core/internal/utils/DMNRuntimeBuilderTest.java
> +        assertThatThrownBy(() -> dmnRuntime.evaluateByName(dmnModel, context, "Can Drive"))
@pibizza Updated the test cases as specified

2024-12-19 08:53 UTC, pibizza approved these changes
This is fine. I would probably split the test file in two - one for normal cases and one for exceptional cases. the one for exceptional cases can greatly be simplified, becoming a single parametric test. We can do this later however.

2024-12-20 07:11 UTC, gitgabrio requested changes
Hi @AthiraHari77 
great job.
But TBH I'm surprised that this modification does not break any test, apparently, and now I'm wondering if there could be something else missing.
At the same time, as maybe mentioned in private, I was pretty sure that we would need to modify, somehow, the message creation to have a better structured information.
Last, we have to be sure that our TCK implementation will be adapted accordingly, because I'm pretty sure that this modification could break the current one.

2024-12-20 07:11 UTC, gitgabrio commented on kie-dmn/kie-dmn-core/src/main/java/org/kie/dmn/core/impl/DMNRuntimeImpl.java
> +        List<String> identifiedErrors = errorMessages.stream().map(Message::getText)
HI @AthiraHari77 
Many thanks for the PR.
I'm only slightly concerned about this assertion.
The logic here is that
1) `decisions` could be `decisionsId` or `decisionName` (IINW)
2) if an error message _**contains**_ one of them, then the decisions it relates to is "wrong"

I'm afraid there could be some cases where an error message contains the decisionId or decisionName, but that the error is not in the decision itself (e.g. another element that refer that decision)

2024-12-20 08:20 UTC, yesamer commented
@gitgabrio @AthiraHari77 I ran the TCK tests against those changes, and there is only one new test failure:
`1131 - feel -function invocation test: Non existing function evaluates to null (10.3.2.13.2)`
I guess we should return null in case those errors occur.

2026-08-09 23:50 UTC, tiagobento commented
Closing as stale.

2026-08-09 23:50 UTC, closed without merging